<script setup lang="ts">
import { onMounted, ref } from "vue";
import { bzaApi, hasBzaPermission } from "../auth/session";
const rows=ref<Record<string,unknown>[]>([]); const loading=ref(false); const error=ref("");
async function load(){loading.value=true;error.value="";try{rows.value=await bzaApi('/api/bza/backoffice/approvals?limit=100');}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function act(item:Record<string,unknown>,action:string){const reason=window.prompt('처리 사유를 입력하세요.');if(!reason)return;try{await bzaApi(`/api/bza/backoffice/approvals/${item.approvalId}/actions`,{method:'POST',body:JSON.stringify({action,idempotencyKey:crypto.randomUUID(),reason,comment:reason})});await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}}
onMounted(load);
</script>
<template><section class="card table-card"><div class="card-head"><div><p class="eyebrow">APPROVAL</p><h2>업무 결재</h2></div><span class="count-pill">{{rows.length}}건</span></div><p v-if="error" class="error-banner">{{error}}</p><div v-if="loading" class="empty-state">조회 중...</div><div v-else class="table-wrap"><table><thead><tr><th>approvalNo</th><th>approvalType</th><th>title</th><th>requesterEmployeeNo</th><th>approvalStatus</th><th>currentStepNo</th><th>versionNo</th><th v-if="hasBzaPermission('APPROVAL','WRITE')">처리</th></tr></thead><tbody><tr v-for="item in rows" :key="String(item.approvalId)"><td>{{item.approvalNo}}</td><td>{{item.approvalType}}</td><td>{{item.title}}</td><td>{{item.requesterEmployeeNo}}</td><td><span class="status-pill">{{item.approvalStatus}}</span></td><td>{{item.currentStepNo}}</td><td>{{item.versionNo}}</td><td v-if="hasBzaPermission('APPROVAL','WRITE')"><div class="inline-actions"><button class="primary small" @click="act(item,'APPROVE')">승인</button><button class="danger small" @click="act(item,'REJECT')">반려</button></div></td></tr><tr v-if="rows.length===0"><td colspan="8" class="empty-cell">조회 결과가 없습니다.</td></tr></tbody></table></div></section></template>
