package com.cpf.starter.sftp;
import java.io.*;import java.nio.file.*;import java.security.*;import java.time.Instant;import java.util.*;import org.apache.sshd.client.SshClient;import org.apache.sshd.client.keyverifier.ServerKeyVerifier;import org.apache.sshd.client.session.ClientSession;import org.apache.sshd.sftp.client.SftpClient;import org.apache.sshd.sftp.client.SftpClientFactory;
public final class CpfSftpClient implements AutoCloseable {private final CpfSftpProperties p;private final ServerKeyVerifier verifier;private final JdbcCpfSftpTransferLedger ledger;private final SshClient client;
 public CpfSftpClient(CpfSftpProperties p,ServerKeyVerifier v,JdbcCpfSftpTransferLedger l){this.p=p;verifier=v;ledger=l;client=SshClient.setUpDefaultClient();client.setServerKeyVerifier(v);client.start();}
 public Result upload(Path local,String remote,String transactionId,boolean resume){requireFile(local);String id=UUID.randomUUID().toString();Instant start=Instant.now();ledger.started(new CpfSftpTransferRecord(id,"UPLOAD",local.toString(),remote,"STARTED",0,null,transactionId,null,start,null));try(var ctx=open()){long offset=resume?remoteSize(ctx.sftp,remote):0;long total=Files.size(local);if(total>p.getMaxTransferBytes())throw new IllegalArgumentException("SFTP file exceeds limit");try(InputStream in=Files.newInputStream(local);OutputStream out=ctx.sftp.write(remote,offset>0?SftpClient.OpenMode.Append:SftpClient.OpenMode.Create,SftpClient.OpenMode.Write)){in.skipNBytes(Math.min(offset,total));in.transferTo(new BoundedOutputStream(out,p.getMaxTransferBytes()));}String checksum=sha256(local);var r=new Result(id,total,checksum,"COMPLETED");ledger.completed(new CpfSftpTransferRecord(id,"UPLOAD",local.toString(),remote,r.status(),r.bytes(),r.checksum(),transactionId,null,start,Instant.now()));return r;}catch(Exception ex){ledger.completed(new CpfSftpTransferRecord(id,"UPLOAD",local.toString(),remote,"FAILED",0,null,transactionId,safe(ex),start,Instant.now()));throw failure("upload",ex);}}
 public Result download(String remote,Path local,String transactionId,boolean resume){String id=UUID.randomUUID().toString();Instant start=Instant.now();ledger.started(new CpfSftpTransferRecord(id,"DOWNLOAD",remote,local.toString(),"STARTED",0,null,transactionId,null,start,null));try(var ctx=open()){long offset=resume&&Files.exists(local)?Files.size(local):0;var attrs=ctx.sftp.stat(remote);if(attrs.getSize()>p.getMaxTransferBytes())throw new IllegalArgumentException("SFTP file exceeds limit");Files.createDirectories(local.toAbsolutePath().getParent());try(InputStream in=ctx.sftp.read(remote);OutputStream out=Files.newOutputStream(local,resume?new StandardOpenOption[]{StandardOpenOption.CREATE,StandardOpenOption.APPEND}:new StandardOpenOption[]{StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING})){in.skipNBytes(Math.min(offset,attrs.getSize()));new BoundedInputStream(in,p.getMaxTransferBytes()).transferTo(out);}String checksum=sha256(local);long bytes=Files.size(local);ledger.completed(new CpfSftpTransferRecord(id,"DOWNLOAD",remote,local.toString(),"COMPLETED",bytes,checksum,transactionId,null,start,Instant.now()));return new Result(id,bytes,checksum,"COMPLETED");}catch(Exception ex){ledger.completed(new CpfSftpTransferRecord(id,"DOWNLOAD",remote,local.toString(),"FAILED",0,null,transactionId,safe(ex),start,Instant.now()));throw failure("download",ex);}}
 public List<String> list(String remoteDir){try(var ctx=open()){List<String> result=new ArrayList<>();for(var e:ctx.sftp.readDir(remoteDir))if(!e.getFilename().equals(".")&&!e.getFilename().equals(".."))result.add(e.getFilename());return List.copyOf(result);}catch(Exception ex){throw failure("list",ex);}}
 public void move(String source,String target){try(var ctx=open()){ctx.sftp.rename(source,target,SftpClient.CopyMode.Atomic,SftpClient.CopyMode.Overwrite);}catch(Exception ex){throw failure("move",ex);}}
 public void delete(String remote){try(var ctx=open()){ctx.sftp.remove(remote);}catch(Exception ex){throw failure("delete",ex);}}
 private Context open()throws IOException{try{ClientSession s=client.connect(p.getUsername(),p.getHost(),p.getPort()).verify(p.getConnectTimeout()).getSession();s.addPasswordIdentity(p.getPassword());s.auth().verify(p.getConnectTimeout());return new Context(s,SftpClientFactory.instance().createSftpClient(s));}catch(RuntimeException ex){throw new IOException("SFTP connection/authentication failed",ex);}}
 private static long remoteSize(SftpClient s,String path){try{return s.stat(path).getSize();}catch(IOException ex){return 0;}}private static void requireFile(Path p){if(p==null||!Files.isRegularFile(p))throw new IllegalArgumentException("local file is required");}private static String sha256(Path p)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(p)){byte[] b=new byte[65536];int n;while((n=in.read(b))>=0)d.update(b,0,n);}return java.util.HexFormat.of().formatHex(d.digest());}private static RuntimeException failure(String op,Exception ex){return new IllegalStateException("SFTP "+op+" failed; reconcile transfer ledger before retry",ex);}private static String safe(Exception ex){String m=ex.getMessage();return m==null?ex.getClass().getSimpleName():m.substring(0,Math.min(1000,m.length()));}public void close(){client.stop();}
 public record Result(String transferId,long bytes,String checksum,String status){}private record Context(ClientSession session,SftpClient sftp) implements AutoCloseable{public void close()throws Exception{sftp.close();session.close();}}
 private static final class BoundedOutputStream extends FilterOutputStream{private final long max;private long count;BoundedOutputStream(OutputStream o,long m){super(o);max=m;}public void write(int b)throws IOException{check(1);super.write(b);}public void write(byte[] b,int o,int l)throws IOException{check(l);super.write(b,o,l);}private void check(int n)throws IOException{count+=n;if(count>max)throw new IOException("transfer limit exceeded");}}
 private static final class BoundedInputStream extends FilterInputStream{private final long max;private long count;BoundedInputStream(InputStream i,long m){super(i);max=m;}public int read()throws IOException{int b=super.read();if(b>=0)check(1);return b;}public int read(byte[] b,int o,int l)throws IOException{int n=super.read(b,o,l);if(n>0)check(n);return n;}private void check(int n)throws IOException{count+=n;if(count>max)throw new IOException("transfer limit exceeded");}}
}
