spring:
  config:
    activate:
      on-profile: local
  datasource:
    exs:
      url: ${EXS_DATASOURCE_URL:}
      database-name: ${EXS_DB_NAME:exsDB}
      username: ${EXS_DATASOURCE_USERNAME:cpf_exs_app}
      password: ${EXS_DATASOURCE_PASSWORD:}
    cpf:
      url: ${CPF_DB_URL:}
      database-name: ${CPF_DB_NAME:cpfDB}
      username: ${CPF_DB_USERNAME:cpf_app}
      password: ${CPF_DB_PASSWORD:}
