param([string]$Root=(Resolve-Path "$PSScriptRoot\..\..").Path)
$ErrorActionPreference='Stop';$errors=[System.Collections.Generic.List[string]]::new()
function Assert-Absent([string]$rel){if(Test-Path (Join-Path $Root $rel)){$errors.Add("obsolete artifact remains: $rel")}}
function Assert-Present([string]$rel){if(-not(Test-Path (Join-Path $Root $rel))){$errors.Add("required artifact missing: $rel")}}
foreach($p in @('docker-compose.local.yml','cpf-tools/db/source','cpf-biz-admin/frontend/src/features/console.ts','cpf-biz-admin/frontend/src/features/directory/DirectoryPage.vue','cpf-biz-admin/frontend/src/features/access/AccessPage.vue','cpf-biz-admin/frontend/src/features/approval/ApprovalPage.vue','cpf-biz-admin/frontend/src/features/support/SupportPage.vue','cpf-admin/frontend/src/app/menuRegistry.ts','cpf-core/src/main/java/com/cpf/core/common/batch','cpf-core/src/main/java/com/cpf/core/config/CpfBatchAutoConfiguration.java','cpf-core/src/main/java/com/cpf/core/config/CpfCenterCutAutoConfiguration.java','cpf-tools/db/vendor/mariadb/source/migration/flyway/V6__bizadm_exs_transaction_identity.sql')){Assert-Absent $p}
foreach($p in @(
'cpf-core/src/main/java/com/cpf/core/api/batch/CpfBatchExecutionRequest.java','cpf-batch/src/main/java/com/cpf/batch/runtime/BatBatchJobLogPath.java','cpf-core/src/main/java/com/cpf/core/api/centercut/CpfCenterCutResult.java','cpf-core/src/main/java/com/cpf/core/spi/centercut/CenterCutHandler.java',
'cpf-admin/frontend/src/features/dashboard/DashboardPage.vue','cpf-admin/frontend/src/features/topology/TopologyPage.vue','cpf-admin/frontend/src/features/recovery-center/RecoveryCenterPage.vue','cpf-admin/frontend/src/features/incidents/IncidentsPage.vue','cpf-admin/frontend/src/features/maintenance/MaintenancePage.vue','cpf-admin/frontend/src/features/workers/WorkersPage.vue','cpf-admin/frontend/src/features/capacity/CapacityPage.vue',
'cpf-biz-admin/frontend/src/features/organizations/OrganizationsPage.vue','cpf-biz-admin/frontend/src/features/approval-inbox/ApprovalInboxPage.vue',
'cpf-common/src/main/java/com/cpf/common/calendar/CmnCalendarService.java','cpf-common/src/main/java/com/cpf/common/template/CmnTemplateService.java',
'cpf-core/src/main/java/com/cpf/core/api/tenant/CpfTenant.java','cpf-core/src/main/java/com/cpf/core/common/database/CpfReadWriteRoutingDataSource.java','cpf-core/src/main/java/com/cpf/core/api/lineage/CpfLineageRecorder.java','cpf-core/src/main/java/com/cpf/core/common/reliability/CpfSelfHealingGuard.java','cpf-core/src/main/java/com/cpf/core/common/reliability/CpfSelfHealingOrchestrator.java','cpf-core/src/main/java/com/cpf/core/common/product/CpfCapabilityRegistry.java','cpf-batch/src/main/java/com/cpf/batch/runtime/centercut/BatRemoteCenterCutHandler.java',
'cpf-tools/scripts/check-database-performance-baseline.ps1','cpf-tools/db/vendor/mariadb/source/migration/flyway/V6__transaction_server_identity.sql','cpf-tools/db/vendor/mariadb/source/migration/flyway/V29__bza_backoffice_baseline.sql','cpf-admin/src/main/java/com/cpf/admin/opr/controller/AdmControlPlaneController.java','cpf-admin/src/main/java/com/cpf/admin/opr/service/AdmControlPlaneService.java','cpf-admin/src/main/java/com/cpf/admin/opr/controller/AdmBreakGlassController.java','cpf-admin/src/main/java/com/cpf/admin/opr/service/AdmBreakGlassService.java','cpf-admin/frontend/src/features/break-glass/BreakGlassPage.vue','cpf-biz-admin/src/main/java/com/cpf/bizadmin/approval/service/BzaApprovalPolicyService.java','cpf-tools/db/vendor/mariadb/source/40_business_modules_schema.sql','cpf-tools/db/vendor/mariadb/source/migration/flyway/V43__bza_approval_lifecycle_resubmit.sql','cpf-tools/db/vendor/mariadb/source/migration/flyway/V44__adm_scoped_break_glass.sql')){Assert-Present $p}
foreach($p in @('10_cpf_schema.sql','20_cmn_schema.sql','30_adm_schema.sql','35_bat_schema.sql','40_business_modules_schema.sql','50_framework_seed_data.sql','60_adm_seed_data.sql')){Assert-Present ("cpf-tools/db/vendor/mariadb/source/"+$p)}
$java=Get-ChildItem $Root -Recurse -File -Filter *.java | Where-Object {$_.FullName -notmatch '[\\/]build[\\/]'}
foreach($f in $java){$t=[IO.File]::ReadAllText($f.FullName);if($t.Contains('com.cpf.core.common.batch.')){$errors.Add("legacy Core Batch import: "+$f.FullName.Substring($Root.Length+1))}}
$engine=Join-Path $Root 'cpf-core/src/main/java/com/cpf/core/common/servicecall/CpfServiceCallEngine.java';if(Test-Path $engine){$t=Get-Content $engine -Raw;if($t -notmatch 'CpfLineageRecorder' -or $t -notmatch 'recordLineage'){$errors.Add('ServiceCallEngine lineage consumer hook missing')}}
$imports=Join-Path $Root 'cpf-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports';if(Test-Path $imports){$t=Get-Content $imports -Raw;if($t -match 'CpfBatchAutoConfiguration|CpfCenterCutAutoConfiguration'){$errors.Add('legacy Core Batch auto-configuration remains registered')}}
foreach($frontend in @('cpf-admin/frontend/src','cpf-biz-admin/frontend/src')){Get-ChildItem (Join-Path $Root $frontend) -Recurse -File | Where-Object {$_.Extension -in '.ts','.vue','.css'} | ForEach-Object {$t=Get-Content $_.FullName -Raw;if($t -match 'https?://'){$errors.Add("runtime external asset/url found: "+$_.FullName.Substring($Root.Length+1))}}}
$admRoutes=Get-Content (Join-Path $Root 'cpf-admin/frontend/src/app/routes.ts') -Raw;if(([regex]::Matches($admRoutes,'component:defineAsyncComponent').Count) -lt 32){$errors.Add('ADM feature route count is below R9 product target')}
$bzaRoutes=Get-Content (Join-Path $Root 'cpf-biz-admin/frontend/src/app/routes.ts') -Raw;if(([regex]::Matches($bzaRoutes,'load:\(\)=>import').Count) -lt 27){$errors.Add('BZA feature route count is below 27')}
if($errors.Count){$errors|ForEach-Object{Write-Error $_};exit 1}
Write-Host 'CPF R9 product hardening static gate PASS.'
