param([string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$schemaPath=Join-Path $Root 'cpf-tools/db/canonical/platform-schema.json'
$seedPath=Join-Path $Root 'cpf-tools/db/canonical/seed-model.json'
$schema=Get-Content $schemaPath -Raw -Encoding UTF8 | ConvertFrom-Json -Depth 50
$seed=Get-Content $seedPath -Raw -Encoding UTF8 | ConvertFrom-Json -Depth 50
$vendors=@('postgresql','oracle')
$fileByDb=@{cpfDB='10_cpf_schema.sql';cmnDB='20_cmn_schema.sql';admDB='30_adm_schema.sql';batDB='35_bat_schema.sql';mbrDB='40_business_modules_schema.sql';accDB='40_business_modules_schema.sql';bzaDB='40_business_modules_schema.sql';refDB='40_business_modules_schema.sql'}
function W([string]$p,[string]$s){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $p)|Out-Null;[IO.File]::WriteAllText($p,$s.TrimEnd()+"`n",[Text.UTF8Encoding]::new($false))}
function Type-For([string]$v,[string]$t){
 $u=$t.ToUpperInvariant()
 if($v -eq 'postgresql'){
  $u=$u -replace '^DATETIME','TIMESTAMP' -replace '^TINYINT','SMALLINT' -replace '^INT$','INTEGER' -replace '^LONGTEXT$','TEXT' -replace '^BLOB$','BYTEA'
  return $u
 }
 if($u -match '^VARCHAR\((\d+)\)$'){return "VARCHAR2($($Matches[1]) CHAR)"}
 if($u -match '^CHAR\((\d+)\)$'){return "CHAR($($Matches[1]) CHAR)"}
 if($u -match '^BIGINT$'){return 'NUMBER(19)'}; if($u -match '^INT$'){return 'NUMBER(10)'}; if($u -match '^TINYINT$'){return 'NUMBER(3)'}
 if($u -match '^DATETIME(\(\d+\))?$'){return 'TIMESTAMP'+$Matches[1]}; if($u -eq 'LONGTEXT' -or $u -eq 'TEXT'){return 'CLOB'}
 return $u
}
function Default-For([string]$v,$d){ if($null -eq $d){return $null};$x=[string]$d;if($v -eq 'postgresql'){$x=[regex]::Replace($x,'(?i)CURRENT_TIMESTAMP\(\d+\)','CURRENT_TIMESTAMP')};return $x }
function Q([string]$s){return $s.Replace("'","''")}
function Render-Table([string]$v,$t){
 $lines=@(); foreach($c in $t.columns){$type=Type-For $v ([string]$c.type);$line='    '+$c.name+' '+$type;if([bool]$c.autoIncrement){$line+=if($v -eq 'postgresql'){' GENERATED BY DEFAULT AS IDENTITY'}else{' GENERATED BY DEFAULT ON NULL AS IDENTITY'}};if(-not [bool]$c.nullable){$line+=' NOT NULL'};$d=Default-For $v $c.default;if($null -ne $d -and $d -ne ''){$line+=' DEFAULT '+$d};$lines+=$line}
 if($t.primaryKey.Count -gt 0){$lines+='    CONSTRAINT pk_'+$t.name+' PRIMARY KEY ('+($t.primaryKey -join ', ')+')'}
 foreach($u in $t.uniqueKeys){$lines+='    CONSTRAINT '+$u.name+' UNIQUE ('+($u.columns -join ', ')+')'}
 foreach($c in $t.checks){$lines+='    CONSTRAINT '+$c.name+' CHECK ('+$c.expression+')'}
 foreach($f in $t.foreignKeys){$line='    CONSTRAINT '+$f.name+' FOREIGN KEY ('+($f.columns -join ', ')+') REFERENCES '+$f.refTable+' ('+($f.refColumns -join ', ')+')';if($f.onDelete){$line+=' ON DELETE '+$f.onDelete};$lines+=$line}
 $out='CREATE TABLE '+$t.name+" (`n"+($lines -join ",`n")+"`n);`n"
 foreach($i in $t.indexes){$out+='CREATE '+($(if($i.unique){'UNIQUE '}else{''}))+'INDEX '+$i.name+' ON '+$t.name+' ('+($i.columns -join ', ')+");`n"}
 if($t.comment){$out+="COMMENT ON TABLE $($t.name) IS '$(Q $t.comment)';`n"}
 foreach($c in $t.columns){if($c.comment){$out+="COMMENT ON COLUMN $($t.name).$($c.name) IS '$(Q $c.comment)';`n"}}
 $touch=@($t.columns|Where-Object{$_.onUpdate}); if($touch.Count -gt 0){
  if($v -eq 'postgresql'){$fn='cpf_touch_'+$t.name;$assign=($touch|ForEach-Object{"NEW.$($_.name) = CURRENT_TIMESTAMP;"}) -join ' ';$out+="CREATE OR REPLACE FUNCTION $fn() RETURNS trigger AS `$`$ BEGIN $assign RETURN NEW; END; `$`$ LANGUAGE plpgsql;`nDROP TRIGGER IF EXISTS trg_$fn ON $($t.name);`nCREATE TRIGGER trg_$fn BEFORE UPDATE ON $($t.name) FOR EACH ROW EXECUTE FUNCTION $fn();`n"}
  else{$assign=($touch|ForEach-Object{":NEW.$($_.name) := CURRENT_TIMESTAMP;"}) -join ' ';$out+="CREATE OR REPLACE TRIGGER trg_touch_$($t.name) BEFORE UPDATE ON $($t.name) FOR EACH ROW BEGIN $assign END;`n/`n"}
 }
 return $out
}
foreach($v in $vendors){
 $bucket=@{}; foreach($db in $fileByDb.Keys){$bucket[$fileByDb[$db]]=@()}
 foreach($db in $fileByDb.Keys){$ts=@($schema.tables|Where-Object{$_.logicalDatabase -eq $db}|Sort-Object name);if($ts.Count -eq 0){continue};$s="-- AUTO-GENERATED from cpf-tools/db/canonical/platform-schema.json`n-- vendor=$v`n-- DO NOT EDIT generated DDL directly.`n`n-- CPF_LOGICAL_DATABASE=$db`n";foreach($t in $ts){$s+=Render-Table $v $t+"`n"};$bucket[$fileByDb[$db]]+=$s}
 foreach($f in $bucket.Keys){if($bucket[$f].Count -gt 0){W (Join-Path $Root "cpf-tools/db/vendor/$v/source/$f") ($bucket[$f] -join "`n")}}
}
# Seed model is canonical too. Rendering is delegated to the dedicated function below so generated SQL never copies another vendor pack.
function Convert-Expr([string]$v,[string]$x){$r=$x;foreach($db in @('cpfDB','cmnDB','admDB','bzaDB','batDB','mbrDB','accDB','refDB')){$r=[regex]::Replace($r,'(?i)(?<![A-Za-z0-9_])'+[regex]::Escape($db)+'\.','')};if($v -eq 'postgresql'){$r=[regex]::Replace($r,'(?i)CURRENT_TIMESTAMP\(\d+\)','CURRENT_TIMESTAMP');$r=$r -replace '(?i)IFNULL\s*\(','COALESCE('};if($v -eq 'oracle'){$r=[regex]::Replace($r,'(?i)\bCONCAT\(([^,]+),\s*([^\)]+)\)','$1 || $2')};return $r}
function Split-Top([string]$s,[char]$sep=','){$a=@();$start=0;$depth=0;$q=[char]0;for($i=0;$i -lt $s.Length;$i++){$c=$s[$i];if($q -ne [char]0){if($c -eq $q){if($i+1 -lt $s.Length -and $s[$i+1] -eq $q){$i++}else{$q=[char]0}};continue};if($c -eq "'" -or $c -eq '"'){$q=$c;continue};if($c -eq '('){$depth++}elseif($c -eq ')'){$depth--}elseif($c -eq $sep -and $depth -eq 0){$a+=$s.Substring($start,$i-$start).Trim();$start=$i+1}};$a+=$s.Substring($start).Trim();return,$a}
function Rows([string]$s){$r=@();$start=-1;$depth=0;$q=[char]0;for($i=0;$i -lt $s.Length;$i++){$c=$s[$i];if($q -ne [char]0){if($c -eq $q){if($i+1 -lt $s.Length -and $s[$i+1] -eq $q){$i++}else{$q=[char]0}};continue};if($c -eq "'" -or $c -eq '"'){$q=$c;continue};if($c -eq '('){if($depth -eq 0){$start=$i+1};$depth++}elseif($c -eq ')'){$depth--;if($depth -eq 0 -and $start -ge 0){$r+=$s.Substring($start,$i-$start);$start=-1}}};return,$r}
function Alias-Select([string]$v,[string]$src,[object[]]$cols){$x=Convert-Expr $v $src;$m=[regex]::Match($x,'(?is)^\s*SELECT\s+(.*?)\s+FROM\s+(.*)$');if(-not $m.Success){return $x};$parts=Split-Top $m.Groups[1].Value;if($parts.Count -ne $cols.Count){return $x};$sel=@();for($i=0;$i -lt $parts.Count;$i++){$sel+=$parts[$i]+' '+$cols[$i]};return 'SELECT '+($sel-join ', ')+' FROM '+$m.Groups[2].Value}
function Render-Insert([string]$v,$st){$cols=@($st.columns);$table=$st.tableName;$src=Convert-Expr $v ([string]$st.source);$keys=@($st.conflictColumns);$ups=@($st.updates)
 if($v -eq 'postgresql'){$base='INSERT INTO '+$table+' ('+($cols-join ', ')+') '+($(if($st.sourceKind -eq 'values'){'VALUES '+$src}else{$src}));if($keys.Count -gt 0){$base+=' ON CONFLICT ('+($keys-join ', ')+') ';if($ups.Count -eq 0){$base+='DO NOTHING'}else{$set=@();foreach($u in $ups){$e=[regex]::Replace((Convert-Expr $v $u.expression),'(?i)VALUES\(([A-Za-z0-9_]+)\)','EXCLUDED.$1');$set+=$u.column+' = '+$e};$base+='DO UPDATE SET '+($set-join ', ')}};return $base+';'}
 if($keys.Count -eq 0){if($st.sourceKind -eq 'select'){return 'INSERT INTO '+$table+' ('+($cols-join ', ')+') '+(Convert-Expr $v $src)+';'};$rs=Rows $src;$b='INSERT ALL'+"`n";foreach($row in $rs){$b+='  INTO '+$table+' ('+($cols-join ', ')+') VALUES ('+(Convert-Expr $v $row)+")`n"};return $b+'SELECT 1 FROM dual;'}
 if($st.sourceKind -eq 'values'){$qs=@();foreach($row in (Rows $src)){$vals=Split-Top $row;$pairs=@();for($i=0;$i -lt $cols.Count;$i++){$pairs+=(Convert-Expr $v $vals[$i])+' '+$cols[$i]};$qs+='SELECT '+($pairs-join ', ')+' FROM dual'};$using=($qs-join "`nUNION ALL`n")}else{$using=Alias-Select $v $src $cols}
 $on=($keys|ForEach-Object{"tgt.$_ = src.$_"}) -join ' AND ';$b="MERGE INTO $table tgt USING (`n$using`n) src ON ($on)`n";if($ups.Count -gt 0){$set=@();foreach($u in $ups){$e=[regex]::Replace((Convert-Expr $v $u.expression),'(?i)VALUES\(([A-Za-z0-9_]+)\)','src.$1');$set+='tgt.'+$u.column+' = '+$e};$b+='WHEN MATCHED THEN UPDATE SET '+($set-join ', ')+"`n"};$b+='WHEN NOT MATCHED THEN INSERT ('+($cols-join ', ')+') VALUES ('+(($cols|ForEach-Object{"src.$_"}) -join ', ')+');';return $b}
foreach($v in $vendors){$files=@{};foreach($f in $seed.canonicalPolicy.sourceFiles){$files[$f]="-- AUTO-GENERATED from cpf-tools/db/canonical/seed-model.json`n-- vendor=$v; source=$f`n-- DO NOT EDIT generated seed directly.`n"};$current=@{};foreach($st in $seed.statements){$f=$st.sourceFile;if(-not $files.ContainsKey($f)){continue};$db=$st.logicalDatabase;if(-not $current.ContainsKey($f) -or $current[$f] -ne $db){$files[$f]+="`n-- CPF_LOGICAL_DATABASE=$db`n";$current[$f]=$db};switch($st.statementKind){'use'{}'insert'{$files[$f]+=(Render-Insert $v $st)+"`n"}'update'{$files[$f]+=(Convert-Expr $v $st.sql)+";`n"}'delete'{$files[$f]+=(Convert-Expr $v $st.sql)+";`n"}'set'{if($v -eq 'postgresql'){$expr=Convert-Expr $v $st.expression;if($expr.Trim().StartsWith('(')){$files[$f]+="SELECT $expr AS $($st.variable) \\gset`n"}else{$files[$f]+="\\set $($st.variable) $expr`n"}}else{$expr=Convert-Expr $v $st.expression;if($expr.Trim().StartsWith('(')){$files[$f]+="COLUMN $($st.variable) NEW_VALUE $($st.variable) NOPRINT`nSELECT $expr AS $($st.variable) FROM dual;`n"}else{$files[$f]+="DEFINE $($st.variable) = $expr`n"}}}}};foreach($f in $files.Keys){$txt=$files[$f];if($v -eq 'postgresql'){$txt=[regex]::Replace($txt,'@([A-Za-z_][A-Za-z0-9_]*)',':$1')}else{$txt=[regex]::Replace($txt,'@([A-Za-z_][A-Za-z0-9_]*)','&&$1')};W (Join-Path $Root "cpf-tools/db/vendor/$v/source/$f") $txt}}
Write-Host 'Canonical schema/seed -> PostgreSQL/Oracle vendor source generation complete.'
