from pathlib import Path
import json,sys,re
root=Path(sys.argv[1] if len(sys.argv)>1 else '.')
required=[
'cpf-core/src/main/java/com/cpf/core/api/security/crypto/CpfCryptoOperations.java','cpf-common/src/main/java/com/cpf/common/security/crypto/JceCpfCryptoOperations.java','cpf-core/src/main/java/com/cpf/core/api/time/CpfTimeOperations.java','cpf-common/src/main/java/com/cpf/common/time/CpfLeaseTimeService.java','cpf-core/src/main/java/com/cpf/core/api/data/encryption/CpfFieldEncryptionOperations.java','cpf-common/src/main/java/com/cpf/common/data/encryption/CpfProtectedRecordService.java','cpf-core/src/main/java/com/cpf/core/api/data/quality/CpfDataQualityOperations.java','cpf-common/src/main/java/com/cpf/common/data/quality/InMemoryCpfDataQualityOperations.java','cpf-core/src/main/java/com/cpf/core/api/webhook/CpfWebhookOperations.java','cpf-starters/integration/webhook/src/main/java/com/cpf/starter/integration/webhook/InMemoryCpfWebhookOperations.java','cpf-admin/src/main/java/com/cpf/admin/opr/controller/AdmIntegrationClosureController.java','cpf-admin/frontend/src/generated/integrationClosureApi.ts','cpf-admin/frontend/src/app/methods/integrationClosureMethods.ts','cpf-tools/generator/templates/webhook/CpfGeneratedWebhookAdapter.java.tpl']
missing=[p for p in required if not (root/p).is_file()]
vendors=[]
for v in ('oracle','postgresql','mariadb'):
 b=root/f'cpf-tools/db/vendor/{v}'; paths=['source/17_integration_closure_lifecycle.sql','install/06_integration_closure_lifecycle.sql','migration/V102__integration_closure_lifecycle.sql','rollback/R102__integration_closure_lifecycle.sql','verify/102_verify_integration_closure_lifecycle.sql','runtime/integration-closure/integration_closure_queries.sql','pack.json']; vendors.append((v,all((b/p).is_file() for p in paths),paths));
 pack=json.loads((b/'pack.json').read_text()); assert pack['integrationClosurePack']['tableCount']==6
catalog=json.loads((root/'cpf-tools/generator/contracts/cpf-starter-catalog.json').read_text()); webhook=[m for m in catalog['modules'] if m.get('projectPath')==':cpf-starter-integration-webhook']
settings=(root/'settings.gradle').read_text(); route=(root/'cpf-admin/frontend/src/app/methods/routeClosureMethods.ts').read_text(); generated=(root/'cpf-admin/frontend/src/generated/integrationClosureApi.ts').read_text();
checks={'missing':missing,'vendorParity':{v:ok for v,ok,_ in vendors},'webhookCatalogExactlyOne':len(webhook)==1,'settingsCatalogDriven':'cpf-starter-catalog.json' in settings,'routeRawAbsoluteUrlAbsent':not re.search(r'https?://',route),'generatedClientRelativeRoutes':not any(token in generated for token in ('fetch(\"http://',"fetch('http://",'fetch(\"https://',"fetch('https://")),'coreProviderBoundary':not any('javax.crypto' in (root/p).read_text() for p in required if p.startswith('cpf-core/'))}
print(json.dumps(checks,ensure_ascii=False,indent=2));sys.exit(0 if not missing and all(checks['vendorParity'].values()) and all(v for k,v in checks.items() if k not in ('missing','vendorParity')) else 1)
