[CmdletBinding()]
param(
 [Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$ExpectedSha,[Parameter(Mandatory)][string]$ReviewerId,[Parameter(Mandatory)][string]$OutputRoot,
 [Parameter(Mandatory)][string]$MariaDbProfile,[Parameter(Mandatory)][string]$PostgreSqlProfile,[Parameter(Mandatory)][string]$OracleProfile,
 [Parameter(Mandatory)][string]$MariaDbUpgradeProfile,[Parameter(Mandatory)][string]$PostgreSqlUpgradeProfile,[Parameter(Mandatory)][string]$OracleUpgradeProfile,[Parameter(Mandatory)][string[]]$BackupManifestPath,
 [Parameter(Mandatory)][string]$ApprovedRegistry,[Parameter(Mandatory)][string]$AdmBaseUrl,[Parameter(Mandatory)][string]$BzaBaseUrl,
 [Parameter(Mandatory)][string]$AdmAuthState,[Parameter(Mandatory)][string]$BzaAuthState,[Parameter(Mandatory)][string]$AdmPrivilegedEndpoints,[Parameter(Mandatory)][string]$BzaPrivilegedEndpoints,
 [Parameter(Mandatory)][string]$AdmRouteMatrix,[Parameter(Mandatory)][string]$BzaRouteMatrix,[Parameter(Mandatory)][string]$AdmFailureMatrix,[Parameter(Mandatory)][string]$BzaFailureMatrix,[Parameter(Mandatory)][string]$AdmSecurityFixture,[Parameter(Mandatory)][string]$BzaSecurityFixture,[string[]]$ArtifactPaths=@()
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$rootPath=(Resolve-Path $Root).Path;$actual=(&git -C $rootPath rev-parse HEAD).Trim();if($ExpectedSha-notmatch'^[0-9a-f]{40}$'-or$actual-ne$ExpectedSha.ToLowerInvariant()){throw"Expected exact SHA $ExpectedSha but found $actual"};if((@(&git -C $rootPath status --porcelain=v1 --untracked-files=all)).Count-gt0){throw'Independent review requires clean fresh clone'}
$remote=(&git -C $rootPath remote get-url origin).Trim();if($remote-notmatch'freeangelsun/202412_01_CPF'){throw"Unexpected origin: $remote"};$out=[IO.Path]::GetFullPath($OutputRoot);New-Item $out -ItemType Directory -Force|Out-Null;$started=(Get-Date).ToUniversalTime().ToString('o')
& (Join-Path $rootPath 'cpf-tools/scripts/verify-cpf-qa34-final-closure.ps1') -Root $rootPath -OutputRoot (Join-Path $out 'closure') -MariaDbProfile $MariaDbProfile -PostgreSqlProfile $PostgreSqlProfile -OracleProfile $OracleProfile -MariaDbUpgradeProfile $MariaDbUpgradeProfile -PostgreSqlUpgradeProfile $PostgreSqlUpgradeProfile -OracleUpgradeProfile $OracleUpgradeProfile -BackupManifestPath $BackupManifestPath -ApprovedRegistry $ApprovedRegistry -AdmBaseUrl $AdmBaseUrl -BzaBaseUrl $BzaBaseUrl -AdmAuthState $AdmAuthState -BzaAuthState $BzaAuthState -AdmPrivilegedEndpoints $AdmPrivilegedEndpoints -BzaPrivilegedEndpoints $BzaPrivilegedEndpoints -AdmRouteMatrix $AdmRouteMatrix -BzaRouteMatrix $BzaRouteMatrix -AdmFailureMatrix $AdmFailureMatrix -BzaFailureMatrix $BzaFailureMatrix -AdmSecurityFixture $AdmSecurityFixture -BzaSecurityFixture $BzaSecurityFixture -ArtifactPaths $ArtifactPaths
if($LASTEXITCODE-and$LASTEXITCODE-ne0){throw"Final closure failed (exit=$LASTEXITCODE)"};if((&git -C $rootPath rev-parse HEAD).Trim()-ne$actual){throw'SHA changed'};if((@(&git -C $rootPath status --porcelain=v1 --untracked-files=all)).Count-gt0){throw'Independent review changed source tree'}
$files=@(Get-ChildItem $out -Recurse -File|ForEach-Object{[ordered]@{path=[IO.Path]::GetRelativePath($out,$_.FullName).Replace('\','/');sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant();bytes=$_.Length}})
$e=[ordered]@{schemaVersion=3;evidenceId='QA34-INDEPENDENT-FRESH-CLONE';sourceSha=$actual;resultSha=$actual;reviewerId=$ReviewerId;origin=$remote;sourceDirty=$false;command='verify-cpf-qa34-independent-review.ps1';startedAt=$started;finishedAt=(Get-Date).ToUniversalTime().ToString('o');exitCode=0;requirements=@('QA34-REQ-020');artifacts=$files;sanitized=$true;releaseEligible=$true};$ep=Join-Path $out 'CPF_QA34_INDEPENDENT_REVIEW.sanitized.json';[IO.File]::WriteAllText($ep,($e|ConvertTo-Json -Depth 15)+"`n",[Text.UTF8Encoding]::new($false));Write-Host"[CPF][QA34][PASS] independent review=$ep"
