[CmdletBinding()]
param(
 [string]$Root=(Get-Location).Path,
 [Parameter(Mandatory)][string]$MariaDbProfile,[Parameter(Mandatory)][string]$PostgreSqlProfile,[Parameter(Mandatory)][string]$OracleProfile,
 [Parameter(Mandatory)][string]$MariaDbUpgradeProfile,[Parameter(Mandatory)][string]$PostgreSqlUpgradeProfile,[Parameter(Mandatory)][string]$OracleUpgradeProfile,
 [Parameter(Mandatory)][string[]]$BackupManifestPath,
 [Parameter(Mandatory)][string]$ApprovedRegistry,[Parameter(Mandatory)][string]$AdmBaseUrl,[Parameter(Mandatory)][string]$BzaBaseUrl,
 [Parameter(Mandatory)][string]$AdmAuthState,[Parameter(Mandatory)][string]$BzaAuthState,[Parameter(Mandatory)][string]$AdmPrivilegedEndpoints,[Parameter(Mandatory)][string]$BzaPrivilegedEndpoints,
 [Parameter(Mandatory)][string]$AdmRouteMatrix,[Parameter(Mandatory)][string]$BzaRouteMatrix,[Parameter(Mandatory)][string]$AdmFailureMatrix,[Parameter(Mandatory)][string]$BzaFailureMatrix,[Parameter(Mandatory)][string]$AdmSecurityFixture,[Parameter(Mandatory)][string]$BzaSecurityFixture,
 [string[]]$ArtifactPaths=@(),[string]$EvidenceOutput='',[switch]$KeepWorkspace
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$Utf8NoBom=[Text.UTF8Encoding]::new($false);$rootPath=(Resolve-Path $Root).Path;$sha=(&git -C $rootPath rev-parse HEAD).Trim();if($sha-notmatch'^[0-9a-f]{40}$'){throw'exact SHA required'};if((@(&git -C $rootPath status --porcelain=v1 --untracked-files=all)).Count-gt0){throw'clean tree required'}
$stage=Join-Path ([IO.Path]::GetTempPath())("cpf-qa34-runtime-{0}"-f[guid]::NewGuid().ToString('N'));New-Item $stage -ItemType Directory -Force|Out-Null;if([string]::IsNullOrWhiteSpace($EvidenceOutput)){$EvidenceOutput=Join-Path $stage 'CPF_QA34_RUNTIME_MATRIX.sanitized.json'};$EvidenceOutput=[IO.Path]::GetFullPath($EvidenceOutput)
$qa33Req=@(Import-Csv (Join-Path $rootPath 'cpf-docs/quality/CPF_20260731_QA33_REQUIREMENT_MATRIX.csv')|ForEach-Object{$_.requirement_id});$qa33Scn=@(Import-Csv (Join-Path $rootPath 'cpf-docs/quality/CPF_20260731_QA33_SCENARIO_MATRIX.csv')|ForEach-Object{$_.scenario_id});$qa33Rows=@(Import-Csv (Join-Path $rootPath 'cpf-docs/quality/CPF_20260731_QA33_RESULT_MATRIX.csv')|ForEach-Object{$_.record_key});if($qa33Req.Count-ne138-or$qa33Scn.Count-ne414-or$qa33Rows.Count-ne552){throw'QA33 canonical count mismatch'}
$started=[DateTimeOffset]::UtcNow;$results=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[string]]::new()
function Safe([string]$v){return($v-replace'(?i)(password|secret|token|authorization|cookie)\s*[:=]\s*\S+','$1=***')}
function Step([string]$name,[scriptblock]$action){$st=[DateTimeOffset]::UtcNow;$code=0;$message='PASS';try{&$action;if($LASTEXITCODE-and$LASTEXITCODE-ne0){throw"exit=$LASTEXITCODE"}}catch{$code=1;$message=Safe $_.Exception.Message;$script:failures.Add("${name}:$message")}finally{$script:results.Add([ordered]@{name=$name;startedAt=$st.ToString('o');finishedAt=[DateTimeOffset]::UtcNow.ToString('o');exitCode=$code;result=$message})}}
Step 'source-closure' {&python (Join-Path $rootPath 'cpf-tools/scripts/verify-cpf-qa34-source-closure.py') --root $rootPath --release --evidence-output (Join-Path $stage 'source-closure.sanitized.json')}
Step 'java25-fresh-cache' {& (Join-Path $rootPath 'cpf-tools/scripts/verify-cpf-qa34-java-build.ps1') -Root $rootPath -EvidenceOutput (Join-Path $stage 'java.sanitized.json')}
Step 'frontend-three-browser' {& (Join-Path $rootPath 'cpf-tools/scripts/verify-cpf-qa34-frontend-runtime.ps1') -Root $rootPath -ApprovedRegistry $ApprovedRegistry -AdmBaseUrl $AdmBaseUrl -BzaBaseUrl $BzaBaseUrl -AdmAuthState $AdmAuthState -BzaAuthState $BzaAuthState -AdmPrivilegedEndpoints $AdmPrivilegedEndpoints -BzaPrivilegedEndpoints $BzaPrivilegedEndpoints -AdmRouteMatrix $AdmRouteMatrix -BzaRouteMatrix $BzaRouteMatrix -AdmFailureMatrix $AdmFailureMatrix -BzaFailureMatrix $BzaFailureMatrix -AdmSecurityFixture $AdmSecurityFixture -BzaSecurityFixture $BzaSecurityFixture -EvidenceOutput (Join-Path $stage 'frontend.sanitized.json')}
Step 'three-vendor-db' {& (Join-Path $rootPath 'cpf-tools/scripts/invoke-cpf-qa34-db-runtime-matrix.ps1') -Root $rootPath -MariaDbProfile $MariaDbProfile -PostgreSqlProfile $PostgreSqlProfile -OracleProfile $OracleProfile -MariaDbUpgradeProfile $MariaDbUpgradeProfile -PostgreSqlUpgradeProfile $PostgreSqlUpgradeProfile -OracleUpgradeProfile $OracleUpgradeProfile -BackupManifestPath $BackupManifestPath -AllowDestructiveRollback -EvidenceRoot (Join-Path $stage 'db')}
Step 'batch-control-plane-static' {&python (Join-Path $rootPath 'cpf-tools/scripts/verify-cpf-qa33-batch-control-plane.py') --root $rootPath --json-report (Join-Path $stage 'batch-control-plane.json')}
Step 'batch-two-worker-process-kill' {& (Join-Path $rootPath 'cpf-tools/scripts/smoke-bat-two-worker-runtime.ps1') -Root $rootPath -ResultDir (Join-Path $stage 'batch-two-worker')}
Step 'qa34-integration-test' {& (Join-Path $rootPath 'gradlew.bat') qa34IntegrationTest --no-daemon --max-workers=1 --stacktrace}
Step 'gateway-bat-runtime' {& (Join-Path $rootPath 'cpf-tools/scripts/smoke-gateway-bat-runtime.ps1') -Root $rootPath -ResultDir (Join-Path $stage 'gateway-bat') -DatabaseProfilePath $MariaDbProfile}
Step 'service-call-runtime' {& (Join-Path $rootPath 'cpf-tools/scripts/smoke-service-call-engine-runtime.ps1') -Root $rootPath -ResultDir (Join-Path $stage 'service-call') -RunRuntime -RequireRuntime}
Step 'supply-chain' {& (Join-Path $rootPath 'cpf-tools/scripts/generate-cpf-supply-chain-evidence.ps1') -Root $rootPath -OutputDir (Join-Path $stage 'supply-chain') -ArtifactPaths $ArtifactPaths}
if((&git -C $rootPath rev-parse HEAD).Trim()-ne$sha){$failures.Add('SHA changed during runtime matrix')};if((@(&git -C $rootPath status --porcelain=v1 --untracked-files=all)).Count-gt0){$failures.Add('Source tree changed during runtime matrix')}
$artifacts=@(Get-ChildItem $stage -Recurse -File|Where-Object{$_.FullName-ne$EvidenceOutput}|ForEach-Object{[ordered]@{path=[IO.Path]::GetRelativePath($stage,$_.FullName).Replace('\','/');sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant();bytes=$_.Length}})
$e=[ordered]@{schemaVersion=3;evidenceId='QA34-FULL-RUNTIME-MATRIX';sourceSha=$sha;resultSha=if($failures.Count-eq0){$sha}else{$null};branch=(&git -C $rootPath branch --show-current).Trim();sourceDirty=$false;startedAt=$started.ToString('o');finishedAt=[DateTimeOffset]::UtcNow.ToString('o');exitCode=if($failures.Count-eq0){0}else{1};requirements=@((1..18|ForEach-Object{'QA34-REQ-{0:D3}'-f$_})+$qa33Req);scenarios=$qa33Scn;resultRows=$qa33Rows;results=$results;failures=$failures;artifacts=$artifacts;sanitized=$true;releaseEligible=($failures.Count-eq0)}
New-Item (Split-Path $EvidenceOutput) -ItemType Directory -Force|Out-Null;[IO.File]::WriteAllText($EvidenceOutput,($e|ConvertTo-Json -Depth 20)+"`n",$Utf8NoBom)
if(-not$KeepWorkspace-and$failures.Count-eq0-and$EvidenceOutput-notlike"$stage*"){Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue}
if($failures.Count-gt0){throw"QA34 runtime matrix failed: $($failures-join'; ')"};Write-Host"[CPF][QA34][PASS] runtime matrix=$EvidenceOutput"
