#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path

VENDORS=("oracle","postgresql","mariadb")
TABLES=("CPF_CACHE_INVALIDATION_EVENT","CPF_CACHE_INVALIDATION_CHECKPOINT")
LIFECYCLE=(
    "source/16_cache_invalidation_ledger.sql",
    "install/05_cache_invalidation_ledger.sql",
    "migration/V101__cache_invalidation_ledger.sql",
    "rollback/R101__cache_invalidation_ledger.sql",
    "runtime/cache/cache_invalidation_queries.sql",
    "verify/101_verify_cache_invalidation_ledger.sql",
)

def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def verify(repo: Path) -> dict:
    repo=repo.resolve()
    coordinator=repo/'cpf-common/src/main/java/com/cpf/common/cache/CpfCacheInvalidationCoordinator.java'
    store=repo/'cpf-starters/data/cache-valkey/src/main/java/com/cpf/starter/data/cache/valkey/JdbcCpfCacheInvalidationStore.java'
    auto=repo/'cpf-starters/data/cache-valkey/src/main/java/com/cpf/starter/data/cache/valkey/CpfValkeyAutoConfiguration.java'
    compat=repo/'cpf-starters/data/cache-valkey/src/main/java/com/cpf/starter/data/cache/valkey/CpfRedisCompatibilityAutoConfiguration.java'
    adm=repo/'cpf-admin/src/main/java/com/cpf/admin/opr/service/AdmCacheOperationService.java'
    required=[coordinator,store,auto,compat,adm]
    for vendor in VENDORS:
        required.extend(repo/f'cpf-tools/db/vendor/{vendor}'/rel for rel in LIFECYCLE)
        required.append(repo/f'cpf-tools/db/vendor/{vendor}/pack.json')
    missing=[p.relative_to(repo).as_posix() for p in required if not p.is_file()]
    if missing: raise FileNotFoundError('missing: '+','.join(missing))

    c=coordinator.read_text(encoding='utf-8')
    s=store.read_text(encoding='utf-8')
    a=auto.read_text(encoding='utf-8')
    x=compat.read_text(encoding='utf-8')
    m=adm.read_text(encoding='utf-8')
    source_checks={
        'durableFirst': c.index('durable.append') < c.index('apply(persisted)'),
        'checkpointAfterApply': c.index('apply(persisted)') < c.index('durable.checkpoint(consumerId(), persisted.eventId())'),
        'reconcileAfterCheckpoint': all(token in c for token in ('loadAfter(', 'checkpoint(consumerId(), event.eventId())')),
        'fastSignalBestEffort': 'Durable ledger + reconciliation remain authoritative.' in c,
        'threeVendorDetection': all(token in s for token in ('ORACLE','POSTGRESQL','MARIADB','DatabaseProductName')),
        'mariadbPagination': 'LIMIT ?' in s,
        'oraclePostgresPagination': 'FETCH FIRST ? ROWS ONLY' in s,
        'generatedKeyColumn': 'new String[] {"EVENT_ID"}' in s,
        'monotonicCheckpoint': 'LAST_EVENT_ID < ?' in s,
        'idempotentEventKey': 'findByEventKey(event.eventKey())' in s and 'DataIntegrityViolationException' in s and 'assertSameRequest' in s and 'eventKey conflict' in s,
        'namespaceKeyUsesSqlNull': 'statement.setNull(4, java.sql.Types.VARCHAR)' in s,
        'autoWiresStore': 'JdbcCpfCacheInvalidationStore cpfCacheInvalidationStore' in a,
        'autoWiresCoordinator': 'CpfCacheInvalidationCoordinator cpfCacheInvalidationCoordinator' in a,
        'autoWiresListener': 'cpfValkeyInvalidationListenerContainer' in a and 'ChannelTopic' in a,
        'compatDurableFirst': all(token in x for token in ('JdbcCpfCacheInvalidationStore','CpfCacheInvalidationCoordinator','InvalidationListenerContainer')),
        'admConsumer': all(token in m for token in ('requireCoordinator()','reconcileNow()','invalidations.backlog')),
    }
    if not all(source_checks.values()): raise AssertionError(source_checks)

    vendor_results={}
    for vendor in VENDORS:
        root=repo/f'cpf-tools/db/vendor/{vendor}'
        texts={rel:(root/rel).read_text(encoding='utf-8') for rel in LIFECYCLE}
        pack=json.loads((root/'pack.json').read_text(encoding='utf-8'))
        cache_pack=pack.get('cacheInvalidationPack',{})
        combined='\n'.join(texts.values()).upper()
        table_coverage={table: all(table in texts[rel].upper() for rel in LIFECYCLE) for table in TABLES}
        parity=(root/LIFECYCLE[0]).read_bytes()==(root/LIFECYCLE[1]).read_bytes()==(root/LIFECYCLE[2]).read_bytes()
        rollback_order=texts[LIFECYCLE[3]].upper().find(TABLES[1]) < texts[LIFECYCLE[3]].upper().find(TABLES[0])
        dialect_checks={
            'oracle': 'VARCHAR2' in combined and 'IDENTITY' in combined and 'SYSTIMESTAMP' in combined,
            'postgresql': 'BIGINT GENERATED BY DEFAULT AS IDENTITY' in combined and 'TIMESTAMP(6) WITH TIME ZONE' in combined,
            'mariadb': 'AUTO_INCREMENT' in combined and 'ENGINE=INNODB' in combined and 'CURRENT_TIMESTAMP(6)' in combined,
        }
        ddl = texts[LIFECYCLE[0]].upper()
        cache_key_line = next(line.strip() for line in ddl.splitlines() if 'CACHE_KEY_VALUE' in line)
        nullable_cache_key = 'NOT NULL' not in cache_key_line and "DEFAULT ''" not in cache_key_line
        oracle_empty_string_safe = vendor != 'oracle' or "DEFAULT ''" not in ddl
        vr={'tableCoverage':table_coverage,'sourceInstallMigrationByteParity':parity,'rollbackDependencyOrder':rollback_order,'dialectSpecific':dialect_checks[vendor],'packDiscoverable':all(cache_pack.get(k) for k in ('canonicalSource','freshInstall','migration','rollback','runtimeQueries','verify')) and cache_pack.get('officialVendor') is True,'nullableNamespaceCacheKey':nullable_cache_key,'oracleEmptyStringSafe':oracle_empty_string_safe,'sha256':{rel:digest(root/rel) for rel in LIFECYCLE}}
        if not all(table_coverage.values()) or not parity or not rollback_order or not dialect_checks[vendor] or not nullable_cache_key or not oracle_empty_string_safe:
            raise AssertionError({vendor:vr})
        vendor_results[vendor]=vr
    return {'status':'PASS','sourceChecks':source_checks,'vendors':vendor_results}

def main():
    p=argparse.ArgumentParser(); p.add_argument('--repo-root',default='.'); p.add_argument('--report-json',required=True); a=p.parse_args()
    result=verify(Path(a.repo_root)); Path(a.report_json).write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(json.dumps(result,ensure_ascii=False))
if __name__=='__main__': main()
