plugins { id 'org.springframework.boot'; id 'maven-publish' }
group='com.cpf.batch'
dependencies {
    implementation project(':cpf-batch:contract')
    implementation project(':cpf-batch:runtime-common')
    implementation project(':cpf-core')
    implementation project(':cpf-common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation project(':cpf-batch:testkit')
}
tasks.named('bootJar') { archiveFileName = "cpf-batch-control-server-${project.version}.jar" }
tasks.named('test') { useJUnitPlatform() }


publishing {
    publications {
        executable(MavenPublication) {
            groupId = 'com.cpf.batch'
            artifactId = 'cpf-batch-control-server'
            version = project.version.toString()
            artifact tasks.named('bootJar')
        }
    }
}
