plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.internal'

dependencies {
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    api project(':framework:core')
    api project(':framework:base-runtime')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-context'
    compileOnly 'org.springframework.security:spring-security-core'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

tasks.named('test') { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-security' } } }
