plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-core')
    api 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-web'
    implementation 'org.springframework:spring-webmvc'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'org.springframework.session:spring-session-jdbc'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-starter-security' } } }
