# ACC ⑤뱢 濡쒖뺄 ?ㅽ뻾???섍꼍 ?ㅼ젙?낅땲??
# Java 21 諛?Spring Boot 3.0??留욎텣 濡쒖뺄 媛쒕컻 ?꾩슜 援ъ꽦?낅땲??

spring:
  datasource:
    hikari:
      data-source-properties:
        logger: SLF4J
    acc:
#     jndi-name: java:comp/env/jdbc/accDS
      url: ${ACC_DB_URL:jdbc:mariadb://localhost:3306/accDB}
      username: ${ACC_DB_USERNAME:cpf_acc_app}
      password: ${ACC_DB_PASSWORD:cpf_local_pw}
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/acc-mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/acc/**/*.xml
  type-aliases-package: cpf.acc.bse.entity



server:
  port: 8080

# 濡쒓렇 ?ㅼ젙
logging:
  config: classpath:log/logback-local.xml
  # 濡쒓렇 ?덈꺼 ?ㅼ젙
  level:
    root: INFO # ?꾩껜 ?좏뵆由ъ??댁뀡??湲곕낯 濡쒓렇 ?덈꺼
    cpf.pfw: DEBUG  # PFW ?꾨젅?꾩썙??濡쒓렇 ?덈꺼
    cpf.cmn: DEBUG  # CMN 媛쒕컻 怨듯넻 濡쒓렇 ?덈꺼
    cpf.acc: DEBUG  # ACC ⑤뱢??????붾쾭源?濡쒓렇 ?덈꺼


