# ACC 모듈 공통 설정 파일입니다.
# Spring Boot 3.0 및 Java 21 환경에서 실행되도록 기본 구성 정보를 제공합니다.

spring:
  application:
    name: acc

  profiles:
    active: local
    include: pfw, cmn  # PFW 프레임워크와 CMN 개발 공통 설정을 함께 로드합니다.

  datasource:
    hikari:
      data-source-properties:
        logger: SLF4J
    acc:
      #     jndi-name: java:comp/env/jdbc/accDS
      url: jdbc:mariadb://localhost:3306/accDB
      username: root
      password: test
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/acc-mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/acc/**/*.xml
  type-aliases-package: fps.acc.bse.entity

server:
  port: 8080

# 로그 설정
logging:
  config: classpath:log/logback-spring.xml
  level:
    root: INFO # 전체 애플리케이션의 기본 로그 레벨
    fps.pfw: DEBUG  # PFW 프레임워크 모듈 로그 레벨
    fps.cmn: DEBUG  # CMN 개발 공통 모듈 로그 레벨
    fps.acc: DEBUG  # ACC 모듈 로그 레벨


