spring:
  datasource:
    acc:
#     jndi-name: java:comp/env/jdbc/accDS
      url: ${ACC_DB_URL:jdbc:mariadb://localhost:3306/accDB}
      username: ${ACC_DB_USERNAME:cpf_acc_app}
      password: ${ACC_DB_PASSWORD:cpf_local_pw}
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/acc-mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/acc/**/*.xml
  type-aliases-package: cpf.acc.bse.entity


server:
  port: 8080

# CPF 설정 설명입니다.
logging:
  config: classpath:log/logback-test.xml
  # CPF 설정 설명입니다.
  level:
    root: INFO # CPF 설정 설명입니다.
    cpf.pfw: INFO  # PFW 한글 한글
    cpf.cmn: INFO  # CPF 설정 설명입니다.
    cpf.acc: INFO  # ACC 한글 한글

