# ACC 紐⑤뱢 怨듯넻 ?ㅼ젙 ?뚯씪?낅땲??
# Spring Boot 3.0 諛?Java 21 ?섍꼍?먯꽌 ?ㅽ뻾?섎룄濡?湲곕낯 援ъ꽦 ?뺣낫瑜??쒓났?⑸땲??

spring:
  application:
    name: acc

  profiles:
    active: local
    include: pfw, cmn  # PFW ?꾨젅?꾩썙?ъ? CMN 媛쒕컻 怨듯넻 ?ㅼ젙???④퍡 濡쒕뱶?⑸땲??

  datasource:
    hikari:
      data-source-properties:
        logger: SLF4J
    acc:
      #     jndi-name: java:comp/env/jdbc/accDS
      url: jdbc:mariadb://localhost:3306/accDB
      username: root
      password: test
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/acc-mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/acc/**/*.xml
  type-aliases-package: cpf.acc.bse.entity

server:
  port: 8080

# 濡쒓렇 ?ㅼ젙
logging:
  config: classpath:log/logback-spring.xml
  level:
    root: INFO # ?꾩껜 ?좏뵆由ъ??댁뀡??湲곕낯 濡쒓렇 ?덈꺼
    cpf.pfw: DEBUG  # PFW ?꾨젅?꾩썙??紐⑤뱢 濡쒓렇 ?덈꺼
    cpf.cmn: DEBUG  # CMN 媛쒕컻 怨듯넻 紐⑤뱢 濡쒓렇 ?덈꺼
    cpf.acc: DEBUG  # ACC 紐⑤뱢 濡쒓렇 ?덈꺼



