# ACC 서비스 기본 설정입니다.

spring:
  config:
    import:
      - optional:classpath:application-pfw.yml
      - optional:classpath:application-pfw-${spring.profiles.active:local}.yml
      - optional:classpath:application-cmn.yml
      - optional:classpath:application-cmn-${spring.profiles.active:local}.yml
      - optional:classpath:application-acc.yml
      - optional:classpath:application-acc-${spring.profiles.active:local}.yml
  application:
    name: acc
  profiles:
    active: local
    include: pfw, cmn
  datasource:
    hikari:
      data-source-properties:
        logger: SLF4J
    acc:
      url: ${ACC_DB_URL:jdbc:mariadb://localhost:3306/accDB}
      username: ${ACC_DB_USERNAME:cpf_acc_app}
      password: ${ACC_DB_PASSWORD:cpf_local_pw}
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/acc-mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/acc/**/*.xml
  type-aliases-package: cpf.acc.bse.entity

server:
  port: ${ACC_SERVER_PORT:8080}

logging:
  config: classpath:log/logback-local.xml
  level:
    root: INFO
    cpf.pfw: DEBUG
    cpf.cmn: DEBUG
    cpf.acc: DEBUG

---
# prod에서는 DB password 기본값을 제거합니다.
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    acc:
      url: ${ACC_DB_URL}
      username: ${ACC_DB_USERNAME}
      password: ${ACC_DB_PASSWORD}

logging:
  config: classpath:log/logback-prod.xml
  level:
    root: INFO
    cpf.pfw: INFO
    cpf.cmn: INFO
    cpf.acc: INFO
