plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.internal'

dependencies {
    api project(':framework:core')
    api project(':framework:base-runtime')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-aop'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    compileOnly 'org.springframework:spring-tx'
}

tasks.named('test') { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-data-persistence' } } }
