plugins { id 'java-library'; id 'maven-publish' }
group='com.cpf.starter'
dependencies {
 api project(':cpf-core')
 implementation project(':cpf-starter-foundation-base')
 implementation project(':cpf-starter-integration-resilience')
 implementation 'org.springframework.boot:spring-boot-autoconfigure'
 implementation 'org.springframework.boot:spring-boot-starter-actuator'
 annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
 testImplementation 'org.junit.jupiter:junit-jupiter'
 testImplementation 'org.assertj:assertj-core'
}
tasks.named('test'){useJUnitPlatform()}
publishing { publications { mavenJava(MavenPublication){from components.java;artifactId='cpf-starter-integration-tcp'} } }
