import com.cpf.security.common.security.crypto.JceCpfCryptoOperations;
import com.cpf.data.api.encryption.*;
import com.cpf.data.quality.*;
import com.cpf.foundation.time.*;
import com.cpf.security.api.crypto.*;
import com.cpf.data.api.encryption.*;
import com.cpf.data.api.quality.*;
import com.cpf.foundation.time.*;
import com.cpf.integration.api.webhook.*;
import java.net.URI; import java.nio.charset.StandardCharsets; import java.security.SecureRandom; import java.time.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.*;
public final class IntegrationClosureHarness {
 private static void check(boolean v,String m){if(!v)throw new AssertionError(m);} private static void expect(Class<? extends Throwable> t,Runnable r){try{r.run();throw new AssertionError("expected "+t.getSimpleName());}catch(Throwable x){if(!t.isInstance(x))throw x;}}
 public static void main(String[] args){crypto();time();quality();webhook();System.out.println("PASS integration-closure crypto/time/field-encryption/data-quality/webhook");}
 static void crypto(){byte[] k1=new byte[32],k2=new byte[32];Arrays.fill(k1,(byte)1);Arrays.fill(k2,(byte)2);CpfCryptoPolicy policy=new CpfCryptoPolicy(Set.of("AES/GCM/NOPADDING"),Set.of("SUNJCE"),Set.of("DES","DESEDE"),256,true);JceCpfCryptoOperations crypto=new JceCpfCryptoOperations(Map.of("v1",k1,"v2",k2),"v1",policy,new SecureRandom(new byte[]{1,2,3}));byte[] aad="record:ssn".getBytes(StandardCharsets.UTF_8);CpfEnvelopeCiphertext c=crypto.encrypt("900101-1234567".getBytes(StandardCharsets.UTF_8),aad);check(new String(crypto.decrypt(c,aad),StandardCharsets.UTF_8).equals("900101-1234567"),"round trip");expect(SecurityException.class,()->crypto.decrypt(c,"wrong".getBytes(StandardCharsets.UTF_8)));CpfRekeyResult rk=crypto.rekey(c,aad,"v2");check(rk.currentKeyVersion().equals("v2"),"rekey version");check(new String(crypto.decrypt(rk.ciphertext(),aad),StandardCharsets.UTF_8).equals("900101-1234567"),"rekey decrypt");check(crypto.searchableToken("abc".getBytes(),"v1").equals(crypto.searchableToken("abc".getBytes(),"v1")),"token deterministic");DefaultCpfFieldEncryptionOperations fields=new DefaultCpfFieldEncryptionOperations(crypto);CpfProtectedRecordService records=new CpfProtectedRecordService(fields);var r=records.save("r1","customerId","ABC-123",CpfFieldClassification.PERSONAL,true);check(!r.value().maskedPreview().contains("ABC-123"),"masked");check(records.reveal("r1","customerId","operator","approved support").equals("ABC-123"),"reveal");}
 static void time(){DeterministicCpfTimeOperations t=new DeterministicCpfTimeOperations(Instant.parse("2026-03-29T00:59:59Z"));CpfDeadline d=t.deadline(Duration.ofSeconds(2));t.advance(Duration.ofSeconds(1));check(!d.expired(t),"deadline early");t.advance(Duration.ofSeconds(1));check(d.expired(t),"deadline expiry");CpfTimeSnapshot s=t.snapshot(ZoneId.of("Europe/Paris"),Duration.ofSeconds(1));check(s.businessTime().getZone().equals(ZoneId.of("Europe/Paris")),"business zone");t.setEstimatedSkew(Duration.ofSeconds(2));check(!t.snapshot(ZoneId.of("UTC"),Duration.ofSeconds(1)).healthy(),"skew health");CpfLeaseTimeService leases=new CpfLeaseTimeService(t);var l=leases.acquire("job","node1",Duration.ofSeconds(10));check(leases.valid(l),"lease valid");}
 static void quality(){InMemoryCpfDataQualityOperations q=new InMemoryCpfDataQualityOperations();q.register(new CpfDataQualityRule("email",1,"email","REGEX:.+@.+\\..+",CpfDataQualityRule.Severity.ERROR,CpfDataQualityRule.State.ACTIVE,Map.of()),"admin","initial rule");var bad=q.validate("r1",Map.of("email","bad"));check(!bad.accepted()&&!bad.quarantineId().isBlank(),"quarantine");var item=q.quarantine(bad.quarantineId()).orElseThrow();q.correct(item.quarantineId(),item.version(),Map.of("email","a@b.com"),"admin","approved correction",true);check(q.replay(item.quarantineId(),"admin","replay").accepted(),"quality replay");}
 static void webhook(){byte[] secret="01234567890123456789012345678901".getBytes(StandardCharsets.UTF_8);var ops=new InMemoryCpfWebhookOperations(new CpfWebhookEndpointValidator(Set.of("example.com")),Map.of("v1",secret),2,Duration.ofSeconds(1));ops.register(new CpfWebhookEndpoint("ep",URI.create("https://example.com/callback"),"v1",Set.of("ORDER"),true,1),"admin","register");expect(SecurityException.class,()->new CpfWebhookEndpointValidator(Set.of()).validate(URI.create("https://127.0.0.1/cb")));Instant now=Instant.parse("2026-08-06T00:00:00Z");var d=ops.enqueue("ep","evt","ORDER","{}".getBytes(),"idemp",now);check(ops.enqueue("ep","evt","ORDER","{}".getBytes(),"idemp",now).deliveryId().equals(d.deliveryId()),"idempotent");try{ExecutorService pool=Executors.newFixedThreadPool(8);List<Future<String>> futures=new ArrayList<>();for(int i=0;i<32;i++)futures.add(pool.submit(()->ops.enqueue("ep","evt","ORDER","{}".getBytes(),"idemp",now).deliveryId()));Set<String> ids=new HashSet<>();for(Future<String> f:futures)ids.add(f.get());pool.shutdownNow();check(ids.size()==1,"concurrent idempotency");}catch(Exception e){throw new IllegalStateException(e);}var a=ops.deliverNext("ep",now,(e,h,p)->new CpfWebhookOperations.TransportResult(503,false,"down"));check(a.delivery().state()==CpfWebhookDelivery.State.RETRY,"retry");var b=ops.deliverNext("ep",now.plusSeconds(2),(e,h,p)->new CpfWebhookOperations.TransportResult(503,false,"down"));check(b.delivery().state()==CpfWebhookDelivery.State.DLQ,"dlq");var replay=ops.replay(b.delivery().deliveryId(),b.delivery().version(),"admin","recover",now.plusSeconds(3));check(replay.state()==CpfWebhookDelivery.State.RETRY,"replay");check(ops.deliverNext("ep",now.plusSeconds(3),(e,h,p)->new CpfWebhookOperations.TransportResult(204,false,"")).delivery().state()==CpfWebhookDelivery.State.DELIVERED,"delivered");var u=ops.enqueue("ep","evt2","ORDER","{}".getBytes(),"unknown",now.plusSeconds(4));var ua=ops.deliverNext("ep",now.plusSeconds(4),(e,h,p)->new CpfWebhookOperations.TransportResult(0,true,"timeout"));check(ua.delivery().state()==CpfWebhookDelivery.State.UNKNOWN,"unknown");expect(ConcurrentModificationException.class,()->ops.replay(ua.delivery().deliveryId(),ua.delivery().version()-1,"admin","stale version must fail",now.plusSeconds(5)));var ur=ops.replay(ua.delivery().deliveryId(),ua.delivery().version(),"admin","approved reconcile",now.plusSeconds(5));check(ur.state()==CpfWebhookDelivery.State.RETRY,"unknown replay");}
}
