spring:
  application:
    name: cpf-local-runtime
server:
  address: 127.0.0.1
  port: 8080

cpf:
  environment: local
  local:
    runtime:
      enabled: false
      allow-remote-bind: false
    modules:
      core: true
      common: true
      gateway: true
      admin: true
      biz-admin: false
