<script lang="ts">
import { defineComponent } from "vue";
import { admConsoleMixin } from "../../app/admConsoleMixin";
import CpfIcon from "../../components/CpfIcon.vue";
export default defineComponent({name:"AdmDashboardPage",components:{CpfIcon},mixins:[admConsoleMixin],computed:{
 instances(){return this.serviceRegistryResult?.instances||[]}, health(){return this.serviceRegistryResult?.health||[]}, unknown(){return this.reliabilityResult?.unknownResults||[]}, dlq(){return this.reliabilityResult?.dlq||[]},
 upCount(){return this.instances.filter((x:any)=>["UP","ACTIVE","READY"].includes(String(x.instanceStatus||x.status||"").toUpperCase())).length},
 unhealthy(){return this.health.filter((x:any)=>!["UP","HEALTHY","OK"].includes(String(x.healthStatus||x.status||"").toUpperCase())).length},
 recentCalls(){return (this.serviceRegistryResult?.callHistory||[]).slice(0,6)}
}});
</script>
<template><div class="cpf-page"><div class="cpf-page-heading"><div><p class="eyebrow">CONTROL PLANE</p><h2>운영 대시보드</h2><p>서비스 상태와 복구 대기 항목을 한 화면에서 우선순위로 확인합니다.</p></div><button class="ghost" @click="loadInitialData"><CpfIcon name="refresh"/> 새로고침</button></div>
<section class="cpf-kpi-grid"><div class="cpf-stat-card"><div class="top"><span class="label">등록 인스턴스</span><span class="icon"><CpfIcon name="service"/></span></div><strong class="value">{{instances.length}}</strong><span class="sub">정상 {{upCount}}</span></div><div class="cpf-stat-card"><div class="top"><span class="label">비정상 Health</span><span class="icon"><CpfIcon name="incident"/></span></div><strong class="value">{{unhealthy}}</strong><span class="sub">즉시 확인 대상</span></div><div class="cpf-stat-card"><div class="top"><span class="label">결과 미확정</span><span class="icon"><CpfIcon name="recovery"/></span></div><strong class="value">{{unknown.length}}</strong><span class="sub">Reconciliation 필요</span></div><div class="cpf-stat-card"><div class="top"><span class="label">DLQ</span><span class="icon"><CpfIcon name="activity"/></span></div><strong class="value">{{dlq.length}}</strong><span class="sub">재처리 후보</span></div></section>
<div class="cpf-grid-2"><section class="cpf-card"><div class="cpf-card-head"><h2>서비스 상태</h2></div><div class="cpf-card-body"><div class="cpf-topology"><article v-for="item in instances.slice(0,8)" :key="String(item.instanceId)" class="cpf-node"><div class="cpf-node-title"><strong>{{item.serviceId||'-'}} / {{item.endpointCode||'-'}}</strong><span class="cpf-status" :class="['UP','ACTIVE','READY'].includes(String(item.instanceStatus||'').toUpperCase())?'success':'danger'">{{item.instanceStatus||'UNKNOWN'}}</span></div><p class="meta">{{item.instanceName||item.instanceId}}</p></article><p v-if="!instances.length" class="cpf-empty">등록된 서비스 인스턴스가 없습니다.</p></div></div></section><section class="cpf-card"><div class="cpf-card-head"><h2>최근 Service Call</h2></div><div class="cpf-card-body"><ul class="cpf-timeline"><li v-for="item in recentCalls" :key="String(item.callId||item.transactionId)"><strong>{{item.serviceId||item.endpointCode||'SERVICE'}}</strong><div class="meta">{{item.callStatus||item.status}} · {{item.durationMs??'-'}}ms · {{item.transactionId||'-'}}</div></li><li v-if="!recentCalls.length" class="cpf-empty">최근 호출 이력이 없습니다.</li></ul></div></section></div></div></template>