<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {fetchCenterCutJobs,fetchJobDefinitionDetail,fetchJobDefinitions,fetchPathAliases,saveJobDefinition,transitionJobDefinition,validateJobDefinition} from '../batch-runtime-control/api'
import ParameterSchemaEditor from '../../components/parameters/ParameterSchemaEditor.vue'
import BatchJobGovernancePanel from './BatchJobGovernancePanel.vue'
import type {ParameterDefinition,ParameterType} from '../../components/parameters/parameterSchema'

type Parameter=ParameterDefinition
type ExecutorOption={value:string;label:string;description:string}
const definitions=ref<Array<Record<string,any>>>([]);const centerCutJobs=ref<Array<Record<string,any>>>([]);const pathAliases=ref<Array<Record<string,any>>>([]);const loading=ref(false);const error=ref('');const validation=ref<Record<string,any>>({});const actionResult=ref<Record<string,any>>({});
const form=reactive({jobId:'',definitionVersion:1,jobName:'',executorType:'SPRING_BATCH',state:'DRAFT',ownerDomain:'BAT',description:'',triggerType:'CRON',triggerExpression:'0 0 1 * * *',timezone:'Asia/Seoul',misfirePolicy:'FAIL_CLOSED',agentPool:'DEFAULT',zone:'',maxConcurrency:1,timeoutSeconds:3600,restartable:true,maxAttempts:1,initialBackoffSeconds:0,multiplier:1,maxBackoffSeconds:0,skipLimit:0,unknownResultPolicy:'FAIL_CLOSED',compensationReference:'',alertDelaySeconds:0,slaSeconds:0,notifyOnFailure:true,notifyOnMissed:true,executorReference:'',checksum:'',reason:'배치 Job Definition 등록',effectiveFrom:'',effectiveUntil:'',expectedRowVersion:0,parameters:[] as Parameter[],dependencies:[] as Array<{relatedJobId:string,condition:string,timeoutSeconds:number,required:boolean}>})
const executorTypes:ExecutorOption[]=[
 {value:'SPRING_BATCH',label:'Java / Spring Batch',description:'등록된 Spring Batch Job 또는 @CpfBatchJob 기반 Java 배치를 실행합니다.'},
 {value:'APPROVED_SHELL',label:'승인 Shell',description:'임의 절대경로가 아닌 승인 SCRIPT Catalog만 실행합니다.'},
 {value:'FILE_WATCH',label:'파일 감시',description:'승인 PATH_ALIAS 아래 파일의 생성·안정화·무결성을 Worker가 확인합니다.'},
 {value:'FILE_PROCESS',label:'파일 처리',description:'승인 PATH_ALIAS와 Processor Catalog를 사용해 파일을 처리합니다.'},
 {value:'FILE_TRANSFER',label:'파일 전송',description:'승인된 경로/전송 계약을 사용합니다.'},
 {value:'CENTER_CUT',label:'Center-Cut',description:'등록된 Center-Cut Job을 CEC Runner가 실행합니다.'},
 {value:'SERVICE_CALL',label:'Service 호출',description:'승인된 SERVICE Operation을 호출합니다.'},
 {value:'MESSAGE_TRIGGER',label:'Message Trigger',description:'등록된 메시지 실행 계약을 사용합니다.'},
 {value:'PROTOCOL_ADAPTER',label:'Protocol Adapter',description:'등록된 Protocol Adapter를 호출합니다.'}
]
const preview=computed(()=>buildDefinition());const immutableVersion=computed(()=>['PUBLISHED','RETIRED'].includes(form.state));const hasSelfDependency=computed(()=>form.dependencies.some(d=>d.relatedJobId.trim()!==''&&d.relatedJobId.trim()===form.jobId.trim()));
const selectedExecutor=computed(()=>executorTypes.find(v=>v.value===form.executorType));const isFileWatch=computed(()=>form.executorType==='FILE_WATCH');const isCenterCut=computed(()=>form.executorType==='CENTER_CUT');const isShell=computed(()=>form.executorType==='APPROVED_SHELL');
const centerCutId=computed({get:()=>form.executorReference.startsWith('CENTER_CUT:')?form.executorReference.slice('CENTER_CUT:'.length):'',set:(v:string)=>form.executorReference=v?`CENTER_CUT:${v}`:''});
const shellCatalogKey=computed({get:()=>form.executorReference.startsWith('SCRIPT:')?form.executorReference.slice('SCRIPT:'.length):'',set:(v:string)=>form.executorReference=v?`SCRIPT:${v.trim()}`:''});
const fileWatchAlias=computed({get:()=>form.executorReference.startsWith('FILE_WATCH:')?form.executorReference.slice('FILE_WATCH:'.length):'',set:(v:string)=>{form.executorReference=v?`FILE_WATCH:${v}`:'';setParameterDefault('sourceAlias',v)}})
function parameter(name:string){return form.parameters.find(p=>p.name===name)}
function parameterDefault(name:string){return String(parameter(name)?.defaultValue??'')}
function setParameterDefault(name:string,value:unknown){const p=parameter(name);if(p)p.defaultValue=value}
function ensureParameter(name:string,type:ParameterType,label:string,description:string,required=true,defaultValue:unknown=''){let p=parameter(name);if(!p){p={name,type,label,description,required,sensitive:false,identifying:true,runtimeOverrideAllowed:true,defaultValue,allowedValues:[],minValue:null,maxValue:null,minLength:null,maxLength:null};form.parameters.push(p)}else{p.type=type;p.label=label;p.description=description;p.required=required;if((p.defaultValue===undefined||p.defaultValue==='')&&defaultValue!=='')p.defaultValue=defaultValue}}
function configureExecutor(type:string){if(type==='FILE_WATCH'){ensureParameter('sourceAlias','PATH_ALIAS','승인 경로 Alias','ADM에서 승인된 PATH_ALIAS입니다.',true,fileWatchAlias.value);ensureParameter('sourcePath','STRING','감시 상대경로','승인 Alias 아래의 상대 경로 또는 파일 패턴입니다.',true,'');ensureParameter('stableWindowSeconds','LONG','안정화 대기(초)','파일 크기/수정시각이 변하지 않아야 하는 최소 시간입니다.',false,5);ensureParameter('completionMarkerSuffix','STRING','완료 Marker suffix','필요한 경우 .done 같은 완료 Marker suffix를 지정합니다.',false,'');ensureParameter('expectedSize','LONG','기대 파일 크기','알고 있는 경우 바이트 단위 기대 크기를 검증합니다.',false,'');ensureParameter('expectedSha256','STRING','기대 SHA-256','알고 있는 경우 64자리 SHA-256을 검증합니다.',false,'')}else if(type==='CENTER_CUT'){form.triggerType='MANUAL'} }
function addDependency(){form.dependencies.push({relatedJobId:'',condition:'SUCCESS',timeoutSeconds:3600,required:true})}
function toDate(value:string){return value?new Date(value).toISOString():null}
function buildDefinition(){return{jobId:form.jobId,definitionVersion:Number(form.definitionVersion),jobName:form.jobName,executorType:form.executorType,state:form.state,ownerDomain:form.ownerDomain,description:form.description,trigger:{type:form.triggerType,expression:form.triggerExpression,timezone:form.timezone,misfirePolicy:form.misfirePolicy,enabled:true},parameters:form.parameters.map(p=>({name:p.name,type:p.type,required:p.required,defaultValue:String(p.defaultValue??''),identifying:Boolean(p.identifying),sensitive:p.sensitive,label:p.label,description:p.description||'',allowedValues:Array.isArray(p.allowedValues)?p.allowedValues:[],pattern:p.pattern||'',minValue:p.minValue==null?'':String(p.minValue),maxValue:p.maxValue==null?'':String(p.maxValue),minLength:p.minLength??null,maxLength:p.maxLength??null,referenceType:p.referenceType||'',alias:p.alias||'',overrideAllowed:p.runtimeOverrideAllowed})),dependencies:form.dependencies,resourcePolicy:{agentPool:form.agentPool,zone:form.zone,maxConcurrency:Number(form.maxConcurrency),timeoutSeconds:Number(form.timeoutSeconds),memoryLimitMb:0,cpuLimitMillicores:0},recoveryPolicy:{maxAttempts:Number(form.maxAttempts),initialBackoffSeconds:Number(form.initialBackoffSeconds),multiplier:Number(form.multiplier),maxBackoffSeconds:Number(form.maxBackoffSeconds),skipLimit:Number(form.skipLimit),restartable:form.restartable,unknownResultPolicy:form.unknownResultPolicy,compensationReference:form.compensationReference},alertPolicy:{delayThresholdSeconds:Number(form.alertDelaySeconds),slaSeconds:Number(form.slaSeconds),notifyOnFailure:form.notifyOnFailure,notifyOnMissed:form.notifyOnMissed,providerKeys:[]},executorReference:form.executorReference,checksum:form.checksum,reason:form.reason,effectiveFrom:toDate(form.effectiveFrom),effectiveUntil:toDate(form.effectiveUntil),expectedRowVersion:Number(form.expectedRowVersion)}}
async function refresh(){loading.value=true;try{const [defs,cec,aliases]=await Promise.all([fetchJobDefinitions(),fetchCenterCutJobs(),fetchPathAliases()]);definitions.value=(defs.items||[]) as Array<Record<string,any>>;centerCutJobs.value=cec as Array<Record<string,any>>;pathAliases.value=aliases as Array<Record<string,any>>;error.value=''}catch(e){error.value=e instanceof Error?e.message:'BAT 등록정보 조회 실패'}finally{loading.value=false}}
async function validate(){try{validation.value=await validateJobDefinition(buildDefinition());error.value=''}catch(e){error.value=e instanceof Error?e.message:'검증 실패'}}
async function save(){if(!form.jobId.trim()){error.value='Job ID를 입력하세요.';return}if(hasSelfDependency.value){error.value='Job이 자기 자신을 선행 Dependency로 참조할 수 없습니다.';return}await validate();if(validation.value.valid!==true)return;try{actionResult.value=await saveJobDefinition(buildDefinition());form.expectedRowVersion=Number(actionResult.value.rowVersion||form.expectedRowVersion);await refresh()}catch(e){error.value=e instanceof Error?e.message:'저장 실패'}}
async function transition(targetState:string){if(!form.reason||form.reason.length<5){error.value='상태 전환 사유를 5자 이상 입력하세요.';return}try{actionResult.value=await transitionJobDefinition(form.jobId,Number(form.definitionVersion),{expectedRowVersion:Number(form.expectedRowVersion),targetState,reason:form.reason});form.state=String(actionResult.value.state||targetState);form.expectedRowVersion=Number(actionResult.value.rowVersion||form.expectedRowVersion);await refresh()}catch(e){error.value=e instanceof Error?e.message:'상태 전환 실패'}}
async function selectDefinition(row:Record<string,any>){try{const jobId=String(row.job_id||row.jobId);const version=Number(row.definition_version||row.definitionVersion);const d:any=await fetchJobDefinitionDetail(jobId,version);form.jobId=d.jobId;form.definitionVersion=Number(d.definitionVersion);form.jobName=d.jobName;form.executorType=d.executorType;form.state=d.state;form.ownerDomain=d.ownerDomain;form.description=d.description||'';form.triggerType=d.trigger?.type||'MANUAL';form.triggerExpression=d.trigger?.expression||'';form.timezone=d.trigger?.timezone||'Asia/Seoul';form.misfirePolicy=d.trigger?.misfirePolicy||'FAIL_CLOSED';form.agentPool=d.resourcePolicy?.agentPool||'DEFAULT';form.zone=d.resourcePolicy?.zone||'';form.maxConcurrency=Number(d.resourcePolicy?.maxConcurrency||1);form.timeoutSeconds=Number(d.resourcePolicy?.timeoutSeconds||3600);form.restartable=Boolean(d.recoveryPolicy?.restartable);form.maxAttempts=Number(d.recoveryPolicy?.maxAttempts||1);form.initialBackoffSeconds=Number(d.recoveryPolicy?.initialBackoffSeconds||0);form.multiplier=Number(d.recoveryPolicy?.multiplier||1);form.maxBackoffSeconds=Number(d.recoveryPolicy?.maxBackoffSeconds||0);form.skipLimit=Number(d.recoveryPolicy?.skipLimit||0);form.unknownResultPolicy=d.recoveryPolicy?.unknownResultPolicy||'FAIL_CLOSED';form.compensationReference=d.recoveryPolicy?.compensationReference||'';form.alertDelaySeconds=Number(d.alertPolicy?.delayThresholdSeconds||0);form.slaSeconds=Number(d.alertPolicy?.slaSeconds||0);form.notifyOnFailure=Boolean(d.alertPolicy?.notifyOnFailure);form.notifyOnMissed=Boolean(d.alertPolicy?.notifyOnMissed);form.executorReference=d.executorReference||'';form.checksum=d.checksum||'';form.reason='배치 Job Definition 변경';form.effectiveFrom=d.effectiveFrom?String(d.effectiveFrom).slice(0,16):'';form.effectiveUntil=d.effectiveUntil?String(d.effectiveUntil).slice(0,16):'';form.expectedRowVersion=Number(d.expectedRowVersion??row.row_version??row.rowVersion??0);form.parameters=(d.parameters||[]).map((v:any)=>({...v,runtimeOverrideAllowed:Boolean(v.overrideAllowed)}));form.dependencies=(d.dependencies||[]).map((v:any)=>({...v}));configureExecutor(form.executorType);error.value=''}catch(e){error.value=e instanceof Error?e.message:'Definition 상세 조회 실패'}}
watch(()=>form.executorType,(next,previous)=>{if(next!==previous){form.executorReference='';configureExecutor(next)}})
onMounted(async()=>{configureExecutor(form.executorType);await refresh()})
</script>
<template>
<section class="job-page">
 <header><div><h1>배치 작업 관리</h1><p>Definition Version, Executor, Trigger, Typed Parameter, Recovery, Approval을 하나의 정본으로 관리합니다.</p></div><button :disabled="loading" @click="refresh">{{loading?'조회 중…':'새로고침'}}</button></header>
 <p v-if="error" role="alert" class="danger">{{error}}</p>
 <div class="wizard">
  <fieldset :disabled="immutableVersion"><legend>1. 기본 정보</legend><div class="grid"><label>Job ID<input v-model="form.jobId"></label><label>Version<input v-model.number="form.definitionVersion" type="number" min="1"></label><label>Job 이름<input v-model="form.jobName"></label><label>Owner Domain<input v-model="form.ownerDomain"></label><label>상태<input :value="form.state" disabled></label><label>Row Version<input :value="form.expectedRowVersion" disabled></label><label class="wide">설명<input v-model="form.description"></label></div></fieldset>
  <fieldset :disabled="immutableVersion"><legend>2. 실행유형·Trigger</legend><div class="grid">
   <label>실행유형<select v-model="form.executorType"><option v-for="v in executorTypes" :key="v.value" :value="v.value">{{v.label}}</option></select><small>{{selectedExecutor?.description}}</small></label>
   <label v-if="isCenterCut">Center-Cut Job<select v-model="centerCutId"><option value="">선택하세요</option><option v-for="j in centerCutJobs" :key="String(j.center_cut_job_id||j.centerCutJobId)" :value="String(j.center_cut_job_id||j.centerCutJobId)">{{j.center_cut_job_id||j.centerCutJobId}} · {{j.job_name||j.jobName||''}}</option></select><small>활성 Center-Cut Job만 Backend에서 최종 검증합니다.</small></label>
   <label v-else-if="isShell">승인 Script Catalog Key<input v-model="shellCatalogKey" placeholder="예: DAILY_SETTLEMENT"><small>실제 저장값은 SCRIPT:&lt;catalogKey&gt;이며 서버 절대경로 입력은 허용하지 않습니다.</small></label>
   <label v-else-if="isFileWatch">승인 Path Alias<select v-model="fileWatchAlias"><option value="">선택하세요</option><option v-for="a in pathAliases" :key="String(a.id)" :value="String(a.id)" :disabled="a.enabled===false">{{a.label||a.id}}{{a.enabled===false?' (비활성)':''}}</option></select><small>실제 파일 존재·권한·안정화·무결성은 Worker Runtime에서 검증합니다.</small></label>
   <label v-else>Executor Reference<input v-model="form.executorReference" placeholder="SERVICE:, PROCESSOR:, ..."></label>
   <template v-if="isFileWatch"><label>감시 상대경로<input :value="parameterDefault('sourcePath')" @input="setParameterDefault('sourcePath',($event.target as HTMLInputElement).value)" placeholder="inbox/*.dat"></label><label>안정화 대기(초)<input type="number" min="1" :value="parameterDefault('stableWindowSeconds')" @input="setParameterDefault('stableWindowSeconds',Number(($event.target as HTMLInputElement).value))"></label><label>완료 Marker suffix<input :value="parameterDefault('completionMarkerSuffix')" @input="setParameterDefault('completionMarkerSuffix',($event.target as HTMLInputElement).value)" placeholder=".done (선택)"></label></template>
   <label>Trigger<select v-model="form.triggerType"><option>CRON</option><option>CALENDAR</option><option>BUSINESS_DAY</option><option>FILE</option><option>MESSAGE</option><option>MANUAL</option><option>DEPENDENCY</option></select></label><label>표현식<input v-model="form.triggerExpression"></label><label>Timezone<input v-model="form.timezone"></label><label>Misfire<select v-model="form.misfirePolicy"><option>FAIL_CLOSED</option><option>FIRE_NOW</option><option>SKIP</option><option>NEXT_SCHEDULE</option></select></label>
  </div></fieldset>
  <fieldset :disabled="immutableVersion"><legend>3. Typed Parameter</legend><ParameterSchemaEditor v-model="form.parameters"/><p class="hint">Secret은 원문이 아니라 Secret Reference, File/Path는 승인 Alias로 등록하며 식별 Parameter는 멱등 실행 Snapshot에 포함됩니다.</p></fieldset>
  <fieldset :disabled="immutableVersion"><legend>4. Resource·Recovery·Unknown</legend><div class="grid"><label>Agent Pool<input v-model="form.agentPool"></label><label>Zone<input v-model="form.zone"></label><label>최대 동시 실행<input v-model.number="form.maxConcurrency" type="number"></label><label>Timeout(초)<input v-model.number="form.timeoutSeconds" type="number"></label><label>최대 시도<input v-model.number="form.maxAttempts" type="number"></label><label>초기 Backoff<input v-model.number="form.initialBackoffSeconds" type="number"></label><label>배수<input v-model.number="form.multiplier" type="number" step="0.1"></label><label>최대 Backoff<input v-model.number="form.maxBackoffSeconds" type="number"></label><label>Skip Limit<input v-model.number="form.skipLimit" type="number"></label><label>결과 불명<select v-model="form.unknownResultPolicy"><option>FAIL_CLOSED</option><option>RECONCILE</option><option>MANUAL_REVIEW</option><option>COMPENSATE</option></select></label><label>보상 Reference<input v-model="form.compensationReference"></label><label><input v-model="form.restartable" type="checkbox">Restartable</label></div></fieldset>
  <fieldset :disabled="immutableVersion"><legend>5. Dependency·Alert</legend><div class="actions"><button @click="addDependency">Dependency 추가</button></div><div v-for="(d,index) in form.dependencies" :key="index" class="dependency-row"><input v-model="d.relatedJobId" placeholder="선행 Job"><select v-model="d.condition"><option>SUCCESS</option><option>FAILED</option><option>COMPLETED</option></select><input v-model.number="d.timeoutSeconds" type="number"><label><input v-model="d.required" type="checkbox">필수</label><button @click="form.dependencies.splice(index,1)">삭제</button></div><div class="grid"><label>지연 알림(초)<input v-model.number="form.alertDelaySeconds" type="number"></label><label>SLA(초)<input v-model.number="form.slaSeconds" type="number"></label><label><input v-model="form.notifyOnFailure" type="checkbox">실패 알림</label><label><input v-model="form.notifyOnMissed" type="checkbox">미실행 알림</label></div></fieldset>
  <fieldset><legend>6. Preview·검증·승인</legend><div class="grid"><label>Checksum<input :value="form.checksum" disabled></label><label>운영자<span class="actor-badge">현재 로그인 운영자</span></label><label class="wide">사유<input v-model="form.reason"></label><label>시행 시작<input v-model="form.effectiveFrom" type="datetime-local"></label><label>시행 종료<input v-model="form.effectiveUntil" type="datetime-local"></label></div><div class="actions"><button @click="validate">검증</button><button v-if="form.state==='DRAFT'" @click="save">Draft 저장</button><button v-if="form.state==='DRAFT'" @click="transition('VALIDATED')">검증 완료</button><button v-if="form.state==='VALIDATED'" @click="transition('APPROVAL')">승인 요청</button><button v-if="form.state==='PUBLISHED'" @click="transition('RETIRED')">Retire</button></div><p v-if="form.state==='APPROVAL'" class="warning">승인 대기 중입니다. Publish는 ADM 승인 실행에서만 수행됩니다.</p><div class="validation"><strong>검증: {{validation.valid===true?'PASS':validation.valid===false?'FAIL':'미실행'}}</strong><ul><li v-for="v in validation.errors||[]" :key="String(v)" class="danger">{{v}}</li><li v-for="v in validation.warnings||[]" :key="String(v)" class="warning">{{v}}</li></ul><dl><dt>Executor</dt><dd>{{preview.executorType}}</dd><dt>Trigger</dt><dd>{{preview.trigger.type}} {{preview.trigger.expression}}</dd><dt>Parameter</dt><dd>{{preview.parameters.length}}개</dd><dt>Unknown</dt><dd>{{preview.recoveryPolicy.unknownResultPolicy}}</dd></dl></div></fieldset>
 </div>
 <section><h2>등록 Definition</h2><div class="table-wrap"><table><thead><tr><th>Job</th><th>Version</th><th>Executor</th><th>State</th><th>Trigger</th><th>Agent</th><th>Concurrency</th><th>Unknown</th><th>Checksum</th><th>Version Lock</th></tr></thead><tbody><tr v-for="row in definitions" :key="`${row.job_id}-${row.definition_version}`" @click="selectDefinition(row)"><td>{{row.job_id}}<small>{{row.job_name}}</small></td><td>{{row.definition_version}}</td><td>{{row.executor_type}}</td><td>{{row.definition_state}}</td><td>{{row.trigger_type}}<small>{{row.trigger_expression}}</small></td><td>{{row.agent_pool}}</td><td>{{row.max_concurrency}}</td><td>{{row.unknown_result_policy}}</td><td>{{row.checksum||'-'}}</td><td>{{row.row_version}}</td></tr><tr v-if="!definitions.length"><td colspan="10">등록된 Definition이 없습니다.</td></tr></tbody></table></div></section>
 <BatchJobGovernancePanel :job-id="form.jobId" />
</section>
</template>
<style scoped>
.job-page{display:grid;gap:1.2rem}header{display:flex;justify-content:space-between;gap:1rem}.wizard{display:grid;gap:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.65rem}.grid label{display:grid;gap:.25rem}.wide{grid-column:1/-1}fieldset{border:1px solid var(--border-color,#d7dde7);border-radius:10px;padding:1rem}.parameter-row,.dependency-row{display:grid;grid-template-columns:1.2fr 1fr 1.2fr 1.4fr repeat(4,auto) auto;gap:.4rem;align-items:center;padding:.4rem 0;border-bottom:1px solid var(--border-color,#d7dde7)}.dependency-row{grid-template-columns:2fr 1fr 1fr auto auto}.actions{display:flex;gap:.5rem;flex-wrap:wrap;margin:.5rem 0}.validation{padding:.8rem;background:rgba(100,120,160,.08);border-radius:8px}.validation dl{display:grid;grid-template-columns:auto 1fr;gap:.3rem 1rem}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.55rem;text-align:left;border-bottom:1px solid var(--border-color,#d7dde7)}tbody tr{cursor:pointer}td small{display:block;opacity:.7}.actor-badge{display:inline-flex;align-items:center;min-height:2.2rem;padding:.3rem .6rem;border-radius:999px;background:rgba(80,110,160,.12)}fieldset:disabled{opacity:.86}.danger{color:#c84646}.warning{color:#a46b00}@media(max-width:1000px){.parameter-row{grid-template-columns:1fr 1fr}.dependency-row{grid-template-columns:1fr 1fr}}
</style>
