<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {fetchJobDefinitions,saveJobDefinition,transitionJobDefinition,validateJobDefinition} from '../batch-runtime-control/api'
import ParameterSchemaEditor from '../../components/parameters/ParameterSchemaEditor.vue'
import type {ParameterDefinition} from '../../components/parameters/parameterSchema'

type Parameter=ParameterDefinition
const definitions=ref<Array<Record<string,any>>>([]);const loading=ref(false);const error=ref('');const validation=ref<Record<string,any>>({});const actionResult=ref<Record<string,any>>({});
const form=reactive({jobId:'BAT.SAMPLE',definitionVersion:1,jobName:'표준 배치 작업',executorType:'SPRING_BATCH',state:'DRAFT',ownerDomain:'BAT',description:'',triggerType:'CRON',triggerExpression:'0 0 1 * * *',timezone:'Asia/Seoul',misfirePolicy:'FAIL_CLOSED',agentPool:'DEFAULT',zone:'',maxConcurrency:1,timeoutSeconds:3600,restartable:true,maxAttempts:1,initialBackoffSeconds:0,multiplier:1,maxBackoffSeconds:0,skipLimit:0,unknownResultPolicy:'FAIL_CLOSED',compensationReference:'',alertDelaySeconds:0,slaSeconds:0,notifyOnFailure:true,notifyOnMissed:true,executorReference:'JOBPACK:sample:job',checksum:'',requestedBy:'ADM',reason:'배치 Job Definition 등록',effectiveFrom:'',effectiveUntil:'',expectedRowVersion:0,parameters:[] as Parameter[],dependencies:[] as Array<{relatedJobId:string,condition:string,timeoutSeconds:number,required:boolean}>})
const executorTypes=['SPRING_BATCH','APPROVED_SHELL','FILE_WATCH','FILE_PROCESS','FILE_TRANSFER','SERVICE_CALL','MESSAGE_TRIGGER','PROTOCOL_ADAPTER'];
const preview=computed(()=>buildDefinition());
function addDependency(){form.dependencies.push({relatedJobId:'',condition:'SUCCESS',timeoutSeconds:3600,required:true})}
function toDate(value:string){return value?new Date(value).toISOString():null}
function buildDefinition(){return{jobId:form.jobId,definitionVersion:Number(form.definitionVersion),jobName:form.jobName,executorType:form.executorType,state:form.state,ownerDomain:form.ownerDomain,description:form.description,trigger:{type:form.triggerType,expression:form.triggerExpression,timezone:form.timezone,misfirePolicy:form.misfirePolicy,enabled:true},parameters:form.parameters.map(p=>({name:p.name,type:p.type,required:p.required,defaultValue:String(p.defaultValue??''),identifying:Boolean(p.identifying),sensitive:p.sensitive,label:p.label,description:p.description||'',allowedValues:Array.isArray(p.allowedValues)?p.allowedValues:[],pattern:p.pattern||'',minValue:p.minValue==null?'':String(p.minValue),maxValue:p.maxValue==null?'':String(p.maxValue),minLength:p.minLength??null,maxLength:p.maxLength??null,referenceType:p.referenceType||'',alias:p.alias||'',overrideAllowed:p.runtimeOverrideAllowed})),dependencies:form.dependencies,resourcePolicy:{agentPool:form.agentPool,zone:form.zone,maxConcurrency:Number(form.maxConcurrency),timeoutSeconds:Number(form.timeoutSeconds),memoryLimitMb:0,cpuLimitMillicores:0},recoveryPolicy:{maxAttempts:Number(form.maxAttempts),initialBackoffSeconds:Number(form.initialBackoffSeconds),multiplier:Number(form.multiplier),maxBackoffSeconds:Number(form.maxBackoffSeconds),skipLimit:Number(form.skipLimit),restartable:form.restartable,unknownResultPolicy:form.unknownResultPolicy,compensationReference:form.compensationReference},alertPolicy:{delayThresholdSeconds:Number(form.alertDelaySeconds),slaSeconds:Number(form.slaSeconds),notifyOnFailure:form.notifyOnFailure,notifyOnMissed:form.notifyOnMissed,providerKeys:[]},executorReference:form.executorReference,checksum:form.checksum,requestedBy:form.requestedBy,reason:form.reason,effectiveFrom:toDate(form.effectiveFrom),effectiveUntil:toDate(form.effectiveUntil),expectedRowVersion:Number(form.expectedRowVersion)}}
async function refresh(){loading.value=true;try{const r=await fetchJobDefinitions();definitions.value=(r.items||[]) as Array<Record<string,any>>;error.value=''}catch(e){error.value=e instanceof Error?e.message:'BAT 조회 실패'}finally{loading.value=false}}
async function validate(){try{validation.value=await validateJobDefinition(buildDefinition());error.value=''}catch(e){error.value=e instanceof Error?e.message:'검증 실패'}}
async function save(){await validate();if(validation.value.valid!==true)return;try{actionResult.value=await saveJobDefinition(buildDefinition());form.expectedRowVersion=Number(actionResult.value.rowVersion||form.expectedRowVersion);await refresh()}catch(e){error.value=e instanceof Error?e.message:'저장 실패'}}
async function transition(targetState:string){if(!form.reason||form.reason.length<5){error.value='상태 전환 사유를 5자 이상 입력하세요.';return}try{actionResult.value=await transitionJobDefinition(form.jobId,Number(form.definitionVersion),{expectedRowVersion:Number(form.expectedRowVersion),targetState,operatorId:form.requestedBy,reason:form.reason});form.state=String(actionResult.value.state||targetState);form.expectedRowVersion=Number(actionResult.value.rowVersion||form.expectedRowVersion);await refresh()}catch(e){error.value=e instanceof Error?e.message:'상태 전환 실패'}}
function selectDefinition(row:Record<string,any>){form.jobId=String(row.job_id||row.jobId);form.definitionVersion=Number(row.definition_version||row.definitionVersion);form.jobName=String(row.job_name||row.jobName);form.executorType=String(row.executor_type||row.executorType);form.state=String(row.definition_state||row.state);form.ownerDomain=String(row.owner_domain||row.ownerDomain);form.triggerType=String(row.trigger_type||row.triggerType);form.triggerExpression=String(row.trigger_expression||row.triggerExpression||'');form.timezone=String(row.timezone_id||row.timezone||'Asia/Seoul');form.agentPool=String(row.agent_pool||row.agentPool||'DEFAULT');form.maxConcurrency=Number(row.max_concurrency||1);form.restartable=String(row.restartable_yn||'Y')==='Y';form.unknownResultPolicy=String(row.unknown_result_policy||'FAIL_CLOSED');form.checksum=String(row.checksum||'');form.expectedRowVersion=Number(row.row_version||row.rowVersion||0)}
onMounted(refresh)
</script>
<template>
<section class="job-page">
 <header><div><h1>배치 작업 관리</h1><p>Definition Version, Executor, Trigger, Typed Parameter, Recovery, Approval을 하나의 정본으로 관리합니다.</p></div><button :disabled="loading" @click="refresh">{{loading?'조회 중…':'새로고침'}}</button></header>
 <p v-if="error" role="alert" class="danger">{{error}}</p>
 <div class="wizard">
  <fieldset><legend>1. 기본 정보</legend><div class="grid"><label>Job ID<input v-model="form.jobId"></label><label>Version<input v-model.number="form.definitionVersion" type="number" min="1"></label><label>Job 이름<input v-model="form.jobName"></label><label>Owner Domain<input v-model="form.ownerDomain"></label><label>상태<input :value="form.state" disabled></label><label>Row Version<input :value="form.expectedRowVersion" disabled></label><label class="wide">설명<input v-model="form.description"></label></div></fieldset>
  <fieldset><legend>2. Executor·Trigger</legend><div class="grid"><label>Executor<select v-model="form.executorType"><option v-for="v in executorTypes" :key="v">{{v}}</option></select></label><label>Executor Reference<input v-model="form.executorReference" placeholder="JOBPACK:, SCRIPT:, SERVICE:"></label><label>Trigger<select v-model="form.triggerType"><option>CRON</option><option>CALENDAR</option><option>BUSINESS_DAY</option><option>FILE</option><option>MESSAGE</option><option>MANUAL</option><option>DEPENDENCY</option></select></label><label>표현식<input v-model="form.triggerExpression"></label><label>Timezone<input v-model="form.timezone"></label><label>Misfire<select v-model="form.misfirePolicy"><option>FAIL_CLOSED</option><option>FIRE_NOW</option><option>SKIP</option><option>NEXT_SCHEDULE</option></select></label></div></fieldset>
  <fieldset><legend>3. Typed Parameter</legend><ParameterSchemaEditor v-model="form.parameters"/><p class="hint">Secret은 원문이 아니라 Secret Reference, File/Path는 승인 Alias로 등록하며 식별 Parameter는 멱등 실행 Snapshot에 포함됩니다.</p></fieldset>
  <fieldset><legend>4. Resource·Recovery·Unknown</legend><div class="grid"><label>Agent Pool<input v-model="form.agentPool"></label><label>Zone<input v-model="form.zone"></label><label>최대 동시 실행<input v-model.number="form.maxConcurrency" type="number"></label><label>Timeout(초)<input v-model.number="form.timeoutSeconds" type="number"></label><label>최대 시도<input v-model.number="form.maxAttempts" type="number"></label><label>초기 Backoff<input v-model.number="form.initialBackoffSeconds" type="number"></label><label>배수<input v-model.number="form.multiplier" type="number" step="0.1"></label><label>최대 Backoff<input v-model.number="form.maxBackoffSeconds" type="number"></label><label>Skip Limit<input v-model.number="form.skipLimit" type="number"></label><label>결과 불명<select v-model="form.unknownResultPolicy"><option>FAIL_CLOSED</option><option>RECONCILE</option><option>MANUAL_REVIEW</option><option>COMPENSATE</option></select></label><label>보상 Reference<input v-model="form.compensationReference"></label><label><input v-model="form.restartable" type="checkbox">Restartable</label></div></fieldset>
  <fieldset><legend>5. Dependency·Alert</legend><div class="actions"><button @click="addDependency">Dependency 추가</button></div><div v-for="(d,index) in form.dependencies" :key="index" class="dependency-row"><input v-model="d.relatedJobId" placeholder="선행 Job"><select v-model="d.condition"><option>SUCCESS</option><option>FAILED</option><option>COMPLETED</option></select><input v-model.number="d.timeoutSeconds" type="number"><label><input v-model="d.required" type="checkbox">필수</label><button @click="form.dependencies.splice(index,1)">삭제</button></div><div class="grid"><label>지연 알림(초)<input v-model.number="form.alertDelaySeconds" type="number"></label><label>SLA(초)<input v-model.number="form.slaSeconds" type="number"></label><label><input v-model="form.notifyOnFailure" type="checkbox">실패 알림</label><label><input v-model="form.notifyOnMissed" type="checkbox">미실행 알림</label></div></fieldset>
  <fieldset><legend>6. Preview·검증·승인</legend><div class="grid"><label>Checksum<input v-model="form.checksum"></label><label>운영자<input v-model="form.requestedBy"></label><label class="wide">사유<input v-model="form.reason"></label><label>시행 시작<input v-model="form.effectiveFrom" type="datetime-local"></label><label>시행 종료<input v-model="form.effectiveUntil" type="datetime-local"></label></div><div class="actions"><button @click="validate">검증</button><button @click="save">Draft 저장</button><button @click="transition('VALIDATED')">Validated</button><button @click="transition('APPROVAL')">승인 요청</button><button @click="transition('PUBLISHED')">Publish</button><button @click="transition('RETIRED')">Retire</button></div><div class="validation"><strong>검증: {{validation.valid===true?'PASS':validation.valid===false?'FAIL':'미실행'}}</strong><ul><li v-for="v in validation.errors||[]" :key="String(v)" class="danger">{{v}}</li><li v-for="v in validation.warnings||[]" :key="String(v)" class="warning">{{v}}</li></ul><dl><dt>Executor</dt><dd>{{preview.executorType}}</dd><dt>Trigger</dt><dd>{{preview.trigger.type}} {{preview.trigger.expression}}</dd><dt>Parameter</dt><dd>{{preview.parameters.length}}개</dd><dt>Unknown</dt><dd>{{preview.recoveryPolicy.unknownResultPolicy}}</dd></dl></div></fieldset>
 </div>
 <section><h2>등록 Definition</h2><div class="table-wrap"><table><thead><tr><th>Job</th><th>Version</th><th>Executor</th><th>State</th><th>Trigger</th><th>Agent</th><th>Concurrency</th><th>Unknown</th><th>Checksum</th><th>Version Lock</th></tr></thead><tbody><tr v-for="row in definitions" :key="`${row.job_id}-${row.definition_version}`" @click="selectDefinition(row)"><td>{{row.job_id}}<small>{{row.job_name}}</small></td><td>{{row.definition_version}}</td><td>{{row.executor_type}}</td><td>{{row.definition_state}}</td><td>{{row.trigger_type}}<small>{{row.trigger_expression}}</small></td><td>{{row.agent_pool}}</td><td>{{row.max_concurrency}}</td><td>{{row.unknown_result_policy}}</td><td>{{row.checksum||'-'}}</td><td>{{row.row_version}}</td></tr><tr v-if="!definitions.length"><td colspan="10">등록된 Definition이 없습니다.</td></tr></tbody></table></div></section>
</section>
</template>
<style scoped>
.job-page{display:grid;gap:1.2rem}header{display:flex;justify-content:space-between;gap:1rem}.wizard{display:grid;gap:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.65rem}.grid label{display:grid;gap:.25rem}.wide{grid-column:1/-1}fieldset{border:1px solid var(--border-color,#d7dde7);border-radius:10px;padding:1rem}.parameter-row,.dependency-row{display:grid;grid-template-columns:1.2fr 1fr 1.2fr 1.4fr repeat(4,auto) auto;gap:.4rem;align-items:center;padding:.4rem 0;border-bottom:1px solid var(--border-color,#d7dde7)}.dependency-row{grid-template-columns:2fr 1fr 1fr auto auto}.actions{display:flex;gap:.5rem;flex-wrap:wrap;margin:.5rem 0}.validation{padding:.8rem;background:rgba(100,120,160,.08);border-radius:8px}.validation dl{display:grid;grid-template-columns:auto 1fr;gap:.3rem 1rem}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.55rem;text-align:left;border-bottom:1px solid var(--border-color,#d7dde7)}tbody tr{cursor:pointer}td small{display:block;opacity:.7}.danger{color:#c84646}.warning{color:#a46b00}@media(max-width:1000px){.parameter-row{grid-template-columns:1fr 1fr}.dependency-row{grid-template-columns:1fr 1fr}}
</style>
