<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { fetchBatchExecutionPage, fetchBatchExecutionTargets, fetchBatchJobDetail, fetchBatchOperationLogs, fetchBatchRelations, type BatchExecutionPage } from '../batch-runtime-control/api'
import { apiMessage, pretty, read, statusClass, text, type AnyRow } from '../batch-runtime-control/pageSupport'
const props=defineProps<{jobId:string}>()
const detail=ref<AnyRow>({});const relations=ref<AnyRow[]>([]);const executions=ref<BatchExecutionPage|null>(null);const targets=ref<AnyRow[]>([]);const logs=ref<AnyRow[]>([]);const loading=ref(false);const error=ref('')
function source(row:AnyRow){return text(row,'sourceJobId','source_job_id','jobId','job_id')}
function target(row:AnyRow){return text(row,'targetJobId','target_job_id','relatedJobId','related_job_id')}
const graphNodes=computed(()=>Array.from(new Set([props.jobId,...relations.value.flatMap(row=>[source(row),target(row)]).filter(v=>v&&v!=='-')])))
const graphEdges=computed(()=>relations.value.map(row=>({from:source(row),to:target(row),condition:text(row,'condition','relation_type','triggerCondition')})).filter(edge=>edge.from!=='-'&&edge.to!=='-'))
const cycle=computed(()=>{const adj=new Map<string,string[]>();for(const n of graphNodes.value)adj.set(n,[]);for(const e of graphEdges.value)adj.get(e.from)?.push(e.to);const visiting=new Set<string>(),done=new Set<string>(),path:string[]=[];function dfs(n:string):string[]|null{if(visiting.has(n)){const i=path.indexOf(n);return [...path.slice(i),n]}if(done.has(n))return null;visiting.add(n);path.push(n);for(const next of adj.get(n)||[]){const found=dfs(next);if(found)return found}path.pop();visiting.delete(n);done.add(n);return null}for(const n of graphNodes.value){const found=dfs(n);if(found)return found}return []})
const downstream=computed(()=>{const seen=new Set<string>(),q=[props.jobId];while(q.length){const n=q.shift()!;for(const e of graphEdges.value.filter(edge=>edge.from===n)){if(!seen.has(e.to)){seen.add(e.to);q.push(e.to)}}}return [...seen]})
async function load(){if(!props.jobId.trim()){detail.value={};relations.value=[];executions.value=null;return}loading.value=true;error.value='';try{const [d,r,e,t,l]=await Promise.all([fetchBatchJobDetail(props.jobId),fetchBatchRelations(props.jobId),fetchBatchExecutionPage({jobId:props.jobId,page:0,size:20}),fetchBatchExecutionTargets(props.jobId,'',100),fetchBatchOperationLogs(props.jobId,undefined,100)]);detail.value=d;relations.value=r;executions.value=e;targets.value=t;logs.value=l}catch(cause){error.value=apiMessage(cause,'Job Governance 상세 조회에 실패했습니다.')}finally{loading.value=false}}
watch(()=>props.jobId,load,{immediate:true})
</script>
<template><section class="governance-panel"><header><div><h2>Job Governance · Dependency · History</h2><p>Definition Version, DAG, 실행 이력, 배정 대상, Artifact/Report와 운영 감사를 Job ID Context로 연결합니다.</p></div><button type="button" :disabled="loading||!jobId" @click="load">새로고침</button></header><p v-if="error" role="alert" class="danger">{{error}}</p><div v-if="cycle.length" class="danger-box" role="alert"><strong>Dependency Cycle</strong> {{cycle.join(' → ')}}</div><div class="kpis"><span>Node {{graphNodes.length}}</span><span>Edge {{graphEdges.length}}</span><span>Downstream {{downstream.length}}</span><span>Execution {{executions?.items.length||0}}</span></div><div class="grid"><article class="card"><h3>Job Detail</h3><pre>{{pretty(detail)}}</pre></article><article class="card"><h3>Dependency Graph</h3><ol class="graph"><li v-for="edge in graphEdges" :key="`${edge.from}-${edge.to}-${edge.condition}`"><strong>{{edge.from}}</strong> → <strong>{{edge.to}}</strong><span>{{edge.condition}}</span></li><li v-if="!graphEdges.length">등록된 관계가 없습니다.</li></ol><p>영향 대상: {{downstream.join(', ')||'없음'}}</p></article><article class="card wide"><h3>최근 실행</h3><div class="table-wrap"><table><thead><tr><th>Execution</th><th>Status</th><th>Started</th><th>Ended</th><th>Worker</th><th>Transaction</th><th>Report/Artifact</th></tr></thead><tbody><tr v-for="row in executions?.items||[]" :key="text(row,'executionId','execution_id')"><td>{{text(row,'executionId','execution_id')}}</td><td><span :class="['status',statusClass(read(row,'status','execution_status'))]">{{text(row,'status','execution_status')}}</span></td><td>{{text(row,'startedAt','started_at')}}</td><td>{{text(row,'endedAt','ended_at')}}</td><td>{{text(row,'workerId','worker_id')}}</td><td>{{text(row,'transactionId','transaction_id')}}</td><td>{{text(row,'reportRef','report_ref','artifactRef','artifact_ref')}}</td></tr><tr v-if="!(executions?.items||[]).length"><td colspan="7">실행 이력이 없습니다.</td></tr></tbody></table></div></article><article class="card"><h3>Execution Targets</h3><pre>{{pretty(targets)}}</pre></article><article class="card"><h3>Operation Audit</h3><pre>{{pretty(logs)}}</pre></article></div></section></template>
<style scoped>.governance-panel{display:grid;gap:1rem;border-top:2px solid var(--el-color-primary,#409eff);padding-top:1rem}header{display:flex;justify-content:space-between;gap:1rem}.kpis{display:flex;gap:.5rem;flex-wrap:wrap}.kpis span{padding:.35rem .6rem;border-radius:999px;background:var(--el-fill-color-light,#f5f7fa)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{border:1px solid var(--el-border-color,#dcdfe6);border-radius:.65rem;padding:1rem;min-width:0}.wide{grid-column:1/-1}.graph{display:grid;gap:.5rem}.graph li{display:grid;grid-template-columns:1fr auto 1fr auto;gap:.5rem;align-items:center}.graph span{font-size:.75rem}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.55rem;border-bottom:1px solid var(--el-border-color,#dcdfe6);text-align:left;white-space:nowrap}pre{white-space:pre-wrap;overflow:auto;max-height:18rem;background:var(--el-fill-color-light,#f5f7fa);padding:.75rem}.danger,.danger-box{color:var(--el-color-danger,#f56c6c)}.danger-box{padding:.75rem;border:1px solid currentColor}@media(max-width:900px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
