<script setup lang="ts">
import {parameterTypes,isReferenceType,type ParameterDefinition, type ParameterType} from './parameterSchema'
const props=withDefaults(defineProps<{modelValue:ParameterDefinition[];disabled?:boolean}>(),{disabled:false})
const emit=defineEmits<{(e:'update:modelValue',value:ParameterDefinition[]):void}>()
function change(index:number,patch:Partial<ParameterDefinition>){const next=props.modelValue.map((v,i)=>i===index?{...v,...patch}:v);emit('update:modelValue',next)}
function add(){emit('update:modelValue',[...props.modelValue,{name:`param${props.modelValue.length+1}`,type:'STRING',label:'',description:'',required:false,sensitive:false,identifying:false,runtimeOverrideAllowed:false,defaultValue:'',allowedValues:[],pattern:'',minValue:null,maxValue:null,minLength:null,maxLength:null,referenceType:'',alias:'',placeholder:'',displayOrder:props.modelValue.length+1,visibleWhen:{parameterName:'',operator:'ALWAYS',values:[]}}])}
function remove(index:number){emit('update:modelValue',props.modelValue.filter((_,i)=>i!==index))}
</script>
<template><div class="schema-editor"><div class="editor-head"><p>Backend Validation·OpenAPI·운영 Form이 공유하는 Versioned Parameter Schema입니다.</p><button type="button" :disabled="disabled" @click="add">Parameter 추가</button></div>
 <article v-for="(p,index) in modelValue" :key="`${p.name}-${index}`" class="parameter-card">
  <div class="grid"><label>이름<input :value="p.name" :disabled="disabled" @input="change(index,{name:($event.target as HTMLInputElement).value})"></label><label>자료형<select :value="p.type" :disabled="disabled" @change="change(index,{type:($event.target as HTMLSelectElement).value as ParameterType})"><option v-for="v in parameterTypes" :key="v">{{v}}</option></select></label><label>표시명<input :value="p.label" :disabled="disabled" @input="change(index,{label:($event.target as HTMLInputElement).value})"></label><label>기본값/Reference<input :type="p.sensitive?'password':'text'" :value="String(p.defaultValue??'')" :disabled="disabled" @input="change(index,{defaultValue:($event.target as HTMLInputElement).value})"></label><label v-if="p.type==='ENUM'||p.type==='CODE_REFERENCE'">허용값<input :value="(p.allowedValues||[]).join(',')" :disabled="disabled" @input="change(index,{allowedValues:($event.target as HTMLInputElement).value.split(',').map(v=>v.trim()).filter(Boolean)})"></label><label v-if="isReferenceType(p.type)">Reference Catalog<input :value="p.referenceType||''" :disabled="disabled" @input="change(index,{referenceType:($event.target as HTMLInputElement).value})"></label><label v-if="isReferenceType(p.type)">승인 Alias<input :value="p.alias||''" :disabled="disabled" @input="change(index,{alias:($event.target as HTMLInputElement).value})"></label><label>Pattern<input :value="p.pattern||''" :disabled="disabled" @input="change(index,{pattern:($event.target as HTMLInputElement).value})"></label><label>설명<input :value="p.description||''" :disabled="disabled" @input="change(index,{description:($event.target as HTMLInputElement).value})"></label></div>
  <div class="checks"><label><input type="checkbox" :checked="p.required" :disabled="disabled" @change="change(index,{required:($event.target as HTMLInputElement).checked})">필수</label><label><input type="checkbox" :checked="p.sensitive" :disabled="disabled" @change="change(index,{sensitive:($event.target as HTMLInputElement).checked})">민감</label><label><input type="checkbox" :checked="p.identifying" :disabled="disabled" @change="change(index,{identifying:($event.target as HTMLInputElement).checked})">식별/멱등</label><label><input type="checkbox" :checked="p.runtimeOverrideAllowed" :disabled="disabled" @change="change(index,{runtimeOverrideAllowed:($event.target as HTMLInputElement).checked})">실행 Override</label><button type="button" class="danger" :disabled="disabled" @click="remove(index)">삭제</button></div>
 </article>
</div></template>
<style scoped>.schema-editor{display:grid;gap:.7rem}.editor-head,.checks{display:flex;gap:.65rem;align-items:center;justify-content:space-between;flex-wrap:wrap}.parameter-card{padding:.8rem;border:1px solid var(--border-color,#d7dde7);border-radius:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.55rem}.grid label{display:grid;gap:.25rem}.checks{justify-content:flex-start;margin-top:.6rem}.danger{margin-left:auto}</style>
