package com.cpf.integration.http.internal;
import com.cpf.integration.http.internal.servicecall.ServiceCallRequest;import java.util.*;import java.util.concurrent.atomic.AtomicReference;
/** CpfWebClient typed 요청이 실제 소비하는 timeout/retry/header policy입니다. */
public final class CpfApiClientRuntimePolicy{
 private final AtomicReference<Snapshot>ref=new AtomicReference<>(Snapshot.initial());public Snapshot current(){return ref.get();}
 public Snapshot replace(long version,ClientPolicy defaults,Map<String,ClientPolicy>services){LinkedHashMap<String,ClientPolicy>m=new LinkedHashMap<>();if(services!=null)services.forEach((k,v)->{if(k!=null&&!k.isBlank()&&v!=null)m.put(k.trim().toLowerCase(Locale.ROOT),v);});Snapshot n=new Snapshot(version,defaults==null?ClientPolicy.defaults():defaults,Map.copyOf(m));ref.set(n);return n;}
 public ServiceCallRequest apply(ServiceCallRequest r){Snapshot s=ref.get();ClientPolicy p=s.services().getOrDefault(r.serviceId().trim().toLowerCase(Locale.ROOT),s.defaults());Integer timeout=r.timeoutMillis()!=null&&r.timeoutMillis()>0?r.timeoutMillis():p.timeoutMillis();Integer retry=r.retryCount()!=null&&r.retryCount()>=0?r.retryCount():p.retryCount();LinkedHashMap<String,String>h=new LinkedHashMap<>();r.headers().forEach((k,v)->{if(p.allowedHeaders().isEmpty()||p.allowedHeaders().contains(k.toLowerCase(Locale.ROOT)))h.put(k,v);});return new ServiceCallRequest(r.serviceId(),r.endpointCode(),r.instanceId(),r.httpMethod(),r.requestPath(),timeout,retry,Map.copyOf(h),r.attributes());}
 public record ClientPolicy(int timeoutMillis,int retryCount,Set<String>allowedHeaders){public ClientPolicy{if(timeoutMillis<1||timeoutMillis>300000||retryCount<0||retryCount>10)throw new IllegalArgumentException("API Client policy 범위 오류");allowedHeaders=normalize(allowedHeaders);}private static ClientPolicy defaults(){return new ClientPolicy(3000,0,Set.of());}private static Set<String>normalize(Set<String>s){if(s==null)return Set.of();LinkedHashSet<String>r=new LinkedHashSet<>();for(String v:s)if(v!=null&&!v.isBlank())r.add(v.trim().toLowerCase(Locale.ROOT));return Set.copyOf(r);}}
 public record Snapshot(long version,ClientPolicy defaults,Map<String,ClientPolicy>services){private static Snapshot initial(){return new Snapshot(0,ClientPolicy.defaults(),Map.of());}}
}
