-- CMN 보안/토큰 관리 기준 DDL입니다.
-- 실제 인증 서버가 별도로 존재하면 원천 토큰은 인증 서버에서 관리하고,
-- 업무 주제영역은 토큰 해시/검증 이력/감사 로그만 저장하는 것을 권장합니다.

CREATE TABLE IF NOT EXISTS security_jwt_key (
    KEY_ID VARCHAR(80) NOT NULL COMMENT 'JWT 키 ID',
    ISSUER VARCHAR(100) NOT NULL COMMENT '발급자',
    ALGORITHM VARCHAR(20) NOT NULL DEFAULT 'HS256' COMMENT '서명 알고리즘',
    SECRET_REF VARCHAR(500) NOT NULL COMMENT 'Vault/KMS/환경변수 키 참조. 원문 시크릿 저장 금지',
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    EXPIRE_AT DATETIME NULL COMMENT '키 만료 시각',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (KEY_ID),
    INDEX IX_SECURITY_JWT_KEY_ISSUER (ISSUER, ACTIVE_YN)
) COMMENT='CMN JWT 서명 키 참조';

CREATE TABLE IF NOT EXISTS security_token_audit_log (
    TOKEN_AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '토큰 검증 감사 ID',
    TRANSACTION_ID VARCHAR(80) NULL COMMENT '글로벌 거래ID',
    TRACE_ID VARCHAR(80) NULL COMMENT 'Trace ID',
    TOKEN_HASH VARCHAR(512) NULL COMMENT '토큰 SHA-256 해시. 원문 토큰 저장 금지',
    TOKEN_TYPE VARCHAR(30) NOT NULL DEFAULT 'Bearer' COMMENT '토큰 유형',
    ISSUER VARCHAR(100) NULL COMMENT '발급자',
    SUBJECT VARCHAR(200) NULL COMMENT '토큰 주체',
    AUDIENCE VARCHAR(200) NULL COMMENT '대상 시스템',
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '유효 여부',
    EXPIRE_AT DATETIME NULL COMMENT '토큰 만료 시각',
    FAILURE_REASON VARCHAR(1000) NULL COMMENT '검증 실패 사유',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (TOKEN_AUDIT_ID),
    INDEX IX_SECURITY_TOKEN_TX (TRANSACTION_ID),
    INDEX IX_SECURITY_TOKEN_HASH (TOKEN_HASH),
    INDEX IX_SECURITY_TOKEN_SUBJECT_TIME (SUBJECT, CREATED_AT)
) COMMENT='CMN 토큰 검증 감사 로그';
