-- CMN 파일/원격 연계 이력 테이블 기준 DDL입니다.
-- 현재 샘플 구현은 인메모리 최근 이력을 제공하며, 운영에서는 이 테이블에 비동기 적재하도록 확장합니다.

CREATE TABLE IF NOT EXISTS file_exchange_log (
    EXCHANGE_ID VARCHAR(80) NOT NULL COMMENT '파일 연계 이력 ID',
    TRANSACTION_ID VARCHAR(80) NULL COMMENT '글로벌 거래ID',
    TRACE_ID VARCHAR(80) NULL COMMENT 'Trace ID',
    BUSINESS_TRANSACTION_ID VARCHAR(20) NULL COMMENT '업무 거래ID',
    ACTION_TYPE VARCHAR(30) NOT NULL COMMENT 'LOCAL_WRITE, LOCAL_READ, LOCAL_COPY, REMOTE_TRANSFER, SSH_COMMAND',
    PROTOCOL VARCHAR(20) NOT NULL COMMENT 'LOCAL, FTP, SFTP, SCP, SSH',
    DIRECTION VARCHAR(20) NULL COMMENT 'UPLOAD, DOWNLOAD, READ, WRITE, COMMAND',
    EXECUTED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '실제 실행 여부',
    SUCCESS_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '성공 여부',
    HOST VARCHAR(255) NULL COMMENT '원격 호스트',
    SOURCE_PATH VARCHAR(1000) NULL COMMENT '원본 경로',
    TARGET_PATH VARCHAR(1000) NULL COMMENT '대상 경로',
    REQUEST_USER VARCHAR(50) NULL COMMENT '요청자',
    MESSAGE VARCHAR(2000) NULL COMMENT '처리 메시지',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (EXCHANGE_ID),
    INDEX IX_FILE_EXCHANGE_TX (TRANSACTION_ID, CREATED_AT),
    INDEX IX_FILE_EXCHANGE_BIZ (BUSINESS_TRANSACTION_ID, CREATED_AT),
    INDEX IX_FILE_EXCHANGE_HOST (HOST, CREATED_AT)
) COMMENT='CMN 파일/원격 연계 이력';
