package com.cpf.reference.edu.runtime.model;
public enum EduWorkflowStep {
    VALIDATE, AUTHORIZE, SCOPE, DEDUPE, VERSION_CHECK, PREVIEW, APPROVAL, READ_SNAPSHOT,
    CLAIM_LEASE, PARTITION, CHECKSUM, QUARANTINE, PROTECT, MUTATE, COMMIT,
    CHECKPOINT, OUTBOX, EXTERNAL_SEND, ACK, RECONCILE, COMPENSATION_READY,
    AUDIT, OBSERVE
}
