# CPF 제품과 기본 구성요소가 함께 사용하는 단일 버전 정본입니다.
platformVersion=1.0.0-SNAPSHOT
compatibleRange=[1.0.0,2.0.0)
component.pfw=inherit
component.cmn=inherit
component.adm=inherit
component.bza=inherit
component.bat=inherit
component.mbr=inherit
component.acc=inherit
component.xyz=inherit
component.pfw-gateway-runtime=inherit
