<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { bzaApi, hasBzaPermission } from "../auth/session";
const canWrite=computed(()=>hasBzaPermission("APPROVAL","WRITE"));
const rows=ref<Record<string,unknown>[]>([]);const error=ref("");
const form=reactive({delegatorEmployeeNo:"",delegateEmployeeNo:"",businessDomain:"",approvalType:"",validFrom:new Date().toISOString(),validTo:"",reason:"결재 위임",useYn:"Y"});
async function load(){try{rows.value=await bzaApi("/api/bza/approvals/delegations");}catch(e){error.value=e instanceof Error?e.message:String(e);}}
async function save(){if(!canWrite.value){error.value="APPROVAL:WRITE 권한이 필요합니다.";return;}try{await bzaApi("/api/bza/approvals/delegations",{method:"POST",body:JSON.stringify(form)});await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}}
onMounted(load);
</script>
<template><div class="page-stack"><section class="card"><div class="card-head"><div><p class="eyebrow">DELEGATION</p><h2>결재 위임·대결</h2></div></div><form v-if="canWrite" class="form-grid" @submit.prevent="save"><label><span>위임자 직원</span><input v-model="form.delegatorEmployeeNo" required></label><label><span>대리 직원</span><input v-model="form.delegateEmployeeNo" required></label><label><span>업무 영역 제한</span><input v-model="form.businessDomain"></label><label><span>결재 유형 제한</span><input v-model="form.approvalType"></label><label><span>시작시각</span><input v-model="form.validFrom" required></label><label><span>종료시각</span><input v-model="form.validTo" required></label><label class="wide"><span>사유</span><textarea v-model="form.reason" required></textarea></label><div class="form-action"><button class="primary">저장</button></div></form><p v-if="error" class="error-banner">{{error}}</p></section><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>delegator</th><th>delegate</th><th>domain</th><th>type</th><th>from</th><th>to</th><th>use</th></tr></thead><tbody><tr v-for="row in rows" :key="String(row.delegationId)"><td>{{row.delegatorEmployeeNo}}</td><td>{{row.delegateEmployeeNo}}</td><td>{{row.businessDomain}}</td><td>{{row.approvalType}}</td><td>{{row.validFrom}}</td><td>{{row.validTo}}</td><td>{{row.useYn}}</td></tr></tbody></table></div></section></div></template>
