package com.cpf.batch.agent.internal;
import com.cpf.batch.agent.AgentProperties;import java.io.*;import java.nio.file.*;import java.time.*;import java.util.zip.*;
public final class LogArchiveService{
 private final AgentProperties p;public LogArchiveService(AgentProperties p){this.p=p;}
 public Path collect(String id)throws IOException{cleanupExpired();var s=p.getServices().values().stream().filter(x->id.equals(x.getServiceId())).findFirst().orElseThrow(()->new SecurityException("unknown service"));Path configured=Path.of(s.getLogRoot()).toAbsolutePath().normalize();if(Files.isSymbolicLink(configured)||!Files.isDirectory(configured,LinkOption.NOFOLLOW_LINKS))throw new FileNotFoundException("log root");Path root=configured.toRealPath(LinkOption.NOFOLLOW_LINKS);Path work=secureWork(s.getInstallRoot());Path zip=Files.createTempFile(work,"logs-"+id+"-",".zip");long[] total={0};try(ZipOutputStream out=new ZipOutputStream(Files.newOutputStream(zip,StandardOpenOption.WRITE));var walk=Files.walk(root)){walk.filter(x->!Files.isSymbolicLink(x)&&Files.isRegularFile(x,LinkOption.NOFOLLOW_LINKS)).filter(x->x.toString().endsWith(".log")||x.toString().endsWith(".gz")).forEach(x->{try{Path real=x.toRealPath(LinkOption.NOFOLLOW_LINKS);if(!real.startsWith(root))throw new SecurityException("path escape");long size=Files.size(real);total[0]+=size;if(total[0]>p.getMaxLogArchiveBytes())throw new IOException("archive limit");String entry=root.relativize(real).toString().replace('\\','/');if(entry.contains(".."))throw new SecurityException("path escape");ZipEntry z=new ZipEntry(entry);z.setTime(Files.getLastModifiedTime(real,LinkOption.NOFOLLOW_LINKS).toMillis());out.putNextEntry(z);try(InputStream in=Files.newInputStream(real,LinkOption.NOFOLLOW_LINKS)){in.transferTo(out);}out.closeEntry();}catch(IOException e){throw new UncheckedIOException(e);}});}catch(UncheckedIOException e){Files.deleteIfExists(zip);throw e.getCause();}return zip;}
 public void delete(Path archive)throws IOException{if(archive!=null)Files.deleteIfExists(archive);}
 public void cleanupExpired()throws IOException{for(var s:p.getServices().values()){Path work=Path.of(s.getInstallRoot()).toAbsolutePath().normalize().resolve("work");if(!Files.isDirectory(work,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(work))continue;Instant cutoff=Instant.now().minusSeconds(Math.max(60,p.getLogArchiveTtlSeconds()));try(var files=Files.list(work)){for(Path f:files.filter(x->x.getFileName().toString().startsWith("logs-")&&x.getFileName().toString().endsWith(".zip")).toList())if(Files.getLastModifiedTime(f,LinkOption.NOFOLLOW_LINKS).toInstant().isBefore(cutoff))Files.deleteIfExists(f);}}}
 private static Path secureWork(String root)throws IOException{Path base=Path.of(root).toAbsolutePath().normalize();if(Files.isSymbolicLink(base))throw new SecurityException("install root symlink");Files.createDirectories(base);base=base.toRealPath(LinkOption.NOFOLLOW_LINKS);Path work=base.resolve("work");if(Files.exists(work,LinkOption.NOFOLLOW_LINKS)&&Files.isSymbolicLink(work))throw new SecurityException("work symlink");Files.createDirectories(work);return work.toRealPath(LinkOption.NOFOLLOW_LINKS);}
}
