plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    implementation project(':framework:base-runtime')
    api project(':framework:operations')
    api project(':framework:file')
    implementation project(':internal:platform-operations:runtime-control')
    api project(':framework:core')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly 'org.springframework:spring-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework:spring-web'
}
tasks.named('test') { useJUnitPlatform() }
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-file-attachment'
        }
    }
}
