cpf:
  openapi:
    webmvc:
      api-docs-enabled: ${CPF_OPENAPI_WEBMVC_API_DOCS_ENABLED:true}
  local:
    runtime:
      enabled: true
    simulators:
      redis: { enabled: true, provider: LOCAL }
      broker: { enabled: true, provider: IN_MEMORY }
      external: { enabled: true, provider: STUB }
      file-transfer: { enabled: true, provider: LOCAL_FS }
