cpf:
  local:
    runtime:
      minimum-max-memory-mb: 750
    simulators:
      redis: { enabled: false, provider: EXTERNAL }
      broker: { enabled: false, provider: EXTERNAL }
      external: { enabled: false, provider: EXTERNAL }
      file-transfer: { enabled: false, provider: EXTERNAL }
