spring:
  config:
    import:
      - optional:classpath:application-pfw.yml
      - optional:classpath:application-cmn.yml
      - classpath:application-mbr.yml
      - classpath:application-mbr-local.yml
