const assert=require('assert');
global.window={location:{origin:'https://cpf.local'}};
let cookie=''; global.document={get cookie(){return cookie},set cookie(v){cookie=v}};
let calls=[]; global.fetch=async (url,options)=>{calls.push([url,options]);return new Response('{}',{status:200,headers:{'Content-Type':'application/json'}})};
async function rejects(fn,part){let e;try{await fn()}catch(x){e=x}assert(e,`expected reject ${part}`);assert(String(e.message).includes(part),`message ${e.message} missing ${part}`)}
async function test(modPath,surface){
  const api=require(modPath); const create=api[`create${surface==='ADM'?'Adm':'Bza'}Headers`]; const raw=api[`${surface.toLowerCase()}RawResponse`];
  let h=create({}); assert.equal(h.get('X-Client-Id'),surface==='ADM'?'cpf-adm-ui':'cpf-bza-ui'); assert.equal(h.get('X-Client-Version'),'1.0.0'); assert(!h.has('Authorization')); for(const name of ['X-Transaction-Id','X-Original-Channel','X-Current-Channel','X-Caller-Channel','X-Target-Channel','X-Target-Operation-Id']){ assert(!h.has(name),`browser must not author ${name}`); assert.throws(()=>create({[name]:'forged'}),new RegExp(name)); }
  assert.throws(()=>create({Authorization:'Bearer x'}),/Browser Bearer Token/);
  await rejects(()=>raw(`https://evil.example/${surface.toLowerCase()}/api/runtime-control/status`),'same-origin');
  await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST',{nested:{operatorId:'evil'}}),'operatorId');
  await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST','{"nested":{"requestedBy":"evil"}}'),'requestedBy');
  await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST','plain'),'raw string body is forbidden');
  const form=new FormData();form.set('OperatorId','evil'); await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST',form),'OperatorId');
  const qs=new URLSearchParams();qs.set('requestedBy','evil'); await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST',qs),'requestedBy');
  await rejects(()=>raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST',new Blob(['x'])),'Blob body is forbidden');
  cookie='XSRF-TOKEN=csrf%20token';calls=[];await raw(`/${surface.toLowerCase()}/api/runtime-control/status`,'POST',{safe:'ok'}); assert.equal(calls.length,1); let [,o]=calls[0];let fh=new Headers(o.headers);assert.equal(fh.get('X-XSRF-TOKEN'),'csrf token');assert.equal(o.credentials,'include');assert.equal(o.cache,'no-store');assert.equal(o.redirect,'error');
  let checks=15;
  if(surface==='ADM'){
    calls=[];await raw('/adm/api/auth/login','POST',{operatorId:'admin',password:'secret'});assert.equal(calls.length,1);
    await rejects(()=>raw('/adm/api/auth/login','POST',{nested:{operatorId:'evil'}}),'operatorId');checks+=2;
  }
  if(surface==='BZA'){
    for(const n of ['bzaQuery','bzaMutation','bzaRawResponse','bzaApi','bzaInvokeOperation'])assert.equal(typeof api[n],'function',n);assert.strictEqual(api.admApi,api.bzaApi);assert.strictEqual(api.admMutation,api.bzaMutation);
    calls=[]; const upload=new FormData(); upload.set('groupId','GENERAL'); upload.set('reason','runtime upload'); upload.set('file',new File(['safe'],'safe.txt',{type:'text/plain'}));
    await api.bzaMutation('/api/bza/attachments','POST',upload); assert.equal(calls.length,1); [,o]=calls[0]; fh=new Headers(o.headers); assert(!fh.has('Content-Type'),'multipart boundary must be generated by fetch'); assert.equal(o.body,upload); assert.equal(o.credentials,'include'); checks+=5;
  }
  return checks;
}

async function testMutator(modPath,surface){
  const mut=require(modPath); calls=[];
  const base=surface==='ADM'?'/adm/api/runtime-control/status':'/bza/api/runtime-control/status';
  await rejects(()=>mut.cpfOrvalRequest({url:base,method:'POST',data:{nested:{operatorId:'evil'}}}),'operatorId');
  await rejects(()=>mut.cpfOrvalRequest({url:base,method:'POST',data:'{"requestedBy":"evil"}'}),'requestedBy');
  await rejects(()=>mut.cpfOrvalRequest({url:base+'?actorId=evil',method:'GET'}),'actorId');
  await rejects(()=>mut.cpfOrvalRequest({url:base,method:'GET',params:{operatorId:'evil'}}),'operatorId');
  const form=new FormData();form.set('operatorId','evil');await rejects(()=>mut.cpfOrvalRequest({url:base,method:'POST',data:form}),'operatorId');
  await mut.cpfOrvalRequest({url:base,method:'POST',data:{reason:'safe'}});assert.equal(calls.length,1);
  if(surface==='ADM'){
    calls=[];
    await mut.cpfOrvalRequest({url:'/adm/api/auth/login',method:'POST',data:{operatorId:'admin',password:'secret'}});
    assert.equal(calls.length,1);
    await rejects(()=>mut.cpfOrvalRequest({url:'/adm/api/auth/login',method:'POST',data:{nested:{operatorId:'evil'}}}),'operatorId');
    return 8;
  }
  await rejects(()=>mut.cpfOrvalRequest({url:'/adm/api/auth/login',method:'POST',data:{operatorId:'evil'}}),'operatorId');
  return 7;
}
(async()=>{let n=0;n+=await test(process.argv[2],'ADM');n+=await test(process.argv[3],'BZA');n+=await testMutator(process.argv[4],'ADM');n+=await testMutator(process.argv[5],'BZA');console.log(`PASS surfaces=2 checks>=${n}`)})().catch(e=>{console.error(e);process.exit(1)});
