package com.cpf.file.objectstorage.s3;

import com.cpf.core.api.context.CpfContextSnapshot;
import com.cpf.core.api.context.CpfContexts;

import com.cpf.file.context.*;

import com.cpf.file.objectstorage.api.*;
import java.io.InputStream;
import java.net.URI;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.function.Supplier;
import java.time.Duration;
import java.time.Instant;
import java.util.HexFormat;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.*;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;
import software.amazon.awssdk.services.s3.presigner.model.*;

public final class CpfS3ObjectStorageOperations implements CpfObjectStorageOperations {
 private final S3Client s3; private final S3Presigner presigner; private final CpfObjectStorageProperties p; private final com.cpf.file.objectstorage.api.CpfObjectStorageScanHook scan; private final CpfObjectStorageLifecycleHook lifecycle; private final CpfFileContextSupport contextSupport;
 public CpfS3ObjectStorageOperations(S3Client s3,S3Presigner pr,CpfObjectStorageProperties p,com.cpf.file.objectstorage.api.CpfObjectStorageScanHook scan,CpfObjectStorageLifecycleHook lifecycle,CpfFileContextSupport contextSupport){this.s3=Objects.requireNonNull(s3);this.presigner=Objects.requireNonNull(pr);this.p=Objects.requireNonNull(p);this.scan=Objects.requireNonNull(scan);this.lifecycle=Objects.requireNonNull(lifecycle);this.contextSupport=Objects.requireNonNull(contextSupport);}
 private String bucket(String requested){return requested==null||requested.isBlank()?p.getBucket():requested;}
 private String key(String tenant,String objectKey){if(tenant==null||tenant.isBlank())throw new IllegalArgumentException("tenantId required");validateKey(objectKey);return tenant.trim()+"/"+objectKey;}
 @Override public CpfObjectStorageMetadata put(CpfObjectStorageRequest r){Objects.requireNonNull(r);String b=bucket(r.bucket());requireBucket(b);return withContext("PUT",b,r.objectKey(),null,null,1,()->{String k=key(r.tenantId(),r.objectKey());try{var digest=MessageDigest.getInstance("SHA-256");InputStream inspected=scan.inspect(r.objectKey(),r.content(),r.contentLength(),r.contentType());if(inspected==null)throw new IllegalStateException("scan hook returned null stream");var body=new DigestInputStream(inspected,digest);var rb=PutObjectRequest.builder().bucket(b).key(k).contentType(r.contentType()).contentLength(r.contentLength()).metadata(r.metadata());applyEncryption(rb);var req=rb.build();var out=s3.putObject(req,RequestBody.fromInputStream(body,r.contentLength()));String sha=HexFormat.of().formatHex(digest.digest());if(r.checksumSha256()!=null&&!r.checksumSha256().isBlank()&&!sha.equalsIgnoreCase(r.checksumSha256())){s3.deleteObject(DeleteObjectRequest.builder().bucket(b).key(k).build());throw new IllegalArgumentException("sha256 checksum mismatch");}return new CpfObjectStorageMetadata(r.tenantId(),b,r.objectKey(),r.contentLength(),r.contentType(),out.eTag(),sha,out.versionId(),Instant.now(),r.metadata());}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException("SHA-256 unavailable",e);}});}
 @Override public Optional<CpfObjectStorageMetadata> head(String t,String b,String k){String rb=bucket(b);return withContext("HEAD",rb,k,null,null,1,()->{try{var h=s3.headObject(HeadObjectRequest.builder().bucket(rb).key(key(t,k)).build());return Optional.of(new CpfObjectStorageMetadata(t,rb,k,h.contentLength(),h.contentType(),h.eTag(),h.checksumSHA256(),h.versionId(),h.lastModified(),h.metadata()));}catch(S3Exception e){if(e.statusCode()==404)return Optional.empty();throw e;}});}
 @Override public InputStream get(String t,String b,String k,long off,long len){if(off<0||len<0)throw new IllegalArgumentException("offset/length must be >= 0");String rbucket=bucket(b);var snap=snapshot("GET",rbucket,k,null,null,1);try(var ignored=CpfContexts.bind(snap)){String range=len>0?"bytes="+off+"-"+(off+len-1):null;var rb=GetObjectRequest.builder().bucket(rbucket).key(key(t,k));if(range!=null)rb.range(range);return new CpfContextAwareInputStream(s3.getObject(rb.build()),snap);}catch(RuntimeException failure){throw failure;}catch(Exception failure){throw new IllegalStateException("CPF context scope close failed",failure);}}
 @Override public boolean delete(String t,String b,String k){String rb=bucket(b);return withContext("DELETE",rb,k,null,null,1,()->{var existing=head(t,rb,k);if(existing.isEmpty())return false;lifecycle.beforeDelete(existing.get(),Instant.now());s3.deleteObject(DeleteObjectRequest.builder().bucket(rb).key(key(t,k)).build());return true;});}
 @Override public URI presignGet(String t,String b,String k,Duration ttl){Duration use=ttl(ttl);String rb=bucket(b);return withContext("PRESIGN_GET",rb,k,null,null,1,()->{var req=GetObjectRequest.builder().bucket(rb).key(key(t,k)).build();return URI.create(presigner.presignGetObject(GetObjectPresignRequest.builder().signatureDuration(use).getObjectRequest(req).build()).url().toString());});}
 @Override public URI presignPut(String t,String b,String k,String contentType,Duration ttl){if(!p.isAllowPresignedPut())throw new IllegalStateException("presigned PUT is disabled because it bypasses the streaming scan hook");Duration use=ttl(ttl);String rb=bucket(b);return withContext("PRESIGN_PUT",rb,k,null,null,1,()->{var pb=PutObjectRequest.builder().bucket(rb).key(key(t,k)).contentType(contentType);applyEncryption(pb);var req=pb.build();return URI.create(presigner.presignPutObject(PutObjectPresignRequest.builder().signatureDuration(use).putObjectRequest(req).build()).url().toString());});}
 @Override public CpfMultipartUpload beginMultipart(String t,String b,String k,String contentType,Map<String,String> metadata){String rb=bucket(b);return withContext("MULTIPART_BEGIN",rb,k,null,null,1,()->{var mb=CreateMultipartUploadRequest.builder().bucket(rb).key(key(t,k)).contentType(contentType).metadata(metadata==null?Map.of():metadata);applyEncryption(mb);var out=s3.createMultipartUpload(mb.build());return new CpfMultipartUpload(t,rb,k,out.uploadId());});}
 @Override public String uploadPart(CpfMultipartUpload u,int part,byte[] bytes){if(u==null||part<1||bytes==null)throw new IllegalArgumentException("invalid multipart part");return withContext("MULTIPART_PART",u.bucket(),u.objectKey(),u.uploadId(),Integer.toString(part),1,()->{var out=s3.uploadPart(UploadPartRequest.builder().bucket(u.bucket()).key(key(u.tenantId(),u.objectKey())).uploadId(u.uploadId()).partNumber(part).contentLength((long)bytes.length).build(),RequestBody.fromBytes(bytes));return out.eTag();});}
 @Override public CpfObjectStorageMetadata completeMultipart(CpfMultipartUpload u,Map<Integer,String> etags){if(u==null||etags==null||etags.isEmpty())throw new IllegalArgumentException("multipart parts required");return withContext("MULTIPART_COMPLETE",u.bucket(),u.objectKey(),u.uploadId(),null,1,()->{var parts=etags.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->CompletedPart.builder().partNumber(e.getKey()).eTag(e.getValue()).build()).toList();s3.completeMultipartUpload(CompleteMultipartUploadRequest.builder().bucket(u.bucket()).key(key(u.tenantId(),u.objectKey())).uploadId(u.uploadId()).multipartUpload(CompletedMultipartUpload.builder().parts(parts).build()).build());try{var h=s3.headObject(HeadObjectRequest.builder().bucket(u.bucket()).key(key(u.tenantId(),u.objectKey())).build());return new CpfObjectStorageMetadata(u.tenantId(),u.bucket(),u.objectKey(),h.contentLength(),h.contentType(),h.eTag(),h.checksumSHA256(),h.versionId(),h.lastModified(),h.metadata());}catch(S3Exception e){throw e;}});}
 @Override public void abortMultipart(CpfMultipartUpload u){Objects.requireNonNull(u);withContextVoid("MULTIPART_ABORT",u.bucket(),u.objectKey(),u.uploadId(),null,1,()->s3.abortMultipartUpload(AbortMultipartUploadRequest.builder().bucket(u.bucket()).key(key(u.tenantId(),u.objectKey())).uploadId(u.uploadId()).build()));}
 @Override public int abortMultipartOlderThan(String b,Duration age){if(age==null||age.isNegative()||age.isZero())throw new IllegalArgumentException("age must be positive");b=bucket(b);Instant cutoff=Instant.now().minus(age);int count=0;String km=null,um=null;do{var r=s3.listMultipartUploads(ListMultipartUploadsRequest.builder().bucket(b).keyMarker(km).uploadIdMarker(um).build());for(var u:r.uploads()){if(u.initiated()!=null&&u.initiated().isBefore(cutoff)){s3.abortMultipartUpload(AbortMultipartUploadRequest.builder().bucket(b).key(u.key()).uploadId(u.uploadId()).build());count++;}}km=r.nextKeyMarker();um=r.nextUploadIdMarker();if(!r.isTruncated())break;}while(true);return count;}
 private CpfContextSnapshot snapshot(String operation,String bucket,String objectKey,String transferId,String partId,int attempt){String logical=objectKey==null?null:objectKey.substring(objectKey.lastIndexOf('/')+1);return contextSupport.child(null,transferId==null?"OBJ-"+UUID.randomUUID():transferId,logical,"S3",bucket,hash(objectKey),"S3",operation,null,partId,null,null,attempt,null);}
 private <T> T withContext(String operation,String bucket,String objectKey,String transferId,String partId,int attempt,Supplier<T> work){var snap=snapshot(operation,bucket,objectKey,transferId,partId,attempt);try(var ignored=CpfContexts.bind(snap)){return work.get();}catch(RuntimeException failure){throw failure;}catch(Exception failure){throw new IllegalStateException("CPF context scope close failed",failure);}}
 private void withContextVoid(String operation,String bucket,String objectKey,String transferId,String partId,int attempt,Runnable work){withContext(operation,bucket,objectKey,transferId,partId,attempt,()->{work.run();return null;});}
 private static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Objects.toString(value,"").getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("SHA-256 unavailable",e);}}

 private void applyEncryption(PutObjectRequest.Builder b){if(p.getKmsKeyId()!=null&&!p.getKmsKeyId().isBlank())b.serverSideEncryption(ServerSideEncryption.AWS_KMS).ssekmsKeyId(p.getKmsKeyId().trim());}
 private void applyEncryption(CreateMultipartUploadRequest.Builder b){if(p.getKmsKeyId()!=null&&!p.getKmsKeyId().isBlank())b.serverSideEncryption(ServerSideEncryption.AWS_KMS).ssekmsKeyId(p.getKmsKeyId().trim());}

 private static void validateKey(String key){if(key==null||key.isBlank()||key.startsWith("/")||key.contains("..")||key.contains("\\"))throw new IllegalArgumentException("unsafe object key");}
 private static void requireBucket(String b){if(b==null||b.isBlank())throw new IllegalStateException("object storage bucket is required");}
 private static Duration ttl(Duration d){Duration use=d==null?Duration.ofMinutes(5):d;if(use.isNegative()||use.isZero()||use.compareTo(Duration.ofDays(7))>0)throw new IllegalArgumentException("presign expiry out of policy");return use;}
}
