spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
cpf.batch.remote.transport=kafka
cpf.batch.remote.kafka.role=MANAGER
cpf.batch.remote.worker-enabled=false
cpf.messaging.kafka.default-binding=${CPF_MESSAGING_KAFKA_DEFAULT_BINDING:true}
