-- V2: 거래 헤더 로그 컬럼 보강 migration입니다.
-- 신규 설치 기준에서는 V1 baseline에 이미 포함되어 있으며, 기존 DB 업그레이드 시에도 idempotent하게 동작합니다.

USE pfwDB;

ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS API_VERSION VARCHAR(20) NULL COMMENT '호출 API 버전' AFTER LOG_TYPE;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS CLIENT_APP_ID VARCHAR(80) NULL COMMENT '클라이언트 앱 또는 제휴 시스템 ID' AFTER API_VERSION;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS CLIENT_VERSION VARCHAR(50) NULL COMMENT '클라이언트 앱 또는 SDK 버전' AFTER CLIENT_APP_ID;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS CALLER_SERVICE VARCHAR(120) NULL COMMENT '호출 서비스명' AFTER CLIENT_VERSION;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS CALLER_INSTANCE_ID VARCHAR(120) NULL COMMENT '호출 인스턴스 ID' AFTER CALLER_SERVICE;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS CORRELATION_ID VARCHAR(120) NULL COMMENT '내부 연계 상관관계 ID' AFTER CALLER_INSTANCE_ID;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS IDEMPOTENCY_KEY VARCHAR(120) NULL COMMENT '중복 처리 방지 멱등키' AFTER CORRELATION_ID;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS LOCALE VARCHAR(20) NULL COMMENT '클라이언트 locale' AFTER IDEMPOTENCY_KEY;
ALTER TABLE pfw_transaction_log ADD COLUMN IF NOT EXISTS TIMEZONE VARCHAR(50) NULL COMMENT '클라이언트 시간대' AFTER LOCALE;

CREATE INDEX IF NOT EXISTS ix_pfw_transaction_log_client_app ON pfw_transaction_log (CLIENT_APP_ID, START_TIME);
CREATE INDEX IF NOT EXISTS ix_pfw_transaction_log_correlation ON pfw_transaction_log (CORRELATION_ID, START_TIME);
CREATE INDEX IF NOT EXISTS ix_pfw_transaction_log_idempotency ON pfw_transaction_log (IDEMPOTENCY_KEY);

USE admDB;

UPDATE adm_audit_log
   SET REASON = '기존 데이터 사유 보정'
 WHERE REASON IS NULL
    OR TRIM(REASON) = '';

ALTER TABLE adm_audit_log MODIFY COLUMN REASON VARCHAR(500) NOT NULL COMMENT '감사 사유';
ALTER TABLE adm_audit_log ADD COLUMN IF NOT EXISTS BEFORE_DATA LONGTEXT NULL COMMENT '변경 전 데이터' AFTER REASON;
ALTER TABLE adm_audit_log ADD COLUMN IF NOT EXISTS AFTER_DATA LONGTEXT NULL COMMENT '변경 후 데이터' AFTER BEFORE_DATA;
ALTER TABLE adm_audit_log ADD COLUMN IF NOT EXISTS DIFF_DATA LONGTEXT NULL COMMENT '변경 차이 데이터' AFTER AFTER_DATA;
ALTER TABLE adm_audit_log ADD COLUMN IF NOT EXISTS RETENTION_UNTIL DATE NULL COMMENT '보존 만료 기준일' AFTER CLIENT_IP;
ALTER TABLE adm_audit_log ADD COLUMN IF NOT EXISTS IMMUTABLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '삭제 불가 여부' AFTER RETENTION_UNTIL;
CREATE INDEX IF NOT EXISTS ix_adm_audit_log_retention ON adm_audit_log (RETENTION_UNTIL, IMMUTABLE_YN);
