package com.cpf.core.common.reconciliation;
import org.springframework.scheduling.annotation.Scheduled;import java.time.Instant;import java.util.*;import java.util.concurrent.atomic.AtomicLong;
/** 분산 claim 후 외부 Probe를 실행하는 결과불명 자동확인 Worker입니다. */
public final class CpfReconciliationWorker{
 private final CpfReconciliationPort port;private final CpfReconciliationWorkPort work;private final CpfReconciliationRuntimePolicy policy;private final List<CpfReconciliationProbePort>probes;private final String workerId;private final AtomicLong nextRun=new AtomicLong();
 public CpfReconciliationWorker(CpfReconciliationPort port,CpfReconciliationWorkPort work,CpfReconciliationRuntimePolicy policy,List<CpfReconciliationProbePort>probes,String workerId){this.port=port;this.work=work;this.policy=policy;this.workerId=workerId==null||workerId.isBlank()?"CPF-RECONCILIATION":workerId;this.probes=probes==null?List.of():List.copyOf(probes);}
 @Scheduled(fixedDelayString="${cpf.reconciliation.worker.tick-millis:1000}")public void tick(){var p=policy.current();long now=System.currentTimeMillis();if(!p.enabled()||now<nextRun.get())return;nextRun.set(now+p.queryIntervalMillis());if(p.unknownTypes().isEmpty()){for(var item:work.claim(null,p.thresholdSeconds(),p.batchSize(),workerId,p.leaseSeconds())){CpfReconciliationProbePort probe=findProbe(item.record().unknownType());if(probe==null){work.defer(item.record().unknownId(),workerId,Instant.now().plusMillis(p.queryIntervalMillis()),"PROBE_NOT_FOUND");}else handle(item,probe,p);}return;}for(String type:p.unknownTypes()){CpfReconciliationProbePort probe=findProbe(type);if(probe==null)continue;for(var item:work.claim(type,p.thresholdSeconds(),p.batchSize(),workerId,p.leaseSeconds()))handle(item,probe,p);}}
 private CpfReconciliationProbePort findProbe(String type){for(var probe:probes)if(probe.supports(type))return probe;return null;}
 private void handle(CpfReconciliationWorkPort.WorkItem item,CpfReconciliationProbePort probe,CpfReconciliationRuntimePolicy.Snapshot p){try{var result=probe.probe(item.record());if(result==null||result.outcome()==CpfReconciliationProbePort.Outcome.PENDING){work.defer(item.record().unknownId(),workerId,Instant.now().plusMillis(p.queryIntervalMillis()),"PROBE_PENDING");return;}String status=result.outcome()==CpfReconciliationProbePort.Outcome.CONFIRMED_SUCCESS?"RESOLVED_SUCCESS":"RESOLVED_FAILED";if(p.manualResolutionRequired())work.markManualReview(item.record().unknownId(),workerId,status+":"+safe(result.reason()));else port.resolve(item.record().unknownId(),status,"CPF_RECONCILIATION","자동 결과 확인: "+safe(result.reason()));}catch(RuntimeException ex){work.defer(item.record().unknownId(),workerId,Instant.now().plusMillis(p.queryIntervalMillis()),"PROBE_ERROR:"+ex.getClass().getSimpleName());}}
 private String safe(String v){if(v==null)return "";String s=v.replaceAll("(?i)(password|token|secret|authorization|api[-_]?key)\\s*[:=]\\s*[^,;\\s]+","$1=***");return s.length()>300?s.substring(0,300):s;}
}
