package com.cpf.batch.agent.internal;
import com.cpf.batch.agent.AgentProperties;import com.cpf.batch.api.AgentArtifactRequest;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.security.spec.X509EncodedKeySpec;import java.util.*;
public final class ArtifactVerifier{
 private final AgentProperties p;public ArtifactVerifier(AgentProperties p){this.p=p;}
 public Verified verify(Path file,AgentArtifactRequest r,long size)throws Exception{String actual=digest(file);if(!actual.equalsIgnoreCase(r.sha256()))throw new SecurityException("checksum mismatch");if(!p.isRequireSignature())throw new SecurityException("unsigned artifact mode is prohibited");if(r.signatureBase64()==null||r.signatureBase64().isBlank()||r.keyId()==null||r.keyId().isBlank())throw new SecurityException("signature/keyId required");Path keyPath=Path.of(Objects.requireNonNull(p.getArtifactPublicKeyPath())).toAbsolutePath().normalize();if(Files.isSymbolicLink(keyPath)||!Files.isRegularFile(keyPath,LinkOption.NOFOLLOW_LINKS))throw new SecurityException("unsafe public key path");String pem=Files.readString(keyPath,StandardCharsets.US_ASCII).replace("-----BEGIN PUBLIC KEY-----","").replace("-----END PUBLIC KEY-----","").replaceAll("\\s","");PublicKey key=KeyFactory.getInstance("Ed25519").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(pem)));String canonical=canonical(r,size,actual);Signature signature=Signature.getInstance("Ed25519");signature.initVerify(key);signature.update(canonical.getBytes(StandardCharsets.UTF_8));if(!signature.verify(Base64.getDecoder().decode(r.signatureBase64())))throw new SecurityException("signature invalid");return new Verified(actual,size,canonical);}
 static String canonical(AgentArtifactRequest r,long size,String digest){return String.join("\n","cpf-artifact-manifest-v1","serviceId="+clean(r.serviceId()),"coordinate="+clean(r.coordinate()),"version="+clean(r.version()),"sha256="+digest.toLowerCase(Locale.ROOT),"size="+size,"runtimeMode="+clean(r.runtimeMode()),"environment="+clean(r.environmentCode()),"channel="+clean(r.channel()),"releaseSequence="+r.releaseSequence(),"keyId="+clean(r.keyId()));}
 private static String clean(String v){if(v==null||v.isBlank()||v.indexOf('\n')>=0||v.indexOf('\r')>=0)throw new SecurityException("invalid manifest field");return v.trim();}
 private static String digest(Path f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(f)){byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}
 public record Verified(String sha256,long size,String canonicalManifest){}
}
