package com.cpf.batch.agent.internal;
import com.cpf.batch.agent.AgentProperties;import com.cpf.batch.runtime.SensitiveTextSanitizer;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;
public final class ServiceManager{
 private final AgentProperties p;public ServiceManager(AgentProperties p){this.p=p;}
 public Result execute(String id,Action a)throws Exception{var s=service(id);List<String> cmd;if(isWindows()){Path script=Path.of(required(s.getWindowsStartScript(),"Windows script")).toAbsolutePath().normalize();if(!Files.isRegularFile(script,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(script))throw new SecurityException("unsafe Windows script");cmd=List.of("pwsh","-NoProfile","-NonInteractive","-ExecutionPolicy","AllSigned","-File",script.toString(),"-Action",a.name());}else{String unit=required(s.getSystemdUnit(),"systemd unit");if(!unit.matches("[A-Za-z0-9@_.-]+\\.service"))throw new SecurityException("invalid unit");cmd=List.of("systemctl",switch(a){case START->"start";case STOP->"stop";case RESTART->"restart";case STATUS->"is-active";},unit);}
  Process pr=new ProcessBuilder(cmd).redirectErrorStream(true).start();ByteArrayOutputStream out=new ByteArrayOutputStream();Future<?> drain=Executors.newVirtualThreadPerTaskExecutor().submit(()->copyBounded(pr.getInputStream(),out,p.getMaxProcessOutputBytes()));boolean done=pr.waitFor(Math.max(1,p.getProcessTimeoutSeconds()),TimeUnit.SECONDS);if(!done){killTree(pr);drain.cancel(true);return new Result(false,-1,"TIMEOUT");}drain.get(5,TimeUnit.SECONDS);String text=SensitiveTextSanitizer.sanitize(out.toString(StandardCharsets.UTF_8));return new Result(pr.exitValue()==0,pr.exitValue(),text);
 }
 public boolean stopped(String id)throws Exception{Result r=execute(id,Action.STATUS);return !r.success()&&Set.of(3,4).contains(r.exitCode())||r.output().toLowerCase(Locale.ROOT).contains("inactive");}
 private static void copyBounded(InputStream in,OutputStream out,long max){try(in){byte[] b=new byte[8192];long n=0;for(int r;(r=in.read(b))>=0;){n+=r;if(n>max)throw new IOException("process output limit exceeded");out.write(b,0,r);}}catch(IOException e){throw new UncheckedIOException(e);}}
 private static void killTree(Process p){p.descendants().forEach(ProcessHandle::destroy);p.destroy();try{if(!p.waitFor(5,TimeUnit.SECONDS)){p.descendants().forEach(ProcessHandle::destroyForcibly);p.destroyForcibly();}}catch(InterruptedException e){Thread.currentThread().interrupt();p.destroyForcibly();}}
 private AgentProperties.ServiceDefinition service(String id){return p.getServices().values().stream().filter(x->id.equals(x.getServiceId())).findFirst().orElseThrow(()->new SecurityException("unknown service"));}private static boolean isWindows(){return System.getProperty("os.name").toLowerCase().contains("windows");}private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalStateException(f+" missing");return v;}public enum Action{START,STOP,RESTART,STATUS}public record Result(boolean success,int exitCode,String output){}
}
