spring.application.name=cpf-batch-worker
server.port=8182
cpf.batch.control.base-url=${CPF_BATCH_CONTROL_BASE_URL:http://127.0.0.1:8180}
cpf.batch.runtime.instance-id=${CPF_INSTANCE_ID:cpf-batch-worker-01}
cpf.batch.runtime.heartbeat-ms=${CPF_RUNTIME_HEARTBEAT_MS:5000}
logging.level.root=${CPF_LOG_LEVEL:INFO}
