<script setup lang="ts">
import {computed,onMounted,reactive,ref} from "vue";
import {bzaApi,hasBzaPermission} from "../auth/session";
import {buildMenuTree,descendantCodes,flattenMenuTree,validateParentMove,type MenuRow} from "./menuTree";
const rows=ref<MenuRow[]>([]),loading=ref(false),error=ref(""),message=ref(""),dialog=ref(false),editing=ref(false),expanded=ref(new Set<string>());
const removeDialog=ref(false),removeRow=ref<MenuRow|null>(null),removeReason=ref("미사용 메뉴 삭제"),removeConfirmed=ref(false);
const form=reactive<any>({menuCode:"",parentMenuCode:"",menuName:"",routePath:"",sortOrder:0,useYn:"Y",expectedVersion:0,reason:"메뉴 Registry 변경"});
const tree=computed(()=>buildMenuTree(rows.value));const visible=computed(()=>{const out:any[]=[];const walk=(nodes:any[])=>nodes.forEach(n=>{out.push(n);if(expanded.value.has(n.menuCode))walk(n.children)});walk(tree.value);return out;});
const canWrite=computed(()=>hasBzaPermission("AUTHORIZATION","WRITE"));const canDelete=computed(()=>hasBzaPermission("AUTHORIZATION","DELETE"));
async function load(){loading.value=true;error.value="";try{const result:any=await bzaApi("/api/bza/menus/page?page=0&size=1000");rows.value=Array.isArray(result)?result:(result.content||[]);for(const root of tree.value)expanded.value.add(root.menuCode);}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
function open(row?:MenuRow){editing.value=!!row;Object.assign(form,{menuCode:row?.menuCode||"",parentMenuCode:row?.parentMenuCode||"",menuName:row?.menuName||"",routePath:row?.routePath||"",sortOrder:Number(row?.sortOrder||0),useYn:row?.useYn||"Y",expectedVersion:Number(row?.versionNo||0),reason:"메뉴 Registry 변경"});dialog.value=true;}
async function save(){const invalid=validateParentMove(rows.value,form.menuCode,form.parentMenuCode);if(invalid){message.value=invalid;return;}if(form.reason.trim().length<5){message.value="감사 사유는 5자 이상이어야 합니다.";return;}try{await bzaApi("/api/bza/menus",{method:"POST",body:JSON.stringify({...form,operationId:crypto.randomUUID(),parentMenuCode:form.parentMenuCode||null})});dialog.value=false;message.value="";await load();}catch(e){message.value=e instanceof Error?e.message:String(e);}}
function remove(row:MenuRow){const children=descendantCodes(rows.value,row.menuCode);if(children.length){error.value=`하위 메뉴 ${children.length}건을 먼저 이동하거나 비활성화해야 합니다.`;return;}removeRow.value=row;removeReason.value="미사용 메뉴 삭제";removeConfirmed.value=false;removeDialog.value=true;}
function cancelRemove(){removeDialog.value=false;removeRow.value=null;removeConfirmed.value=false;}
async function confirmRemove(){const row=removeRow.value;if(!row)return;if(removeReason.value.trim().length<5){error.value="삭제 사유는 5자 이상이어야 합니다.";return;}if(!removeConfirmed.value)return;try{await bzaApi(`/api/bza/menus/${encodeURIComponent(row.menuCode)}`,{method:"DELETE",body:JSON.stringify({operationId:crypto.randomUUID(),expectedVersion:Number(row.versionNo||0),reason:removeReason.value.trim()})});cancelRemove();await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}}
function toggle(code:string){const next=new Set(expanded.value);next.has(code)?next.delete(code):next.add(code);expanded.value=next;}
onMounted(load);
</script>
<template><section class="card table-card"><div class="card-head"><div><p class="eyebrow">TREE REGISTRY</p><h2>메뉴 Registry</h2><p>상하위 메뉴를 Tree로 확인하고 이동·정렬·사용 여부를 낙관적 잠금으로 관리합니다.</p></div><div class="inline-actions"><span class="count-pill">{{rows.length}}건</span><button class="ghost" @click="load">새로고침</button><button v-if="canWrite" class="primary" @click="open()">등록</button></div></div><p v-if="error" class="error-banner">{{error}}</p><div v-if="loading" class="empty-state">조회 중...</div><div v-else class="table-wrap"><table><thead><tr><th>메뉴</th><th>상위</th><th>Route</th><th>정렬</th><th>사용</th><th>Version</th><th>관리</th></tr></thead><tbody><tr v-for="node in visible" :key="node.menuCode"><td><span :style="{paddingLeft:`${node.depth*22}px`}"><button v-if="node.children.length" class="icon-button" @click="toggle(node.menuCode)">{{expanded.has(node.menuCode)?'−':'+'}}</button><span v-else class="tree-spacer"></span><strong>{{node.menuName}}</strong> <small>{{node.menuCode}}</small><span v-if="node.orphan||node.cycle" class="status danger">{{node.cycle?'순환':'상위 없음'}}</span></span></td><td>{{node.parentMenuCode||'-'}}</td><td>{{node.routePath||'-'}}</td><td>{{node.sortOrder}}</td><td>{{node.useYn}}</td><td>{{node.versionNo}}</td><td><button v-if="canWrite" class="ghost" @click="open(node)">수정·이동</button><button v-if="canDelete" class="danger" @click="remove(node)">삭제</button></td></tr><tr v-if="!visible.length"><td colspan="7" class="empty-cell">등록된 메뉴가 없습니다.</td></tr></tbody></table></div>
<dialog :open="dialog" class="modal"><form class="modal-card" @submit.prevent="save"><div class="card-head"><div><p class="eyebrow">TREE EDIT</p><h2>메뉴 등록·수정</h2></div><button type="button" class="icon-button" @click="dialog=false">×</button></div><div class="form-grid"><label><span>메뉴 코드</span><input v-model.trim="form.menuCode" :readonly="editing" required></label><label><span>상위 메뉴</span><select v-model="form.parentMenuCode"><option value="">최상위</option><option v-for="row in rows.filter(r=>r.menuCode!==form.menuCode)" :key="row.menuCode" :value="row.menuCode">{{row.menuName}} ({{row.menuCode}})</option></select></label><label><span>메뉴명</span><input v-model.trim="form.menuName" required></label><label><span>Route</span><input v-model.trim="form.routePath"></label><label><span>정렬</span><input v-model.number="form.sortOrder" type="number"></label><label><span>사용</span><select v-model="form.useYn"><option>Y</option><option>N</option></select></label><label class="wide"><span>영향</span><div class="hint">현재 하위 메뉴 {{descendantCodes(rows,form.menuCode).length}}건. 상위 이동 시 전체 경로와 권한 Manifest 영향을 확인하세요.</div></label><label class="wide"><span>감사 사유</span><textarea v-model.trim="form.reason" rows="3" required></textarea></label></div><p v-if="message" class="error-banner">{{message}}</p><div class="dialog-actions"><button type="button" class="ghost" @click="dialog=false">취소</button><button class="primary" type="submit">저장</button></div></form></dialog>
<dialog :open="removeDialog" class="modal"><form class="modal-card" @submit.prevent="confirmRemove"><div class="card-head"><div><p class="eyebrow">DANGEROUS ACTION</p><h2>메뉴 삭제 확인</h2></div><button type="button" class="icon-button" @click="cancelRemove">×</button></div><p v-if="removeRow"><strong>{{removeRow.menuName}}</strong> ({{removeRow.menuCode}})</p><label><span>감사 사유</span><textarea v-model.trim="removeReason" rows="3" required></textarea></label><label><input v-model="removeConfirmed" type="checkbox"> 하위 메뉴와 권한 영향이 없음을 확인했습니다.</label><div class="dialog-actions"><button type="button" class="ghost" @click="cancelRemove">취소</button><button type="submit" class="danger" :disabled="!removeConfirmed||removeReason.trim().length<5">삭제</button></div></form></dialog>
</section></template>
