<script setup lang="ts">
import { reactive, ref } from "vue";
import DataTable from "../../components/DataTable.vue";
import { bzaApi } from "../auth/session";
const compare=reactive({leftRoleCode:"",rightRoleCode:""});
const simulation=reactive({roleCode:"",menuCode:"",actionCode:"",httpMethod:"GET",apiPath:"/api/bza/",environmentCode:"ALL",domainCode:"BZA",reason:"권한 시뮬레이션"});
const compareRows=ref<Record<string,unknown>[]>([]); const simulationResult=ref<unknown>(null); const error=ref("");
async function compareRoles(){try{compareRows.value=await bzaApi(`/api/bza/permissions/compare?leftRoleCode=${encodeURIComponent(compare.leftRoleCode)}&rightRoleCode=${encodeURIComponent(compare.rightRoleCode)}`);}catch(e){error.value=e instanceof Error?e.message:String(e);}}
async function simulate(){try{simulationResult.value=await bzaApi("/api/bza/permissions/simulate",{method:"POST",body:JSON.stringify(simulation)});}catch(e){error.value=e instanceof Error?e.message:String(e);}}
</script>
<template><div class="page-stack"><p v-if="error" class="error-banner">{{error}}</p><section class="card"><div class="card-head"><div><p class="eyebrow">COMPARE</p><h2>역할 권한 비교</h2></div></div><form class="form-grid compact" @submit.prevent="compareRoles"><label><span>기준 역할</span><input v-model="compare.leftRoleCode" required></label><label><span>비교 역할</span><input v-model="compare.rightRoleCode" required></label><div class="form-action"><button class="primary">비교</button></div></form></section><DataTable title="권한 차이" :rows="compareRows" :columns="['permissionKey','leftRoleCode','rightRoleCode','different']"/><section class="card"><div class="card-head"><div><p class="eyebrow">SIMULATION</p><h2>권한 시뮬레이션</h2></div></div><form class="form-grid" @submit.prevent="simulate"><label><span>역할</span><input v-model="simulation.roleCode" required></label><label><span>메뉴</span><input v-model="simulation.menuCode" required></label><label><span>행위</span><input v-model="simulation.actionCode" required></label><label><span>HTTP</span><input v-model="simulation.httpMethod"></label><label class="wide"><span>API 경로</span><input v-model="simulation.apiPath"></label><label><span>환경</span><input v-model="simulation.environmentCode"></label><label><span>업무 영역</span><input v-model="simulation.domainCode"></label><label class="wide"><span>감사 사유</span><textarea v-model="simulation.reason" required></textarea></label><div class="form-action"><button class="primary">실행</button></div></form><pre v-if="simulationResult" class="json-block">{{JSON.stringify(simulationResult,null,2)}}</pre></section></div></template>
