package com.cpf.reference.transaction.tcc;

import static org.assertj.core.api.Assertions.*;import com.cpf.core.api.transaction.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class ReferenceDurableTccReservationParticipantTest {
 @Test void emptyRollbackPreventsHangingTry(){var s=new MemoryStore();var p=new ReferenceDurableTccReservationParticipant(s);var c=ctx(Instant.now().plusSeconds(60));var cmd=cmd();assertThat(p.cancel(c,cmd)).isEqualTo(CpfTccResult.EMPTY_ROLLBACK);assertThat(p.tryAction(c,cmd)).isEqualTo(CpfTccResult.HANGING_REJECTED);}
 @Test void duplicateConfirmIsIdempotent(){var s=new MemoryStore();var p=new ReferenceDurableTccReservationParticipant(s);var c=ctx(Instant.now().plusSeconds(60));var cmd=cmd();assertThat(p.tryAction(c,cmd)).isEqualTo(CpfTccResult.APPLIED);assertThat(p.confirm(c,cmd)).isEqualTo(CpfTccResult.APPLIED);assertThat(p.confirm(c,cmd)).isEqualTo(CpfTccResult.ALREADY_APPLIED);}
 @Test void confirmAfterDeadlineRoutesManualReview(){var s=new MemoryStore();var p=new ReferenceDurableTccReservationParticipant(s);var fresh=ctx(Instant.now().plusSeconds(60));var cmd=cmd();p.tryAction(fresh,cmd);var expired=ctx(Instant.now().minusSeconds(1));assertThat(p.confirm(expired,cmd)).isEqualTo(CpfTccResult.MANUAL_REVIEW);assertThat(s.row.state()).isEqualTo(ReferenceTccReservationState.MANUAL_REVIEW);}
 private static CpfTccContext ctx(Instant deadline){return new CpfTccContext("tx","b","idem",deadline,Map.of());} private static ReferenceTccReservationCommand cmd(){return new ReferenceTccReservationCommand("acct",BigDecimal.TEN);}
 static final class MemoryStore implements ReferenceTccReservationStore {ReferenceTccReservationRecord row;public Optional<ReferenceTccReservationRecord> find(String t,String b){return Optional.ofNullable(row);}public boolean createTry(ReferenceTccReservationRecord r){if(row!=null)return false;row=r;return true;}public boolean createEmptyRollback(ReferenceTccReservationRecord r){if(row!=null)return false;row=r;return true;}public boolean transition(String t,String b,ReferenceTccReservationState e,ReferenceTccReservationState n,long f){if(row==null||row.state()!=e||row.fencingToken()!=f)return false;row=new ReferenceTccReservationRecord(row.transactionId(),row.branchId(),row.idempotencyKey(),row.accountId(),row.amount(),n,row.deadline(),f+1,Instant.now());return true;}public boolean markManualReview(String t,String b,String reason){if(row==null)return false;row=new ReferenceTccReservationRecord(row.transactionId(),row.branchId(),row.idempotencyKey(),row.accountId(),row.amount(),ReferenceTccReservationState.MANUAL_REVIEW,row.deadline(),row.fencingToken()+1,Instant.now());return true;}public List<ReferenceTccReservationRecord> findExpired(int l){return row==null?List.of():List.of(row);}}
}
