package com.cpf.file.common.attachment;
import com.cpf.file.spi.attachment.CpfAttachmentDownloadContext;
import com.cpf.file.attachment.internal.CpfAttachmentRuntimePolicy;
import com.cpf.file.spi.attachment.CpfAttachmentInspectionPort;
import com.cpf.file.spi.attachment.CpfAttachmentWatermarkPort;
import com.cpf.file.attachment.api.*;import com.cpf.core.api.error.CpfValidationException;import java.io.*;import java.nio.file.*;import java.security.*;import java.time.*;import java.util.*;
/** Temp+atomic move, size/hash 검증, symlink 방어를 적용한 bounded streaming Adapter입니다. */
public class LocalCpfAttachmentStorageAdapter implements CpfAttachmentStoragePort{
 private final Path root;private final Clock clock;private final CpfAttachmentRuntimePolicy policy;private final CpfAttachmentInspectionPort inspection;private final CpfAttachmentWatermarkPort watermark;
 public LocalCpfAttachmentStorageAdapter(Path root,long maxBytes,Set<String>ext){this(root,new CpfAttachmentRuntimePolicy(),null,null,Clock.systemUTC());this.policy.replaceAttachment(0,maxBytes,ext,Set.of(),false,3650,true,false);}public LocalCpfAttachmentStorageAdapter(Path root,CpfAttachmentRuntimePolicy p,CpfAttachmentInspectionPort i,CpfAttachmentWatermarkPort w){this(root,p,i,w,Clock.systemUTC());}LocalCpfAttachmentStorageAdapter(Path root,CpfAttachmentRuntimePolicy p,CpfAttachmentInspectionPort i,CpfAttachmentWatermarkPort w,Clock c){this.root=Objects.requireNonNull(root).toAbsolutePath().normalize();this.policy=Objects.requireNonNull(p);this.inspection=i;this.watermark=w;this.clock=c;}
 @Override public CpfStoredAttachment store(String groupId,String originalFileName,String contentType,InputStream content,long declaredSize){Objects.requireNonNull(content);String group=segment(groupId),name=fileName(originalFileName),ext=extension(name),mime=mime(contentType);var upload=policy.current().upload();if(declaredSize<=0||declaredSize>upload.maxBytes())throw new CpfValidationException("첨부파일 크기 정책 위반");if(!upload.allowedExtensions().isEmpty()&&!upload.allowedExtensions().contains(ext))throw new CpfValidationException("허용되지 않은 확장자");if(!upload.allowedMimeTypes().isEmpty()&&!upload.allowedMimeTypes().contains(mime.toLowerCase(Locale.ROOT)))throw new CpfValidationException("허용되지 않은 MIME");String stored=UUID.randomUUID().toString().replace("-","")+"."+ext;Path dir=safe(root.resolve(group)),target=safe(dir.resolve(stored)),temp=safe(dir.resolve(stored+".part"));try{Files.createDirectories(dir);noLink(root);noLink(dir);MessageDigest d=MessageDigest.getInstance("SHA-256");long total=0;try(InputStream in=content;OutputStream out=Files.newOutputStream(temp,StandardOpenOption.CREATE_NEW)){byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;){total+=n;if(total>upload.maxBytes()||total>declaredSize)throw new CpfValidationException("첨부파일 stream 크기 위반");d.update(b,0,n);out.write(b,0,n);}}if(total!=declaredSize)throw new CpfValidationException("선언 크기와 실제 크기가 다릅니다.");if(upload.scanRequired()){if(inspection==null)throw new CpfValidationException("첨부 scan adapter 필요");byte[] bounded=readBounded(temp,upload.maxBytes());var result=inspection.inspect(name,mime,bounded,upload.quarantineOnFailure());if(result==null||!result.accepted())throw new CpfValidationException("첨부 scan 거부");}atomic(temp,target);return new CpfStoredAttachment(root.relativize(target).toString().replace('\\','/'),name,stored,mime,total,HexFormat.of().formatHex(d.digest()),Instant.now(clock));}catch(Exception e){try{Files.deleteIfExists(temp);}catch(IOException ignored){}if(e instanceof RuntimeException r)throw r;throw new IllegalStateException("첨부파일 저장 실패",e);}}
 @Override public CpfAttachmentStream open(String storageKey){Path target=safe(root.resolve(required(storageKey)));noLink(target);var snapshot=policy.current();download(snapshot.download());try{long size=Files.size(target);if(size>snapshot.upload().maxBytes())throw new CpfValidationException("첨부 읽기 크기 위반");if(Files.getLastModifiedTime(target).toInstant().plus(Duration.ofDays(snapshot.upload().retentionDays())).isBefore(Instant.now(clock))){Files.deleteIfExists(target);throw new CpfValidationException("첨부 보관기간 만료");}String hash=hash(target);if(snapshot.download().watermarkRequired()){if(watermark==null)throw new CpfValidationException("watermark adapter 필요");byte[] transformed=watermark.apply(storageKey,readBounded(target,snapshot.upload().maxBytes()),CpfAttachmentDownloadContext.current());if(transformed.length>snapshot.upload().maxBytes())throw new CpfValidationException("watermark 결과 크기 위반");return new CpfAttachmentStream(new ByteArrayInputStream(transformed),transformed.length,sha(transformed));}return new CpfAttachmentStream(Files.newInputStream(target,LinkOption.NOFOLLOW_LINKS),size,hash);}catch(IOException e){throw new IllegalStateException("첨부파일 읽기 실패",e);}}
 @Override public void delete(String key){Path target=safe(root.resolve(required(key)));noLink(target);try{Files.deleteIfExists(target);}catch(IOException e){throw new IllegalStateException(e);}}
 private void download(CpfAttachmentRuntimePolicy.Download p){if(!p.permissionRequired()&&!p.approvalRequired()&&!p.watermarkRequired())return;var c=CpfAttachmentDownloadContext.current();if(c==null||p.permissionRequired()&&!c.permitted()||p.approvalRequired()&&(c.approvalId()==null||c.approvalId().isBlank()))throw new CpfValidationException("다운로드 권한/승인 필요");Instant now=Instant.now(clock);if(c.expiresAt()!=null&&now.isAfter(c.expiresAt())||Duration.between(c.requestedAt(),now).getSeconds()>p.linkExpirySeconds())throw new CpfValidationException("다운로드 만료");}
 private Path safe(Path p){Path n=p.toAbsolutePath().normalize();if(!n.startsWith(root))throw new CpfValidationException("경로 이탈");return n;}private static void noLink(Path p){if(Files.exists(p,LinkOption.NOFOLLOW_LINKS)&&Files.isSymbolicLink(p))throw new CpfValidationException("symlink 금지");}private static void atomic(Path a,Path b)throws IOException{try{Files.move(a,b,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(a,b);}}private static byte[] readBounded(Path p,long max)throws IOException{try(InputStream in=Files.newInputStream(p)){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];long n=0;for(int r;(r=in.read(b))>=0;){n+=r;if(n>max)throw new CpfValidationException("bounded read 초과");out.write(b,0,r);}return out.toByteArray();}}private static String hash(Path p){try{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(p)){byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}catch(Exception e){throw new IllegalStateException(e);}}private static String sha(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}private static String required(String s){if(s==null||s.isBlank())throw new CpfValidationException("필수값");return s.trim();}private static String segment(String s){s=required(s);if(!s.matches("[A-Za-z0-9_-]{1,80}"))throw new CpfValidationException("groupId");return s;}private static String fileName(String s){s=required(s);if(!Path.of(s).getFileName().toString().equals(s)||s.contains("..")||s.length()>255)throw new CpfValidationException("파일명");return s;}private static String extension(String s){int i=s.lastIndexOf('.');if(i<1||i==s.length()-1)throw new CpfValidationException("확장자");return s.substring(i+1).toLowerCase(Locale.ROOT);}private static String mime(String s){return s==null||s.isBlank()?"application/octet-stream":s.trim();}
}
