package com.cpf.starter.messaging.reliability.jdbc.internal;

import com.cpf.core.common.broker.*;
import java.util.Arrays;
import java.util.Objects;

/**
 * Defines the stable idempotency identity of an outbox request.
 *
 * <p>{@code occurredAt} is intentionally excluded. It is an observation timestamp generated by
 * the caller and changes on a legitimate retry; treating it as business identity would reject an
 * otherwise identical retry after a timeout or process restart.</p>
 */
final class CpfBrokerOutboxIdentity {
    private CpfBrokerOutboxIdentity() {
    }

    static boolean same(CpfBrokerEnvelope left, CpfBrokerEnvelope right) {
        Objects.requireNonNull(left, "left");
        Objects.requireNonNull(right, "right");
        return Objects.equals(left.transactionId(), right.transactionId())
                && Objects.equals(left.segmentId(), right.segmentId())
                && Objects.equals(left.producerModule(), right.producerModule())
                && Objects.equals(left.consumerModule(), right.consumerModule())
                && Objects.equals(left.idempotencyKey(), right.idempotencyKey())
                && Objects.equals(left.attributes(), right.attributes())
                && Objects.equals(left.message().messageId(), right.message().messageId())
                && Objects.equals(left.message().topic(), right.message().topic())
                && Objects.equals(left.message().key(), right.message().key())
                && Arrays.equals(left.message().payload(), right.message().payload())
                && Objects.equals(left.message().contentType(), right.message().contentType())
                && Objects.equals(left.message().headers(), right.message().headers());
    }
}
