export function createAdmState() {
      return {
        activeMenu: "logs",
        token: localStorage.getItem("admAccessToken") || "",
        currentOperator: {} as Record<string, any>,
        authorizedMenus: [],
        authMessage: "",
        uiMessage: "",
        loginForm: { operatorId: "admin", password: "" },
        forcedPasswordForm: {
          currentPassword: "",
          newPassword: "",
          newPasswordConfirm: "",
          reason: "최초 로그인 비밀번호 변경"
        },
        menus: [
          { id: "logs", menuId: "LOG_LIST", label: "거래 로그" },
          { id: "transactionGroups", menuId: "LOG_LIST", label: "거래 그룹" },
          { id: "transactions", menuId: "TRANSACTION_META", label: "거래 메타" },
          { id: "standardExecutions", menuId: "STANDARD_EXECUTION", label: "표준 실행" },
          { id: "channelPolicy", menuId: "CHANNEL_POLICY", label: "채널 정책" },
          { id: "remoteLogs", menuId: "REMOTE_LOG", label: "원격 로그" },
          { id: "auditLogs", menuId: "AUDIT_LOG", label: "감사 로그" },
          { id: "serviceRegistry", menuId: "SERVICE_REGISTRY", label: "서비스 호출" },
          { id: "reliability", menuId: "RELIABILITY", label: "신뢰성 처리" },
          { id: "members", menuId: "MEMBER", label: "회원" },
          { id: "batch", menuId: "BATCH", label: "배치" },
          { id: "notifications", menuId: "NOTIFICATION", label: "알림" },
          { id: "downloads", menuId: "DOWNLOAD", label: "다운로드" },
          { id: "cache", menuId: "CACHE", label: "캐시" },
          { id: "messages", menuId: "MESSAGE", label: "메시지" },
          { id: "codes", menuId: "CODE", label: "코드" },
          { id: "responseCodes", menuId: "RESPONSE_CODE", label: "응답코드" },
          { id: "configs", menuId: "CONFIG", label: "설정" },
          { id: "logLevel", menuId: "DYNAMIC_LOG", label: "동적 로그" },
          { id: "logPolicies", menuId: "LOG_POLICY", label: "로그 정책" },
          { id: "permissions", menuId: "PERMISSION", label: "권한" },
          { id: "password", menuId: "PASSWORD", label: "비밀번호" },
          { id: "security", menuId: "SECURITY", label: "보안" },
          { id: "operators", menuId: "OPERATOR", label: "운영자" }
        ],
        logSearch: {
          transactionId: "",
          traceId: "",
          businessTransactionId: "",
          uri: "",
          responseCode: "",
          httpStatus: "",
          memberNo: "",
          customerNo: "",
          channelCode: "",
          logType: ""
        },
        transactionGroupSearch: {
          startedAtFrom: "",
          startedAtTo: "",
          transactionGlobalId: "",
          transactionSegmentId: "",
          status: "",
          failureYn: "",
          moduleCode: "",
          sourceModuleCode: "",
          targetModuleCode: "",
          transactionRole: "",
          direction: "",
          customerNo: "",
          memberNo: "",
          userId: "",
          operatorId: "",
          channelCode: "",
          originalChannelCode: "",
          externalInstitutionCode: "",
          externalTransactionId: "",
          apiPath: "",
          transactionName: "",
          failureCode: "",
          durationMsFrom: "",
          durationMsTo: "",
          standardHeaderValue: "",
          extensionHeaderValue: ""
        },
        transactionSearch: { moduleCode: "", activeYn: "Y", transactionId: "", selectedTransactionId: "", reason: "거래 메타 운영" },
        standardExecutionSearch: { type: "", ownerDomain: "", keyword: "", selectedId: "" },
        channelSnapshot: { version: 0, channels: {}, policies: [] } as any,
        channelForm: {
          channelCode: "WEB",
          channelName: "웹",
          channelType: "CLIENT",
          trustLevel: "EXTERNAL",
          clientChannel: true,
          internalChannel: false,
          authenticationRequired: true,
          signatureRequired: false,
          active: true,
          description: "웹 브라우저 채널",
          reason: "채널 레지스트리 변경",
          requestUser: "admin-ui"
        },
        channelPolicyForm: {
          policyKey: "WEB.DEFAULT",
          standardExecutionId: "*",
          originalChannelCode: "WEB",
          callerChannelCode: "WEB",
          requestType: "*",
          allowed: true,
          authenticationRequired: true,
          signatureRequired: false,
          maxTps: 0,
          effectiveFrom: null,
          effectiveTo: null,
          active: true,
          reason: "거래별 채널 정책 변경",
          requestUser: "admin-ui"
        },
        channelPackageText: "",
        channelImportDryRun: true,
        remoteLogSearch: {
          environment: "",
          module: "",
          service: "",
          instance: "",
          logType: "",
          fileName: "",
          standardTransactionId: "",
          standardBatchId: "",
          transactionGlobalId: "",
          transactionId: "",
          segmentId: "",
          jobInstanceId: "",
          jobExecutionId: "",
          stepExecutionId: "",
          schedulerId: "",
          modifiedFrom: "",
          modifiedTo: "",
          minSize: "",
          maxSize: "",
          compressed: "",
          active: "",
          limit: 100,
          lastLines: 200,
          keyword: "",
          reason: "운영 로그 확인"
        },
        logSort: { key: "LOG_IDX", direction: "desc" },
        logPage: { page: 1, size: 10 },
        logDetailTab: "요약",
        logDetailTabs: ["요약", "수신 헤더", "해석 헤더", "전파 헤더", "응답 헤더", "요청", "응답", "오류", "상세", "전문"],
        transactionGroupSort: "startedAtDesc",
        transactionGroupPage: { page: 1, size: 10 },
        transactionGroupDetailTab: "요약",
        transactionGroupDetailTabs: ["요약", "Timeline", "Segments", "표준 헤더", "확장 헤더", "External Logs", "원본 JSON"],
        auditSearch: { operatorId: "", actionType: "", targetType: "", targetId: "", limit: 100 },
        memberSearch: {
          memberNo: "",
          customerNo: "",
          loginId: "",
          name: "",
          email: "",
          mobileNo: "",
          memberStatus: "",
          channelCode: "",
          roleCode: "",
          limit: 100
        },
        memberForm: {
          memberId: null,
          memberNo: "",
          customerNo: "",
          loginId: "",
          name: "",
          email: "",
          mobileNo: "",
          memberStatus: "ACTIVE",
          channelCode: "WEB",
          description: "",
          requestUser: "admin-ui",
          reason: "회원 운영 변경"
        },
        memberStatusForm: { memberStatus: "ACTIVE", lockYn: "N", withdrawYn: "N" },
        memberRoleForm: {
          serviceCode: "MBR",
          roleCode: "MBR_USER",
          roleName: "일반 회원",
          temporaryYn: "N",
          expireAt: "",
          reason: "회원 권한 변경",
          requestUser: "admin-ui"
        },
        batchForm: {
          jobId: "CPF_EDU_TASKLET_JOB",
          jobName: "CPF EDU Tasklet Job",
          jobType: "TASKLET",
          executionId: null,
          scheduleId: "CPF_EDU_TASKLET_DAILY",
          jobParameters: "{\"edu\":true}",
          calendarId: "DEFAULT",
          businessDate: new Date().toISOString().slice(0, 10),
          simulationDays: 14,
          dispatchStatus: "WAITING",
          heartbeatTimeoutSeconds: 120,
          lockKey: "",
          ghostActionType: "FAIL",
          holidayYn: "N",
          businessDayYn: "Y",
          description: "ADM batch education data",
          reason: "배치 운영 변경"
        },
        centerCutForm: {
          centerCutJobId: "CPF_REF_CENTER_CUT_SAMPLE_JOB",
          statusCode: "",
          resultStatus: "",
          limit: 100
        },
        notificationForm: {
          ruleId: null,
          eventType: "BATCH",
          eventSubType: "FAILED",
          channelCode: "ADM",
          templateCode: "",
          severity: "WARN",
          receiverGroup: "ADM_OPERATOR",
          useYn: "Y",
          targetType: "ADM_TEST",
          targetId: "TEST",
          receiver: "ADM_OPERATOR",
          message: "ADM notification test message.",
          reason: "알림 규칙 변경",
          requestUser: "admin-ui"
        },
        downloadForm: {
          downloadType: "TRANSACTION_LOGS",
          targetType: "LOG_LIST",
          fromDate: "",
          toDate: "",
          transactionId: "",
          traceId: "",
          jobId: "",
          limit: 1000,
          includeSensitive: false,
          reason: "운영 증적 다운로드",
          requestUser: "admin-ui"
        },
        cacheTargets: ["ALL", "CODE", "MESSAGE", "RESPONSE_CODE", "CONFIG"],
        cacheReason: "캐시 갱신",
        responseCodeReason: "응답코드 변경",
        logLevelForm: { businessTransactionId: "", transactionId: "", logLevel: "DEBUG", ttlSeconds: 600, reason: "운영 진단" },
        logPolicyForm: {
          policyId: null,
          policyKey: "ONLINE_DEFAULT",
          policyName: "온라인 거래 기본 로그 정책",
          targetType: "ONLINE_TRANSACTION",
          targetId: "*",
          logLevel: "INFO",
          dbLogEnabledYn: "Y",
          fileLogEnabledYn: "Y",
          requestBodyLogYn: "N",
          responseBodyLogYn: "N",
          errorStackLogYn: "Y",
          retentionDays: 90,
          samplingRate: 100,
          priority: 100,
          activeYn: "Y",
          description: "ADM managed log policy",
          traceBoostTransactionGlobalId: "",
          traceBoostBusinessTransactionId: "",
          traceBoostApiPath: "",
          traceBoostStatus: "",
          traceBoostFailureCode: "",
          traceBoostDurationMsGreaterThan: null,
          traceBoostTtlSeconds: 600,
          effectiveStartAt: "",
          effectiveEndAt: "",
          reason: "로그 정책 변경",
          requestUser: "admin-ui"
        },
        operatorForm: { operatorId: "", operatorName: "", password: "", reason: "운영자 등록" },
        messageForm: {
          messageId: null,
          messageCode: "MCPF990099",
          locale: "ko",
          messageFormatType: "FIXED",
          externalMessage: "샘플 메시지",
          internalMessage: "샘플 내부 메시지",
          parameterCount: 0,
          parameterSample: "[]",
          description: "ADM sample",
          useYn: "Y",
          requestUser: "admin-ui",
          reason: "메시지 변경"
        },
        codeForm: {
          codeId: null,
          parentId: null,
          codeKey: "ADM_SAMPLE",
          codeValue: "SAMPLE",
          description: "ADM sample code",
          useYn: "Y",
          requestUser: "admin-ui",
          reason: "코드 변경"
        },
        configForm: {
          configId: null,
          configKey: "CPF.ADM.SAMPLE",
          configValue: "Y",
          configType: "BOOLEAN",
          description: "ADM sample config",
          encryptedYn: "N",
          useYn: "Y",
          requestUser: "admin-ui",
          reason: "설정 변경"
        },
        permissionForm: { roleId: "ADM_VIEWER", menuId: "LOG_LIST", buttonId: "LOG_LIST_READ", apiPermissionId: "API_LOG_LIST_READ", readYn: "Y", writeYn: "N", deleteYn: "N", reason: "권한 변경" },
        roleForm: { roleId: "ADM_SAMPLE_ROLE", roleName: "샘플 운영 역할", roleType: "BUSINESS_OPERATOR", description: "ADM permission sample role", useYn: "Y", requestUser: "admin-ui", reason: "역할 관리" },
        menuManageForm: { menuId: "SAMPLE_MENU", parentMenuId: "", menuName: "샘플 메뉴", menuPath: "/adm#sample", sortOrder: 990, useYn: "Y", requestUser: "admin-ui", reason: "메뉴 관리" },
        buttonForm: { buttonId: "SAMPLE_MENU_READ", menuId: "SAMPLE_MENU", actionCode: "READ", buttonName: "샘플 조회", httpMethod: "GET", apiPattern: "/adm/api/sample/**", sortOrder: 10, useYn: "Y", requestUser: "admin-ui", reason: "버튼 관리" },
        apiPermissionForm: { apiPermissionId: "API_SAMPLE_MENU_READ", apiGroupCode: "SAMPLE_MENU", httpMethod: "GET", apiPath: "/adm/api/sample/**", apiName: "샘플 API 조회", permissionCode: "READ", menuId: "SAMPLE_MENU", buttonId: "SAMPLE_MENU_READ", useYn: "Y", requestUser: "admin-ui", reason: "API 권한 관리" },
        passwordForm: { operatorId: "", newPassword: "", forceChange: true, sessionId: "", reason: "비밀번호 운영" },
        securityForm: { ipPattern: "127.0.0.1", description: "local development", operatorId: "admin", secretRef: "ENV:ADM_ADMIN_OTP_SECRET", otpCode: "", reason: "보안 운영" },
        responseCodeForm: {
          responseCode: "EREF010001",
          messageCode: "MREF090001",
          resultType: "E",
          moduleId: "REF",
          responseGroup: "01",
          sequenceNo: "0001",
          httpStatus: 400,
          description: "REF sample response code",
          useYn: "Y",
          requestUser: "admin-ui"
        },
        serviceRegistrySearch: {
          serviceId: "",
          endpointCode: "",
          instanceStatus: "",
          transactionGlobalId: "",
          limit: 50
        },
        reliabilitySearch: {
          scope: "",
          status: "",
          key: "",
          transactionGlobalId: "",
          topic: "",
          endpointCode: "",
          type: "",
          businessDate: "",
          jobName: "",
          jobInstanceId: null,
          limit: 100
        },
        reliabilityAction: {
          messageId: "",
          unknownId: "",
          targetStatus: "MANUAL_REVIEW",
          reason: "신뢰성 운영 조치"
        },
        logs: [],
        transactionGroupResult: { items: [] },
        transactionGroupDetail: {} as Record<string, any>,
        transactionResult: {} as Record<string, any>,
        standardExecutionResult: { items: [], summary: {} },
        standardExecutionDetail: {} as Record<string, any>,
        auditLogs: [],
        logDetail: {} as Record<string, any>,
        memberResult: { items: [] },
        memberDetail: {} as Record<string, any>,
        auditResult: {} as Record<string, any>,
        batchResult: {} as Record<string, any>,
        centerCutResult: {} as Record<string, any>,
        notificationResult: {} as Record<string, any>,
        downloadResult: {} as Record<string, any>,
        cacheResult: {} as Record<string, any>,
        responseCodeResult: {} as Record<string, any>,
        logLevelResult: {} as Record<string, any>,
        logPolicyResult: {} as Record<string, any>,
        operatorResult: {} as Record<string, any>,
        messageResult: {} as Record<string, any>,
        codeResult: {} as Record<string, any>,
        configResult: {} as Record<string, any>,
        permissionResult: {} as Record<string, any>,
        passwordResult: {} as Record<string, any>,
        securityResult: {} as Record<string, any>,
        serviceRegistryResult: {} as Record<string, any>,
        reliabilityResult: {} as Record<string, any>,
        remoteLogResult: [],
        remoteLogPreview: {} as Record<string, any>,
        selectedRemoteLog: null,
        remoteLogSelectedIds: [],
        remoteLogDiagnostics: {} as Record<string, any>,
        remoteLogBundleJob: {} as Record<string, any>,
        remoteLogBundleGrant: {} as Record<string, any>
      };
    }
