package com.cpf.core.common.runtimecontrol.applier;
import com.cpf.core.api.runtimecontrol.*;import com.cpf.core.common.http.CpfServiceEndpointRegistry;import com.cpf.core.api.fixedlength.CpfFixedLengthLayoutRegistry;import java.util.*;
/** 기관/외부 시스템 endpoint 정본을 CpfServiceEndpointRegistry에 원자 적용합니다. */
public final class CpfExternalInstitutionRuntimeApplier implements CpfRuntimeChangeApplier{
 private final CpfServiceEndpointRegistry registry;private final CpfFixedLengthLayoutRegistry layouts;public CpfExternalInstitutionRuntimeApplier(CpfServiceEndpointRegistry registry,CpfFixedLengthLayoutRegistry layouts){this.registry=registry;this.layouts=layouts;}
 public String changeType(){return "EXTERNAL_INSTITUTION";}public boolean supportsIdempotentReplay(){return true;}public boolean snapshotCapable(){return true;}
 @SuppressWarnings("unchecked")public CpfRuntimeApplyResult apply(CpfRuntimeDelivery d){try{Object raw=d.payload().get("endpoints");if(!(raw instanceof List<?>list))throw new IllegalArgumentException("endpoints array 필수");LinkedHashMap<String,CpfServiceEndpointRegistry.RuntimeEndpoint>m=new LinkedHashMap<>();for(Object item:list){if(!(item instanceof Map<?,?>r))throw new IllegalArgumentException("endpoint object 필요");Map<String,Object>v=(Map<String,Object>)r;String id=req(v,"serviceId");Map<String,String>a=new LinkedHashMap<>();if(v.get("attributes")instanceof Map<?,?>am)am.forEach((k,x)->a.put(String.valueOf(k),String.valueOf(x)));String layoutId=opt(v,"layoutId",""),layoutVersion=opt(v,"layoutVersion","");if(!layoutId.isBlank()){if(layouts==null||layoutVersion.isBlank())throw new IllegalArgumentException("layout registry/version 필수");layouts.require(layoutId,layoutVersion);}m.put(id,new CpfServiceEndpointRegistry.RuntimeEndpoint(id,opt(v,"endpointType","HTTP"),req(v,"baseUrl"),opt(v,"credentialRef",""),layoutId,layoutVersion,(int)num(v.get("timeoutMillis"),3000),bool(v,"active",true),bool(v,"maintenance",false),a));}registry.replaceRuntime(d.desiredVersion(),m);return CpfRuntimeApplyResult.success(d.payloadHash());}catch(RuntimeException e){return CpfRuntimeApplyResult.failure("EXTERNAL_INSTITUTION_INVALID","External institution endpoint payload 오류");}}
 private String req(Map<String,Object>m,String k){String v=opt(m,k,"");if(v.isBlank())throw new IllegalArgumentException(k+" 필수");return v;}private String opt(Map<String,Object>m,String k,String f){Object v=m.get(k);return v==null?f:String.valueOf(v).trim();}private boolean bool(Map<String,Object>m,String k,boolean f){Object v=m.get(k);return v instanceof Boolean b?b:v==null?f:Boolean.parseBoolean(String.valueOf(v));}private long num(Object v,long f){return v instanceof Number n?n.longValue():v==null?f:Long.parseLong(String.valueOf(v));}
}
