package com.cpf.core.common.runtimecontrol.applier;
import com.cpf.core.api.runtimecontrol.*;import com.cpf.core.common.filetransfer.*;import com.cpf.core.common.security.CpfCredentialRef;import java.time.Duration;import java.util.*;
/** 실제 FileTransferEngine이 사용하는 SFTP/FTP endpoint 전체 snapshot을 교체합니다. */
public final class CpfSftpTransferRuntimeApplier implements CpfRuntimeChangeApplier{
 private final CpfFileTransferRuntimeState state;public CpfSftpTransferRuntimeApplier(CpfFileTransferRuntimeState state){this.state=state;}
 public String changeType(){return "SFTP_TRANSFER";}public boolean supportsIdempotentReplay(){return true;}public boolean snapshotCapable(){return true;}
 public CpfRuntimeApplyResult apply(CpfRuntimeDelivery d){try{Object raw=d.payload().get("endpoints");if(!(raw instanceof List<?>l))return CpfRuntimeApplyResult.failure("SFTP_ENDPOINTS_REQUIRED","endpoints snapshot이 필요합니다.");LinkedHashMap<String,CpfFileTransferEndpoint>m=new LinkedHashMap<>();for(Object item:l){if(!(item instanceof Map<?,?>x))throw new IllegalArgumentException();String code=req(x,"endpointCode");String protocol=req(x,"protocol");String host=req(x,"host");int port=intv(x.get("port"),22);String base=req(x,"remoteBasePath");String cred=req(x,"credentialId");CpfCredentialRef ref=new CpfCredentialRef(opt(x,"credentialScope","default"),cred,opt(x,"credentialVersion","latest"),code);long timeout=num(x.get("timeoutMillis"),30000L);Map<String,String>a=attrs(x.get("attributes"));m.put(code,new CpfFileTransferEndpoint(code,protocol,host,port,base,ref,Duration.ofMillis(timeout),a));}state.replaceEndpoints(d.desiredVersion(),m);return CpfRuntimeApplyResult.success(d.payloadHash());}catch(RuntimeException e){return CpfRuntimeApplyResult.failure("SFTP_ENDPOINT_INVALID","SFTP endpoint snapshot이 유효하지 않습니다.");}}
 private String req(Map<?,?>m,String k){Object v=m.get(k);if(v==null||String.valueOf(v).isBlank())throw new IllegalArgumentException();return String.valueOf(v);}private String opt(Map<?,?>m,String k,String f){Object v=m.get(k);return v==null||String.valueOf(v).isBlank()?f:String.valueOf(v);}private int intv(Object v,int f){return v instanceof Number n?n.intValue():v==null?f:Integer.parseInt(String.valueOf(v));}private long num(Object v,long f){return v instanceof Number n?n.longValue():v==null?f:Long.parseLong(String.valueOf(v));}private Map<String,String>attrs(Object v){if(!(v instanceof Map<?,?>x))return Map.of();LinkedHashMap<String,String>r=new LinkedHashMap<>();x.forEach((k,a)->{if(k!=null&&a!=null)r.put(String.valueOf(k),String.valueOf(a));});return Map.copyOf(r);}
}
