package com.cpf.gateway.runtime;
import com.cpf.core.api.runtimecontrol.*;import java.util.*;
public final class CpfGatewayRuntimeApplier implements CpfRuntimeChangeApplier{
 private final String type;private final CpfGatewayRuntimePolicy policy;public CpfGatewayRuntimeApplier(String type,CpfGatewayRuntimePolicy policy){this.type=type;this.policy=policy;}
 public String changeType(){return type;}public boolean supportsIdempotentReplay(){return true;}public boolean snapshotCapable(){return true;}
 @SuppressWarnings("unchecked") public CpfRuntimeApplyResult apply(CpfRuntimeDelivery d){try{Map<String,Object>p=d.payload();switch(type){case"GATEWAY_HEADER"->policy.replaceHeaders(d.desiredVersion(),set(p.get("requestAllowlist")),set(p.get("responseAllowlist")));case"GATEWAY_CORS"->policy.replaceCors(d.desiredVersion(),bool(p.get("enabled"),true),set(p.get("allowedOrigins")),set(p.get("allowedMethods")),set(p.get("allowedHeaders")),set(p.get("exposedHeaders")),bool(p.get("allowCredentials"),false),num(p.get("maxAgeSeconds"),3600));case"RATE_LIMIT"->{Map<String,CpfGatewayRuntimePolicy.Limit>routes=new LinkedHashMap<>();Object raw=p.get("routes");if(raw instanceof Map<?,?>m)for(var e:m.entrySet())if(e.getValue()instanceof Map<?,?>v)routes.put(String.valueOf(e.getKey()),limit((Map<String,Object>)v));policy.replaceRates(d.desiredVersion(),limit(p),routes);}default->throw new IllegalArgumentException("unsupported");}return CpfRuntimeApplyResult.success(d.payloadHash());}catch(RuntimeException e){return CpfRuntimeApplyResult.failure(type+"_INVALID","Gateway runtime policy payload 오류");}}
 private CpfGatewayRuntimePolicy.Limit limit(Map<String,Object>p){return new CpfGatewayRuntimePolicy.Limit((int)num(p.get("permits"),0),num(p.get("windowMillis"),60000));}
 private Set<String>set(Object v){if(!(v instanceof List<?>l))return Set.of();LinkedHashSet<String>s=new LinkedHashSet<>();for(Object x:l)if(x!=null&&!String.valueOf(x).isBlank())s.add(String.valueOf(x));return Set.copyOf(s);}private long num(Object v,long f){return v instanceof Number n?n.longValue():v==null?f:Long.parseLong(String.valueOf(v));}private boolean bool(Object v,boolean f){return v instanceof Boolean b?b:v==null?f:Boolean.parseBoolean(String.valueOf(v));}
}
