plugins { id 'java-library'; id 'maven-publish' }
group='com.cpf.starter'
dependencies {
    api project(':framework:operations')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-actuator'
    implementation 'org.springframework:spring-webmvc'
    implementation 'org.slf4j:slf4j-api'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
}
tasks.named('test'){ useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication){ from components.java; artifactId = 'cpf-starter-platform-operations-health' } } }
