<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import CpfIcon from "../../components/CpfIcon.vue";
import { bzaApprovalParticipantDecision } from "../../generated/orval/cpf-api";
import { bzaApi, hasBzaPermission } from "../auth/session";
type Row = Record<string, any>;
const rows=ref<Row[]>([]),error=ref(""),selected=ref<Row|null>(null),dialogOpen=ref(false),action=ref("APPROVE"),reason=ref("");
const canDecide=computed(()=>hasBzaPermission("APPROVAL","DECIDE"));
const groups=computed(()=>({urgent:rows.value.filter(r=>String(r.actionableYn||'').toUpperCase()==='Y'),done:rows.value.filter(r=>["APPROVED","COMPLETED"].includes(String(r.approvalStatus||'').toUpperCase())),other:rows.value.filter(r=>String(r.actionableYn||'').toUpperCase()!=='Y'&&!["APPROVED","COMPLETED"].includes(String(r.approvalStatus||'').toUpperCase()))}));
async function load(){try{rows.value=await bzaApi('/api/bza/approvals/inbox?limit=100')}catch(e){error.value=e instanceof Error?e.message:String(e)}}
function open(row:Row,next:string){if(!canDecide.value){error.value='APPROVAL:DECIDE 권한이 필요합니다.';return}selected.value=row;action.value=next;reason.value='';dialogOpen.value=true}
async function submit(){
  if(!canDecide.value){error.value="APPROVAL:DECIDE 권한이 필요합니다.";return;}
  if(!selected.value||!reason.value.trim())return;
  try{
    await bzaApprovalParticipantDecision(Number(selected.value.approvalId),{action:action.value,idempotencyKey:crypto.randomUUID(),reason:reason.value,comment:reason.value});
    dialogOpen.value=false;await load();
  }catch(e){error.value=e instanceof Error?e.message:String(e)}
}
onMounted(load);
</script><template><div class="page-stack"><div class="cpf-page-heading"><div><p class="eyebrow">APPROVAL WORKSPACE</p><h2>결재 Inbox</h2><p>처리 대기 건을 우선순위로 보고 승인·합의·반려 사유를 감사 가능한 Dialog에서 입력합니다.</p></div><button class="ghost" @click="load"><CpfIcon name="refresh"/> 새로고침</button></div><p v-if="error" class="error-banner">{{error}}</p><div class="approval-board"><section class="approval-lane"><header><span>처리 대기</span><b>{{groups.urgent.length}}</b></header><article v-for="r in groups.urgent" :key="String(r.approvalId)" class="approval-ticket"><div class="ticket-head"><span class="cpf-status warning">Step {{r.currentStepNo??'-'}}</span><small>{{r.approvalNo}}</small></div><h3>{{r.title}}</h3><p>{{r.requesterEmployeeNo||'-'}} · {{r.updatedAt||''}}</p><div v-if="canDecide" class="ticket-actions"><button class="primary small" @click="open(r,'APPROVE')">승인</button><button class="ghost small" @click="open(r,'AGREE')">합의</button><button class="danger small" @click="open(r,'REJECT')">반려</button></div></article><p v-if="!groups.urgent.length" class="cpf-empty">처리 대기 건이 없습니다.</p></section><section class="approval-lane"><header><span>완료</span><b>{{groups.done.length}}</b></header><article v-for="r in groups.done.slice(0,20)" :key="String(r.approvalId)" class="approval-ticket compact"><span class="cpf-status success">{{r.approvalStatus}}</span><h3>{{r.title}}</h3><small>{{r.approvalNo}}</small></article></section><section class="approval-lane"><header><span>반려·기타</span><b>{{groups.other.length}}</b></header><article v-for="r in groups.other.slice(0,20)" :key="String(r.approvalId)" class="approval-ticket compact"><span class="cpf-status danger">{{r.approvalStatus}}</span><h3>{{r.title}}</h3><small>{{r.approvalNo}}</small></article></section></div><dialog :open="dialogOpen" class="modal"><form class="modal-card" @submit.prevent="submit"><div class="card-head"><div><p class="eyebrow">{{action}}</p><h2>{{selected?.title}}</h2></div><button type="button" class="icon-button" @click="dialogOpen=false">×</button></div><div class="approval-stepper"><span class="done">상신</span><span class="active">Step {{selected?.currentStepNo??'-'}}</span><span>완료</span></div><label class="dialog-field">처리 사유<textarea v-model="reason" rows="4" required placeholder="감사 로그에 남을 처리 사유를 입력하세요."></textarea></label><div class="dialog-actions"><button type="button" class="ghost" @click="dialogOpen=false">취소</button><button v-if="canDecide" :class="action==='REJECT'?'danger':'primary'">{{action==='REJECT'?'반려 확정':'처리 확정'}}</button></div></form></dialog></div></template>
