spring:
  datasource:
    cmn:
      #      jndi-name: java:comp/env/jdbc/cmnDS
      url: jdbc:mariadb://localhost:3306/cmnDB
      username: root
      password: test
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/cmn-mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/cmn/**/*.xml
  type-aliases-package: cpf.cmn.smp.entity

cpf:
  cmn:
    cache:
      preload-enabled: ${FPS_CMN_CACHE_PRELOAD_ENABLED:true}
      event-poll-enabled: ${FPS_CMN_CACHE_EVENT_POLL_ENABLED:true}
      refresh-poll-millis: ${FPS_CMN_CACHE_REFRESH_POLL_MILLIS:5000}
      refresh-initial-delay-millis: ${FPS_CMN_CACHE_REFRESH_INITIAL_DELAY_MILLIS:5000}
      periodic-refresh-millis: ${FPS_CMN_CACHE_PERIODIC_REFRESH_MILLIS:1800000}
      periodic-refresh-initial-delay-millis: ${FPS_CMN_CACHE_PERIODIC_REFRESH_INITIAL_DELAY_MILLIS:1800000}





