plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-common')
    api project(':cpf-core')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
tasks.named('test') { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-starter-runtime-control-client' } } }
