package com.cpf.starter.integration.ai;
import com.cpf.core.api.ai.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;
/** Ordered routing + bounded retry + circuit breaker + timeout/fallback. Prompt/token 원문은 오류/상태에 보관하지 않습니다. */
public final class CpfAiRouter implements CpfAiOperations, AutoCloseable {
 private final List<CpfAiProvider> providers;private final CpfAiPolicy policy;private final CpfAiProperties props;private final ExecutorService executor=Executors.newVirtualThreadPerTaskExecutor();private final ConcurrentMap<String,Circuit> circuits=new ConcurrentHashMap<>();
 public CpfAiRouter(List<CpfAiProvider> providers,CpfAiPolicy policy,CpfAiProperties props){this.providers=order(providers,props.getProviderOrder());this.policy=Objects.requireNonNull(policy);this.props=Objects.requireNonNull(props);if(this.providers.isEmpty())throw new IllegalStateException("AI enabled but no CpfAiProvider is available");}
 @Override public CpfAiResponse execute(CpfAiRequest original){CpfAiRequest request=policy.authorizeAndMask(Objects.requireNonNull(original));if(request.risk()==CpfAiRisk.HIGH&&!request.humanApproved())throw new SecurityException("HIGH risk AI request requires human approval");Throwable last=null;int totalAttempts=0;
   for(CpfAiProvider provider:providers){if(!provider.supports(request.model()))continue;Circuit circuit=circuits.computeIfAbsent(provider.providerId(),k->new Circuit());if(circuit.isOpen(props.getCircuitOpenDuration()))continue;
     for(int n=1;n<=props.getRetryAttemptsPerProvider()&&totalAttempts<props.getMaxAttempts();n++){totalAttempts++;Future<CpfAiResponse> future=null;try{future=executor.submit(()->provider.execute(request));long timeoutMs=Math.max(1,Math.min(request.timeout().toMillis(),props.getTimeout().toMillis()));CpfAiResponse response=future.get(timeoutMs,TimeUnit.MILLISECONDS);circuit.success();policy.audit(request,response,null);return response;}catch(TimeoutException timeout){if(future!=null)future.cancel(true);last=timeout;circuit.failure(props.getCircuitFailureThreshold());if(!provider.safeToFallbackAfterTimeout()){policy.audit(request,null,timeout);throw new CpfAiUnknownResultException(request.transactionId(),timeout);}break;}catch(InterruptedException interrupted){Thread.currentThread().interrupt();last=interrupted;circuit.failure(props.getCircuitFailureThreshold());break;}catch(Exception failure){last=failure instanceof ExecutionException&&failure.getCause()!=null?failure.getCause():failure;circuit.failure(props.getCircuitFailureThreshold());if(n<props.getRetryAttemptsPerProvider()&&totalAttempts<props.getMaxAttempts())sleep(props.getRetryBackoff());}}
   }
   policy.audit(request,null,last);throw new CpfAiUnknownResultException(request.transactionId(),last);
 }
 private static void sleep(Duration d){if(d.isZero())return;try{Thread.sleep(d.toMillis());}catch(InterruptedException e){Thread.currentThread().interrupt();}}
 private static List<CpfAiProvider> order(List<CpfAiProvider> in,List<String> order){List<CpfAiProvider> src=in==null?List.of():List.copyOf(in);if(order==null||order.isEmpty())return src;Map<String,CpfAiProvider> by=new LinkedHashMap<>();for(var p:src){if(by.put(p.providerId(),p)!=null)throw new IllegalArgumentException("Duplicate AI providerId: "+p.providerId());}List<CpfAiProvider> out=new ArrayList<>();for(String id:order){var p=by.remove(id);if(p!=null)out.add(p);}out.addAll(by.values());return List.copyOf(out);}
 @Override public void close(){executor.close();}
 private static final class Circuit{private final AtomicInteger failures=new AtomicInteger();private volatile long openedAtNanos=-1L;void success(){failures.set(0);openedAtNanos=-1L;}void failure(int threshold){if(failures.incrementAndGet()>=threshold)openedAtNanos=System.nanoTime();}boolean isOpen(Duration duration){long opened=openedAtNanos;if(opened<0)return false;if(System.nanoTime()-opened>=duration.toNanos()){success();return false;}return true;}}
}
