<script setup lang="ts">
import { ref } from "vue";
import { createDeploymentPlan } from "../batch-runtime-control/api";
import { useAdmSessionStore } from "../../stores/admSessionStore";
const session=useAdmSessionStore();const planId=ref("");const reason=ref("");const manifestJson=ref('{"cellId":"","environment":"","runtimeRole":"WORKER","serviceId":"","artifact":{},"runtimeMode":"","instances":[],"desiredState":"RUNNING","deployment":{},"dependencies":[],"secretReferences":[],"labels":{}}');const busy=ref(false),error=ref(""),result=ref<Record<string,unknown>|null>(null);
async function create(){if(!session.hasButton("admBatchRuntimeCreateDeploymentPlan"))return;busy.value=true;error.value="";try{const manifest=JSON.parse(manifestJson.value);if(!manifest||Array.isArray(manifest)||typeof manifest!=="object")throw new Error("manifest JSON object가 필요합니다.");if(reason.value.trim().length<8)throw new Error("사유는 8자 이상 입력하세요.");result.value=await createDeploymentPlan({planId:planId.value.trim()||undefined,manifest,reason:reason.value.trim()});}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
</script>
<template><section class="cpf-card deployment-plan-create"><div class="cpf-card-head"><div><h3>Deployment Plan 생성</h3><p>BAT Owner의 DeploymentCellManifest 계약으로 계획만 생성합니다. 실제 배포/Rollback은 별도 승인 실행을 사용합니다.</p></div></div><label>Plan ID (선택)<input v-model.trim="planId"></label><label>Manifest JSON<textarea v-model="manifestJson" rows="10" spellcheck="false"></textarea></label><label>사유<textarea v-model.trim="reason" minlength="8" rows="3"></textarea></label><p v-if="error" class="state error">{{error}}</p><button class="primary" :disabled="busy||!session.hasButton('admBatchRuntimeCreateDeploymentPlan')" @click="create">{{busy?'생성 중…':'Plan 생성'}}</button><pre v-if="result">{{JSON.stringify(result,null,2)}}</pre></section></template>
<style scoped>.deployment-plan-create{display:grid;gap:.75rem;margin-bottom:1rem}.deployment-plan-create label{display:grid;gap:.35rem}.deployment-plan-create textarea{font-family:ui-monospace,monospace}.error{color:#a51d1d}pre{max-height:18rem;overflow:auto}</style>
