plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    implementation project(':cpf-starter-platform-operations-runtime-control-client')
    api project(':cpf-core')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-starter-security-secret' } } }
