plugins { id 'java-library'; id 'maven-publish' }
group='com.cpf.starter'
dependencies {
 api project(':cpf-starter-foundation-base')
 api project(':cpf-starter-messaging-reliability-jdbc')
 api project(':cpf-starter-integration-resilience')
 api 'org.springframework.boot:spring-boot-starter-actuator'
}
tasks.named('test'){useJUnitPlatform()}
publishing { publications { mavenJava(MavenPublication){from components.java;artifactId='cpf-starter-profile-event-service'} } }
