plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'

dependencies {
    api project(':cpf-core')
    api project(':cpf-starter-base')
    implementation project(':cpf-starter-persistence-jdbc')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-tx'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
}

tasks.named('test') { useJUnitPlatform() }

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-notification'
        }
    }
}
