plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    api project(':cpf-core')
api project(':cpf-starter-base')
implementation project(':cpf-starter-persistence-jdbc')
implementation 'org.springframework.boot:spring-boot-starter-actuator'
annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
tasks.named('test') { useJUnitPlatform() }
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-notification'
        }
    }
}

