package com.cpf.platform.operations.featureflag.openfeature;
import com.cpf.platform.operations.api.featureflag.*; import com.cpf.platform.operations.spi.featureflag.*; import java.time.*; import java.util.*; import java.util.concurrent.atomic.*;
public final class CpfFeatureFlagRuntimeHarness {
 static final Instant NOW=Instant.parse("2026-08-05T12:00:00Z"); static final Clock CLOCK=Clock.fixed(NOW,ZoneOffset.UTC);
 public static void main(String[] a){Store s=new Store(); Audit au=new Audit(false); Provider p=new Provider(); CpfFeatureFlagRuntime r=new CpfFeatureFlagRuntime(p,s,au,CLOCK,Duration.ofMinutes(5)); CpfFeatureFlagValue fb=new CpfFeatureFlagValue.BooleanValue(false); CpfFeatureFlagContext c=new CpfFeatureFlagContext("prod","pay","t","web","m",Map.of("segment","gold","authorization","Bearer secret","token","secret-token")); req(!c.attributes().containsKey("authorization")&&!c.attributes().containsKey("token"),"context mask");
  req(r.evaluate("pay.write",fb,c).source()==CpfFeatureFlagResult.Source.PROVIDER,"provider"); req(r.evaluate("pay.write",fb,c).source()==CpfFeatureFlagResult.Source.CACHE&&p.calls.get()==1,"cache"); p.fail=true; req(r.evaluate("pay.read",fb,c).source()==CpfFeatureFlagResult.Source.FALLBACK,"fallback"); p.fail=false; s.control=res("pay.write",false,CpfFeatureFlagResult.Source.KILL_SWITCH,2); s.rev++; req(r.evaluate("pay.write",fb,c).source()==CpfFeatureFlagResult.Source.KILL_SWITCH,"precedence");
  String id=r.requestOverride("pay.write",new CpfFeatureFlagValue.BooleanValue(true),NOW.plusSeconds(60),"operator","reason"); req("request-1".equals(id),"request"); req(r.approveOverride(id,"approver","dual").source()==CpfFeatureFlagResult.Source.SECURE_OVERRIDE,"approve"); r.revokeOverride(id,"operator","rollback"); r.setKillSwitch("pay.write",true,"operator","incident"); req(s.requests==1&&s.approves==1&&s.revokes==1&&s.kills==1,"mutations"); illegal(()->r.requestOverride("x",fb,NOW.minusSeconds(1),"o","r")); illegal(()->r.search("",-1,10)); RuntimeException x=runtime(()->new CpfFeatureFlagRuntime(new Provider(),new Store(),new Audit(true),CLOCK,Duration.ofSeconds(1)).evaluate("x",fb,c)); req(x.getMessage().contains("audit unavailable"),"audit fail closed"); System.out.println("FEATURE_FLAG_RUNTIME_PASS"); }
 static CpfFeatureFlagResult<CpfFeatureFlagValue> res(String k,boolean v,CpfFeatureFlagResult.Source s,long rev){return new CpfFeatureFlagResult<>(k,new CpfFeatureFlagValue.BooleanValue(v),null,s.name(),s,rev,NOW);} static void req(boolean b,String m){if(!b)throw new AssertionError(m);} static void illegal(R r){try{r.run();throw new AssertionError("expected illegal");}catch(IllegalArgumentException ok){}} static RuntimeException runtime(R r){try{r.run();throw new AssertionError("expected runtime");}catch(RuntimeException x){return x;}} interface R{void run();}
 static final class Provider implements CpfFeatureFlagProvider{AtomicInteger calls=new AtomicInteger();boolean fail; public CpfFeatureFlagResult<CpfFeatureFlagValue> evaluate(String k,CpfFeatureFlagValue f,CpfFeatureFlagContext c){calls.incrementAndGet();if(fail)throw new IllegalStateException("down");return res(k,true,CpfFeatureFlagResult.Source.PROVIDER,1);}public long revision(){return 1;}}
 static final class Store implements CpfFeatureFlagStateStore{CpfFeatureFlagResult<CpfFeatureFlagValue> control;long rev=1;int requests,approves,revokes,kills;public Optional<CpfFeatureFlagResult<CpfFeatureFlagValue>> findEffective(String k,Instant n){return Optional.ofNullable(control!=null&&control.flagKey().equals(k)?control:null);}public List<CpfFeatureFlagResult<CpfFeatureFlagValue>> search(String f,int o,int l,Instant n){return control==null?List.of():List.of(control);}public String requestOverride(String k,CpfFeatureFlagValue v,Instant e,String q,String reason){requests++;return "request-1";}public CpfFeatureFlagResult<CpfFeatureFlagValue> approveOverride(String id,String a,String reason,Instant n){approves++;control=res("pay.write",true,CpfFeatureFlagResult.Source.SECURE_OVERRIDE,++rev);return control;}public void revokeOverride(String id,String o,String reason,Instant n){revokes++;control=null;rev++;}public void setKillSwitch(String k,boolean e,String o,String reason,Instant n){kills++;control=res(k,e,CpfFeatureFlagResult.Source.KILL_SWITCH,++rev);}public long revision(){return rev;}}
 static final class Audit implements CpfFeatureFlagAuditSink{boolean fail;Audit(boolean f){fail=f;}public void record(String e,String k,String a,String r,Map<String,String> attrs,Instant at){if(fail)throw new IllegalStateException("audit unavailable");String s=e+k+r+attrs;req(!s.contains("secret-token")&&!s.contains("Bearer secret"),"audit secret");}}
}
