package com.cpf.data.cache.valkey;
import com.cpf.data.cache.api.*; import java.nio.charset.StandardCharsets; import java.time.*; import org.springframework.data.redis.core.StringRedisTemplate;
public final class ValkeyCpfCacheRuntimeHarness {
 public static void main(String[] args)throws Exception{
  StringRedisTemplate redis=new StringRedisTemplate(); CpfValkeyProperties p=new CpfValkeyProperties();p.setEnabled(true);p.setMaximumPayloadBytes(16);p.setScanCount(100);p.validate(); ValkeyCpfCache c=new ValkeyCpfCache(redis,p,true);
  CpfCacheKey a=new CpfCacheKey("profile","a","T1"),b=new CpfCacheKey("profile","b","T1"),other=new CpfCacheKey("profile","a","T2"); c.put(a,val("A"),Duration.ofMillis(100));c.put(b,val("B"),Duration.ofSeconds(5));c.put(other,val("O"),Duration.ofSeconds(5));req(txt(c.get(a)).equals("A"),"get");Thread.sleep(150);req(!c.get(a).found(),"ttl");req(c.evictNamespace("T1","profile")==1,"scan namespace");req(c.get(other).found(),"tenant isolation");req(!redis.published().isEmpty(),"pubsub");
  CpfLockToken l1=c.tryAcquire("job:1",Duration.ZERO,Duration.ofSeconds(1)).orElseThrow();req(c.tryAcquire("job:1",Duration.ZERO,Duration.ofSeconds(1)).isEmpty(),"contention");CpfLockToken forged=new CpfLockToken(l1.lockName(),"forged",l1.fencingToken(),l1.acquiredAt(),l1.expiresAt());req(!c.release(forged),"atomic owner release");req(c.release(l1),"release");CpfLockToken l2=c.tryAcquire("job:1",Duration.ZERO,Duration.ofSeconds(1)).orElseThrow();req(l2.fencingToken()>l1.fencingToken(),"fencing");c.release(l2);req(c.health().ready(),"health");req(c.metrics().lockContentions()>=1,"metrics");illegal(()->c.put(a,val("payload-too-large-123"),Duration.ofSeconds(1)));System.out.println("VALKEY_RUNTIME_PASS");
 }
 static CpfCacheValue val(String s){return new CpfCacheValue(true,false,s.getBytes(StandardCharsets.UTF_8),"text/plain",1,Instant.now().plusSeconds(5));}static String txt(CpfCacheValue v){return new String(v.payload(),StandardCharsets.UTF_8);}static void req(boolean b,String m){if(!b)throw new AssertionError(m);}static void illegal(R r){try{r.run();throw new AssertionError("expected illegal");}catch(IllegalArgumentException ok){}}interface R{void run();}
}
