plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-starter-messaging-jms')
implementation 'org.springframework.boot:spring-boot-autoconfigure'
annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
tasks.named('test') { useJUnitPlatform() }
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-messaging-ibm-mq'
        }
    }
}

