plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-core')
api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
api 'org.springdoc:springdoc-openapi-starter-webmvc-scalar:3.0.3'
compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
}
tasks.named('test') { useJUnitPlatform() }
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-openapi-webmvc'
        }
    }
}

