package com.cpf.core.common.attachment;
import com.cpf.core.api.attachment.CpfAttachmentContent;
import com.cpf.core.api.attachment.CpfAttachmentStoragePort;
import com.cpf.core.api.attachment.CpfStoredAttachment;

import com.cpf.core.common.exception.CpfValidationException;
import java.io.IOException;import java.nio.file.*;import java.security.*;import java.time.*;import java.util.*;

/** Runtime Attachment/Download 정책을 실제 저장·읽기 경로에서 집행하는 로컬 Adapter입니다. */
public class LocalCpfAttachmentStorageAdapter implements CpfAttachmentStoragePort{
 private final Path root;private final Clock clock;private final CpfAttachmentRuntimePolicy policy;private final CpfAttachmentInspectionPort inspectionPort;private final CpfAttachmentWatermarkPort watermarkPort;
 public LocalCpfAttachmentStorageAdapter(Path root,long maxBytes,Set<String>allowedExtensions){this(root,new CpfAttachmentRuntimePolicy(),null,null,Clock.systemUTC());this.policy.replaceAttachment(0,maxBytes,allowedExtensions,Set.of(),false,3650,true,false);}
 public LocalCpfAttachmentStorageAdapter(Path root,CpfAttachmentRuntimePolicy policy,CpfAttachmentInspectionPort inspectionPort,CpfAttachmentWatermarkPort watermarkPort){this(root,policy,inspectionPort,watermarkPort,Clock.systemUTC());}
 LocalCpfAttachmentStorageAdapter(Path root,CpfAttachmentRuntimePolicy policy,CpfAttachmentInspectionPort inspectionPort,CpfAttachmentWatermarkPort watermarkPort,Clock clock){if(root==null)throw new IllegalArgumentException("첨부파일 저장 root는 필수입니다.");this.root=root.toAbsolutePath().normalize();this.policy=Objects.requireNonNull(policy);this.inspectionPort=inspectionPort;this.watermarkPort=watermarkPort;this.clock=clock;}
 @Override public CpfStoredAttachment store(String groupId,String originalFileName,String contentType,byte[]content){String group=safeSegment(groupId,"groupId");String name=safeFileName(originalFileName);byte[]bytes=content==null?new byte[0]:content.clone();var p=policy.current().upload();if(bytes.length==0||bytes.length>p.maxBytes())throw new CpfValidationException("첨부파일 크기 정책 위반");String ext=extension(name);if(!p.allowedExtensions().isEmpty()&&!p.allowedExtensions().contains(ext))throw new CpfValidationException("허용되지 않은 확장자");String mime=normalizeContentType(contentType);if(!p.allowedMimeTypes().isEmpty()&&!p.allowedMimeTypes().contains(mime.toLowerCase(Locale.ROOT)))throw new CpfValidationException("허용되지 않은 MIME");if(p.scanRequired()){if(inspectionPort==null)throw new CpfValidationException("첨부 scan adapter가 필요합니다.");var result=inspectionPort.inspect(name,mime,bytes,p.quarantineOnFailure());if(result==null||!result.accepted())throw new CpfValidationException("첨부 scan 거부");}String stored=UUID.randomUUID().toString().replace("-","")+"."+ext;Path dir=resolveSafe(root.resolve(group));Path target=resolveSafe(dir.resolve(stored));try{Files.createDirectories(dir);rejectSymbolicLink(root);rejectSymbolicLink(dir);Files.write(target,bytes,StandardOpenOption.CREATE_NEW);return new CpfStoredAttachment(root.relativize(target).toString().replace('\\','/'),name,stored,mime,bytes.length,sha256(bytes),Instant.now(clock));}catch(IOException ex){throw new IllegalStateException("첨부파일 저장 실패",ex);}}
 @Override public CpfAttachmentContent read(String storageKey){Path target=resolveSafe(root.resolve(required(storageKey,"storageKey")));rejectSymbolicLink(target);var snapshot=policy.current();enforceDownload(snapshot.download());try{Instant modified=Files.getLastModifiedTime(target).toInstant();if(modified.plus(Duration.ofDays(snapshot.upload().retentionDays())).isBefore(Instant.now(clock))){Files.deleteIfExists(target);throw new CpfValidationException("첨부파일 보관기간이 만료되었습니다.");}byte[]bytes=Files.readAllBytes(target);if(bytes.length>snapshot.upload().maxBytes())throw new CpfValidationException("첨부파일 읽기 크기 정책 위반");if(snapshot.download().watermarkRequired()){if(watermarkPort==null)throw new CpfValidationException("watermark adapter가 필요합니다.");bytes=watermarkPort.apply(storageKey,bytes,CpfAttachmentDownloadContext.current());}return new CpfAttachmentContent(bytes,sha256(bytes));}catch(IOException ex){throw new IllegalStateException("첨부파일 읽기 실패",ex);}}
 @Override public void delete(String storageKey){Path target=resolveSafe(root.resolve(required(storageKey,"storageKey")));rejectSymbolicLink(target);try{Files.deleteIfExists(target);}catch(IOException ex){throw new IllegalStateException("첨부파일 삭제 실패",ex);}}
 private void enforceDownload(CpfAttachmentRuntimePolicy.Download p){if(!p.permissionRequired()&&!p.approvalRequired()&&!p.watermarkRequired())return;var c=CpfAttachmentDownloadContext.current();if(c==null)throw new CpfValidationException("다운로드 Context가 필요합니다.");if(p.permissionRequired()&&!c.permitted())throw new CpfValidationException("다운로드 권한이 없습니다.");if(p.approvalRequired()&&(c.approvalId()==null||c.approvalId().isBlank()))throw new CpfValidationException("다운로드 승인이 필요합니다.");Instant now=Instant.now(clock);if(c.expiresAt()!=null&&now.isAfter(c.expiresAt()))throw new CpfValidationException("다운로드 링크가 만료되었습니다.");if(Duration.between(c.requestedAt(),now).getSeconds()>p.linkExpirySeconds())throw new CpfValidationException("다운로드 요청이 만료되었습니다.");}
 private Path resolveSafe(Path c){Path n=c.toAbsolutePath().normalize();if(!n.startsWith(root))throw new CpfValidationException("첨부 경로 이탈");return n;}private void rejectSymbolicLink(Path p){if(Files.exists(p,LinkOption.NOFOLLOW_LINKS)&&Files.isSymbolicLink(p))throw new CpfValidationException("심볼릭 링크 금지");}
 private String safeFileName(String v){String n=required(v,"originalFileName");if(!Path.of(n).getFileName().toString().equals(n)||n.contains("..")||n.chars().anyMatch(Character::isISOControl)||n.length()>255)throw new CpfValidationException("안전하지 않은 파일명");return n;}private String safeSegment(String v,String f){String s=required(v,f);if(!s.matches("[A-Za-z0-9_-]{1,80}"))throw new CpfValidationException(f+" 형식 오류");return s;}private String extension(String n){int i=n.lastIndexOf('.');if(i<1||i==n.length()-1)throw new CpfValidationException("확장자 필요");return n.substring(i+1).toLowerCase(Locale.ROOT);}private String normalizeContentType(String v){String c=v==null||v.isBlank()?"application/octet-stream":v.trim();if(c.length()>120||c.contains("\r")||c.contains("\n"))throw new CpfValidationException("Content-Type 오류");return c;}private String required(String v,String f){if(v==null||v.isBlank())throw new CpfValidationException(f+" 필수");return v.trim();}private String sha256(byte[]b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
