package com.cpf.admin.opr.centercut;
import com.cpf.core.api.batch.CpfBatchOwnerUnknownResultException;
import com.cpf.core.api.batch.CpfCenterCutOperationsPort;
import com.cpf.core.common.servicecall.*;
import org.springframework.web.reactive.function.client.WebClient;
import java.util.*;
public class RemoteCpfCenterCutOperationsAdapter implements CpfCenterCutOperationsPort {
 private final CpfServiceCallEngine engine;private final WebClient web;
 public RemoteCpfCenterCutOperationsAdapter(CpfServiceCallEngine e,WebClient.Builder b){engine=e;web=b.build();}
 private Object call(String op,Map<String,Object> payload){String path="/bat/internal/center-cut/"+op;ServiceCallRequest q=ServiceCallRequest.builder("BAT").endpointCode("SBATCT0001").httpMethod("POST").requestPath(path).attribute("ownerDomain","BAT").attribute("callerDomain","ADM").build();ServiceCallResult<Object> r=engine.invoke(q,t->web.post().uri(join(t.baseUrl(),path)).bodyValue(payload==null?Map.of():payload).retrieve().bodyToMono(Object.class).block());if("UNKNOWN".equals(r.status()))throw new CpfBatchOwnerUnknownResultException(r.failureCode(),"BAT Center-Cut 결과불명: "+r.failureMessage());if(!"SUCCESS".equals(r.status()))throw new IllegalStateException("BAT Center-Cut 호출 실패: "+r.failureMessage());return r.responseBody();}
 private static String join(String b,String p){if(b==null||b.isBlank())throw new IllegalStateException("BAT baseUrl missing");return b.endsWith("/")?b.substring(0,b.length()-1)+p:b+p;}private static Map<String,Object> p(Object...k){LinkedHashMap<String,Object>m=new LinkedHashMap<>();for(int i=0;i<k.length;i+=2)if(k[i+1]!=null)m.put(String.valueOf(k[i]),k[i+1]);return m;}@SuppressWarnings("unchecked")private static List<Map<String,Object>> l(Object o){return o==null?List.of():(List<Map<String,Object>>)o;}@SuppressWarnings("unchecked")private static Map<String,Object> m(Object o){return o==null?Map.of():(Map<String,Object>)o;}
 public List<Map<String,Object>> findJobs(){return l(call("findJobs",Map.of()));}public Map<String,Object> findJobDetail(String id){return m(call("findJobDetail",p("centerCutJobId",id)));}public List<Map<String,Object>> findParameters(String id){return l(call("findParameters",p("centerCutJobId",id)));}public Map<String,Object> findSummary(String id){return m(call("findSummary",p("centerCutJobId",id)));}public List<Map<String,Object>> findTargets(String id,String st,int limit){return l(call("findTargets",p("centerCutJobId",id,"statusCode",st,"limit",limit)));}public List<Map<String,Object>> findResults(String id,String st,int limit){return l(call("findResults",p("centerCutJobId",id,"resultStatus",st,"limit",limit)));}public Map<String,Object> findResultDetail(String id){return m(call("findResultDetail",p("resultId",id)));}
}
