package com.cpf.education.operations.runtime.persistence;
import com.cpf.education.operations.runtime.application.EduConflictException;
import com.cpf.education.operations.runtime.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
/** JdbcEduOperationRepository 타입의 역할과 책임을 정의하며 CPF 계약 경계를 명확히 유지한다. */
public final class JdbcEduOperationRepository implements EduOperationRepository {
    private final JdbcTemplate jdbc; private final ObjectMapper json;
    public JdbcEduOperationRepository(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
    public EduCreateResult create(EduOperationRecord r){try{jdbc.update("insert into CPF_EDU_OPERATION (OPERATION_ID,REQUIREMENT_ID,BUSINESS_KEY,IDEMPOTENCY_KEY,PAYLOAD_HASH,ACTOR_ID,ACTOR_ROLES,DATA_SCOPE,STATE,EXPECTED_VERSION,RECORD_VERSION,FENCING_TOKEN,RETRY_COUNT,MAX_RETRIES,FAILURE_POINT,RESULT_CODE,RESULT_MESSAGE,REQUEST_ID,TRACE_ID,PAYLOAD_JSON,RESULT_JSON,CREATED_AT,UPDATED_AT) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.operationId(),r.requirementId(),r.businessKey(),r.idempotencyKey(),r.payloadHash(),r.actorId(),r.actorRoles(),r.dataScope(),r.state().name(),r.expectedBusinessVersion(),r.recordVersion(),r.fencingToken(),r.retryCount(),r.maxRetries(),r.failurePoint().name(),r.resultCode(),r.resultMessage(),r.requestId(),r.traceId(),toJson(r.payload()),toJson(r.result()),ts(r.createdAt()),ts(r.updatedAt()));return new EduCreateResult(r,false);}catch(DuplicateKeyException e){EduOperationRecord old=findByIdempotency(r.requirementId(),r.idempotencyKey()).orElseThrow(()->e);if(!old.payloadHash().equals(r.payloadHash()))throw new EduConflictException("Idempotency key payload mismatch");return new EduCreateResult(old,true);}}
    public Optional<EduOperationRecord> find(String id){return jdbc.query("select * from CPF_EDU_OPERATION where OPERATION_ID=?",this::map,id).stream().findFirst();}
    public Optional<EduOperationRecord> findByIdempotency(String req,String key){return jdbc.query("select * from CPF_EDU_OPERATION where REQUIREMENT_ID=? and IDEMPOTENCY_KEY=?",this::map,req,key).stream().findFirst();}
    public List<EduOperationRecord> findByRequirement(String req,int limit){return jdbc.query("select * from CPF_EDU_OPERATION where REQUIREMENT_ID=? order by CREATED_AT desc",this::map,req).stream().limit(limit).toList();}
    public EduOperationRecord save(EduOperationRecord r,long expected){int n=jdbc.update("update CPF_EDU_OPERATION set STATE=?,RECORD_VERSION=?,FENCING_TOKEN=?,RETRY_COUNT=?,RESULT_CODE=?,RESULT_MESSAGE=?,RESULT_JSON=?,UPDATED_AT=?,COMPLETED_AT=? where OPERATION_ID=? and RECORD_VERSION=?",r.state().name(),r.recordVersion(),r.fencingToken(),r.retryCount(),r.resultCode(),r.resultMessage(),toJson(r.result()),ts(r.updatedAt()),ts(r.completedAt()),r.operationId(),expected);if(n!=1)throw new EduConflictException("record version conflict");return r;}
    /** appendAudit 작업을 CPF 표준 계약에 따라 수행한다. */
    public void appendAudit(EduAuditRecord a){jdbc.update("insert into CPF_EDU_OPERATION_AUDIT (AUDIT_ID,OPERATION_ID,REQUIREMENT_ID,ACTION,BEFORE_STATE,AFTER_STATE,ACTOR_ID,REASON,TRACE_ID,CREATED_AT) values (?,?,?,?,?,?,?,?,?,?)",a.auditId(),a.operationId(),a.requirementId(),a.action(),a.beforeState(),a.afterState(),a.actorId(),a.reason(),a.traceId(),ts(a.createdAt()));}
    public List<EduAuditRecord> audits(String id){return jdbc.query("select * from CPF_EDU_OPERATION_AUDIT where OPERATION_ID=? order by CREATED_AT",(rs,n)->new EduAuditRecord(rs.getString("AUDIT_ID"),rs.getString("OPERATION_ID"),rs.getString("REQUIREMENT_ID"),rs.getString("ACTION"),rs.getString("BEFORE_STATE"),rs.getString("AFTER_STATE"),rs.getString("ACTOR_ID"),rs.getString("REASON"),rs.getString("TRACE_ID"),rs.getTimestamp("CREATED_AT").toInstant()),id);}
    public void saveTarget(EduTargetRecord t){int n=jdbc.update("update CPF_EDU_OPERATION_TARGET set STATE=?,BEFORE_JSON=?,AFTER_JSON=?,ERROR_CODE=?,ERROR_MESSAGE=?,TARGET_VERSION=?,UPDATED_AT=? where TARGET_ID=?",t.state(),toJson(t.beforeValue()),toJson(t.afterValue()),t.errorCode(),t.errorMessage(),t.version(),ts(t.updatedAt()),t.targetId());if(n==0)jdbc.update("insert into CPF_EDU_OPERATION_TARGET (TARGET_ID,OPERATION_ID,TARGET_KEY,STATE,BEFORE_JSON,AFTER_JSON,ERROR_CODE,ERROR_MESSAGE,TARGET_VERSION,UPDATED_AT) values (?,?,?,?,?,?,?,?,?,?)",t.targetId(),t.operationId(),t.targetKey(),t.state(),toJson(t.beforeValue()),toJson(t.afterValue()),t.errorCode(),t.errorMessage(),t.version(),ts(t.updatedAt()));}
    public List<EduTargetRecord> targets(String id){return jdbc.query("select * from CPF_EDU_OPERATION_TARGET where OPERATION_ID=? order by TARGET_KEY",(rs,n)->new EduTargetRecord(rs.getString("TARGET_ID"),rs.getString("OPERATION_ID"),rs.getString("TARGET_KEY"),rs.getString("STATE"),fromJson(rs.getString("BEFORE_JSON")),fromJson(rs.getString("AFTER_JSON")),rs.getString("ERROR_CODE"),rs.getString("ERROR_MESSAGE"),rs.getLong("TARGET_VERSION"),rs.getTimestamp("UPDATED_AT").toInstant()),id);}
    public void enqueue(EduOutboxRecord e){jdbc.update("insert into CPF_EDU_OUTBOX (EVENT_ID,OPERATION_ID,DESTINATION,EVENT_KEY,PAYLOAD_JSON,STATE,ATTEMPT_COUNT,NEXT_ATTEMPT_AT,CLAIMED_BY,FENCING_TOKEN,CREATED_AT,UPDATED_AT) values (?,?,?,?,?,?,?,?,?,?,?,?)",e.eventId(),e.operationId(),e.destination(),e.eventKey(),toJson(e.payload()),e.state(),e.attemptCount(),ts(e.nextAttemptAt()),e.claimedBy(),e.fencingToken(),ts(e.createdAt()),ts(e.updatedAt()));}
    public void saveOutbox(EduOutboxRecord e){int n=jdbc.update("update CPF_EDU_OUTBOX set STATE=?,ATTEMPT_COUNT=?,NEXT_ATTEMPT_AT=?,CLAIMED_BY=?,FENCING_TOKEN=?,UPDATED_AT=? where EVENT_ID=?",e.state(),e.attemptCount(),ts(e.nextAttemptAt()),e.claimedBy(),e.fencingToken(),ts(e.updatedAt()),e.eventId());if(n==0)enqueue(e);}
    public List<EduOutboxRecord> outbox(String id){return jdbc.query("select * from CPF_EDU_OUTBOX where OPERATION_ID=? order by CREATED_AT",(rs,n)->new EduOutboxRecord(rs.getString("EVENT_ID"),rs.getString("OPERATION_ID"),rs.getString("DESTINATION"),rs.getString("EVENT_KEY"),fromJson(rs.getString("PAYLOAD_JSON")),rs.getString("STATE"),rs.getInt("ATTEMPT_COUNT"),rs.getTimestamp("NEXT_ATTEMPT_AT").toInstant(),rs.getString("CLAIMED_BY"),rs.getLong("FENCING_TOKEN"),rs.getTimestamp("CREATED_AT").toInstant(),rs.getTimestamp("UPDATED_AT").toInstant()),id);}
    /** claimLease 작업을 CPF 표준 계약에 따라 수행한다. */
    public long claimLease(String key,String owner,Instant expires){return jdbc.execute((ConnectionCallback<Long>)con->{con.setAutoCommit(false);try(var q=con.prepareStatement("select OWNER_ID,FENCING_TOKEN,EXPIRES_AT from CPF_EDU_LEASE where LEASE_KEY=? for update")){q.setString(1,key);var rs=q.executeQuery();long token;if(rs.next()){Timestamp old=rs.getTimestamp(3);if(old.toInstant().isAfter(Instant.now())&&!owner.equals(rs.getString(1)))throw new EduConflictException("lease held by "+rs.getString(1));token=rs.getLong(2)+1;try(var u=con.prepareStatement("update CPF_EDU_LEASE set OWNER_ID=?,FENCING_TOKEN=?,EXPIRES_AT=?,UPDATED_AT=? where LEASE_KEY=?")){u.setString(1,owner);u.setLong(2,token);u.setTimestamp(3,ts(expires));u.setTimestamp(4,ts(Instant.now()));u.setString(5,key);u.executeUpdate();}}else{token=1;try(var i=con.prepareStatement("insert into CPF_EDU_LEASE (LEASE_KEY,OWNER_ID,FENCING_TOKEN,EXPIRES_AT,UPDATED_AT) values (?,?,?,?,?)")){i.setString(1,key);i.setString(2,owner);i.setLong(3,token);i.setTimestamp(4,ts(expires));i.setTimestamp(5,ts(Instant.now()));i.executeUpdate();}}con.commit();return token;}catch(Exception e){con.rollback();if(e instanceof RuntimeException r)throw r;throw new IllegalStateException(e);}});}
    private EduOperationRecord map(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new EduOperationRecord(rs.getString("OPERATION_ID"),rs.getString("REQUIREMENT_ID"),rs.getString("BUSINESS_KEY"),rs.getString("IDEMPOTENCY_KEY"),rs.getString("PAYLOAD_HASH"),rs.getString("ACTOR_ID"),rs.getString("ACTOR_ROLES"),rs.getString("DATA_SCOPE"),EduExecutionState.valueOf(rs.getString("STATE")),rs.getLong("EXPECTED_VERSION"),rs.getLong("RECORD_VERSION"),rs.getLong("FENCING_TOKEN"),rs.getInt("RETRY_COUNT"),rs.getInt("MAX_RETRIES"),EduFailurePoint.valueOf(rs.getString("FAILURE_POINT")),rs.getString("RESULT_CODE"),rs.getString("RESULT_MESSAGE"),rs.getString("REQUEST_ID"),rs.getString("TRACE_ID"),fromJson(rs.getString("PAYLOAD_JSON")),fromJson(rs.getString("RESULT_JSON")),rs.getTimestamp("CREATED_AT").toInstant(),rs.getTimestamp("UPDATED_AT").toInstant(),rs.getTimestamp("COMPLETED_AT")==null?null:rs.getTimestamp("COMPLETED_AT").toInstant());}
    private String toJson(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}
    private Map<String,Object> fromJson(String v){try{return v==null||v.isBlank()?Map.of():json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}
    private static Timestamp ts(Instant i){return i==null?null:Timestamp.from(i);}
}
