# Account 주제영역 공통 설정입니다.
cpf:
  framework:
    module-id: ${ACC_MODULE_ID:ACC}
  datasource:
    mode: ${ACC_DATASOURCE_MODE:url}
    jndi-name: ${ACC_DATASOURCE_JNDI_NAME:java:comp/env/jdbc/cpfAccountDataSource}
    url: ${ACC_DATASOURCE_URL:jdbc:mariadb://localhost:3306/accDB}
    username: ${ACC_DATASOURCE_USERNAME:cpf_acc_app}
    password: ${ACC_DATASOURCE_PASSWORD:}
  logging:
    file:
      file-pattern: "cpf-{moduleCode}-{logType}-{instanceId}.{date}.log"
