# Account local profile 설정입니다.
spring:
  config:
    activate:
      on-profile: local

server:
  port: ${ACC_SERVER_PORT:8082}

cpf:
  framework:
    module-id: ${ACC_MODULE_ID:ACC}
    instance-id: ${ACC_INSTANCE_ID:ACC01}
    was-id: ${ACC_WAS_ID:ACCL001}
  datasource:
    mode: ${ACC_DATASOURCE_MODE:url}
    url: ${ACC_DATASOURCE_URL:}
    database-name: ${ACC_DB_NAME:accDB}
    driver-class-name: ${ACC_DB_DRIVER:}
    username: ${ACC_DATASOURCE_USERNAME:cpf_acc_app}
    password: ${ACC_DATASOURCE_PASSWORD}
    jndi-name: ${ACC_DATASOURCE_JNDI_NAME:java:comp/env/jdbc/cpfAccountDataSource}
