import { defineAsyncComponent, type Component } from "vue";
import type { RouteRecordRaw } from "vue-router";

export type AdmFeatureGroup = "home" | "online" | "batch" | "integration" | "monitoring" | "framework";
export type AdmRouteRiskLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

export interface AdmCapabilityRoute {
  routeId: string;
  path: string;
  menuId: string;
  label: string;
  group: AdmFeatureGroup;
  component: Component;
  icon: string;
  ownerModule: "cpf-admin" | "cpf-biz-admin";
  riskLevel: AdmRouteRiskLevel;
  featureFlag: string;
  expectedOperationIds: readonly string[];
  props?: Record<string, unknown>;
}

export const admGroupLabels: Record<AdmFeatureGroup, string> = {
  home: "홈",
  online: "온라인 운영",
  batch: "배치 운영",
  integration: "연계 관리",
  monitoring: "통합 관제",
  framework: "프레임워크 관리"
};

export const admCapabilityRegistry: Record<string, AdmCapabilityRoute> = {
  "dashboard": { routeId: "dashboard", path: "/", menuId: "DASHBOARD", label: "통합 운영 Dashboard", group: "home", icon: "dashboard", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.dashboard.enabled", expectedOperationIds: ["admRuntimeControlFindHealth", "admRuntimeControlFindStatus", "findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "admBatchFindExecutionPage", "getAdmReadiness", "getAdmLiveness", "getAdmSystemVersion"], component: defineAsyncComponent(() => import("../features/operations/UnifiedOperationsDashboardPage.vue")), props: undefined },
  "topology": { routeId: "topology", path: "/topology", menuId: "TOPOLOGY", label: "서비스 토폴로지", group: "home", icon: "topology", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.topology.enabled", expectedOperationIds: ["admServiceRegistryFindServices", "admServiceRegistryFindInstances", "admServiceRegistryFindEndpoints", "admServiceRegistryFindHealth"], component: defineAsyncComponent(() => import("../features/topology/TopologyPage.vue")), props: undefined },
  "health-instances": { routeId: "health-instances", path: "/health-instances", menuId: "TOPOLOGY", label: "Runtime Instance Health", group: "home", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.topology.enabled", expectedOperationIds: ["admHealthInstanceList", "admHealthInstanceDetail"], component: defineAsyncComponent(() => import("../features/health/InstanceHealthPage.vue")), props: undefined },
  "capacity": { routeId: "capacity", path: "/capacity", menuId: "CAPACITY", label: "Online Runtime Diagnostics", group: "home", icon: "capacity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.capacity.enabled", expectedOperationIds: ["admRuntimeControlFindHealth", "admRuntimeControlFindStatus", "findAdmBrokerOutbox", "findAdmBrokerInbox", "findAdmIdempotencyRecords", "findAdmFileTransferHistory"], component: defineAsyncComponent(() => import("../features/operations/OnlineDiagnosticsPage.vue")), props: undefined },
  "logs": { routeId: "logs", path: "/logs", menuId: "LOG_LIST", label: "거래 로그", group: "monitoring", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.logs.enabled", expectedOperationIds: ["admLogFindLogs", "admLogGetLogDetail", "admLogExportCreate", "admLogExportDownload"], component: defineAsyncComponent(() => import("../features/logs/LogsPage.vue")), props: undefined },
  "transactionGroups": { routeId: "transactionGroups", path: "/transactionGroups", menuId: "LOG_LIST", label: "Online·Batch 통합 Trace", group: "online", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.transactionGroups.enabled", expectedOperationIds: ["traceAdmByTransactionId", "traceAdmByTraceId", "traceAdmByBusinessTransactionId", "admTransactionGroupFindTimeline", "admTransactionGroupFindGroups", "admTransactionGroupFindDetail", "admTransactionGroupFindExternalLogs", "admTransactionGroupFindHeaders", "admTransactionGroupFindSegments"], component: defineAsyncComponent(() => import("../features/operations/IntegratedTracePage.vue")), props: undefined },
  "transactions": { routeId: "transactions", path: "/transactions", menuId: "TRANSACTION_META", label: "온라인 거래 정의", group: "online", icon: "activity", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.transactions.enabled", expectedOperationIds: ["admTransactionMetaFindPage", "admTransactionMetaFindTransaction", "admTransactionMetaScan", "admTransactionMetaInactivate", "admTransactionMetaFindTransactions"], component: defineAsyncComponent(() => import("../features/transactions/TransactionsPage.vue")), props: undefined },
  "remoteLogs": { routeId: "remoteLogs", path: "/remoteLogs", menuId: "REMOTE_LOG", label: "원격 로그", group: "monitoring", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.remoteLogs.enabled", expectedOperationIds: ["admRemoteLogSearch", "admRemoteLogPreview", "admRemoteLogBundleJobCreate", "admRemoteLogBundleJobFind", "admRemoteLogBundleJobDownload", "admRemoteLogBundleDownloadTokenIssue", "admRemoteLogBundleDownload", "admRemoteLogDiagnostics", "admRemoteLogDownload"], component: defineAsyncComponent(() => import("../features/remote-logs/RemoteLogsPage.vue")), props: undefined },
  "auditLogs": { routeId: "auditLogs", path: "/auditLogs", menuId: "AUDIT_LOG", label: "감사 로그", group: "monitoring", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.auditLogs.enabled", expectedOperationIds: ["admAuditLogFindAuditLogs", "admAuditDeliveryList", "admAuditDeliveryRetry", "admLogPolicyAuditFindPolicyAudits"], component: defineAsyncComponent(() => import("../features/audit-logs/AuditLogsPage.vue")), props: undefined },
  "logLevel": { routeId: "logLevel", path: "/logLevel", menuId: "DYNAMIC_LOG", label: "동적 로그", group: "monitoring", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.logLevel.enabled", expectedOperationIds: ["admDynamicLogLevelFindRules", "admDynamicLogLevelRegister", "admDynamicLogLevelRemove"], component: defineAsyncComponent(() => import("../features/log-level/LogLevelPage.vue")), props: undefined },
  "logPolicies": { routeId: "logPolicies", path: "/logPolicies", menuId: "LOG_POLICY", label: "로그 정책", group: "monitoring", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.logPolicies.enabled", expectedOperationIds: ["admLogPolicyFindPolicies", "admLogPolicyFindPolicy", "admLogPolicyCreatePolicy", "admLogPolicyUpdatePolicy", "admLogPolicyDisablePolicy", "admLogPolicyDistributionStatus", "admLogPolicyClearCache", "admLogPolicyRefreshCache", "admLogPolicyFindTraceBoostHistory", "admLogPolicyCreateOverride", "admLogPolicyDisableOverride", "admLogPolicyFindTraceBoostRuntimeState", "admLogPolicyCreateTraceBoost"], component: defineAsyncComponent(() => import("../features/log-policies/LogPoliciesPage.vue")), props: undefined },
  "standardExecutions": { routeId: "standardExecutions", path: "/standardExecutions", menuId: "STANDARD_EXECUTION", label: "표준 실행", group: "online", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.standardExecutions.enabled", expectedOperationIds: ["admStandardExecutionFindAll", "admStandardExecutionFindOne"], component: defineAsyncComponent(() => import("../features/standard-executions/StandardExecutionsPage.vue")), props: undefined },
  "channelPolicy": { routeId: "channelPolicy", path: "/channelPolicy", menuId: "CHANNEL_POLICY", label: "채널 정책", group: "online", icon: "service", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.channelPolicy.enabled", expectedOperationIds: ["admChannelFindSnapshot", "admChannelRefreshSnapshot", "admChannelSave", "admChannelSaveExecutionPolicy", "admChannelExportPackage", "admChannelImportPackage"], component: defineAsyncComponent(() => import("../features/channel-policy/ChannelPolicyPage.vue")), props: undefined },
  "serviceRegistry": { routeId: "serviceRegistry", path: "/serviceRegistry", menuId: "SERVICE_REGISTRY", label: "서비스 레지스트리", group: "online", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.serviceRegistry.enabled", expectedOperationIds: ["admServiceRegistryFindServices", "admServiceRegistryFindInstances", "admServiceRegistryFindEndpoints", "admServiceRegistryFindHealth", "admServiceRegistrySaveService", "admServiceRegistrySaveInstance", "admServiceRegistrySaveEndpoint", "admServiceRegistryChangeInstanceState", "admServiceRegistryDeleteEndpoint", "admServiceRegistryDeleteInstance", "admServiceRegistryDeleteService", "admServiceRegistryFindCallHistory", "admServiceRegistryCapabilities", "admServiceRegistryFindCircuitStates", "admServiceRegistryFindRoutingPolicies"], component: defineAsyncComponent(() => import("../features/service-registry/ServiceRegistryPage.vue")), props: undefined },
  "runtimeControl": { routeId: "runtimeControl", path: "/runtimeControl", menuId: "RUNTIME_CONTROL", label: "Deployment·Promotion·Rollback", group: "online", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.runtimeControl.enabled", expectedOperationIds: ["admRuntimeControlFindHealth", "admRuntimeControlFindStatus", "admRuntimeControlFindCapabilities", "admRuntimeControlPreviewChange", "admRuntimeControlCreateChange", "admRuntimeControlFindChange", "admRuntimeControlFindByOperation", "admRuntimeControlCancelChange", "admRuntimeControlRollbackChange", "admRuntimeControlVerifyAudit", "admRuntimeControlSaveGroup", "admRuntimeControlFindGroup", "admRuntimeControlDeleteGroup", "admRuntimeControlChangeGroupMember", "admRuntimeControlPreviewTargets", "admRuntimeControlFindStateCatalog"], component: defineAsyncComponent(() => import("../features/operations/OnlineDeploymentWorkbenchPage.vue")), props: undefined },
  "maintenance": { routeId: "maintenance", path: "/maintenance", menuId: "MAINTENANCE", label: "점검·Drain", group: "framework", icon: "maintenance", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.maintenance.enabled", expectedOperationIds: ["admMaintenanceFindActions", "admMaintenanceExecuteAction"], component: defineAsyncComponent(() => import("../features/maintenance/MaintenancePage.vue")), props: undefined },
  "cache": { routeId: "cache", path: "/cache", menuId: "CACHE", label: "캐시", group: "framework", icon: "service", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.cache.enabled", expectedOperationIds: ["admCacheSummary", "admCacheRefresh", "admCacheEvictKey", "admCacheEvictNamespace", "admCacheReconcile"], component: defineAsyncComponent(() => import("../features/cache/CachePage.vue")), props: undefined },
  "configs": { routeId: "configs", path: "/configs", menuId: "CONFIG", label: "설정", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.configs.enabled", expectedOperationIds: ["admConfigFindConfigs", "admConfigFindConfig", "admConfigCreateConfig", "admConfigUpdateConfig", "admConfigDeleteConfig", "admParameterReferenceSearch"], component: defineAsyncComponent(() => import("../features/configs/ConfigsPage.vue")), props: undefined },
  "responseCodes": { routeId: "responseCodes", path: "/responseCodes", menuId: "RESPONSE_CODE", label: "응답코드", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.responseCodes.enabled", expectedOperationIds: ["admResponseCodeFindAll", "admResponseCodeFindOne", "admResponseCodeCreate", "admResponseCodeUpdate", "admResponseCodeDelete"], component: defineAsyncComponent(() => import("../features/response-codes/ResponseCodesPage.vue")), props: undefined },
  "businessCalendar": { routeId: "businessCalendar", path: "/businessCalendar", menuId: "BUSINESS_CALENDAR", label: "영업일 · 휴일", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.businessCalendar.enabled", expectedOperationIds: ["admCalendarFindDays", "admCalendarResolveDate", "admCalendarSaveDay", "admCalendarDeleteDay"], component: defineAsyncComponent(() => import("../features/business-calendar/BusinessCalendarPage.vue")), props: undefined },
  "recoveryCenter": { routeId: "recoveryCenter", path: "/recoveryCenter", menuId: "RECOVERY_CENTER", label: "복구 센터", group: "monitoring", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.recoveryCenter.enabled", expectedOperationIds: ["getAdmTransactionLogRecoveryStatus", "runAdmTransactionLogRecovery", "retryAdmTraceRecoveryPoison", "resolveAdmUnknownResult", "requestAdmBrokerDlqReplay"], component: defineAsyncComponent(() => import("../features/recovery-center/RecoveryCenterPage.vue")), props: undefined },
  "incidents": { routeId: "incidents", path: "/incidents", menuId: "INCIDENT", label: "Error·Unknown Result", group: "monitoring", icon: "incident", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.incidents.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "requestAdmBrokerDlqReplay", "resolveAdmUnknownResult", "getAdmTransactionLogRecoveryStatus", "runAdmTransactionLogRecovery", "admIncidentFindIncidents", "admIncidentFindMaintenance", "admIncidentFindPolicies", "admIncidentIngestSignal", "admIncidentCreateMaintenance", "admIncidentUpdateMaintenance", "admIncidentCreatePolicy", "admIncidentUpdatePolicy", "admIncidentFindIncident", "admIncidentAcknowledge", "admIncidentEscalate", "admIncidentReopen", "admIncidentResolve", "admIncidentFindTimeline"], component: defineAsyncComponent(() => import("../features/operations/ErrorWorkbenchPage.vue")), props: undefined },
  "reliability": { routeId: "reliability", path: "/reliability", menuId: "RELIABILITY", label: "Analysis Center", group: "monitoring", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.reliability.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "findAdmBrokerInbox", "findAdmIdempotencyRecords", "findAdmFileTransferHistory", "getAdmTransactionLogRecoveryStatus", "findAdmBatchJobInstanceLogs"], component: defineAsyncComponent(() => import("../features/operations/AnalysisCenterPage.vue")), props: undefined },
  "notifications": { routeId: "notifications", path: "/notifications", menuId: "NOTIFICATION", label: "알림", group: "integration", icon: "incident", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.notifications.enabled", expectedOperationIds: ["admNotificationFindRules", "admNotificationFindRule", "admNotificationFindDeliveryLogs", "admNotificationFindDeliveryAttempts", "admNotificationSaveRule", "admNotificationUpdateRule", "admNotificationRetryDelivery", "admNotificationCancelDelivery", "admNotificationSendTest", "admNotificationFindDlq", "admNotificationDisableRule"], component: defineAsyncComponent(() => import("../features/notifications/NotificationsPage.vue")), props: undefined },
  "batch": { routeId: "batch", path: "/batch", menuId: "BATCH", label: "Batch / Center-Cut", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch.enabled", expectedOperationIds: ["admBatchFindJobs", "admBatchFindSchedules", "admBatchFindExecutionPage", "admBatchFindInstances", "admBatchFindWorkers", "admBatchWorkbenchJobDetail", "admBatchFindExecutionTargets", "admBatchFindExecutions", "admBatchRegisterJob", "admBatchFindJobDetail", "admBatchRunJob", "admBatchFindRelations"], component: defineAsyncComponent(() => import("../features/batch/BatchPage.vue")), props: undefined },
  "batch-overview": { routeId: "batch-overview", path: "/batch-overview", menuId: "BATCH_OVERVIEW", label: "Batch Overview", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-overview.enabled", expectedOperationIds: ["admBatchWorkbenchOverview", "admBatchFindJobs", "admBatchFindSchedules", "admBatchFindExecutionPage", "admBatchFindInstances", "admBatchFindWorkers", "admBatchFindLocks"], component: defineAsyncComponent(() => import("../features/batch-overview/BatchOverviewPage.vue")), props: undefined },
  "batch-runtime": { routeId: "batch-runtime", path: "/batch-runtime", menuId: "BATCH_RUNTIME", label: "Runtime Topology", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.batch-runtime.enabled", expectedOperationIds: ["admBatchRuntimeInstances", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../features/batch-runtime-control/RuntimeTopologyPage.vue")), props: undefined },
  "batch-instances": { routeId: "batch-instances", path: "/batch-instances", menuId: "BATCH_INSTANCES", label: "Runtime Instances", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-instances.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchFindInstances", "admBatchRuntimeInstances", "admBatchRuntimeView"], component: defineAsyncComponent(() => import("../features/batch-instances/BatchInstancesPage.vue")), props: undefined },
  "batch-scheduler": { routeId: "batch-scheduler", path: "/batch-scheduler", menuId: "BATCH_SCHEDULER", label: "Scheduler HA", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-scheduler.enabled", expectedOperationIds: ["admBatchWorkbenchSchedules", "admBatchFindSchedules", "admBatchSimulateSchedule", "admBatchEnableSchedule", "admBatchDisableSchedule", "admBatchRunSchedulerOnce"], component: defineAsyncComponent(() => import("../features/batch-scheduler/BatchSchedulerPage.vue")), props: undefined },
  "batch-worker-pools": { routeId: "batch-worker-pools", path: "/batch-worker-pools", menuId: "BATCH_WORKER_POOLS", label: "Worker Pools", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-worker-pools.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchFindWorkers", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../features/batch-worker-pools/BatchWorkerPoolsPage.vue")), props: undefined },
  "batch-center-cut": { routeId: "batch-center-cut", path: "/batch-center-cut", menuId: "BATCH_CENTER_CUT", label: "Center-Cut", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-center-cut.enabled", expectedOperationIds: ["admCenterCutFindSummary", "admCenterCutFindJobs", "admCenterCutFindJobDetail", "admCenterCutFindResults", "admCenterCutFindResultDetail", "admCenterCutFindTargets", "admCenterCutFindParameters", "admCenterCutReprocessFailedExecution", "admCenterCutReconcileUnknownExecution"], component: defineAsyncComponent(() => import("../features/batch-center-cut/BatchCenterCutPage.vue")), props: undefined },
  "batch-agents": { routeId: "batch-agents", path: "/batch-agents", menuId: "BATCH_AGENTS", label: "Host Agents", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-agents.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchRuntimeInstances", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../features/batch-agents/BatchAgentsPage.vue")), props: undefined },
  "batch-job-packs": { routeId: "batch-job-packs", path: "/batch-job-packs", menuId: "BATCH_JOB_PACKS", label: "Job Packs", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-job-packs.enabled", expectedOperationIds: ["admBatchWorkbenchJobDetail", "admBatchWorkbenchJobs", "admBatchJobDefinitions", "admBatchJobDefinitionDetail", "admBatchJobDefinitionValidate", "admBatchJobDefinitionSave", "admBatchJobDefinitionTransition", "admBatchFindJobs"], component: defineAsyncComponent(() => import("../features/batch-job-packs/BatchJobPacksPage.vue")), props: undefined },
  "batch-executions": { routeId: "batch-executions", path: "/batch-executions", menuId: "BATCH_EXECUTIONS", label: "Executions", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-executions.enabled", expectedOperationIds: ["admBatchWorkbenchExecutionDetail", "admBatchWorkbenchExecutions", "admBatchFindExecutionPage", "admBatchFindExecutionDetail", "admBatchFindStepExecutions", "admBatchRetryExecution", "admBatchStopExecution"], component: defineAsyncComponent(() => import("../features/batch-executions/BatchExecutionsPage.vue")), props: undefined },
  "batch-deployment": { routeId: "batch-deployment", path: "/batch-deployment", menuId: "BATCH_DEPLOYMENT", label: "Deployment / Rollback", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.batch-deployment.enabled", expectedOperationIds: ["admBatchRuntimeCreateDeploymentPlan", "admBatchRuntimeView", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../features/batch-deployment/BatchDeploymentPage.vue")), props: undefined },
  "batch-recovery": { routeId: "batch-recovery", path: "/batch-recovery", menuId: "BATCH_RECOVERY", label: "Recovery / Unknown", group: "monitoring", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-recovery.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchRuntimeView", "admBatchFindGhostCandidates", "admBatchActGhostExecution", "findAdmUnknownResults", "resolveAdmUnknownResult"], component: defineAsyncComponent(() => import("../features/batch-recovery/BatchRecoveryPage.vue")), props: undefined },
  "batch-leases": { routeId: "batch-leases", path: "/batch-leases", menuId: "BATCH_LEASES", label: "Lease / Fencing", group: "monitoring", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-leases.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchRuntimeView", "admBatchFindLocks", "admBatchReleaseLock"], component: defineAsyncComponent(() => import("../features/batch-leases/BatchLeasesPage.vue")), props: undefined },
  "batch-alerts": { routeId: "batch-alerts", path: "/batch-alerts", menuId: "BATCH_ALERTS", label: "Batch Alerts", group: "monitoring", icon: "incident", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-alerts.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "admBatchFindOperationLogs"], component: defineAsyncComponent(() => import("../features/batch-alerts/BatchAlertsPage.vue")), props: undefined },
  "batch-audit": { routeId: "batch-audit", path: "/batch-audit", menuId: "BATCH_AUDIT", label: "Audit / Evidence", group: "monitoring", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-audit.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchFindOperationLogs", "admAuditLogFindAuditLogs", "admAuditDeliveryList", "getAdmBatchJobInstanceLog"], component: defineAsyncComponent(() => import("../features/batch-audit/BatchAuditEvidencePage.vue")), props: undefined },
  "workers": { routeId: "workers", path: "/workers", menuId: "WORKER", label: "Agent / Worker", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.workers.enabled", expectedOperationIds: ["admBatchFindWorkers", "admBatchFindInstances", "admBatchRuntimeInstances"], component: defineAsyncComponent(() => import("../features/workers/WorkersPage.vue")), props: undefined },
  "downloads": { routeId: "downloads", path: "/downloads", menuId: "DOWNLOAD", label: "다운로드", group: "integration", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.downloads.enabled", expectedOperationIds: ["admDownloadFindPolicies", "admDownloadFindDownloadAuditLogs", "admDownloadDownloadCsv"], component: defineAsyncComponent(() => import("../features/downloads/DownloadsPage.vue")), props: undefined },
  "file-jobs": { routeId: "file-jobs", path: "/file-jobs", menuId: "FILE_JOB", label: "대량파일 Job", group: "batch", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.file-jobs.enabled", expectedOperationIds: ["admFileJobList", "admFileJobDetail", "admFileJobRows", "admFileJobUpload", "admFileJobApply", "admFileJobRetry", "admFileJobCancel", "admFileJobRollback", "admFileJobResolveUnknown", "admFileJobArtifact"], component: defineAsyncComponent(() => import("../features/file-jobs/FileJobsPage.vue")), props: undefined },
  "messages": { routeId: "messages", path: "/messages", menuId: "MESSAGE", label: "전문·Protocol Message", group: "integration", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.messages.enabled", expectedOperationIds: ["admMessageFindMessages", "admMessageFindMessage", "admMessageCreateMessage", "admMessageUpdateMessage", "admMessageDeleteMessage", "traceAdmByTransactionId"], component: defineAsyncComponent(() => import("../features/operations/ProtocolMessageWorkbenchPage.vue")), props: undefined },
  "codes": { routeId: "codes", path: "/codes", menuId: "CODE", label: "코드", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.codes.enabled", expectedOperationIds: ["admCodeFindCodes", "admCodeFindCode", "admCodeCreateCode", "admCodeUpdateCode", "admCodeDeleteCode"], component: defineAsyncComponent(() => import("../features/codes/CodesPage.vue")), props: undefined },
  "gateway-dashboard": { routeId: "gateway-dashboard", path: "/gateway-dashboard", menuId: "GATEWAY_DASHBOARD", label: "Gateway 대시보드", group: "online", icon: "dashboard", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-dashboard.enabled", expectedOperationIds: ["admGatewayCapability", "admGatewayOperationsSnapshot", "admGatewayOperationsEvents", "admGatewayOperationsStream"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "dashboard" } },
  "gateway-servers": { routeId: "gateway-servers", path: "/gateway-servers", menuId: "GATEWAY_SERVERS", label: "Gateway 연동 서버", group: "online", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-servers.enabled", expectedOperationIds: ["admGatewayFindServerGroups", "admGatewayFindGroupMembers", "admGatewaySaveServerGroup", "admGatewayDeleteServerGroup"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "servers" } },
  "gateway-groups": { routeId: "gateway-groups", path: "/gateway-groups", menuId: "GATEWAY_GROUPS", label: "Gateway 서버 그룹", group: "online", icon: "topology", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-groups.enabled", expectedOperationIds: ["admGatewayFindServerGroups", "admGatewayFindGroupMembers", "admGatewaySaveServerGroup", "admGatewayDeleteServerGroup"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "groups" } },
  "gateway-routes": { routeId: "gateway-routes", path: "/gateway-routes", menuId: "GATEWAY_ROUTES", label: "Gateway 경로·라우팅", group: "online", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-routes.enabled", expectedOperationIds: ["admGatewayFindBindings", "admGatewaySaveBinding", "admGatewayChangeBindingState", "admGatewayDeleteBinding"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "bindings" } },
  "gateway-security": { routeId: "gateway-security", path: "/gateway-security", menuId: "GATEWAY_SECURITY", label: "Gateway 보안·제한", group: "online", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.gateway-security.enabled", expectedOperationIds: ["admGatewayFindBindings", "admGatewaySaveBinding", "admGatewayChangeBindingState"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "security" } },
  "gateway-health": { routeId: "gateway-health", path: "/gateway-health", menuId: "GATEWAY_HEALTH", label: "Gateway Health·연결시험", group: "online", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-health.enabled", expectedOperationIds: ["admGatewayCapability", "admGatewayFindApplyStatus", "admGatewayFindConnectionTests", "admGatewayRequestConnectionTest", "admGatewayFindConnectionTestOperation", "admGatewayCancelConnectionTest", "admGatewayRevalidateConnectionTest"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "health" } },
  "gateway-transactions": { routeId: "gateway-transactions", path: "/gateway-transactions", menuId: "GATEWAY_TRANSACTIONS", label: "Gateway 거래 조회", group: "online", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-transactions.enabled", expectedOperationIds: ["admGatewayOperationsSnapshot", "admGatewayOperationsEvents", "traceAdmByTransactionId"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "transactions" } },
  "gateway-log-policies": { routeId: "gateway-log-policies", path: "/gateway-log-policies", menuId: "GATEWAY_LOG_POLICY", label: "Gateway 로그 정책", group: "online", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-log-policies.enabled", expectedOperationIds: ["admGatewayOperationsSnapshot", "admLogPolicyFindPolicies", "admLogPolicyDistributionStatus"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "log-policies" } },
  "gateway-apply-status": { routeId: "gateway-apply-status", path: "/gateway-apply-status", menuId: "GATEWAY_APPLY_STATUS", label: "Gateway 적용 상태·이력", group: "online", icon: "approval", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-apply-status.enabled", expectedOperationIds: ["admGatewayFindApplyStatus", "admGatewayOperationsEvents", "admGatewayFindConnectionTestOperation"], component: defineAsyncComponent(() => import("../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "apply" } },
  "permissions": { routeId: "permissions", path: "/permissions", menuId: "PERMISSION", label: "권한", group: "framework", icon: "role", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.permissions.enabled", expectedOperationIds: ["admPermissionFindManagedMenus", "admPermissionFindButtons", "admPermissionFindApiPermissions", "admPermissionFindRoles", "admPermissionFindMenuMatrix", "admPermissionFindButtonMatrix", "admPermissionFindApiPermissionMatrix", "admPermissionFindApiPermission", "admPermissionUpdateApiPermissionStatus", "admPermissionFindButton", "admPermissionUpdateButtonStatus", "admPermissionFindManagedMenu", "admPermissionUpdateMenuStatus", "admPermissionFindRole", "admPermissionUpdateRoleStatus", "admPermissionCreateApiPermission", "admPermissionUpdateApiPermission", "admPermissionCreateButton", "admPermissionUpdateButton", "admPermissionCreateMenu", "admPermissionUpdateMenu", "admPermissionCreateRole", "admPermissionUpdateRole", "admPermissionUpdateRoleApiPermission", "admPermissionUpdateButtonPermission", "admPermissionUpdateMenuPermission"], component: defineAsyncComponent(() => import("../features/permissions/PermissionsPage.vue")), props: undefined },
  "password": { routeId: "password", path: "/password", menuId: "PASSWORD", label: "비밀번호", group: "framework", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.password.enabled", expectedOperationIds: ["admOperatorPasswordPolicy", "admOperatorValidatePassword", "admOperatorChangePassword", "admOperatorResetPassword", "admOperatorRevokeSession"], component: defineAsyncComponent(() => import("../features/password/PasswordPage.vue")), props: undefined },
  "security": { routeId: "security", path: "/security", menuId: "SECURITY", label: "보안", group: "framework", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.security.enabled", expectedOperationIds: ["admSecurityFindMfaStates", "admSecurityRegisterMfa", "admSecurityVerifyMfa", "admSecurityDisableMfa", "admSecurityFindIpAllowlist", "admSecuritySaveIpAllowlist"], component: defineAsyncComponent(() => import("../features/security/SecurityPage.vue")), props: undefined },
  "operators": { routeId: "operators", path: "/operators", menuId: "OPERATOR", label: "운영자", group: "framework", icon: "users", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.operators.enabled", expectedOperationIds: ["admOperatorFindOperators", "admOperatorFindRoles", "admOperatorFindSessions", "admOperatorCreateOperator", "admOperatorUpdateRoles", "admOperatorUpdateStatus", "admOperatorUnlockOperator", "admOperatorUpdateContact", "admOperatorFindMenus", "admOperatorFindCreateResult", "admOperatorCleanupExpiredSessions", "admOperatorRawContact"], component: defineAsyncComponent(() => import("../features/operators/OperatorsPage.vue")), props: undefined },
  "secrets": { routeId: "secrets", path: "/secrets", menuId: "SECRET", label: "Secret / Key", group: "framework", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.secrets.enabled", expectedOperationIds: ["admSecretFindMetadata", "admSecretFindProviders", "admSecretRotate"], component: defineAsyncComponent(() => import("../features/secrets/SecretsPage.vue")), props: undefined },
  "approvals": { routeId: "approvals", path: "/approvals", menuId: "APPROVAL", label: "위험조치 승인", group: "framework", icon: "approval", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.approvals.enabled", expectedOperationIds: ["admApprovalPolicies", "admApprovalPolicyDetail", "admApprovalPolicySave", "admApprovalRequest", "admApprovalRequestDetail", "admApprovalDecision", "admApprovalExecute", "admApprovalReconcile", "admRuntimeControlFindChange", "admRuntimeControlFindByOperation", "admBreakGlassFindSessions", "admBreakGlassReviewSession"], component: defineAsyncComponent(() => import("../features/approvals/ApprovalsPage.vue")), props: undefined },
  "breakGlass": { routeId: "breakGlass", path: "/breakGlass", menuId: "BREAK_GLASS", label: "Break-glass", group: "framework", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.breakGlass.enabled", expectedOperationIds: ["admBreakGlassFindSessions", "admBreakGlassOpenSession", "admBreakGlassReviewSession", "admBreakGlassCloseSession"], component: defineAsyncComponent(() => import("../features/break-glass/BreakGlassPage.vue")), props: undefined },
  "featureFlags": { routeId: "featureFlags", path: "/featureFlags", menuId: "FEATURE_FLAG", label: "Feature Flag", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.featureFlags.enabled", expectedOperationIds: ["admFeatureFlagSearch", "admFeatureFlagFind", "admFeatureFlagEvaluate", "admFeatureFlagRequestOverride", "admFeatureFlagApproveOverride", "admFeatureFlagRevokeOverride", "admFeatureFlagSetKillSwitch"], component: defineAsyncComponent(() => import("../features/feature-flags/FeatureFlagsPage.vue")), props: undefined },
  "integrationClosure": { routeId: "integrationClosure", path: "/integrationClosure", menuId: "INTEGRATION_CLOSURE", label: "통합 운영 정정 승인", group: "integration", icon: "approval", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.integrationClosure.enabled", expectedOperationIds: ["admIntegrationCryptoStatus", "admIntegrationTimeHealth", "admIntegrationDataQualityValidate", "admIntegrationDataQualityCorrectionApprovalRequest", "admIntegrationDataQualityCorrectionExecute", "admIntegrationDataQualityReplay", "admIntegrationWebhookDlq", "admIntegrationWebhookReplay"], component: defineAsyncComponent(() => import("../features/integration-closure/IntegrationClosurePage.vue")), props: undefined },
  "openApiOperations": { routeId: "openApiOperations", path: "/openApiOperations", menuId: "OPENAPI_OPERATIONS", label: "OpenAPI 운영", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.openApiOperations.enabled", expectedOperationIds: ["admOpenApiStatus", "admOpenApiRefresh"], component: defineAsyncComponent(() => import("../features/openapi-operations/OpenApiOperationsPage.vue")), props: undefined },
  "resiliencePolicies": { routeId: "resiliencePolicies", path: "/resiliencePolicies", menuId: "RESILIENCE_POLICY", label: "Resilience 정책", group: "framework", icon: "settings", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.resiliencePolicies.enabled", expectedOperationIds: ["admResiliencePolicySearch", "admResiliencePolicyFind", "admResiliencePolicyRequest", "admResiliencePolicyApprove", "admResiliencePolicyReject"], component: defineAsyncComponent(() => import("../features/resilience-policies/ResiliencePoliciesPage.vue")), props: undefined },
};

// Backward-compatible export name. The registry is now the single route/menu/component capability source.
export const admFeatureRoutes = admCapabilityRegistry;

export function findCapabilityByRouteName(name: unknown): AdmCapabilityRoute | undefined {
  return typeof name === "string" ? admCapabilityRegistry[name] : undefined;
}

export function findCapabilityByPath(path: string): AdmCapabilityRoute | undefined {
  return Object.values(admCapabilityRegistry).find(route => route.path === path);
}

export function featureGroupForMenu(routeId: string): AdmFeatureGroup | undefined {
  return admCapabilityRegistry[routeId]?.group;
}

export function componentForMenu(routeId: string): Component | undefined {
  return admCapabilityRegistry[routeId]?.component;
}

export function iconForMenu(routeId: string): string {
  return admCapabilityRegistry[routeId]?.icon ?? "logs";
}

export const admRouterRecords: RouteRecordRaw[] = Object.values(admCapabilityRegistry).map(route => ({
  path: route.path,
  name: route.routeId,
  component: route.component,
  props: route.props,
  meta: {
    routeId: route.routeId,
    menuId: route.menuId,
    group: route.group,
    ownerModule: route.ownerModule,
    riskLevel: route.riskLevel,
    featureFlag: route.featureFlag,
    expectedOperationIds: route.expectedOperationIds
  }
}));

export function menuIdFromRouteName(name: unknown): string | undefined {
  return findCapabilityByRouteName(name)?.menuId;
}
