const assert=require('node:assert/strict');
const path=require('node:path');
const root=process.argv[2];
function req(rel){return require(path.join(root,rel));}
const bg=req('cpf-admin/frontend/src/features/break-glass/breakGlassWorkflow.js');
const mt=req('cpf-admin/frontend/src/features/maintenance/maintenanceWorkflow.js');
const employee=req('cpf-biz-frontend/src/features/employees/model/employeeModel.js');
const approval=req('cpf-biz-frontend/src/features/approvals/model/approvalModel.js');
let checks=0; const eq=(a,b,msg)=>{checks++;assert.deepEqual(a,b,msg)}; const throws=(fn,re,msg)=>{checks++;assert.throws(fn,re,msg)};
eq(bg.validateBreakGlassRequest(' MBR-01 ','긴급 장애 복구',15),{scopeValue:'MBR-01',reason:'긴급 장애 복구',ttlMinutes:15},'break-glass normalized');
throws(()=>bg.validateBreakGlassRequest('','긴급 장애 복구',15),/대상/,'break-glass target');
eq(mt.validateMaintenanceAction({serviceId:' MBR ',endpointCode:' API ',instanceId:' I-1 ',action:'DRAIN',reason:' 장애 대응 점검 '}),{serviceId:'MBR',endpointCode:'API',instanceId:'I-1',action:'DRAIN',reason:'장애 대응 점검'},'maintenance normalized');
throws(()=>mt.validateMaintenanceAction({serviceId:'MBR',endpointCode:'API',instanceId:'I-1',action:'DRAIN',reason:'짧음'}),/8자/,'maintenance reason');
const saved=employee.validateEmployeeSavePayload({employeeNo:' E-1 ',employeeName:' 홍길동 ',useYn:'Y',reason:' 업무상 정보 변경 ',clearEmail:false,clearMobileNo:false,clearOfficePhoneNo:false});
eq(saved.employeeNo,'E-1','employee id normalized');eq(saved.reason,'업무상 정보 변경','employee reason normalized');
throws(()=>employee.validateEmployeeSavePayload({employeeNo:'',employeeName:'홍길동',useYn:'Y',reason:'업무상 정보 변경',clearEmail:false,clearMobileNo:false,clearOfficePhoneNo:false}),/직원번호/,'employee id required');
const decided=approval.validateApprovalDecision({action:' approve ',reason:' 정상 승인 처리 ',comment:' 확인 '});
eq(decided.action,'APPROVE','approval normalized');eq(decided.comment,'확인','approval comment normalized');
throws(()=>approval.validateApprovalDecision({action:'APPROVE',reason:'짧음'}),/5자/,'approval reason');
console.log(`CPF_FRONTEND_WORKFLOW_RUNTIME_PASS checks=${checks}`);
