const assert=require('node:assert/strict');
const path=require('node:path');
const root=process.argv[2];
function req(rel){return require(path.join(root,rel));}
const bg=req('cpf-admin/frontend/src/features/break-glass/breakGlassWorkflow.js');
const at=req('cpf-biz-admin/frontend/src/features/attachments/attachmentWorkflow.js');
const se=req('cpf-biz-admin/frontend/src/features/sessions/sessionWorkflow.js');
const dg=req('cpf-biz-admin/frontend/src/components/dangerousOperationWorkflow.js');
const mt=req('cpf-admin/frontend/src/features/maintenance/maintenanceWorkflow.js');
let checks=0; const ok=(cond,msg)=>{checks++;assert.ok(cond,msg)}; const eq=(a,b,msg)=>{checks++;assert.deepEqual(a,b,msg)}; const throws=(fn,re,msg)=>{checks++;assert.throws(fn,re,msg)};
eq(bg.validateBreakGlassRequest(' MBR-01 ','긴급 장애 복구',15),{scopeValue:'MBR-01',reason:'긴급 장애 복구',ttlMinutes:15},'break-glass normalized');
throws(()=>bg.validateBreakGlassRequest('','긴급 장애 복구',15),/대상/,'break-glass target');
throws(()=>bg.validateBreakGlassRequest('A','긴급 장애 복구',0),/1분 이상/,'break-glass ttl lower');
throws(()=>bg.validateBreakGlassRequest('A','긴급 장애 복구',31),/30분 이하/,'break-glass ttl upper');
eq(at.requireAuditReason('  업무상 재검사 요청  '),'업무상 재검사 요청','attachment reason');
throws(()=>at.requireAuditReason('짧음'),/5자 이상/,'attachment short reason');
eq(at.safeAttachmentFilename('../../secret?.txt','ATT-1'),'.._.._secret_.txt','filename sanitization');
eq(at.filenameFromContentDisposition("attachment; filename*=UTF-8''%ED%95%9C%EA%B8%80.txt",'fallback'),'한글.txt','rfc5987');
eq(se.requireSessionId(' S-1 '),'S-1','session id');
throws(()=>se.requireSessionId(''),/식별자/,'session id missing');
eq(se.requireSessionRevokeReason('  계정 탈취 의심 세션 폐기  '),'계정 탈취 의심 세션 폐기','session reason');
throws(()=>se.requireSessionRevokeReason('짧음'),/5자 이상/,'session short reason');
eq(dg.validatePathValues(['sessionId','tenantId'],{sessionId:' S-1 ',tenantId:' T-1 '}),{sessionId:'S-1',tenantId:'T-1'},'path values');
throws(()=>dg.validatePathValues(['sessionId'],{}),/sessionId/,'path missing');
eq(dg.attachDangerousReason({}, {}, '운영 장애 긴급 복구').body.reason,'운영 장애 긴급 복구','reason injected');
ok(dg.attachDangerousReason({reason:'query'}, {}, '운영 장애 긴급 복구').body.reason===undefined,'query reason retained');
eq(dg.attachDangerousReason({}, {reason:'body'}, '운영 장애 긴급 복구').body.reason,'body','body reason retained');
eq(mt.validateMaintenanceAction({serviceId:' MBR ',endpointCode:' API ',instanceId:' I-1 ',action:'DRAIN',reason:' 장애 대응 점검 '}),{serviceId:'MBR',endpointCode:'API',instanceId:'I-1',action:'DRAIN',reason:'장애 대응 점검'},'maintenance normalized');
throws(()=>mt.validateMaintenanceAction({serviceId:'MBR',endpointCode:'API',instanceId:'I-1',action:'DRAIN',reason:'짧음'}),/5자/,'maintenance reason');
console.log(`CPF_FRONTEND_WORKFLOW_RUNTIME_PASS checks=${checks}`);
