<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from "vue";
import { bzaApi,hasBzaPermission } from "../features/auth/session";
export interface CrudField{name:string;label:string;type?:string;sourceName?:string;required?:boolean;readonlyOnEdit?:boolean;}
interface Page<T>{content:T[];totalElements:number;page:number;size:number;}
const props=withDefaults(defineProps<{title:string;endpoint:string;writeEndpoint?:string;menuCode:string;columns:string[];fields:CrudField[];paged?:boolean;pageSize?:number;}>(),{paged:true,pageSize:20});
const rows=ref<Record<string,unknown>[]>([]),loading=ref(false),dialogOpen=ref(false),message=ref(""),error=ref("");
const page=ref(0),size=ref(props.pageSize),total=ref(0),editing=ref(false);const form=reactive<Record<string,any>>({});const writable=computed(()=>hasBzaPermission(props.menuCode,"WRITE"));
const totalPages=computed(()=>total.value===0?0:Math.ceil(total.value/size.value));
async function load(){loading.value=true;error.value="";try{if(props.paged){const sep=props.endpoint.includes("?")?"&":"?";const url=`${props.endpoint.replace(/\/$/,"")}/page${sep}page=${page.value}&size=${size.value}`;const result=await bzaApi<Page<Record<string,unknown>>>(url);rows.value=result.content||[];total.value=Number(result.totalElements||0);}else{rows.value=await bzaApi<Record<string,unknown>[]>(props.endpoint);total.value=rows.value.length;}}catch(e){error.value=e instanceof Error?e.message:String(e);rows.value=[];}finally{loading.value=false;}}
function open(item:Record<string,unknown>={}){for(const k of Object.keys(form))delete form[k];editing.value=Object.keys(item).length>0;for(const f of props.fields)form[f.name]=item[f.sourceName||f.name]??(f.type==="yn"?"Y":"");for(const id of ["permissionId","assignmentId","responsibilityId","userRoleId"])if(item[id]!=null)form[id]=item[id];if(item.versionNo!=null)form.expectedVersion=item.versionNo;form.reason="업무 기준정보 변경";message.value="";dialogOpen.value=true;}
async function save(){const payload:Record<string,unknown>={...form};for(const f of props.fields){if(f.type==="number"&&payload[f.name]!=="")payload[f.name]=Number(payload[f.name]);if(f.type==="password"&&payload[f.name]==="")delete payload[f.name];}if("operationId" in payload && !payload.operationId)payload.operationId=crypto.randomUUID();try{await bzaApi(props.writeEndpoint||props.endpoint,{method:"POST",body:JSON.stringify(payload)});dialogOpen.value=false;await load();}catch(e){message.value=e instanceof Error?e.message:String(e);}}
function prev(){if(page.value>0){page.value--;load();}}function next(){if((page.value+1)*size.value<total.value){page.value++;load();}}
onMounted(load);watch(()=>props.endpoint,()=>{page.value=0;load();});
</script>
<template><section class="card table-card"><div class="card-head"><div><p class="eyebrow">MANAGEMENT</p><h2>{{title}}</h2></div><div class="inline-actions"><span class="count-pill">{{total}}건</span><button v-if="writable" class="primary" type="button" @click="open()">등록</button></div></div><p v-if="error" class="error-banner">{{error}}</p><div v-if="loading" class="empty-state">조회 중...</div><div v-else class="table-wrap"><table><thead><tr><th v-for="c in columns" :key="c">{{c}}</th><th v-if="writable">관리</th></tr></thead><tbody><tr v-for="(row,index) in rows" :key="String(row.id||row.permissionId||row.assignmentId||row.organizationCode||row.employeeNo||index)"><td v-for="c in columns" :key="c">{{row[c]??"-"}}</td><td v-if="writable"><button type="button" class="ghost" @click="open(row)">수정</button></td></tr><tr v-if="rows.length===0"><td :colspan="columns.length+(writable?1:0)" class="empty-cell">조회 결과가 없습니다.</td></tr></tbody></table></div><div v-if="paged" class="pager"><button class="ghost" :disabled="page===0" @click="prev">이전</button><span>{{page+1}} / {{Math.max(totalPages,1)}}</span><button class="ghost" :disabled="(page+1)*size>=total" @click="next">다음</button></div>
<dialog :open="dialogOpen" class="modal"><form class="modal-card" @submit.prevent="save"><div class="card-head"><div><p class="eyebrow">EDIT</p><h2>{{title}} 등록·수정</h2></div><button type="button" class="icon-button" @click="dialogOpen=false">×</button></div><div class="form-grid"><label v-for="f in fields" :key="f.name" :class="{wide:f.type==='textarea'}"><span>{{f.label}}</span><textarea v-if="f.type==='textarea'" v-model="form[f.name]" rows="4" :required="f.required"></textarea><select v-else-if="f.type==='yn'" v-model="form[f.name]" :disabled="editing&&f.readonlyOnEdit"><option value="Y">Y</option><option value="N">N</option></select><input v-else v-model="form[f.name]" :type="f.type||'text'" :required="f.required" :readonly="editing&&f.readonlyOnEdit"></label><label class="wide"><span>감사 사유</span><textarea v-model="form.reason" rows="3" required></textarea></label></div><p v-if="message" class="error-banner">{{message}}</p><div class="dialog-actions"><button type="button" class="ghost" @click="dialogOpen=false">취소</button><button type="submit" class="primary">저장</button></div></form></dialog></section></template>
