<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import CpfIcon from "../../components/CpfIcon.vue";
import { bzaApprovalCancel, bzaApprovalWithdraw } from "../../generated/cpf-api";
import { bzaApi } from "../auth/session";
type Row=Record<string,any>;
type LifecycleAction = "WITHDRAW" | "CANCEL";
const rows=ref<Row[]>([]),result=ref<any>(null),error=ref(""),busy=ref(false),lifecycleOpen=ref(false),selected=ref<Row|null>(null),lifecycleAction=ref<LifecycleAction>("WITHDRAW"),lifecycleReason=ref("");
const form=reactive({policyCode:"",policyVersion:"",businessDomain:"BZA",approvalType:"GENERAL",requesterEmployeeNo:"",title:"",approvalMode:"SEQUENTIAL",dueAt:"",payloadJson:"{}",attachmentGroupId:"",requestIdempotencyKey:"",reason:"업무 결재 상신"});
const active=computed(()=>rows.value.filter(r=>r.approvalStatus==='IN_REVIEW').length),terminal=computed(()=>rows.value.filter(r=>['REJECTED','WITHDRAWN','CANCELED','EXPIRED'].includes(String(r.approvalStatus))).length);
async function load(){try{rows.value=await bzaApi('/api/bza/approvals/submissions?limit=100')}catch(e){error.value=e instanceof Error?e.message:String(e)}}
async function submit(resubmitFrom?:number){busy.value=true;error.value='';try{if(!form.requestIdempotencyKey)form.requestIdempotencyKey=crypto.randomUUID();const body={...form,policyVersion:form.policyVersion?Number(form.policyVersion):null,dueAt:form.dueAt||null,attachmentGroupId:form.attachmentGroupId||null};result.value=await bzaApi(resubmitFrom?`/api/bza/approvals/submissions/${resubmitFrom}/resubmit`:'/api/bza/approvals/submissions',{method:'POST',body:JSON.stringify(body)});form.requestIdempotencyKey='';await load()}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
function openLifecycle(row:Row,action:LifecycleAction){selected.value=row;lifecycleAction.value=action;lifecycleReason.value='';lifecycleOpen.value=true}
async function lifecycle(){if(!selected.value||!lifecycleReason.value.trim())return;try{const options={path:{approvalId:String(selected.value.approvalId)},data:{idempotencyKey:crypto.randomUUID(),reason:lifecycleReason.value,comment:lifecycleReason.value}};if(lifecycleAction.value==='WITHDRAW')await bzaApprovalWithdraw(options);else await bzaApprovalCancel(options);lifecycleOpen.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:String(e)}}
async function prepareResubmit(row:Row){try{const d:any=await bzaApi(`/api/bza/approvals/submissions/${row.approvalId}`);form.policyCode=d.policyCode||'';form.policyVersion=String(d.policyVersion||'');form.businessDomain=d.businessDomain||'BZA';form.approvalType=d.approvalType||'GENERAL';form.requesterEmployeeNo=d.requesterEmployeeNo||'';form.title=`[재상신] ${d.title||''}`;form.approvalMode=d.approvalMode||'SEQUENTIAL';form.dueAt='';form.payloadJson=d.payloadJson||'{}';form.attachmentGroupId=d.attachmentGroupId||'';form.requestIdempotencyKey=crypto.randomUUID();form.reason='반려/철회/만료 후 재상신';result.value={resubmitFrom:row.approvalId};window.scrollTo({top:0,behavior:'smooth'});}catch(e){error.value=e instanceof Error?e.message:String(e)}}
async function doResubmit(){const id=result.value?.resubmitFrom;if(!id)return;await submit(Number(id));result.value=null}
onMounted(load);
</script>
<template><div class="page-stack">
<div class="cpf-page-heading"><div><p class="eyebrow">APPROVAL SUBMISSION</p><h2>내 상신·Lifecycle</h2><p>정책 Snapshot을 기준으로 상신하고 진행 중 철회·취소, 종료 문서 재상신을 감사 가능하게 처리합니다.</p></div><button class="ghost" @click="load"><CpfIcon name="refresh"/> 새로고침</button></div>
<section class="cpf-stat-grid"><article class="cpf-stat-card"><span>전체</span><strong>{{rows.length}}</strong><small>최근 100건</small></article><article class="cpf-stat-card"><span>진행 중</span><strong>{{active}}</strong><small>IN_REVIEW</small></article><article class="cpf-stat-card"><span>재상신 가능</span><strong>{{terminal}}</strong><small>반려·철회·취소·만료</small></article></section>
<section class="card"><div class="card-head"><div><p class="eyebrow">IMMUTABLE SNAPSHOT</p><h2>{{result?.resubmitFrom?'새 Snapshot 재상신':'정책 기반 상신'}}</h2></div><span v-if="result?.resubmitFrom" class="cpf-status warning">원본 #{{result.resubmitFrom}}</span></div><form class="form-grid" @submit.prevent="result?.resubmitFrom?doResubmit():submit()"><label><span>정책 코드(선택)</span><input v-model="form.policyCode"></label><label><span>버전</span><input v-model="form.policyVersion" type="number"></label><label><span>업무 영역</span><input v-model="form.businessDomain"></label><label><span>결재 유형</span><input v-model="form.approvalType"></label><label><span>요청 직원</span><input v-model="form.requesterEmployeeNo" required></label><label><span>제목</span><input v-model="form.title" required></label><label><span>방식</span><select v-model="form.approvalMode"><option>SEQUENTIAL</option><option>PARALLEL</option></select></label><label><span>기한</span><input v-model="form.dueAt" type="datetime-local"></label><label class="wide"><span>Payload JSON</span><textarea v-model="form.payloadJson" rows="5" required></textarea></label><label><span>멱등 Key</span><input v-model="form.requestIdempotencyKey" placeholder="미입력 시 UUID 생성"></label><label class="wide"><span>사유</span><textarea v-model="form.reason" required></textarea></label><div class="form-action"><button class="primary" :disabled="busy">{{result?.resubmitFrom?'재상신':'상신'}}</button><button v-if="result?.resubmitFrom" type="button" class="ghost" @click="result=null">재상신 취소</button></div></form><p v-if="error" class="error-banner">{{error}}</p></section>
<section class="card table-card"><div class="card-head"><div><h2>상신 문서</h2><p>진행 중 문서는 요청자 본인만 철회/취소할 수 있습니다.</p></div></div><div class="table-wrap"><table><thead><tr><th>문서</th><th>유형</th><th>제목</th><th>요청자</th><th>상태</th><th>Step</th><th>조치</th></tr></thead><tbody><tr v-for="row in rows" :key="String(row.approvalId)"><td><strong>{{row.approvalNo}}</strong><small v-if="row.resubmittedFromApprovalId" class="block">← #{{row.resubmittedFromApprovalId}}</small></td><td>{{row.approvalType}}</td><td>{{row.title}}</td><td>{{row.requesterEmployeeNo}}</td><td><span class="cpf-status" :class="row.approvalStatus==='IN_REVIEW'?'warning':row.approvalStatus==='APPROVED'?'success':'danger'">{{row.approvalStatus}}</span></td><td>{{row.currentStepNo}}</td><td><div class="cpf-toolbar"><template v-if="row.approvalStatus==='IN_REVIEW'"><button class="ghost small" @click="openLifecycle(row,'WITHDRAW')">철회</button><button class="danger small" @click="openLifecycle(row,'CANCEL')">취소</button></template><button v-if="['REJECTED','WITHDRAWN','CANCELED','EXPIRED'].includes(String(row.approvalStatus))" class="primary small" @click="prepareResubmit(row)">재상신</button></div></td></tr></tbody></table></div></section>
<dialog :open="lifecycleOpen" class="modal"><form class="modal-card" @submit.prevent="lifecycle"><div class="card-head"><div><p class="eyebrow">{{lifecycleAction}}</p><h2>{{selected?.title}}</h2></div><button type="button" class="icon-button" @click="lifecycleOpen=false">×</button></div><label class="dialog-field">처리 사유<textarea v-model="lifecycleReason" rows="4" required></textarea></label><div class="dialog-actions"><button type="button" class="ghost" @click="lifecycleOpen=false">닫기</button><button class="danger">{{lifecycleAction==='WITHDRAW'?'철회 확정':'취소 확정'}}</button></div></form></dialog>
</div></template>
