<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { bzaApi } from "../auth/session";
const rows=ref<Record<string,unknown>[]>([]);const result=ref<unknown>(null);const error=ref("");
const form=reactive({policyCode:"",policyVersion:"",businessDomain:"BZA",approvalType:"GENERAL",requesterEmployeeNo:"",title:"",approvalMode:"SEQUENTIAL",dueAt:"",payloadJson:"{}",attachmentGroupId:"",requestIdempotencyKey:"",reason:"업무 결재 상신"});
async function load(){try{rows.value=await bzaApi("/api/bza/backoffice/approvals?limit=100");}catch(e){error.value=e instanceof Error?e.message:String(e);}}
async function submit(){try{if(!form.requestIdempotencyKey)form.requestIdempotencyKey=crypto.randomUUID();result.value=await bzaApi("/api/bza/approval/submissions",{method:"POST",body:JSON.stringify({...form,policyVersion:form.policyVersion?Number(form.policyVersion):null,dueAt:form.dueAt||null,attachmentGroupId:form.attachmentGroupId||null})});await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}}
onMounted(load);
</script>
<template><div class="page-stack"><section class="card"><div class="card-head"><div><p class="eyebrow">SNAPSHOT SUBMISSION</p><h2>정책 기반 상신</h2></div></div><form class="form-grid" @submit.prevent="submit"><label><span>정책 코드(선택)</span><input v-model="form.policyCode"></label><label><span>버전</span><input v-model="form.policyVersion" type="number"></label><label><span>업무 영역</span><input v-model="form.businessDomain"></label><label><span>결재 유형</span><input v-model="form.approvalType"></label><label><span>요청 직원</span><input v-model="form.requesterEmployeeNo" required></label><label><span>제목</span><input v-model="form.title" required></label><label><span>방식</span><select v-model="form.approvalMode"><option>SEQUENTIAL</option><option>PARALLEL</option></select></label><label><span>기한</span><input v-model="form.dueAt"></label><label class="wide"><span>Payload JSON</span><textarea v-model="form.payloadJson" rows="5" required></textarea></label><label><span>멱등 Key</span><input v-model="form.requestIdempotencyKey" placeholder="미입력 시 UUID 생성"></label><label class="wide"><span>사유</span><textarea v-model="form.reason" required></textarea></label><div class="form-action"><button class="primary">상신</button></div></form><p v-if="error" class="error-banner">{{error}}</p><pre v-if="result" class="json-block">{{JSON.stringify(result,null,2)}}</pre></section><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>approvalNo</th><th>type</th><th>title</th><th>requester</th><th>status</th><th>step</th></tr></thead><tbody><tr v-for="row in rows" :key="String(row.approvalId)"><td>{{row.approvalNo}}</td><td>{{row.approvalType}}</td><td>{{row.title}}</td><td>{{row.requesterEmployeeNo}}</td><td>{{row.approvalStatus}}</td><td>{{row.currentStepNo}}</td></tr></tbody></table></div></section></div></template>
