package com.cpf.integration.webhook;
import com.cpf.integration.api.webhook.*;
import com.cpf.foundation.execution.CpfContextExecutionFactory;
import com.cpf.foundation.id.spi.CpfExecutionIdGenerator;
import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicLong;
/** Ordered, idempotent, signed callback lifecycle with retry, UNKNOWN, DLQ and reconcile. */
public final class InMemoryCpfWebhookOperations implements CpfWebhookOperations {
 private record Payload(byte[] body){} private final CpfWebhookEndpointValidator validator; private final Map<String,byte[]> secrets; private final Map<String,CpfWebhookEndpoint> endpoints=new ConcurrentHashMap<>(); private final Map<String,CpfWebhookDelivery> deliveries=new ConcurrentHashMap<>(); private final Map<String,Payload> payloads=new ConcurrentHashMap<>(); private final Map<String,Map<String,String>> contexts=new ConcurrentHashMap<>(); private final Map<String,String> idempotency=new ConcurrentHashMap<>(); private final AtomicLong sequence=new AtomicLong(); private final int maxAttempts; private final Duration baseDelay; private final CpfWebhookContextSupport contextSupport;
 public InMemoryCpfWebhookOperations(CpfWebhookEndpointValidator validator,Map<String,byte[]> secrets,int maxAttempts,Duration baseDelay,CpfWebhookContextSupport contextSupport){this.validator=Objects.requireNonNull(validator);Map<String,byte[]> s=new HashMap<>();secrets.forEach((k,v)->s.put(k,v.clone()));this.secrets=Map.copyOf(s);if(maxAttempts<1)throw new IllegalArgumentException("maxAttempts");this.maxAttempts=maxAttempts;this.baseDelay=baseDelay;this.contextSupport=Objects.requireNonNull(contextSupport);}
 public InMemoryCpfWebhookOperations(CpfWebhookEndpointValidator validator,Map<String,byte[]> secrets,int maxAttempts,Duration baseDelay){this(validator,secrets,maxAttempts,baseDelay,new CpfWebhookContextSupport(new CpfContextExecutionFactory(new CpfExecutionIdGenerator(){public String newExecutionId(){return "EX-"+UUID.randomUUID();}public String newSegmentId(){return "SG-"+UUID.randomUUID();}},Clock.systemUTC())));}
 @Override public CpfWebhookEndpoint register(CpfWebhookEndpoint endpoint,String actor,String reason){require(actor,"actor");require(reason,"reason");validator.validate(endpoint.uri());if(!secrets.containsKey(endpoint.secretVersion()))throw new IllegalArgumentException("unknown webhook secret version");endpoints.compute(endpoint.endpointId(),(id,old)->{if(old!=null&&endpoint.version()<=old.version())throw new ConcurrentModificationException("endpoint version must increase");return endpoint;});return endpoint;}
 @Override public synchronized CpfWebhookDelivery enqueue(String endpointId,String eventId,String eventType,byte[] payload,String key,Instant now){CpfWebhookEndpoint e=requireEndpoint(endpointId);if(!e.enabled()||!e.allowedEventTypes().contains(eventType))throw new SecurityException("event type not allowed");String idem=endpointId+":"+key;String existing=idempotency.get(idem);if(existing!=null)return Optional.ofNullable(deliveries.get(existing)).orElseThrow(()->new IllegalStateException("idempotency index is inconsistent"));String id="WH-"+UUID.randomUUID();CpfWebhookDelivery d=new CpfWebhookDelivery(id,endpointId,eventId,eventType,key,sequence.incrementAndGet(),CpfWebhookDelivery.State.PENDING,0,now,"",1);payloads.put(id,new Payload(payload.clone()));contexts.put(id,contextSupport.capture());deliveries.put(id,d);idempotency.put(idem,id);return d;}
 @Override public synchronized DeliveryAttempt deliverNext(String endpointId,Instant now,Transport transport){CpfWebhookDelivery d=deliveries.values().stream().filter(x->x.endpointId().equals(endpointId)&&(x.state()==CpfWebhookDelivery.State.PENDING||x.state()==CpfWebhookDelivery.State.RETRY||x.state()==CpfWebhookDelivery.State.UNKNOWN)&&!x.nextAttemptAt().isAfter(now)).min(Comparator.comparingLong(value -> value.sequence())).orElseThrow(()->new NoSuchElementException("no due delivery"));CpfWebhookEndpoint e=requireEndpoint(endpointId);byte[] body=payloads.get(d.deliveryId()).body();Map<String,String> headers=signedHeaders(e,d,body,now);TransportResult r;int attempts=d.attempts()+1;Map<String,String> captured=Optional.ofNullable(contexts.get(d.deliveryId())).orElseThrow(()->new IllegalStateException("WEBHOOK_CONTEXT_SNAPSHOT_MISSING"));try(AutoCloseable _=contextSupport.bind(captured,d.endpointId(),d.eventId(),attempts,d.state()==CpfWebhookDelivery.State.UNKNOWN)){r=transport.send(e,headers,body);}catch(Exception ex){r=new TransportResult(0,true,ex.getClass().getSimpleName()+":"+ex.getMessage());}CpfWebhookDelivery.State state;if(r.success())state=CpfWebhookDelivery.State.DELIVERED;else if(r.resultUnknown())state=CpfWebhookDelivery.State.UNKNOWN;else if(attempts>=maxAttempts)state=CpfWebhookDelivery.State.DLQ;else state=CpfWebhookDelivery.State.RETRY;Instant next=(state==CpfWebhookDelivery.State.RETRY||state==CpfWebhookDelivery.State.UNKNOWN)?now.plus(backoff(attempts)):now;CpfWebhookDelivery updated=new CpfWebhookDelivery(d.deliveryId(),d.endpointId(),d.eventId(),d.eventType(),d.idempotencyKey(),d.sequence(),state,attempts,next,r.error()==null?"":r.error(),d.version()+1);deliveries.put(d.deliveryId(),updated);return new DeliveryAttempt(updated,headers,r);}
 @Override public List<CpfWebhookDelivery> dlq(int limit){return deliveries.values().stream().filter(d->d.state()==CpfWebhookDelivery.State.DLQ).sorted(Comparator.comparingLong(value -> value.sequence())).limit(Math.max(0,limit)).toList();}
 @Override public CpfWebhookDelivery replay(String id,long expected,String actor,String reason,Instant now){require(actor,"actor");require(reason,"reason");return deliveries.compute(id,(k,d)->{if(d==null)throw new NoSuchElementException(id);if(d.version()!=expected)throw new ConcurrentModificationException("delivery version conflict");if(d.state()!=CpfWebhookDelivery.State.DLQ&&d.state()!=CpfWebhookDelivery.State.UNKNOWN)throw new IllegalStateException("only DLQ/UNKNOWN can be replayed");return new CpfWebhookDelivery(d.deliveryId(),d.endpointId(),d.eventId(),d.eventType(),d.idempotencyKey(),d.sequence(),CpfWebhookDelivery.State.RETRY,0,now,"",d.version()+1);});}
 @Override public ReconcileResult reconcile(Instant now,Transport transport){int inspected=0,delivered=0,retried=0,dlq=0,unknown=0;for(String endpoint:endpoints.keySet()){while(true){try{DeliveryAttempt a=deliverNext(endpoint,now,transport);inspected++;switch(a.delivery().state()){case DELIVERED->delivered++;case RETRY->retried++;case DLQ->dlq++;case UNKNOWN->unknown++;default->{}}}catch(NoSuchElementException done){break;}}}return new ReconcileResult(inspected,delivered,retried,dlq,unknown);}
 private Map<String,String> signedHeaders(CpfWebhookEndpoint e,CpfWebhookDelivery d,byte[] body,Instant now){String ts=Long.toString(now.getEpochSecond());String digest=hex(sha256(body));String canonical=d.deliveryId()+"."+d.eventId()+"."+ts+"."+digest;String sig=hmac(secrets.get(e.secretVersion()),canonical);return Map.of("X-CPF-Delivery-Id",d.deliveryId(),"X-CPF-Event-Id",d.eventId(),"X-CPF-Timestamp",ts,"X-CPF-Content-SHA256",digest,"X-CPF-Signature","v1="+sig,"Idempotency-Key",d.idempotencyKey());}
 private Duration backoff(int attempt){long multiplier=1L<<Math.min(20,Math.max(0,attempt-1));return baseDelay.multipliedBy(multiplier);} private CpfWebhookEndpoint requireEndpoint(String id){return Optional.ofNullable(endpoints.get(id)).orElseThrow(()->new NoSuchElementException(id));} private static byte[] sha256(byte[] b){try{return MessageDigest.getInstance("SHA-256").digest(b);}catch(Exception e){throw new IllegalStateException(e);}} private static String hmac(byte[] key,String value){try{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(key,"HmacSHA256"));return hex(m.doFinal(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private static String hex(byte[] b){return HexFormat.of().formatHex(b);} private static void require(String v,String n){if(v==null||v.isBlank())throw new IllegalArgumentException(n+" required");}
}
