plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-core')
api project(':cpf-integration-fixedlength-core')
implementation 'org.springframework.boot:spring-boot-autoconfigure'
}
tasks.named('test') { useJUnitPlatform() }
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'cpf-starter-integration-fixedlength'
        }
    }
}

