<template>
<section class="workbench" data-cpf-page="integrated-causal-timeline">
  <header class="header"><div><h1>Online·Batch 통합 Trace</h1><p>Online Transaction → Gateway/External → Batch Execution/Step → Incident → Approval → Audit를 동일 Context로 추적합니다.</p></div><button :disabled="loading" @click="search">{{ loading ? '조회 중…' : '조회' }}</button></header>
  <form class="filters" @submit.prevent="search"><label>식별자 유형<select v-model="kind"><option value="transaction">Transaction ID</option><option value="trace">Trace ID</option><option value="business">Business Transaction ID</option></select></label><label>식별자<input v-model.trim="identifier" required autocomplete="off"></label><label>최대 건수<select v-model.number="limit"><option :value="20">20</option><option :value="50">50</option><option :value="100">100</option><option :value="200">200</option></select></label><button class="primary" type="submit" :disabled="loading || !identifier">통합 조회</button></form>
  <p v-if="error" class="state error" role="alert">{{ error }}</p><p v-else-if="loading" class="state" role="status">Owner Runtime에서 인과 관계를 수집하고 있습니다.</p><p v-else-if="payload && timeline.length===0" class="state">연결된 Timeline Event가 없습니다.</p>
  <div v-if="payload" class="cards"><article class="card"><span>Transaction</span><strong>{{ identifier }}</strong><small>{{ kind }}</small></article><article class="card"><span>Timeline Event</span><strong>{{ timeline.length }}</strong><small>정렬된 인과 이벤트</small></article><article class="card"><span>Failure</span><strong>{{ failureCount }}</strong><small>실패·Incident·Unknown</small></article><article class="card"><span>Batch</span><strong>{{ batchCount }}</strong><small>Execution·Step 연결</small></article></div>
  <div v-if="timeline.length" class="table-wrap"><table><thead><tr><th>시각</th><th>유형</th><th>상태</th><th>Module/Service</th><th>Execution/Segment</th><th>요약</th></tr></thead><tbody><tr v-for="(event,index) in timeline" :key="index" @click="selected=event"><td>{{ text(event,'timestamp','createdAt','created_at','startedAt','started_at') }}</td><td><span class="badge">{{ text(event,'eventType') }}</span></td><td>{{ text(event,'status','result','state') }}</td><td>{{ text(event,'moduleCode','module_code','serviceId','service_id','target') }}</td><td>{{ text(event,'executionId','execution_id','segmentId','segment_id','traceId','trace_id') }}</td><td>{{ text(event,'message','summary','action','errorMessage','error_message') }}</td></tr></tbody></table></div>
  <article v-if="selected" class="panel"><div class="header"><h2>Event 상세</h2><button @click="selected=null">닫기</button></div><pre class="detail">{{ pretty(selected) }}</pre><div class="links"><RouterLink :to="{name:'batch-executions',query:{transactionId:identifier}}">Batch Execution</RouterLink><RouterLink :to="{name:'logs',query:{transactionId:identifier}}">통합 Log</RouterLink><RouterLink :to="{name:'auditLogs',query:{transactionId:identifier}}">Audit</RouterLink><RouterLink :to="{name:'incidents',query:{transactionId:identifier}}">Incident</RouterLink></div></article>
</section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { RouterLink, useRoute } from 'vue-router'; import { traceBusinessTransaction, traceByTraceId, traceTransaction, traceTransactionGroup, type JsonMap } from './api'; import { errorMessage, flattenTimeline, pretty, read, text } from './support';
const route=useRoute(); const kind=ref<'transaction'|'trace'|'business'>('transaction'); const identifier=ref(''); const limit=ref(100); const loading=ref(false); const error=ref(''); const payload=ref<JsonMap|null>(null); const selected=ref<JsonMap|null>(null); const timeline=computed(()=>flattenTimeline(payload.value)); const failureCount=computed(()=>timeline.value.filter(v=>/FAIL|ERROR|UNKNOWN|INCIDENT/i.test(String(read(v,'status','state','eventType')??''))).length); const batchCount=computed(()=>timeline.value.filter(v=>/batch|execution|step/i.test(String(read(v,'eventType','moduleCode','module_code')??''))).length);
async function search(){if(!identifier.value)return;loading.value=true;error.value='';payload.value=null;selected.value=null;try{if(kind.value==='trace')payload.value=await traceByTraceId(identifier.value,limit.value);else if(kind.value==='business')payload.value=await traceBusinessTransaction(identifier.value,limit.value);else{const [observability,groupTimeline]=await Promise.all([traceTransaction(identifier.value,limit.value),traceTransactionGroup(identifier.value)]);payload.value={...observability,transactionGroupTimeline:groupTimeline}}}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
onMounted(()=>{const q=route.query; identifier.value=String(q.transactionId??q.traceId??q.businessTransactionId??''); if(q.traceId)kind.value='trace';else if(q.businessTransactionId)kind.value='business'; if(identifier.value)void search()});
</script>
<style scoped>
.workbench{display:grid;gap:1rem}.header,.actions,.tabs,.pager{display:flex;gap:.65rem;align-items:center;justify-content:space-between;flex-wrap:wrap}.header h1,.header h2{margin:0}.header p{margin:.35rem 0 0;color:#52606d}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.7rem;align-items:end}.filters label,.dialog label{display:grid;gap:.3rem}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:.75rem}.card,.panel{border:1px solid #d7dde5;border-radius:.6rem;padding:1rem;background:#fff}.card strong{font-size:1.35rem;display:block}.table-wrap{overflow:auto;border:1px solid #d7dde5;border-radius:.5rem}table{border-collapse:collapse;width:100%;min-width:900px}th,td{padding:.65rem;border-bottom:1px solid #e4e8ed;text-align:left;vertical-align:top}tbody tr{cursor:pointer}tbody tr:hover,tbody tr.selected{background:#f3f6f9}.state{padding:.75rem;border-radius:.4rem;background:#eef3f7}.state.error{background:#fff0f0;color:#a51d1d}.state.warning{background:#fff8dc;color:#715600}.state.success{background:#edf9f0;color:#126b35}.danger{background:#9d1c1c;color:white}.primary{background:#1f5f99;color:white}.detail{white-space:pre-wrap;overflow:auto;max-height:480px;background:#111827;color:#e5e7eb;padding:1rem;border-radius:.5rem}.dialog-backdrop{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:1000}.dialog{width:min(620px,calc(100vw - 2rem));max-height:90vh;overflow:auto;background:#fff;border-radius:.65rem;padding:1.2rem;display:grid;gap:1rem}.dialog textarea{min-height:100px}.confirm{display:flex!important;grid-template-columns:auto 1fr!important;align-items:center}.muted{color:#68737d}.badge{display:inline-block;padding:.15rem .45rem;border-radius:999px;background:#e9eef5}.links{display:flex;gap:.6rem;flex-wrap:wrap}@media(max-width:720px){.header{display:grid}.actions{justify-content:flex-start}}
</style>