import { createApp } from "vue";
import { createPinia } from "pinia";
import { VueQueryPlugin } from "@tanstack/vue-query";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import App from "./App.vue";
import { bzaRouter } from "./app/router";
import { cpfQueryClient } from "./shared/queryClient";
import "./styles/bza.css";
import "./styles/cpf-design.css";
createApp(App).use(createPinia()).use(bzaRouter).use(VueQueryPlugin, { queryClient: cpfQueryClient }).use(ElementPlus).mount("#app");
