plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':framework:file')
    api project(':starters:common')
    api 'org.apache.poi:poi-ooxml:5.5.1'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
tasks.named('test') { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-starter-file-tabular-poi' } } }
