package com.cpf.starter.security.session.valkey;
import com.cpf.core.api.security.*; import java.time.*; import java.util.*; import org.springframework.data.redis.core.StringRedisTemplate;
public final class ValkeyCpfSessionOperations implements CpfSessionOperations {
 private final StringRedisTemplate redis; private final CpfValkeySessionProperties p; private final CpfSessionAuditSink audit;
 public ValkeyCpfSessionOperations(StringRedisTemplate r,CpfValkeySessionProperties p,CpfSessionAuditSink audit){this.redis=r;this.p=p;this.audit=audit;}
 private String key(String id){return p.getKeyPrefix()+id;} private String index(String t,String u){return p.getKeyPrefix()+"idx:"+t+":"+u;}
 public CpfSessionSnapshot create(String tenant,String principal,Duration ttl,Map<String,String> attrs){Objects.requireNonNull(tenant);Objects.requireNonNull(principal);String id=UUID.randomUUID().toString();Instant now=Instant.now(), exp=now.plus(ttl==null?p.getDefaultTtl():ttl); Map<String,String> m=new HashMap<>();m.put("tenantId",tenant);m.put("principalId",principal);m.put("createdAt",now.toString());m.put("lastAccessedAt",now.toString());m.put("expiresAt",exp.toString());m.put("generation","1");m.put("revoked","false"); if(attrs!=null) attrs.forEach((k,v)->m.put("a."+k,v));redis.opsForHash().putAll(key(id),m);redis.expireAt(key(id),exp);redis.opsForSet().add(index(tenant,principal),id);redis.expireAt(index(tenant,principal),exp.plus(p.getDefaultTtl())); enforceLimit(tenant,principal);audit.record("CREATE",id,principal,"created");return decode(id,m);}
 public Optional<CpfSessionSnapshot> find(String id){Map<Object,Object> m=redis.opsForHash().entries(key(id));if(m.isEmpty())return Optional.empty();Map<String,String>s=new HashMap<>();m.forEach((k,v)->s.put(String.valueOf(k),String.valueOf(v)));var snap=decode(id,s);if(snap.revoked()||snap.expiresAt().isBefore(Instant.now()))return Optional.empty();return Optional.of(snap);}
 public CpfSessionSnapshot renew(String id,Duration ttl){var old=find(id).orElseThrow();Duration use=ttl==null?p.getDefaultTtl():ttl;Instant now=Instant.now(),exp=now.plus(use);redis.opsForHash().put(key(id),"lastAccessedAt",now.toString());redis.opsForHash().put(key(id),"expiresAt",exp.toString());redis.expireAt(key(id),exp);audit.record("RENEW",id,old.principalId(),"renewed");return find(id).orElseThrow();}
 public CpfSessionSnapshot rotate(String id,Duration ttl){var old=find(id).orElseThrow();revoke(id,"ROTATE");CpfSessionSnapshot rotated=create(old.tenantId(),old.principalId(),ttl,old.attributes());audit.record("ROTATE",rotated.sessionId(),old.principalId(),"fixation-defense");return rotated;}
 public boolean revoke(String id,String reason){var old=find(id);if(old.isEmpty())return false;redis.opsForHash().put(key(id),"revoked","true");redis.opsForHash().put(key(id),"revokeReason",reason==null?"":reason);redis.opsForSet().remove(index(old.get().tenantId(),old.get().principalId()),id);redis.expire(key(id),Duration.ofMinutes(5));audit.record("REVOKE",id,old.get().principalId(),reason==null?"unspecified":reason);return true;}
 public int revokePrincipal(String t,String u,String reason){Set<String> ids=redis.opsForSet().members(index(t,u));if(ids==null)return 0;int n=0;for(String id:ids)if(revoke(id,reason))n++;return n;}
 public List<CpfSessionSnapshot> findByPrincipal(String t,String u){Set<String> ids=redis.opsForSet().members(index(t,u));if(ids==null)return List.of();return ids.stream().map(this::find).flatMap(Optional::stream).sorted(Comparator.comparing(CpfSessionSnapshot::lastAccessedAt).reversed()).toList();}
 private void enforceLimit(String t,String u){var all=findByPrincipal(t,u);for(int i=p.getMaxConcurrentSessions();i<all.size();i++)revoke(all.get(i).sessionId(),"CONCURRENT_LIMIT");}
 private CpfSessionSnapshot decode(String id,Map<String,String> m){Map<String,String>a=new HashMap<>();m.forEach((k,v)->{if(k.startsWith("a."))a.put(k.substring(2),v);});return new CpfSessionSnapshot(id,m.get("tenantId"),m.get("principalId"),Instant.parse(m.get("createdAt")),Instant.parse(m.get("lastAccessedAt")),Instant.parse(m.get("expiresAt")),Long.parseLong(m.getOrDefault("generation","1")),Boolean.parseBoolean(m.getOrDefault("revoked","false")),a);}
}
