plugins { id 'java-library'; id 'maven-publish' }
group='com.cpf.starter'
dependencies { api project(':cpf-core'); implementation 'com.fasterxml.jackson.core:jackson-databind'; implementation 'org.apache.avro:avro:1.12.0'; implementation 'com.google.protobuf:protobuf-java:4.33.2'; implementation 'org.springframework.boot:spring-boot-autoconfigure'; testImplementation 'org.springframework.boot:spring-boot-starter-test' }
tasks.named('test'){useJUnitPlatform()}
publishing { publications { mavenJava(MavenPublication){from components.java;artifactId='cpf-starter-messaging-schema-governance'} } }
