from __future__ import annotations

import os
import unittest
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[3]
ROOT = Path(os.environ.get("CPF_REPO_ROOT", DEFAULT_ROOT))
SERVICE = ROOT / "cpf-common/src/main/java/com/cpf/common/sample/CmnSampleItemService.java"
DIALECT = ROOT / "cpf-common/src/main/java/com/cpf/common/sample/CmnSampleSqlDialect.java"


class CmnSampleDbPortabilityTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.service = SERVICE.read_text(encoding="utf-8")
        cls.dialect = DIALECT.read_text(encoding="utf-8")

    def test_only_official_vendors_are_routed_fail_closed(self) -> None:
        self.assertIn('normalized.contains("mariadb")', self.dialect)
        self.assertIn('normalized.contains("postgresql")', self.dialect)
        self.assertIn('normalized.contains("oracle")', self.dialect)
        self.assertIn("Unsupported CMN Sample database vendor", self.dialect)
        self.assertNotIn('normalized.contains("mysql")', self.dialect)

    def test_oracle_and_limit_dialects_are_separated(self) -> None:
        resources = ROOT / "cpf-tools/db/runtime-template/cmn/sample"
        oracle_offset = (resources / "offset-oracle.sql").read_text(encoding="utf-8")
        oracle_cursor = (resources / "cursor-oracle.sql").read_text(encoding="utf-8")
        maria_offset = (resources / "offset-mariadb.sql").read_text(encoding="utf-8")
        pg_offset = (resources / "offset-postgresql.sql").read_text(encoding="utf-8")
        self.assertIn("OFFSET ? ROWS FETCH NEXT ? ROWS ONLY", oracle_offset)
        self.assertIn("FETCH FIRST ? ROWS ONLY", oracle_cursor)
        self.assertIn("LIMIT ? OFFSET ?", maria_offset)
        self.assertIn("LIMIT ? OFFSET ?", pg_offset)
        self.assertIn("NVL(searchable_text,'')", oracle_offset)
        self.assertIn("COALESCE(searchable_text,'')", maria_offset)
        self.assertIn('ORACLE("sample/offset-oracle.sql", "sample/cursor-oracle.sql")', self.dialect)

    def test_generated_key_is_bound_to_canonical_identity_column(self) -> None:
        self.assertIn('new String[] {"sample_item_id"}', self.service)
        self.assertNotIn("Statement.RETURN_GENERATED_KEYS", self.service)

    def test_all_official_vendor_schemas_define_identity_sample_table(self) -> None:
        expected = {
            "mariadb": "AUTO_INCREMENT",
            "postgresql": "GENERATED BY DEFAULT AS IDENTITY",
            "oracle": "GENERATED BY DEFAULT ON NULL AS IDENTITY",
        }
        for vendor, identity in expected.items():
            ddl = ROOT / f"cpf-tools/db/vendor/{vendor}/source/20_cmn_schema.sql"
            text = ddl.read_text(encoding="utf-8")
            self.assertIn("cmn_sample_item", text)
            self.assertIn(identity, text)


if __name__ == "__main__":
    unittest.main()
