from __future__ import annotations

import hashlib
import json
import os
import unittest
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[3]
ROOT = Path(os.environ.get("CPF_REPO_ROOT", DEFAULT_ROOT)).resolve()
EDUCATION = ROOT / "cpf-education"
SERVICE = EDUCATION / "src/main/java/com/cpf/education/common/sample/CmnSampleItemService.java"
DIALECT = EDUCATION / "src/main/java/com/cpf/education/common/sample/CmnSampleSqlDialect.java"
VENDOR = ROOT / "cpf-starters/data/persistence/src/main/java/com/cpf/data/persistence/api/database/CpfDatabaseVendor.java"
SQL = EDUCATION / "src/main/resources/sql/common/sample"
GENERATED = ROOT / "cpf-tools/db/generated/current"
VENDORS = ("mariadb", "postgresql", "oracle")


class CmnSampleDbPortabilityTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.service = SERVICE.read_text(encoding="utf-8")
        cls.dialect = DIALECT.read_text(encoding="utf-8")
        cls.vendor = VENDOR.read_text(encoding="utf-8")

    def test_only_official_vendors_are_routed_by_canonical_vendor_contract(self) -> None:
        self.assertIn("CpfDatabaseVendor.fromDatabaseProductName(productName)", self.dialect)
        self.assertNotIn('normalized.contains("mariadb")', self.dialect)
        self.assertIn('MARIADB("mariadb", "org.mariadb.jdbc.Driver", 3306)', self.vendor)
        self.assertIn('POSTGRESQL("postgresql", "org.postgresql.Driver", 5432)', self.vendor)
        self.assertIn('ORACLE("oracle", "oracle.jdbc.OracleDriver", 1521)', self.vendor)
        self.assertIn("fromDatabaseProductName(String productName)", self.vendor)
        self.assertNotIn('MYSQL(', self.vendor)
        self.assertNotIn('MSSQL(', self.vendor)

    def test_oracle_and_limit_dialects_are_separated(self) -> None:
        oracle_offset = (SQL / "offset-oracle.sql").read_text(encoding="utf-8")
        oracle_cursor = (SQL / "cursor-oracle.sql").read_text(encoding="utf-8")
        maria_offset = (SQL / "offset-mariadb.sql").read_text(encoding="utf-8")
        pg_offset = (SQL / "offset-postgresql.sql").read_text(encoding="utf-8")
        self.assertIn("OFFSET ? ROWS FETCH NEXT ? ROWS ONLY", oracle_offset)
        self.assertIn("FETCH FIRST ? ROWS ONLY", oracle_cursor)
        self.assertIn("LIMIT ? OFFSET ?", maria_offset)
        self.assertIn("LIMIT ? OFFSET ?", pg_offset)
        self.assertIn("NVL(searchable_text,'')", oracle_offset)
        self.assertIn("COALESCE(searchable_text,'')", maria_offset)
        self.assertIn(
            'ORACLE("sample/offset-oracle.sql", "sample/cursor-oracle.sql", true)',
            self.dialect,
        )

    def test_education_sample_consumes_reference_fixture_with_education_query_loader(self) -> None:
        self.assertIn("CmnEducationSqlResourceLoader.load", self.service)
        self.assertNotIn("com.cpf.common.sql", self.service)
        self.assertNotIn("com.cpf.data.persistence.sql.CmnSqlResourceLoader", self.service)
        self.assertNotIn("com.cpf.data.persistence.sql.CmnSqlResourceLoader", self.dialect)
        self.assertIn('new String[] {"sample_item_id"}', self.service)
        self.assertNotIn("Statement.RETURN_GENERATED_KEYS", self.service)

    def test_all_official_generated_reference_packs_define_identity_sample_table(self) -> None:
        identity_by_vendor = {
            "mariadb": "AUTO_INCREMENT",
            "postgresql": "GENERATED BY DEFAULT AS IDENTITY",
            "oracle": "GENERATED BY DEFAULT AS IDENTITY",
        }
        for vendor, identity in identity_by_vendor.items():
            pack = GENERATED / vendor
            ddl = (pack / "reference-fixture-schema.sql").read_text(encoding="utf-8-sig")
            self.assertIn("REF_CMN_SAMPLE_ITEM", ddl, vendor)
            self.assertIn(identity, ddl, vendor)
            manifest = json.loads((pack / "manifest.json").read_text(encoding="utf-8-sig"))
            expected_hash = manifest["artifacts"]["reference-fixture-schema.sql"]
            actual_hash = hashlib.sha256((pack / "reference-fixture-schema.sql").read_bytes()).hexdigest()
            self.assertEqual(expected_hash, actual_hash, vendor)

    def test_sample_sql_targets_reference_fixture_table(self) -> None:
        for path in SQL.glob("*.sql"):
            text = path.read_text(encoding="utf-8")
            if "cmn_sample_item" in text.lower() or "ref_cmn_sample_item" in text.lower():
                self.assertIn("REF_CMN_SAMPLE_ITEM", text.upper(), path.name)


if __name__ == "__main__":
    unittest.main()
