-- ADM 관리자 기본 테이블 DDL입니다.
-- 운영 환경에서는 DBA 표준에 맞춰 tablespace, charset, 권한, 인덱스명을 조정한 뒤 반영합니다.

CREATE TABLE IF NOT EXISTS operator_user (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    OPERATOR_NAME VARCHAR(100) NOT NULL COMMENT '운영자명',
    PASSWORD_HASH VARCHAR(512) NOT NULL COMMENT 'PBKDF2/BCrypt/Argon2 비밀번호 해시. 원문 비밀번호 저장 금지',
    LOCKED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '계정 잠금 여부',
    FAIL_COUNT INT NOT NULL DEFAULT 0 COMMENT '로그인 실패 횟수',
    PASSWORD_CHANGED_AT DATETIME NULL COMMENT '비밀번호 마지막 변경 시각',
    PASSWORD_CHANGE_REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '비밀번호 변경 강제 여부',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (OPERATOR_ID)
) COMMENT='ADM 운영자 계정';

CREATE TABLE IF NOT EXISTS operator_role (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    ROLE_NAME VARCHAR(100) NOT NULL COMMENT '역할명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '역할 설명',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (ROLE_ID)
) COMMENT='ADM 역할';

CREATE TABLE IF NOT EXISTS operator_user_role (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (OPERATOR_ID, ROLE_ID)
) COMMENT='ADM 운영자 역할 매핑';

CREATE TABLE IF NOT EXISTS operator_menu (
    MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    PARENT_MENU_ID VARCHAR(50) NULL COMMENT '상위 메뉴 ID',
    MENU_NAME VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_PATH VARCHAR(200) NOT NULL COMMENT '화면 경로',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (MENU_ID),
    INDEX IX_OPERATOR_MENU_PARENT (PARENT_MENU_ID, SORT_ORDER)
) COMMENT='ADM 메뉴';

CREATE TABLE IF NOT EXISTS operator_role_menu (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    READ_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '조회 권한',
    WRITE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '등록/수정 권한',
    DELETE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 권한',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (ROLE_ID, MENU_ID)
) COMMENT='ADM 역할별 메뉴 권한';

CREATE TABLE IF NOT EXISTS operator_audit_log (
    AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '운영자 감사 로그 ID',
    TRANSACTION_ID VARCHAR(80) NULL COMMENT '글로벌 거래ID',
    TRACE_ID VARCHAR(80) NULL COMMENT 'Trace ID',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    MENU_ID VARCHAR(50) NULL COMMENT '메뉴 ID',
    ACTION_TYPE VARCHAR(30) NOT NULL COMMENT '작업 유형',
    TARGET_TYPE VARCHAR(50) NULL COMMENT '대상 유형',
    TARGET_ID VARCHAR(100) NULL COMMENT '대상 ID',
    REASON VARCHAR(500) NULL COMMENT '작업 사유',
    REQUEST_BODY LONGTEXT NULL COMMENT '요청 본문',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (AUDIT_ID),
    INDEX IX_OPERATOR_AUDIT_TX (TRANSACTION_ID),
    INDEX IX_OPERATOR_AUDIT_OPERATOR_TIME (OPERATOR_ID, CREATED_AT)
) COMMENT='ADM 운영자 작업 감사 로그';

CREATE TABLE IF NOT EXISTS operator_session (
    SESSION_ID VARCHAR(80) NOT NULL COMMENT '운영자 세션 ID',
    TOKEN_HASH VARCHAR(512) NOT NULL COMMENT '토큰 SHA-256 등 해시값. 원문 토큰 저장 금지',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    ROLE_IDS VARCHAR(1000) NULL COMMENT '세션 발급 시점 역할 목록',
    ISSUED_AT DATETIME NOT NULL COMMENT '발급 시각',
    EXPIRE_AT DATETIME NOT NULL COMMENT '만료 시각',
    REVOKED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '폐기 여부',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    USER_AGENT VARCHAR(500) NULL COMMENT 'User-Agent',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (SESSION_ID),
    INDEX IX_OPERATOR_SESSION_TOKEN (TOKEN_HASH),
    INDEX IX_OPERATOR_SESSION_USER (OPERATOR_ID, EXPIRE_AT)
) COMMENT='ADM 운영자 세션';

CREATE TABLE IF NOT EXISTS dynamic_log_level_rule (
    RULE_ID VARCHAR(80) NOT NULL COMMENT '동적 로그레벨 규칙 ID',
    TRANSACTION_ID VARCHAR(80) NULL COMMENT '글로벌 거래ID',
    BUSINESS_TRANSACTION_ID VARCHAR(20) NULL COMMENT '업무 거래ID',
    MODULE_ID VARCHAR(10) NULL COMMENT '모듈 ID',
    LOG_LEVEL VARCHAR(10) NOT NULL COMMENT '적용 로그레벨',
    EXPIRE_AT DATETIME NOT NULL COMMENT '만료 시각',
    REASON VARCHAR(500) NULL COMMENT '등록 사유',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록시각',
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    PRIMARY KEY (RULE_ID),
    INDEX IX_DYNAMIC_LOG_BIZ_TX (BUSINESS_TRANSACTION_ID, EXPIRE_AT),
    INDEX IX_DYNAMIC_LOG_TX (TRANSACTION_ID, EXPIRE_AT)
) COMMENT='ADM 특정 거래 동적 로그레벨 규칙';
