-- CMN common schema.
-- Target DB: cmnDB

USE cmnDB;

CREATE TABLE IF NOT EXISTS code_table (
    code_id BIGINT NOT NULL AUTO_INCREMENT,
    parent_id BIGINT NULL,
    code_key VARCHAR(80) NOT NULL,
    code_value VARCHAR(120) NOT NULL,
    description VARCHAR(500) NULL,
    use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (code_id),
    CONSTRAINT FK_CODE_PARENT
        FOREIGN KEY (parent_id) REFERENCES code_table(code_id)
        ON DELETE SET NULL,
    UNIQUE KEY UK_CODE_KEY_VALUE (code_key, code_value),
    INDEX IDX_CODE_PARENT (parent_id),
    INDEX IDX_CODE_USE (use_yn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_table (
    message_id BIGINT NOT NULL AUTO_INCREMENT,
    message_code VARCHAR(20) NOT NULL,
    locale VARCHAR(10) NOT NULL DEFAULT 'ko',
    message_format_type VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    external_message VARCHAR(2000) NOT NULL,
    internal_message VARCHAR(4000) NOT NULL,
    parameter_count INT NOT NULL DEFAULT 0,
    parameter_sample VARCHAR(1000) NULL,
    description VARCHAR(500) NULL,
    use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (message_id),
    UNIQUE KEY UK_MESSAGE_CODE_LOCALE (message_code, locale),
    INDEX IDX_MESSAGE_CODE_USE (message_code, use_yn),
    INDEX IDX_MESSAGE_USE (use_yn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS response_code_table (
    response_code VARCHAR(20) NOT NULL,
    message_code VARCHAR(20) NOT NULL,
    result_type CHAR(1) NOT NULL,
    module_id VARCHAR(3) NOT NULL,
    response_group VARCHAR(2) NOT NULL,
    sequence_no VARCHAR(4) NOT NULL,
    http_status INT NOT NULL,
    description VARCHAR(500) NULL,
    use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (response_code),
    INDEX IDX_RESPONSE_CODE_MESSAGE (message_code),
    INDEX IDX_RESPONSE_CODE_MODULE (module_id, result_type, response_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS config_table (
    config_id BIGINT NOT NULL AUTO_INCREMENT,
    config_key VARCHAR(150) NOT NULL,
    config_value VARCHAR(2000) NOT NULL,
    config_type VARCHAR(30) NOT NULL DEFAULT 'STRING',
    description VARCHAR(500) NULL,
    encrypted_yn CHAR(1) NOT NULL DEFAULT 'N',
    use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (config_id),
    UNIQUE KEY UK_CONFIG_KEY (config_key),
    INDEX IDX_CONFIG_USE (use_yn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cache_refresh_event (
    event_id BIGINT NOT NULL AUTO_INCREMENT,
    cache_name VARCHAR(50) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    event_key VARCHAR(200) NULL,
    source_was_id VARCHAR(50) NULL,
    published_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    published_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id),
    INDEX IDX_CACHE_REFRESH_EVENT_CACHE_ID (cache_name, event_id),
    INDEX IDX_CACHE_REFRESH_EVENT_TIME (published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_exchange_log (
    EXCHANGE_ID VARCHAR(80) NOT NULL,
    TRANSACTION_ID VARCHAR(80) NULL,
    TRACE_ID VARCHAR(80) NULL,
    BUSINESS_TRANSACTION_ID VARCHAR(20) NULL,
    ACTION_TYPE VARCHAR(30) NOT NULL,
    PROTOCOL VARCHAR(20) NOT NULL,
    DIRECTION VARCHAR(20) NULL,
    EXECUTED_YN CHAR(1) NOT NULL DEFAULT 'N',
    SUCCESS_YN CHAR(1) NOT NULL DEFAULT 'N',
    HOST VARCHAR(255) NULL,
    SOURCE_PATH VARCHAR(1000) NULL,
    TARGET_PATH VARCHAR(1000) NULL,
    REQUEST_USER VARCHAR(50) NULL,
    MESSAGE VARCHAR(2000) NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (EXCHANGE_ID),
    INDEX IX_FILE_EXCHANGE_TX (TRANSACTION_ID, CREATED_AT),
    INDEX IX_FILE_EXCHANGE_BIZ (BUSINESS_TRANSACTION_ID, CREATED_AT),
    INDEX IX_FILE_EXCHANGE_HOST (HOST, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS security_jwt_key (
    KEY_ID VARCHAR(80) NOT NULL,
    ISSUER VARCHAR(100) NOT NULL,
    ALGORITHM VARCHAR(20) NOT NULL DEFAULT 'HS256',
    SECRET_REF VARCHAR(500) NOT NULL,
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    EXPIRE_AT DATETIME NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (KEY_ID),
    INDEX IX_SECURITY_JWT_KEY_ISSUER (ISSUER, ACTIVE_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS security_token_audit_log (
    TOKEN_AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT,
    TRANSACTION_ID VARCHAR(80) NULL,
    TRACE_ID VARCHAR(80) NULL,
    TOKEN_HASH VARCHAR(512) NULL,
    TOKEN_TYPE VARCHAR(30) NOT NULL DEFAULT 'Bearer',
    ISSUER VARCHAR(100) NULL,
    SUBJECT VARCHAR(200) NULL,
    AUDIENCE VARCHAR(200) NULL,
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'N',
    EXPIRE_AT DATETIME NULL,
    FAILURE_REASON VARCHAR(1000) NULL,
    CLIENT_IP VARCHAR(50) NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'CMN',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TOKEN_AUDIT_ID),
    INDEX IX_SECURITY_TOKEN_TX (TRANSACTION_ID),
    INDEX IX_SECURITY_TOKEN_HASH (TOKEN_HASH),
    INDEX IX_SECURITY_TOKEN_SUBJECT_TIME (SUBJECT, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
