-- ADM 관리자 운영 스키마입니다.
-- 운영자, 역할, 메뉴/버튼 권한, 세션, 감사 로그, 보안 운영 메타를 admDB에 배치합니다.

USE admDB;

CREATE TABLE IF NOT EXISTS adm_operator (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    OPERATOR_NAME VARCHAR(100) NOT NULL COMMENT '운영자명',
    PASSWORD_HASH VARCHAR(512) NOT NULL COMMENT '비밀번호 해시',
    LOCKED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '잠금 여부',
    FAIL_COUNT INT NOT NULL DEFAULT 0 COMMENT '로그인 실패 횟수',
    PASSWORD_CHANGED_AT DATETIME NULL COMMENT '비밀번호 변경일시',
    PASSWORD_EXPIRE_AT DATETIME NULL COMMENT '비밀번호 만료일시',
    PASSWORD_CHANGE_REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '비밀번호 변경 필요 여부',
    LAST_LOGIN_AT DATETIME NULL COMMENT '마지막 로그인 일시',
    LAST_LOGIN_IP VARCHAR(50) NULL COMMENT '마지막 로그인 IP',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (OPERATOR_ID),
    INDEX ix_adm_operator_use (USE_YN),
    INDEX ix_adm_operator_lock (LOCKED_YN, FAIL_COUNT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영자';

CREATE TABLE IF NOT EXISTS adm_role (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    ROLE_NAME VARCHAR(100) NOT NULL COMMENT '역할명',
    ROLE_TYPE VARCHAR(30) NOT NULL DEFAULT 'BUSINESS_OPERATOR' COMMENT '역할 유형',
    DESCRIPTION VARCHAR(500) NULL COMMENT '역할 설명',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ROLE_ID),
    INDEX ix_adm_role_type (ROLE_TYPE, USE_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 역할';

CREATE TABLE IF NOT EXISTS adm_operator_role (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (OPERATOR_ID, ROLE_ID),
    CONSTRAINT fk_adm_operator_role_operator
        FOREIGN KEY (OPERATOR_ID) REFERENCES adm_operator(OPERATOR_ID)
        ON DELETE CASCADE,
    CONSTRAINT fk_adm_operator_role_role
        FOREIGN KEY (ROLE_ID) REFERENCES adm_role(ROLE_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영자 역할 매핑';

CREATE TABLE IF NOT EXISTS adm_menu (
    MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    PARENT_MENU_ID VARCHAR(50) NULL COMMENT '상위 메뉴 ID',
    MENU_NAME VARCHAR(100) NOT NULL COMMENT '메뉴명',
    MENU_PATH VARCHAR(200) NOT NULL COMMENT '메뉴 경로',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MENU_ID),
    INDEX ix_adm_menu_parent (PARENT_MENU_ID, SORT_ORDER),
    CONSTRAINT fk_adm_menu_parent
        FOREIGN KEY (PARENT_MENU_ID) REFERENCES adm_menu(MENU_ID)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 메뉴';

CREATE TABLE IF NOT EXISTS adm_role_menu (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    READ_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '조회 권한 여부',
    WRITE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '등록/수정 권한 여부',
    DELETE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 권한 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ROLE_ID, MENU_ID),
    CONSTRAINT fk_adm_role_menu_role
        FOREIGN KEY (ROLE_ID) REFERENCES adm_role(ROLE_ID)
        ON DELETE CASCADE,
    CONSTRAINT fk_adm_role_menu_menu
        FOREIGN KEY (MENU_ID) REFERENCES adm_menu(MENU_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 역할별 메뉴 권한';

CREATE TABLE IF NOT EXISTS adm_button (
    BUTTON_ID VARCHAR(80) NOT NULL COMMENT '버튼/행위 ID',
    MENU_ID VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    ACTION_CODE VARCHAR(50) NOT NULL COMMENT '행위 코드',
    BUTTON_NAME VARCHAR(100) NOT NULL COMMENT '버튼/행위명',
    HTTP_METHOD VARCHAR(10) NULL COMMENT '대상 HTTP 메서드',
    API_PATTERN VARCHAR(300) NULL COMMENT '대상 API 경로 패턴',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (BUTTON_ID),
    UNIQUE KEY uk_adm_button_menu_action (MENU_ID, ACTION_CODE),
    INDEX ix_adm_button_menu (MENU_ID, SORT_ORDER),
    CONSTRAINT fk_adm_button_menu
        FOREIGN KEY (MENU_ID) REFERENCES adm_menu(MENU_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 메뉴별 버튼/행위';

CREATE TABLE IF NOT EXISTS adm_role_button (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    BUTTON_ID VARCHAR(80) NOT NULL COMMENT '버튼/행위 ID',
    ALLOW_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '허용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ROLE_ID, BUTTON_ID),
    CONSTRAINT fk_adm_role_button_role
        FOREIGN KEY (ROLE_ID) REFERENCES adm_role(ROLE_ID)
        ON DELETE CASCADE,
    CONSTRAINT fk_adm_role_button_button
        FOREIGN KEY (BUTTON_ID) REFERENCES adm_button(BUTTON_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 역할별 버튼/행위 권한';

CREATE TABLE IF NOT EXISTS adm_api_permission (
    API_PERMISSION_ID VARCHAR(120) NOT NULL COMMENT 'API 권한 ID',
    API_GROUP_CODE VARCHAR(50) NOT NULL COMMENT 'API 그룹 코드',
    HTTP_METHOD VARCHAR(10) NOT NULL COMMENT 'HTTP 메서드',
    API_PATH VARCHAR(300) NOT NULL COMMENT 'API 경로 패턴',
    API_NAME VARCHAR(150) NOT NULL COMMENT 'API명',
    PERMISSION_CODE VARCHAR(50) NOT NULL COMMENT '권한 코드',
    MENU_ID VARCHAR(50) NULL COMMENT '연결 메뉴 ID',
    BUTTON_ID VARCHAR(80) NULL COMMENT '연결 버튼/행위 ID',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (API_PERMISSION_ID),
    UNIQUE KEY uk_adm_api_permission_method_path (HTTP_METHOD, API_PATH),
    INDEX ix_adm_api_permission_group (API_GROUP_CODE, USE_YN),
    INDEX ix_adm_api_permission_menu (MENU_ID, BUTTON_ID),
    CONSTRAINT fk_adm_api_permission_menu
        FOREIGN KEY (MENU_ID) REFERENCES adm_menu(MENU_ID)
        ON DELETE SET NULL,
    CONSTRAINT fk_adm_api_permission_button
        FOREIGN KEY (BUTTON_ID) REFERENCES adm_button(BUTTON_ID)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM API 권한';

CREATE TABLE IF NOT EXISTS adm_role_api_permission (
    ROLE_ID VARCHAR(50) NOT NULL COMMENT '역할 ID',
    API_PERMISSION_ID VARCHAR(120) NOT NULL COMMENT 'API 권한 ID',
    ALLOW_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '허용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ROLE_ID, API_PERMISSION_ID),
    CONSTRAINT fk_adm_role_api_permission_role
        FOREIGN KEY (ROLE_ID) REFERENCES adm_role(ROLE_ID)
        ON DELETE CASCADE,
    CONSTRAINT fk_adm_role_api_permission_api
        FOREIGN KEY (API_PERMISSION_ID) REFERENCES adm_api_permission(API_PERMISSION_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 역할별 API 권한';

CREATE TABLE IF NOT EXISTS adm_audit_log (
    AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '감사 로그 순번',
    TRANSACTION_ID VARCHAR(80) NULL COMMENT '프레임워크 거래 ID',
    TRACE_ID VARCHAR(80) NULL COMMENT '분산 추적 ID',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    MENU_ID VARCHAR(50) NULL COMMENT '메뉴 ID',
    BUTTON_ID VARCHAR(80) NULL COMMENT '버튼/행위 ID',
    ACTION_TYPE VARCHAR(30) NOT NULL COMMENT '행위 유형',
    TARGET_TYPE VARCHAR(50) NULL COMMENT '대상 유형',
    TARGET_ID VARCHAR(100) NULL COMMENT '대상 ID',
    REASON VARCHAR(500) NOT NULL COMMENT '감사 사유',
    BEFORE_DATA LONGTEXT NULL COMMENT '변경 전 데이터',
    AFTER_DATA LONGTEXT NULL COMMENT '변경 후 데이터',
    DIFF_DATA LONGTEXT NULL COMMENT '변경 차이 데이터',
    REQUEST_BODY LONGTEXT NULL COMMENT '요청 본문',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    RETENTION_UNTIL DATE NULL COMMENT '보존 만료 기준일',
    IMMUTABLE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '삭제 불가 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (AUDIT_ID),
    INDEX ix_adm_audit_log_tx (TRANSACTION_ID),
    INDEX ix_adm_audit_log_operator_time (OPERATOR_ID, created_at),
    INDEX ix_adm_audit_log_action_time (ACTION_TYPE, created_at),
    INDEX ix_adm_audit_log_target_time (TARGET_TYPE, TARGET_ID, created_at),
    INDEX ix_adm_audit_log_retention (RETENTION_UNTIL, IMMUTABLE_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 감사 로그';

CREATE TABLE IF NOT EXISTS adm_download_audit_log (
    DOWNLOAD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '다운로드 감사 로그 순번',
    ADMIN_ID VARCHAR(50) NOT NULL COMMENT '요청 운영자 ID',
    MENU_ID VARCHAR(50) NULL COMMENT '메뉴 ID',
    SCREEN_ID VARCHAR(100) NULL COMMENT '화면 ID',
    DOWNLOAD_TYPE VARCHAR(50) NOT NULL COMMENT '다운로드 유형',
    TARGET_TYPE VARCHAR(50) NULL COMMENT '대상 유형',
    SEARCH_CONDITION_SUMMARY LONGTEXT NULL COMMENT '검색 조건 요약',
    ROW_COUNT INT NOT NULL DEFAULT 0 COMMENT '다운로드 행 수',
    MASKED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '마스킹 적용 여부',
    INCLUDE_SENSITIVE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '민감정보 포함 요청 여부',
    REASON VARCHAR(500) NOT NULL COMMENT '다운로드 사유',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    USER_AGENT VARCHAR(500) NULL COMMENT 'User-Agent',
    REQUESTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '요청 일시',
    COMPLETED_AT DATETIME NULL COMMENT '완료 일시',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'REQUESTED' COMMENT '처리 상태',
    FAILURE_REASON VARCHAR(1000) NULL COMMENT '실패 사유',
    FILE_NAME VARCHAR(300) NULL COMMENT '파일명',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DOWNLOAD_ID),
    INDEX ix_adm_download_audit_log_admin_time (ADMIN_ID, REQUESTED_AT),
    INDEX ix_adm_download_audit_log_type_time (DOWNLOAD_TYPE, REQUESTED_AT),
    INDEX ix_adm_download_audit_log_status_time (STATUS, REQUESTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 다운로드 감사 로그';

CREATE TABLE IF NOT EXISTS adm_operator_session (
    SESSION_ID VARCHAR(80) NOT NULL COMMENT '세션 ID',
    TOKEN_HASH VARCHAR(512) NOT NULL COMMENT '토큰 해시',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    ROLE_IDS VARCHAR(1000) NULL COMMENT '역할 ID 목록',
    ISSUED_AT DATETIME NOT NULL COMMENT '발급일시',
    EXPIRE_AT DATETIME NOT NULL COMMENT '만료일시',
    REVOKED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '폐기 여부',
    CLIENT_IP VARCHAR(50) NULL COMMENT '클라이언트 IP',
    USER_AGENT VARCHAR(500) NULL COMMENT 'User-Agent',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (SESSION_ID),
    INDEX ix_adm_operator_session_token (TOKEN_HASH),
    INDEX ix_adm_operator_session_user (OPERATOR_ID, EXPIRE_AT),
    INDEX ix_adm_operator_session_active (REVOKED_YN, EXPIRE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영자 세션';

CREATE TABLE IF NOT EXISTS adm_dynamic_log_level_rule (
    RULE_ID VARCHAR(80) NOT NULL COMMENT '동적 로그 레벨 규칙 ID',
    TRANSACTION_ID VARCHAR(100) NULL COMMENT '프레임워크 거래 ID',
    BUSINESS_TRANSACTION_ID VARCHAR(20) NULL COMMENT '업무 거래 ID',
    MODULE_ID VARCHAR(10) NULL COMMENT '모듈 ID',
    LOG_LEVEL VARCHAR(10) NOT NULL COMMENT '적용 로그 레벨',
    EXPIRE_AT DATETIME NOT NULL COMMENT '만료일시',
    REASON VARCHAR(500) NULL COMMENT '적용 사유',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (RULE_ID),
    INDEX ix_adm_dynamic_log_level_rule_biz_tx (BUSINESS_TRANSACTION_ID, EXPIRE_AT),
    INDEX ix_adm_dynamic_log_level_rule_tx (TRANSACTION_ID, EXPIRE_AT),
    INDEX ix_adm_dynamic_log_level_rule_active (USE_YN, EXPIRE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 동적 로그 레벨 규칙';

CREATE TABLE IF NOT EXISTS adm_ip_allowlist (
    ALLOW_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'IP 허용 목록 순번',
    IP_PATTERN VARCHAR(100) NOT NULL COMMENT '허용 IP 또는 CIDR 패턴',
    DESCRIPTION VARCHAR(500) NULL COMMENT '허용 사유',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ALLOW_ID),
    UNIQUE KEY uk_adm_ip_allowlist_pattern (IP_PATTERN),
    INDEX ix_adm_ip_allowlist_use (USE_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 관리자 IP 허용 목록';

CREATE TABLE IF NOT EXISTS adm_mfa_otp_secret (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    SECRET_REF VARCHAR(500) NOT NULL COMMENT 'OTP secret 참조',
    ENABLED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'MFA 사용 여부',
    VERIFIED_AT DATETIME NULL COMMENT 'MFA 검증일시',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (OPERATOR_ID),
    CONSTRAINT fk_adm_mfa_otp_secret_operator
        FOREIGN KEY (OPERATOR_ID) REFERENCES adm_operator(OPERATOR_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영자 MFA OTP secret 메타';

CREATE TABLE IF NOT EXISTS adm_password_policy (
    POLICY_ID VARCHAR(50) NOT NULL COMMENT '비밀번호 정책 ID',
    MIN_LENGTH INT NOT NULL DEFAULT 12 COMMENT '최소 길이',
    REQUIRE_UPPER_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '대문자 필수 여부',
    REQUIRE_LOWER_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '소문자 필수 여부',
    REQUIRE_DIGIT_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '숫자 필수 여부',
    REQUIRE_SPECIAL_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '특수문자 필수 여부',
    MAX_FAIL_COUNT INT NOT NULL DEFAULT 5 COMMENT '최대 실패 횟수',
    EXPIRE_DAYS INT NOT NULL DEFAULT 90 COMMENT '만료 일수',
    HISTORY_LIMIT INT NOT NULL DEFAULT 5 COMMENT '재사용 금지 이력 수',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (POLICY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 비밀번호 정책';

CREATE TABLE IF NOT EXISTS adm_password_history (
    HISTORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '비밀번호 이력 순번',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    PASSWORD_HASH VARCHAR(512) NOT NULL COMMENT '이전 비밀번호 해시',
    CHANGED_REASON VARCHAR(500) NULL COMMENT '변경 사유',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (HISTORY_ID),
    INDEX ix_adm_password_history_operator_time (OPERATOR_ID, created_at),
    CONSTRAINT fk_adm_password_history_operator
        FOREIGN KEY (OPERATOR_ID) REFERENCES adm_operator(OPERATOR_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 비밀번호 변경 이력';

-- ============================================================================
-- ADM 운영자 Directory Profile과 위험조치 Approval
-- adm_operator는 인증 Identity이며 아래 Profile/조직 메타는 승인·감사 문맥을 위한 최소 정보입니다.
-- 고객 HR Master를 대체하지 않으며 LDAP/AD/IAM/HR Adapter로 교체·동기화할 수 있어야 합니다.
-- ============================================================================

CREATE TABLE IF NOT EXISTS adm_organization (
    ORGANIZATION_CODE VARCHAR(50) NOT NULL COMMENT '운영 조직 코드',
    PARENT_ORGANIZATION_CODE VARCHAR(50) NULL COMMENT '상위 조직 코드',
    ORGANIZATION_NAME VARCHAR(120) NOT NULL COMMENT '운영 조직명',
    ORGANIZATION_TYPE VARCHAR(30) NOT NULL DEFAULT 'DEPARTMENT' COMMENT '조직 유형',
    MANAGER_OPERATOR_ID VARCHAR(50) NULL COMMENT '기본 DB Directory Adapter의 조직 책임자 운영자 ID',
    EFFECTIVE_FROM DATE NULL COMMENT '적용 시작일',
    EFFECTIVE_TO DATE NULL COMMENT '적용 종료일',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (ORGANIZATION_CODE),
    INDEX ix_adm_organization_parent (PARENT_ORGANIZATION_CODE, USE_YN),
    CONSTRAINT fk_adm_organization_parent FOREIGN KEY (PARENT_ORGANIZATION_CODE)
        REFERENCES adm_organization(ORGANIZATION_CODE) ON DELETE SET NULL,
    CONSTRAINT fk_adm_organization_manager FOREIGN KEY (MANAGER_OPERATOR_ID)
        REFERENCES adm_operator(OPERATOR_ID) ON DELETE SET NULL,
    CONSTRAINT ck_adm_organization_use CHECK (USE_YN IN ('Y','N')),
    CONSTRAINT ck_adm_organization_effective CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영 조직 Directory 기본 Adapter';

CREATE TABLE IF NOT EXISTS adm_operator_profile (
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '운영자 ID',
    EMPLOYEE_NO VARCHAR(50) NULL COMMENT '외부/내부 사번',
    EXTERNAL_SUBJECT VARCHAR(200) NULL COMMENT 'LDAP/IAM 등 외부 Identity Subject',
    ORGANIZATION_CODE VARCHAR(50) NULL COMMENT '대표 운영 조직 코드',
    POSITION_CODE VARCHAR(50) NULL COMMENT '직급 코드',
    POSITION_NAME VARCHAR(100) NULL COMMENT '직급명 Snapshot/표시값',
    JOB_TITLE_CODE VARCHAR(50) NULL COMMENT '직책 코드',
    JOB_TITLE_NAME VARCHAR(100) NULL COMMENT '직책명 Snapshot/표시값',
    EMAIL VARCHAR(200) NULL COMMENT '업무 이메일',
    EFFECTIVE_FROM DATETIME(3) NULL COMMENT 'Profile 적용 시작시각',
    EFFECTIVE_TO DATETIME(3) NULL COMMENT 'Profile 적용 종료시각',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (OPERATOR_ID),
    UNIQUE KEY uk_adm_operator_profile_employee (EMPLOYEE_NO),
    INDEX ix_adm_operator_profile_org (ORGANIZATION_CODE, EFFECTIVE_TO),
    CONSTRAINT fk_adm_operator_profile_operator FOREIGN KEY (OPERATOR_ID)
        REFERENCES adm_operator(OPERATOR_ID) ON DELETE CASCADE,
    CONSTRAINT fk_adm_operator_profile_org FOREIGN KEY (ORGANIZATION_CODE)
        REFERENCES adm_organization(ORGANIZATION_CODE) ON DELETE SET NULL,
    CONSTRAINT ck_adm_operator_profile_effective CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 운영자 조직/직급 Profile';

CREATE TABLE IF NOT EXISTS adm_approval_policy (
    POLICY_CODE VARCHAR(80) NOT NULL COMMENT '위험조치 승인 정책 코드',
    POLICY_VERSION INT NOT NULL COMMENT '정책 버전',
    POLICY_NAME VARCHAR(150) NOT NULL COMMENT '정책명',
    ACTION_TYPE VARCHAR(80) NOT NULL COMMENT '대상 위험조치 유형',
    EFFECTIVE_FROM DATETIME(3) NOT NULL COMMENT '시행 시작시각',
    EFFECTIVE_TO DATETIME(3) NULL COMMENT '시행 종료시각',
    ENABLED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '활성 여부',
    SELF_APPROVAL_ALLOWED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '자기승인 허용 여부',
    BREAK_GLASS_ALLOWED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '긴급 우회 허용 여부',
    DESCRIPTION VARCHAR(1000) NULL COMMENT '정책 설명',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (POLICY_CODE, POLICY_VERSION),
    INDEX ix_adm_approval_policy_action (ACTION_TYPE, ENABLED_YN, EFFECTIVE_FROM, EFFECTIVE_TO),
    CONSTRAINT ck_adm_approval_policy_version CHECK (POLICY_VERSION > 0),
    CONSTRAINT ck_adm_approval_policy_flags CHECK (
        ENABLED_YN IN ('Y','N')
        AND SELF_APPROVAL_ALLOWED_YN IN ('Y','N')
        AND BREAK_GLASS_ALLOWED_YN IN ('Y','N')
    ),
    CONSTRAINT ck_adm_approval_policy_effective CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 위험조치 승인 정책 Version';

CREATE TABLE IF NOT EXISTS adm_approval_policy_step (
    POLICY_CODE VARCHAR(80) NOT NULL COMMENT '승인 정책 코드',
    POLICY_VERSION INT NOT NULL COMMENT '승인 정책 버전',
    STEP_NO INT NOT NULL COMMENT '승인 단계',
    STEP_TYPE VARCHAR(30) NOT NULL DEFAULT 'APPROVAL' COMMENT 'APPROVAL/REVIEW',
    TARGET_TYPE VARCHAR(30) NOT NULL COMMENT 'OPERATOR/ROLE/ORGANIZATION/ORG_MANAGER',
    TARGET_CODE VARCHAR(100) NOT NULL COMMENT '대상 운영자/역할/조직 코드',
    DECISION_RULE VARCHAR(20) NOT NULL DEFAULT 'ALL' COMMENT 'ALL/ANY/N_OF_M',
    REQUIRED_COUNT INT NULL COMMENT 'N_OF_M 최소 승인 수',
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '필수 단계 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (POLICY_CODE, POLICY_VERSION, STEP_NO, TARGET_TYPE, TARGET_CODE),
    CONSTRAINT fk_adm_approval_policy_step_policy FOREIGN KEY (POLICY_CODE, POLICY_VERSION)
        REFERENCES adm_approval_policy(POLICY_CODE, POLICY_VERSION) ON DELETE CASCADE,
    CONSTRAINT ck_adm_approval_policy_step_no CHECK (STEP_NO >= 1),
    CONSTRAINT ck_adm_approval_policy_step_type CHECK (STEP_TYPE IN ('APPROVAL','REVIEW')),
    CONSTRAINT ck_adm_approval_policy_step_target CHECK (
        TARGET_TYPE IN ('OPERATOR','ROLE','ORGANIZATION','ORG_MANAGER')
    ),
    CONSTRAINT ck_adm_approval_policy_step_rule CHECK (DECISION_RULE IN ('ALL','ANY','N_OF_M')),
    CONSTRAINT ck_adm_approval_policy_step_required CHECK (
        REQUIRED_YN IN ('Y','N')
        AND (
            (DECISION_RULE = 'N_OF_M' AND REQUIRED_COUNT IS NOT NULL AND REQUIRED_COUNT > 0)
            OR (DECISION_RULE <> 'N_OF_M' AND REQUIRED_COUNT IS NULL)
        )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 승인 정책 단계';

CREATE TABLE IF NOT EXISTS adm_approval_request (
    APPROVAL_REQUEST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '위험조치 승인 요청 순번',
    REQUEST_KEY VARCHAR(120) NOT NULL COMMENT '멱등 승인 요청 키',
    POLICY_CODE VARCHAR(80) NOT NULL COMMENT '적용 정책 코드',
    POLICY_VERSION INT NOT NULL COMMENT '적용 정책 버전 Snapshot',
    ACTION_TYPE VARCHAR(80) NOT NULL COMMENT '위험조치 유형',
    OWNER_MODULE VARCHAR(30) NOT NULL COMMENT '실제 Command Owner Module',
    OWNER_COMMAND VARCHAR(120) NOT NULL COMMENT '실행할 Owner Command',
    TARGET_TYPE VARCHAR(80) NOT NULL COMMENT '위험조치 대상 유형',
    TARGET_ID VARCHAR(200) NOT NULL COMMENT '위험조치 대상 ID',
    REQUESTED_BY VARCHAR(50) NOT NULL COMMENT '요청 운영자',
    REQUEST_REASON VARCHAR(1000) NOT NULL COMMENT '요청 사유',
    COMMAND_PAYLOAD_HASH CHAR(64) NOT NULL COMMENT '승인 대상 Command payload SHA-256',
    COMMAND_PAYLOAD_SNAPSHOT LONGTEXT NULL COMMENT '마스킹된 승인 대상 Command Snapshot',
    APPROVAL_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED/CANCELLED/EXPIRED/EXECUTING/COMPLETED/FAILED/UNKNOWN',
    CURRENT_STEP_NO INT NOT NULL DEFAULT 1 COMMENT '현재 승인 단계',
    EXPIRE_AT DATETIME(3) NULL COMMENT '승인 만료시각',
    TRANSACTION_GLOBAL_ID VARCHAR(100) NULL COMMENT 'CPF 전역 거래 ID',
    VERSION_NO BIGINT NOT NULL DEFAULT 0 COMMENT '낙관적 잠금 버전',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (APPROVAL_REQUEST_ID),
    UNIQUE KEY uk_adm_approval_request_key (REQUEST_KEY),
    INDEX ix_adm_approval_request_status (APPROVAL_STATUS, EXPIRE_AT, APPROVAL_REQUEST_ID),
    INDEX ix_adm_approval_request_actor (REQUESTED_BY, created_at),
    CONSTRAINT fk_adm_approval_request_policy FOREIGN KEY (POLICY_CODE, POLICY_VERSION)
        REFERENCES adm_approval_policy(POLICY_CODE, POLICY_VERSION),
    CONSTRAINT ck_adm_approval_request_status CHECK (
        APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED','EXPIRED','EXECUTING','COMPLETED','FAILED','UNKNOWN')
    ),
    CONSTRAINT ck_adm_approval_request_version CHECK (VERSION_NO >= 0),
    CONSTRAINT ck_adm_approval_request_step CHECK (CURRENT_STEP_NO >= 1),
    CONSTRAINT ck_adm_approval_request_hash CHECK (CHAR_LENGTH(COMMAND_PAYLOAD_HASH) = 64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 위험조치 승인 요청';

CREATE TABLE IF NOT EXISTS adm_approval_participant (
    APPROVAL_PARTICIPANT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '승인 참여자 순번',
    APPROVAL_REQUEST_ID BIGINT NOT NULL COMMENT '승인 요청 순번',
    STEP_NO INT NOT NULL COMMENT '승인 단계',
    OPERATOR_ID VARCHAR(50) NOT NULL COMMENT '해석된 실제 승인 운영자',
    SOURCE_TARGET_TYPE VARCHAR(30) NOT NULL COMMENT '정책 대상 유형 Snapshot',
    SOURCE_TARGET_CODE VARCHAR(100) NOT NULL COMMENT '정책 대상 코드 Snapshot',
    ORGANIZATION_CODE_SNAPSHOT VARCHAR(50) NULL COMMENT '승인 시 조직 Snapshot',
    POSITION_CODE_SNAPSHOT VARCHAR(50) NULL COMMENT '승인 시 직급 Snapshot',
    JOB_TITLE_CODE_SNAPSHOT VARCHAR(50) NULL COMMENT '승인 시 직책 Snapshot',
    DECISION_STATUS VARCHAR(30) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/APPROVED/REJECTED/SKIPPED',
    IDEMPOTENCY_KEY VARCHAR(120) NULL COMMENT '결정 멱등 키',
    DECISION_REASON VARCHAR(1000) NULL COMMENT '승인/반려 사유',
    DECIDED_AT DATETIME(3) NULL COMMENT '결정 시각',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (APPROVAL_PARTICIPANT_ID),
    UNIQUE KEY uk_adm_approval_participant (APPROVAL_REQUEST_ID, STEP_NO, OPERATOR_ID),
    UNIQUE KEY uk_adm_approval_participant_idem (IDEMPOTENCY_KEY),
    INDEX ix_adm_approval_participant_inbox (OPERATOR_ID, DECISION_STATUS, APPROVAL_REQUEST_ID),
    CONSTRAINT fk_adm_approval_participant_request FOREIGN KEY (APPROVAL_REQUEST_ID)
        REFERENCES adm_approval_request(APPROVAL_REQUEST_ID) ON DELETE CASCADE,
    CONSTRAINT ck_adm_approval_participant_status CHECK (
        DECISION_STATUS IN ('WAITING','APPROVED','REJECTED','SKIPPED')
    ),
    CONSTRAINT ck_adm_approval_participant_step CHECK (STEP_NO >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 승인 참여자 Snapshot';

CREATE TABLE IF NOT EXISTS adm_approval_history (
    APPROVAL_HISTORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '승인 이력 순번',
    APPROVAL_REQUEST_ID BIGINT NOT NULL COMMENT '승인 요청 순번',
    EVENT_TYPE VARCHAR(40) NOT NULL COMMENT 'REQUEST/APPROVE/REJECT/CANCEL/EXPIRE/BREAK_GLASS/EXECUTE/RESULT/REVIEW',
    ACTOR_ID VARCHAR(50) NOT NULL COMMENT '행위 운영자/시스템 ID',
    BEFORE_STATUS VARCHAR(30) NULL COMMENT '변경 전 상태',
    AFTER_STATUS VARCHAR(30) NOT NULL COMMENT '변경 후 상태',
    REASON VARCHAR(1000) NOT NULL COMMENT '행위 사유',
    EVENT_DATA LONGTEXT NULL COMMENT '마스킹된 사건 Snapshot',
    TRANSACTION_GLOBAL_ID VARCHAR(100) NULL COMMENT 'CPF 전역 거래 ID',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    PRIMARY KEY (APPROVAL_HISTORY_ID),
    INDEX ix_adm_approval_history_request (APPROVAL_REQUEST_ID, APPROVAL_HISTORY_ID),
    CONSTRAINT fk_adm_approval_history_request FOREIGN KEY (APPROVAL_REQUEST_ID)
        REFERENCES adm_approval_request(APPROVAL_REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 승인 Immutable 이력';

CREATE TABLE IF NOT EXISTS adm_approval_execution (
    APPROVAL_REQUEST_ID BIGINT NOT NULL COMMENT '승인 요청 순번',
    COMMAND_REQUEST_ID VARCHAR(120) NOT NULL COMMENT 'Owner Command 멱등 요청 ID',
    EXECUTION_STATUS VARCHAR(30) NOT NULL COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED/UNKNOWN/RECOVERED',
    OWNER_RESULT_CODE VARCHAR(80) NULL COMMENT 'Owner 응답 코드',
    OWNER_RESULT_MESSAGE VARCHAR(1000) NULL COMMENT '마스킹된 Owner 응답 메시지',
    STARTED_AT DATETIME(3) NULL COMMENT '실행 시작시각',
    COMPLETED_AT DATETIME(3) NULL COMMENT '실행 종료시각',
    RECOVERY_REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '결과불명/복구 필요 여부',
    created_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '등록자',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '등록일시',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'ADM' COMMENT '수정자',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정일시',
    PRIMARY KEY (APPROVAL_REQUEST_ID),
    UNIQUE KEY uk_adm_approval_execution_command (COMMAND_REQUEST_ID),
    INDEX ix_adm_approval_execution_recovery (RECOVERY_REQUIRED_YN, EXECUTION_STATUS),
    CONSTRAINT fk_adm_approval_execution_request FOREIGN KEY (APPROVAL_REQUEST_ID)
        REFERENCES adm_approval_request(APPROVAL_REQUEST_ID),
    CONSTRAINT ck_adm_approval_execution_status CHECK (
        EXECUTION_STATUS IN ('PENDING','RUNNING','SUCCEEDED','FAILED','UNKNOWN','RECOVERED')
    ),
    CONSTRAINT ck_adm_approval_execution_recovery CHECK (RECOVERY_REQUIRED_YN IN ('Y','N')),
    CONSTRAINT ck_adm_approval_execution_time CHECK (
        COMPLETED_AT IS NULL OR STARTED_AT IS NULL OR COMPLETED_AT >= STARTED_AT
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ADM 승인 후 Owner Command 실행 상태';
