-- ADM administration schema.
-- Target DB: admDB

USE admDB;

CREATE TABLE IF NOT EXISTS operator_user (
    OPERATOR_ID VARCHAR(50) NOT NULL,
    OPERATOR_NAME VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(512) NOT NULL,
    LOCKED_YN CHAR(1) NOT NULL DEFAULT 'N',
    FAIL_COUNT INT NOT NULL DEFAULT 0,
    PASSWORD_CHANGED_AT DATETIME NULL,
    PASSWORD_CHANGE_REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (OPERATOR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_role (
    ROLE_ID VARCHAR(50) NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_user_role (
    OPERATOR_ID VARCHAR(50) NOT NULL,
    ROLE_ID VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (OPERATOR_ID, ROLE_ID),
    CONSTRAINT FK_OPERATOR_USER_ROLE_USER
        FOREIGN KEY (OPERATOR_ID) REFERENCES operator_user(OPERATOR_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_OPERATOR_USER_ROLE_ROLE
        FOREIGN KEY (ROLE_ID) REFERENCES operator_role(ROLE_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_menu (
    MENU_ID VARCHAR(50) NOT NULL,
    PARENT_MENU_ID VARCHAR(50) NULL,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_PATH VARCHAR(200) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MENU_ID),
    INDEX IX_OPERATOR_MENU_PARENT (PARENT_MENU_ID, SORT_ORDER),
    CONSTRAINT FK_OPERATOR_MENU_PARENT
        FOREIGN KEY (PARENT_MENU_ID) REFERENCES operator_menu(MENU_ID)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_role_menu (
    ROLE_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(50) NOT NULL,
    READ_YN CHAR(1) NOT NULL DEFAULT 'Y',
    WRITE_YN CHAR(1) NOT NULL DEFAULT 'N',
    DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID, MENU_ID),
    CONSTRAINT FK_OPERATOR_ROLE_MENU_ROLE
        FOREIGN KEY (ROLE_ID) REFERENCES operator_role(ROLE_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_OPERATOR_ROLE_MENU_MENU
        FOREIGN KEY (MENU_ID) REFERENCES operator_menu(MENU_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_audit_log (
    AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT,
    TRANSACTION_ID VARCHAR(80) NULL,
    TRACE_ID VARCHAR(80) NULL,
    OPERATOR_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(50) NULL,
    ACTION_TYPE VARCHAR(30) NOT NULL,
    TARGET_TYPE VARCHAR(50) NULL,
    TARGET_ID VARCHAR(100) NULL,
    REASON VARCHAR(500) NULL,
    REQUEST_BODY LONGTEXT NULL,
    CLIENT_IP VARCHAR(50) NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (AUDIT_ID),
    INDEX IX_OPERATOR_AUDIT_TX (TRANSACTION_ID),
    INDEX IX_OPERATOR_AUDIT_OPERATOR_TIME (OPERATOR_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operator_session (
    SESSION_ID VARCHAR(80) NOT NULL,
    TOKEN_HASH VARCHAR(512) NOT NULL,
    OPERATOR_ID VARCHAR(50) NOT NULL,
    ROLE_IDS VARCHAR(1000) NULL,
    ISSUED_AT DATETIME NOT NULL,
    EXPIRE_AT DATETIME NOT NULL,
    REVOKED_YN CHAR(1) NOT NULL DEFAULT 'N',
    CLIENT_IP VARCHAR(50) NULL,
    USER_AGENT VARCHAR(500) NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SESSION_ID),
    INDEX IX_OPERATOR_SESSION_TOKEN (TOKEN_HASH),
    INDEX IX_OPERATOR_SESSION_USER (OPERATOR_ID, EXPIRE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dynamic_log_level_rule (
    RULE_ID VARCHAR(80) NOT NULL,
    TRANSACTION_ID VARCHAR(100) NULL,
    BUSINESS_TRANSACTION_ID VARCHAR(20) NULL,
    MODULE_ID VARCHAR(10) NULL,
    LOG_LEVEL VARCHAR(10) NOT NULL,
    EXPIRE_AT DATETIME NOT NULL,
    REASON VARCHAR(500) NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADM',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RULE_ID),
    INDEX IX_DYNAMIC_LOG_BIZ_TX (BUSINESS_TRANSACTION_ID, EXPIRE_AT),
    INDEX IX_DYNAMIC_LOG_TX (TRANSACTION_ID, EXPIRE_AT),
    INDEX IX_DYNAMIC_LOG_ACTIVE (USE_YN, EXPIRE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

