-- ADM initial roles, menus, permissions, and local/test account.
-- Target DB: admDB

USE admDB;

INSERT INTO operator_role (ROLE_ID, ROLE_NAME, DESCRIPTION, USE_YN, CREATED_BY, UPDATED_BY)
VALUES
    ('ADM_ADMIN', 'Framework Administrator', 'Can manage every ADM menu and operation.', 'Y', 'SYSTEM', 'SYSTEM'),
    ('ADM_OPERATOR', 'Operations User', 'Can query logs, refresh caches, and manage dynamic log levels.', 'Y', 'SYSTEM', 'SYSTEM'),
    ('ADM_VIEWER', 'Read Only User', 'Can query logs and settings without changing data.', 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    ROLE_NAME = VALUES(ROLE_NAME),
    DESCRIPTION = VALUES(DESCRIPTION),
    USE_YN = VALUES(USE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_menu (MENU_ID, PARENT_MENU_ID, MENU_NAME, MENU_PATH, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY)
VALUES
    ('DASHBOARD', NULL, 'Dashboard', '/adm', 10, 'Y', 'SYSTEM', 'SYSTEM'),
    ('LOG_LIST', NULL, 'Transaction Logs', '/adm#logs', 20, 'Y', 'SYSTEM', 'SYSTEM'),
    ('CACHE', NULL, 'Cache Management', '/adm#cache', 30, 'Y', 'SYSTEM', 'SYSTEM'),
    ('RESPONSE_CODE', NULL, 'Response Codes', '/adm#response-codes', 40, 'Y', 'SYSTEM', 'SYSTEM'),
    ('DYNAMIC_LOG', NULL, 'Dynamic Log Level', '/adm#log-level', 50, 'Y', 'SYSTEM', 'SYSTEM'),
    ('AUDIT_LOG', NULL, 'Audit Logs', '/adm#audit-logs', 60, 'Y', 'SYSTEM', 'SYSTEM'),
    ('OPERATOR', NULL, 'Operator Management', '/adm#operators', 70, 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    PARENT_MENU_ID = VALUES(PARENT_MENU_ID),
    MENU_NAME = VALUES(MENU_NAME),
    MENU_PATH = VALUES(MENU_PATH),
    SORT_ORDER = VALUES(SORT_ORDER),
    USE_YN = VALUES(USE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_user (
    OPERATOR_ID,
    OPERATOR_NAME,
    PASSWORD_HASH,
    LOCKED_YN,
    FAIL_COUNT,
    PASSWORD_CHANGED_AT,
    PASSWORD_CHANGE_REQUIRED_YN,
    USE_YN,
    CREATED_BY,
    UPDATED_BY
) VALUES (
    'admin',
    'Local Administrator',
    'PBKDF2$120000$AQIDBAUGBwgJCgsMDQ4PEA==$cjgjgGQwgcZ0+fFaA8Z4qBJkZfszRZ73BSBIMXAJkqI=',
    'N',
    0,
    DATE_SUB(NOW(), INTERVAL 91 DAY),
    'Y',
    'Y',
    'SYSTEM',
    'SYSTEM'
)
ON DUPLICATE KEY UPDATE
    OPERATOR_NAME = VALUES(OPERATOR_NAME),
    PASSWORD_HASH = VALUES(PASSWORD_HASH),
    LOCKED_YN = VALUES(LOCKED_YN),
    FAIL_COUNT = VALUES(FAIL_COUNT),
    PASSWORD_CHANGE_REQUIRED_YN = VALUES(PASSWORD_CHANGE_REQUIRED_YN),
    USE_YN = VALUES(USE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_user_role (OPERATOR_ID, ROLE_ID, CREATED_BY, UPDATED_BY)
VALUES ('admin', 'ADM_ADMIN', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_role_menu (ROLE_ID, MENU_ID, READ_YN, WRITE_YN, DELETE_YN, CREATED_BY, UPDATED_BY)
SELECT 'ADM_ADMIN', MENU_ID, 'Y', 'Y', 'Y', 'SYSTEM', 'SYSTEM'
FROM operator_menu
ON DUPLICATE KEY UPDATE
    READ_YN = VALUES(READ_YN),
    WRITE_YN = VALUES(WRITE_YN),
    DELETE_YN = VALUES(DELETE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_role_menu (ROLE_ID, MENU_ID, READ_YN, WRITE_YN, DELETE_YN, CREATED_BY, UPDATED_BY)
SELECT 'ADM_OPERATOR', MENU_ID, 'Y',
       CASE WHEN MENU_ID IN ('CACHE', 'DYNAMIC_LOG') THEN 'Y' ELSE 'N' END,
       CASE WHEN MENU_ID = 'DYNAMIC_LOG' THEN 'Y' ELSE 'N' END,
       'SYSTEM', 'SYSTEM'
FROM operator_menu
WHERE MENU_ID NOT IN ('OPERATOR', 'RESPONSE_CODE')
ON DUPLICATE KEY UPDATE
    READ_YN = VALUES(READ_YN),
    WRITE_YN = VALUES(WRITE_YN),
    DELETE_YN = VALUES(DELETE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_role_menu (ROLE_ID, MENU_ID, READ_YN, WRITE_YN, DELETE_YN, CREATED_BY, UPDATED_BY)
SELECT 'ADM_VIEWER', MENU_ID, 'Y', 'N', 'N', 'SYSTEM', 'SYSTEM'
FROM operator_menu
WHERE MENU_ID NOT IN ('DYNAMIC_LOG', 'OPERATOR', 'RESPONSE_CODE', 'AUDIT_LOG')
ON DUPLICATE KEY UPDATE
    READ_YN = VALUES(READ_YN),
    WRITE_YN = VALUES(WRITE_YN),
    DELETE_YN = VALUES(DELETE_YN),
    UPDATED_BY = VALUES(UPDATED_BY),
    UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO operator_audit_log (
    TRANSACTION_ID,
    TRACE_ID,
    OPERATOR_ID,
    MENU_ID,
    ACTION_TYPE,
    TARGET_TYPE,
    TARGET_ID,
    REASON,
    REQUEST_BODY,
    CLIENT_IP,
    CREATED_BY,
    UPDATED_BY
) VALUES (
    'INITIAL_SQL_SEED',
    'INITIAL_SQL_SEED',
    'admin',
    'DASHBOARD',
    'SEED',
    'ADM',
    'INITIAL_DATA',
    'Initial ADM seed data registered.',
    NULL,
    '127.0.0.1',
    'SYSTEM',
    'SYSTEM'
);
