#!/usr/bin/env python3
"""Generate fail-closed REF overlay verify SQL from canonical source DDL."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


def fail(message: str) -> None:
    print(f"[CPF][REF-DB-VERIFY-GENERATOR][FAIL] {message}", file=sys.stderr)
    raise SystemExit(1)


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"JSON read failed: {path}: {exc}")
    if not isinstance(value, dict):
        fail(f"JSON root must be an object: {path}")
    return value


def identifiers(sql: str, pattern: str) -> tuple[str, ...]:
    values = tuple(match.upper() for match in re.findall(pattern, sql, re.IGNORECASE))
    if len(values) != len(set(values)):
        fail(f"Canonical source has duplicate identifiers for pattern: {pattern}")
    return values


def sql_list(values: tuple[str, ...]) -> str:
    return ",".join(f"'{value}'" for value in values)


def render_mariadb(pack_name: str, tables: tuple[str, ...], indexes: tuple[str, ...], constraints: tuple[str, ...]) -> str:
    prefix = f"cpf_ref_{pack_name}"
    message = f"CPF reference {pack_name} schema verification failed"
    return f"""-- Generated by cpf-tools/generator/generate-reference-db-verify.py. Do not edit directly.
SET @{prefix}_table_count := (
  SELECT COUNT(*) FROM information_schema.tables
   WHERE table_schema = DATABASE() AND UPPER(table_name) IN ({sql_list(tables)})
);
SET @{prefix}_index_count := (
  SELECT COUNT(DISTINCT UPPER(index_name)) FROM information_schema.statistics
   WHERE table_schema = DATABASE() AND UPPER(index_name) IN ({sql_list(indexes)})
);
SET @{prefix}_constraint_count := (
  SELECT COUNT(*) FROM information_schema.table_constraints
   WHERE table_schema = DATABASE() AND UPPER(constraint_name) IN ({sql_list(constraints)})
);
SET @{prefix}_assert_sql := IF(
  @{prefix}_table_count = {len(tables)}
  AND @{prefix}_index_count = {len(indexes)}
  AND @{prefix}_constraint_count = {len(constraints)},
  'SELECT 1',
  'SIGNAL SQLSTATE ''45000'' SET MESSAGE_TEXT = ''{message}'''
);
PREPARE cpf_ref_verify_statement FROM @{prefix}_assert_sql;
EXECUTE cpf_ref_verify_statement;
DEALLOCATE PREPARE cpf_ref_verify_statement;
SELECT 'reference_{pack_name}_schema' AS check_name, 1 AS passed;
"""


def render_postgresql(pack_name: str, tables: tuple[str, ...], indexes: tuple[str, ...], constraints: tuple[str, ...]) -> str:
    message = f"CPF reference {pack_name} schema verification failed"
    return f"""-- Generated by cpf-tools/generator/generate-reference-db-verify.py. Do not edit directly.
DO $$
DECLARE
  v_table_count INTEGER;
  v_index_count INTEGER;
  v_constraint_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_table_count FROM information_schema.tables
   WHERE table_schema = current_schema() AND UPPER(table_name) IN ({sql_list(tables)});
  SELECT COUNT(*) INTO v_index_count FROM pg_indexes
   WHERE schemaname = current_schema() AND UPPER(indexname) IN ({sql_list(indexes)});
  SELECT COUNT(*) INTO v_constraint_count FROM information_schema.table_constraints
   WHERE constraint_schema = current_schema() AND UPPER(constraint_name) IN ({sql_list(constraints)});
  IF v_table_count <> {len(tables)} OR v_index_count <> {len(indexes)} OR v_constraint_count <> {len(constraints)} THEN
    RAISE EXCEPTION '{message}: tables=% indexes=% constraints=%', v_table_count, v_index_count, v_constraint_count;
  END IF;
END $$;
SELECT 'reference_{pack_name}_schema' AS check_name, 1 AS passed;
"""


def render_oracle(pack_name: str, tables: tuple[str, ...], indexes: tuple[str, ...], constraints: tuple[str, ...]) -> str:
    message = f"CPF reference {pack_name} schema verification failed"
    return f"""-- Generated by cpf-tools/generator/generate-reference-db-verify.py. Do not edit directly.
DECLARE
  V_TABLE_COUNT NUMBER;
  V_INDEX_COUNT NUMBER;
  V_CONSTRAINT_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_TABLE_COUNT FROM USER_TABLES WHERE TABLE_NAME IN ({sql_list(tables)});
  SELECT COUNT(*) INTO V_INDEX_COUNT FROM USER_INDEXES WHERE INDEX_NAME IN ({sql_list(indexes)});
  SELECT COUNT(*) INTO V_CONSTRAINT_COUNT FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME IN ({sql_list(constraints)});
  IF V_TABLE_COUNT <> {len(tables)} OR V_INDEX_COUNT <> {len(indexes)} OR V_CONSTRAINT_COUNT <> {len(constraints)} THEN
    RAISE_APPLICATION_ERROR(-20994, '{message}');
  END IF;
END;
/
SELECT 'reference_{pack_name}_schema' AS check_name, 1 AS passed FROM DUAL;
"""


RENDERERS = {
    "mariadb": render_mariadb,
    "postgresql": render_postgresql,
    "oracle": render_oracle,
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    contract = load_json(root / "cpf-tools/generator/contracts/education-reference-fixture-contract.json")
    policy = contract.get("verificationPolicy")
    if not isinstance(policy, dict) or policy.get("failClosed") is not True:
        fail("Canonical verificationPolicy.failClosed must be true")

    changed: list[str] = []
    signatures: dict[str, dict[str, tuple[tuple[str, ...], ...]]] = {}
    for vendor in contract.get("requiredVendors", ()):
        if vendor not in RENDERERS:
            fail(f"Unsupported official vendor: {vendor}")
        vendor_base = root / f"cpf-tools/db/vendor/{vendor}"
        signatures[vendor] = {}
        for pack_name, metadata in contract["featurePacks"].items():
            artifacts = metadata["artifacts"]
            source = vendor_base / artifacts["source"]
            target = vendor_base / artifacts["verify"]
            if not source.is_file():
                fail(f"Canonical source missing: {source.relative_to(root)}")
            sql = source.read_text(encoding="utf-8")
            tables = identifiers(sql, r"\bCREATE\s+TABLE\s+([A-Za-z][A-Za-z0-9_$#]*)")
            indexes = identifiers(sql, r"\bCREATE\s+(?:UNIQUE\s+)?INDEX\s+([A-Za-z][A-Za-z0-9_$#]*)")
            constraints = identifiers(sql, r"\bCONSTRAINT\s+([A-Za-z][A-Za-z0-9_$#]*)")
            expected_tables = {str(table).upper() for table in metadata["tables"]}
            if set(tables) != expected_tables:
                fail(f"Canonical source table set differs from ownership metadata: {vendor}/{pack_name}")
            if not indexes or not constraints:
                fail(f"Canonical source index/constraint metadata is empty: {vendor}/{pack_name}")
            signatures[vendor][pack_name] = (tables, indexes, constraints)
            rendered = RENDERERS[vendor](pack_name, tables, indexes, constraints)
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != rendered:
                changed.append(str(target.relative_to(root)).replace("\\", "/"))
                if args.apply:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(rendered, encoding="utf-8", newline="\n")

    reference_vendor = next(iter(signatures))
    reference_signature = signatures[reference_vendor]
    for vendor, signature in signatures.items():
        if signature != reference_signature:
            fail(f"Cross-vendor logical DDL object names differ: {reference_vendor}/{vendor}")
    if changed and not args.apply:
        fail("Generated verify SQL drift: " + ", ".join(changed))
    status = "UPDATED" if changed else "PASS"
    print(f"[CPF][REF-DB-VERIFY-GENERATOR][{status}] vendors={len(signatures)} packs=2 changed={len(changed)}")


if __name__ == "__main__":
    main()
