plugins { id 'java-library'; id 'maven-publish' }
group='com.cpf.starter'
dependencies {
    api project(':framework:base-runtime')
    api project(':framework:security')
    api project(':framework:core')
    api 'org.springframework.boot:spring-boot-starter-oauth2-client'
    api 'jakarta.servlet:jakarta.servlet-api'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core'
}
tasks.named('test'){useJUnitPlatform()}
publishing { publications { mavenJava(MavenPublication){from components.java;artifactId = 'cpf-starter-oidc'} } }
