import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const batchRoutes = {
  "batch": { routeId: "batch", path: "/batch", menuId: "BATCH", label: "Batch / Center-Cut", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch.enabled", expectedOperationIds: ["admBatchFindJobs", "admBatchFindSchedules", "admBatchFindExecutionPage", "admBatchFindInstances", "admBatchFindWorkers", "admBatchWorkbenchJobDetail", "admBatchFindExecutionTargets", "admBatchFindExecutions", "admBatchRegisterJob", "admBatchFindJobDetail", "admBatchRunJob", "admBatchFindRelations"], component: defineAsyncComponent(() => import("../../features/batch/BatchPage.vue")), props: undefined },
  "batch-overview": { routeId: "batch-overview", path: "/batch-overview", menuId: "BATCH_OVERVIEW", label: "Batch Overview", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-overview.enabled", expectedOperationIds: ["admBatchWorkbenchOverview", "admBatchFindJobs", "admBatchFindSchedules", "admBatchFindExecutionPage", "admBatchFindInstances", "admBatchFindWorkers", "admBatchFindLocks"], component: defineAsyncComponent(() => import("../../features/batch-overview/BatchOverviewPage.vue")), props: undefined },
  "batch-runtime": { routeId: "batch-runtime", path: "/batch-runtime", menuId: "BATCH_RUNTIME", label: "Runtime Topology", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.batch-runtime.enabled", expectedOperationIds: ["admBatchRuntimeInstances", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../../features/batch-runtime-control/RuntimeTopologyPage.vue")), props: undefined },
  "batch-instances": { routeId: "batch-instances", path: "/batch-instances", menuId: "BATCH_INSTANCES", label: "Runtime Instances", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-instances.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchFindInstances", "admBatchRuntimeInstances", "admBatchRuntimeView"], component: defineAsyncComponent(() => import("../../features/batch-instances/BatchInstancesPage.vue")), props: undefined },
  "batch-scheduler": { routeId: "batch-scheduler", path: "/batch-scheduler", menuId: "BATCH_SCHEDULER", label: "Scheduler HA", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-scheduler.enabled", expectedOperationIds: ["admBatchWorkbenchSchedules", "admBatchFindSchedules", "admBatchSimulateSchedule", "admBatchEnableSchedule", "admBatchDisableSchedule", "admBatchRunSchedulerOnce"], component: defineAsyncComponent(() => import("../../features/batch-scheduler/BatchSchedulerPage.vue")), props: undefined },
  "batch-worker-pools": { routeId: "batch-worker-pools", path: "/batch-worker-pools", menuId: "BATCH_WORKER_POOLS", label: "Worker Pools", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-worker-pools.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchFindWorkers", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../../features/batch-worker-pools/BatchWorkerPoolsPage.vue")), props: undefined },
  "batch-center-cut": { routeId: "batch-center-cut", path: "/batch-center-cut", menuId: "BATCH_CENTER_CUT", label: "Center-Cut", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-center-cut.enabled", expectedOperationIds: ["admCenterCutFindSummary", "admCenterCutFindJobs", "admCenterCutFindJobDetail", "admCenterCutFindResults", "admCenterCutFindResultDetail", "admCenterCutFindTargets", "admCenterCutFindParameters", "admCenterCutReprocessFailedExecution", "admCenterCutReconcileUnknownExecution"], component: defineAsyncComponent(() => import("../../features/batch-center-cut/BatchCenterCutPage.vue")), props: undefined },
  "batch-agents": { routeId: "batch-agents", path: "/batch-agents", menuId: "BATCH_AGENTS", label: "Host Agents", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-agents.enabled", expectedOperationIds: ["admBatchWorkbenchInfrastructure", "admBatchRuntimeInstances", "admBatchRuntimeView", "admBatchRuntimeCommand", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../../features/batch-agents/BatchAgentsPage.vue")), props: undefined },
  "batch-job-packs": { routeId: "batch-job-packs", path: "/batch-job-packs", menuId: "BATCH_JOB_PACKS", label: "Job Packs", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-job-packs.enabled", expectedOperationIds: ["admBatchWorkbenchJobDetail", "admBatchWorkbenchJobs", "admBatchJobDefinitions", "admBatchJobDefinitionDetail", "admBatchJobDefinitionValidate", "admBatchJobDefinitionSave", "admBatchJobDefinitionTransition", "admBatchFindJobs"], component: defineAsyncComponent(() => import("../../features/batch-job-packs/BatchJobPacksPage.vue")), props: undefined },
  "batch-executions": { routeId: "batch-executions", path: "/batch-executions", menuId: "BATCH_EXECUTIONS", label: "Executions", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-executions.enabled", expectedOperationIds: ["admBatchWorkbenchExecutionDetail", "admBatchWorkbenchExecutions", "admBatchFindExecutionPage", "admBatchFindExecutionDetail", "admBatchFindStepExecutions", "admBatchRetryExecution", "admBatchStopExecution"], component: defineAsyncComponent(() => import("../../features/batch-executions/BatchExecutionsPage.vue")), props: undefined },
  "batch-deployment": { routeId: "batch-deployment", path: "/batch-deployment", menuId: "BATCH_DEPLOYMENT", label: "Deployment / Rollback", group: "batch", icon: "batch", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.batch-deployment.enabled", expectedOperationIds: ["admBatchRuntimeCreateDeploymentPlan", "admBatchRuntimeView", "admBatchRuntimeCommandState"], component: defineAsyncComponent(() => import("../../features/batch-deployment/BatchDeploymentPage.vue")), props: undefined },
  "batch-recovery": { routeId: "batch-recovery", path: "/batch-recovery", menuId: "BATCH_RECOVERY", label: "Recovery / Unknown", group: "batch", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-recovery.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchRuntimeView", "admBatchFindGhostCandidates", "admBatchActGhostExecution", "findAdmUnknownResults", "resolveAdmUnknownResult"], component: defineAsyncComponent(() => import("../../features/batch-recovery/BatchRecoveryPage.vue")), props: undefined },
  "batch-leases": { routeId: "batch-leases", path: "/batch-leases", menuId: "BATCH_LEASES", label: "Lease / Fencing", group: "batch", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-leases.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchRuntimeView", "admBatchFindLocks", "admBatchReleaseLock"], component: defineAsyncComponent(() => import("../../features/batch-leases/BatchLeasesPage.vue")), props: undefined },
  "batch-alerts": { routeId: "batch-alerts", path: "/batch-alerts", menuId: "BATCH_ALERTS", label: "Batch Alerts", group: "batch", icon: "incident", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-alerts.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "admBatchFindOperationLogs"], component: defineAsyncComponent(() => import("../../features/batch-alerts/BatchAlertsPage.vue")), props: undefined },
  "batch-audit": { routeId: "batch-audit", path: "/batch-audit", menuId: "BATCH_AUDIT", label: "Audit / Evidence", group: "batch", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.batch-audit.enabled", expectedOperationIds: ["admBatchWorkbenchRecovery", "admBatchFindOperationLogs", "admAuditLogFindAuditLogs", "admAuditDeliveryList", "getAdmBatchJobInstanceLog"], component: defineAsyncComponent(() => import("../../features/batch-audit/BatchAuditEvidencePage.vue")), props: undefined },
  "batch-retention": { routeId: "batch-retention", path: "/batch-retention", menuId: "LOG_POLICY", label: "Logging / Retention", group: "batch", icon: "logs", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.batch-runtime.enabled", expectedOperationIds: ["admRetentionPolicies", "admRetentionRuns", "admRetentionPolicySave", "admRetentionPreview", "admRetentionRunNow", "admRetentionRunPause", "admRetentionRunResume", "admRetentionPolicyPause", "admRetentionPolicyResume"], component: defineAsyncComponent(() => import("../../features/batch-runtime-control/RetentionWorkbench.vue")), props: undefined },
  "workers": { routeId: "workers", path: "/workers", menuId: "WORKER", label: "Agent / Worker", group: "batch", icon: "worker", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.workers.enabled", expectedOperationIds: ["admBatchFindWorkers", "admBatchFindInstances", "admBatchRuntimeInstances"], component: defineAsyncComponent(() => import("../../features/workers/WorkersPage.vue")), props: undefined },
  "file-jobs": { routeId: "file-jobs", path: "/file-jobs", menuId: "FILE_JOB", label: "대량파일 Job", group: "batch", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.file-jobs.enabled", expectedOperationIds: ["admFileJobList", "admFileJobDetail", "admFileJobRows", "admFileJobUpload", "admFileJobArtifact", "admApprovalRequest"], component: defineAsyncComponent(() => import("../../features/file-jobs/FileJobsPage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
