import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const configPolicyRoutes = {
  "operations-governance": { routeId: "operations-governance", path: "/operations-governance", menuId: "OPS_GOVERNANCE", label: "운영 정책·SLO", group: "configPolicy", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.operations-governance.enabled", expectedOperationIds: ["admOperationsGovernanceSnapshot"], component: defineAsyncComponent(() => import("../../features/operations/OperationsGovernancePage.vue")), props: undefined },
  "logLevel": { routeId: "logLevel", path: "/logLevel", menuId: "DYNAMIC_LOG", label: "동적 로그", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.logLevel.enabled", expectedOperationIds: ["admDynamicLogLevelFindRules", "admApprovalRequest"], component: defineAsyncComponent(() => import("../../features/log-level/LogLevelPage.vue")), props: undefined },
  "logPolicies": { routeId: "logPolicies", path: "/logPolicies", menuId: "LOG_POLICY", label: "로그 정책", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.logPolicies.enabled", expectedOperationIds: ["admLogPolicyFindPolicies", "admLogPolicyFindPolicy", "admLogPolicyCreatePolicy", "admLogPolicyUpdatePolicy", "admLogPolicyDisablePolicy", "admLogPolicyDistributionStatus", "admLogPolicyClearCache", "admLogPolicyRefreshCache", "admLogPolicyFindTraceBoostHistory", "admLogPolicyCreateOverride", "admLogPolicyDisableOverride", "admLogPolicyFindTraceBoostRuntimeState", "admLogPolicyCreateTraceBoost"], component: defineAsyncComponent(() => import("../../features/log-policies/LogPoliciesPage.vue")), props: undefined },
  "channelPolicy": { routeId: "channelPolicy", path: "/channelPolicy", menuId: "CHANNEL_POLICY", label: "채널 정책", group: "configPolicy", icon: "service", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.channelPolicy.enabled", expectedOperationIds: ["admChannelFindSnapshot", "admChannelRefreshSnapshot", "admChannelSave", "admChannelSaveExecutionPolicy", "admChannelExportPackage", "admChannelImportPackage"], component: defineAsyncComponent(() => import("../../features/channel-policy/ChannelPolicyPage.vue")), props: undefined },
  "cache": { routeId: "cache", path: "/cache", menuId: "CACHE", label: "캐시", group: "configPolicy", icon: "service", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.cache.enabled", expectedOperationIds: ["admCacheSummary", "admApprovalRequest"], component: defineAsyncComponent(() => import("../../features/cache/CachePage.vue")), props: undefined },
  "configs": { routeId: "configs", path: "/configs", menuId: "CONFIG", label: "설정", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.configs.enabled", expectedOperationIds: ["admConfigFindConfigs", "admConfigFindConfig", "admConfigCreateConfig", "admConfigUpdateConfig", "admConfigDeleteConfig", "admParameterReferenceSearch"], component: defineAsyncComponent(() => import("../../features/configs/ConfigsPage.vue")), props: undefined },
  "responseCodes": { routeId: "responseCodes", path: "/responseCodes", menuId: "RESPONSE_CODE", label: "응답코드", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.responseCodes.enabled", expectedOperationIds: ["admResponseCodeFindAll", "admResponseCodeFindOne", "admResponseCodeCreate", "admResponseCodeUpdate", "admResponseCodeDelete"], component: defineAsyncComponent(() => import("../../features/response-codes/ResponseCodesPage.vue")), props: undefined },
  "businessCalendar": { routeId: "businessCalendar", path: "/businessCalendar", menuId: "BUSINESS_CALENDAR", label: "영업일 · 휴일", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.businessCalendar.enabled", expectedOperationIds: ["admCalendarFindDays", "admCalendarResolveDate", "admCalendarSaveDay", "admCalendarDeleteDay"], component: defineAsyncComponent(() => import("../../features/business-calendar/BusinessCalendarPage.vue")), props: undefined },
  "messages": { routeId: "messages", path: "/messages", menuId: "MESSAGE", label: "전문·Protocol Message", group: "configPolicy", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.messages.enabled", expectedOperationIds: ["admMessageFindMessages", "admMessageFindMessage", "admMessageCreateMessage", "admMessageUpdateMessage", "admMessageDeleteMessage", "traceAdmByTransactionId"], component: defineAsyncComponent(() => import("../../features/operations/ProtocolMessageWorkbenchPage.vue")), props: undefined },
  "codes": { routeId: "codes", path: "/codes", menuId: "CODE", label: "코드", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.codes.enabled", expectedOperationIds: ["admCodeFindCodes", "admCodeFindCode", "admCodeCreateCode", "admCodeUpdateCode", "admCodeDeleteCode"], component: defineAsyncComponent(() => import("../../features/codes/CodesPage.vue")), props: undefined },
  "featureFlags": { routeId: "featureFlags", path: "/featureFlags", menuId: "FEATURE_FLAG", label: "Feature Flag", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.featureFlags.enabled", expectedOperationIds: ["admFeatureFlagSearch", "admFeatureFlagFind", "admFeatureFlagEvaluate", "admFeatureFlagRequestOverride", "admFeatureFlagApproveOverride", "admFeatureFlagRevokeOverride", "admApprovalRequest"], component: defineAsyncComponent(() => import("../../features/feature-flags/FeatureFlagsPage.vue")), props: undefined },
  "openApiOperations": { routeId: "openApiOperations", path: "/openApiOperations", menuId: "OPENAPI_OPERATIONS", label: "OpenAPI 운영", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.openApiOperations.enabled", expectedOperationIds: ["admOpenApiStatus", "admOpenApiRefresh"], component: defineAsyncComponent(() => import("../../features/openapi-operations/OpenApiOperationsPage.vue")), props: undefined },
  "resiliencePolicies": { routeId: "resiliencePolicies", path: "/resiliencePolicies", menuId: "RESILIENCE_POLICY", label: "Resilience 정책", group: "configPolicy", icon: "settings", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.resiliencePolicies.enabled", expectedOperationIds: ["admResiliencePolicySearch", "admResiliencePolicyFind", "admResiliencePolicyRequest", "admResiliencePolicyApprove", "admResiliencePolicyReject"], component: defineAsyncComponent(() => import("../../features/resilience-policies/ResiliencePoliciesPage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
