import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const failureRecoveryRoutes = {
  "recoveryCenter": { routeId: "recoveryCenter", path: "/recoveryCenter", menuId: "RECOVERY_CENTER", label: "복구 센터", group: "failureRecovery", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.recoveryCenter.enabled", expectedOperationIds: ["getAdmTransactionLogRecoveryStatus", "runAdmTransactionLogRecovery", "retryAdmTraceRecoveryPoison", "resolveAdmUnknownResult", "requestAdmBrokerDlqReplay"], component: defineAsyncComponent(() => import("../../features/recovery-center/RecoveryCenterPage.vue")), props: undefined },
  "incidents": { routeId: "incidents", path: "/incidents", menuId: "INCIDENT", label: "Error·Unknown Result", group: "failureRecovery", icon: "incident", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.incidents.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "requestAdmBrokerDlqReplay", "resolveAdmUnknownResult", "getAdmTransactionLogRecoveryStatus", "runAdmTransactionLogRecovery", "admIncidentFindIncidents", "admIncidentFindMaintenance", "admIncidentFindPolicies", "admIncidentIngestSignal", "admIncidentCreateMaintenance", "admIncidentUpdateMaintenance", "admIncidentCreatePolicy", "admIncidentUpdatePolicy", "admIncidentFindIncident", "admIncidentAcknowledge", "admIncidentEscalate", "admIncidentReopen", "admIncidentResolve", "admIncidentRecordPostmortem", "admIncidentFindTimeline"], component: defineAsyncComponent(() => import("../../features/operations/ErrorWorkbenchPage.vue")), props: undefined },
  "reliability": { routeId: "reliability", path: "/reliability", menuId: "RELIABILITY", label: "Analysis Center", group: "failureRecovery", icon: "recovery", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.reliability.enabled", expectedOperationIds: ["findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "findAdmBrokerInbox", "findAdmIdempotencyRecords", "findAdmFileTransferHistory", "getAdmTransactionLogRecoveryStatus", "findAdmBatchJobInstanceLogs"], component: defineAsyncComponent(() => import("../../features/operations/AnalysisCenterPage.vue")), props: undefined },
  "integrationClosure": { routeId: "integrationClosure", path: "/integrationClosure", menuId: "INTEGRATION_CLOSURE", label: "통합 운영 정정 승인", group: "failureRecovery", icon: "approval", ownerModule: "cpf-admin", riskLevel: "CRITICAL", featureFlag: "adm.route.integrationClosure.enabled", expectedOperationIds: ["admIntegrationCryptoStatus", "admIntegrationTimeHealth", "admIntegrationDataQualityValidate", "admIntegrationDataQualityCorrectionApprovalRequest", "admIntegrationDataQualityCorrectionExecute", "admIntegrationDataQualityReplay", "admIntegrationWebhookDlq", "admIntegrationWebhookReplay"], component: defineAsyncComponent(() => import("../../features/integration-closure/IntegrationClosurePage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
