import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const gatewayRoutes = {
  "gateway-dashboard": { routeId: "gateway-dashboard", path: "/gateway-dashboard", menuId: "GATEWAY_DASHBOARD", label: "Gateway 대시보드", group: "gateway", icon: "dashboard", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-dashboard.enabled", expectedOperationIds: ["admGatewayCapability", "admGatewayOperationsSnapshot", "admGatewayOperationsEvents", "admGatewayOperationsStream"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "dashboard" } },
  "gateway-servers": { routeId: "gateway-servers", path: "/gateway-servers", menuId: "GATEWAY_SERVERS", label: "Gateway 연동 서버", group: "gateway", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-servers.enabled", expectedOperationIds: ["admGatewayFindServerGroups", "admGatewayFindGroupMembers", "admGatewaySaveServerGroup", "admGatewayDeleteServerGroup"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "servers" } },
  "gateway-groups": { routeId: "gateway-groups", path: "/gateway-groups", menuId: "GATEWAY_GROUPS", label: "Gateway 서버 그룹", group: "gateway", icon: "topology", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-groups.enabled", expectedOperationIds: ["admGatewayFindServerGroups", "admGatewayFindGroupMembers", "admGatewaySaveServerGroup", "admGatewayDeleteServerGroup"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "groups" } },
  "gateway-routes": { routeId: "gateway-routes", path: "/gateway-routes", menuId: "GATEWAY_ROUTES", label: "Gateway 경로·라우팅", group: "gateway", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-routes.enabled", expectedOperationIds: ["admGatewayFindBindings", "admGatewaySaveBinding", "admGatewayChangeBindingState", "admGatewayDeleteBinding"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "bindings" } },
  "gateway-security": { routeId: "gateway-security", path: "/gateway-security", menuId: "GATEWAY_SECURITY", label: "Gateway 보안·제한", group: "gateway", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.gateway-security.enabled", expectedOperationIds: ["admGatewayFindBindings", "admGatewaySaveBinding", "admGatewayChangeBindingState"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "security" } },
  "gateway-health": { routeId: "gateway-health", path: "/gateway-health", menuId: "GATEWAY_HEALTH", label: "Gateway Health·연결시험", group: "gateway", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-health.enabled", expectedOperationIds: ["admGatewayCapability", "admGatewayFindApplyStatus", "admGatewayFindConnectionTests", "admGatewayRequestConnectionTest", "admGatewayFindConnectionTestOperation", "admGatewayCancelConnectionTest", "admGatewayRevalidateConnectionTest"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "health" } },
  "gateway-transactions": { routeId: "gateway-transactions", path: "/gateway-transactions", menuId: "GATEWAY_TRANSACTIONS", label: "Gateway 거래 조회", group: "gateway", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-transactions.enabled", expectedOperationIds: ["admGatewayOperationsSnapshot", "admGatewayOperationsEvents", "traceAdmByTransactionId"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "transactions" } },
  "gateway-log-policies": { routeId: "gateway-log-policies", path: "/gateway-log-policies", menuId: "GATEWAY_LOG_POLICY", label: "Gateway 로그 정책", group: "gateway", icon: "settings", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-log-policies.enabled", expectedOperationIds: ["admGatewayOperationsSnapshot", "admLogPolicyFindPolicies", "admLogPolicyDistributionStatus"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "log-policies" } },
  "gateway-apply-status": { routeId: "gateway-apply-status", path: "/gateway-apply-status", menuId: "GATEWAY_APPLY_STATUS", label: "Gateway 적용 상태·이력", group: "gateway", icon: "approval", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.gateway-apply-status.enabled", expectedOperationIds: ["admGatewayFindApplyStatus", "admGatewayOperationsEvents", "admGatewayFindConnectionTestOperation"], component: defineAsyncComponent(() => import("../../features/gateway-operations/GatewayOperationsPage.vue")), props: { initialMode: "apply" } },
} satisfies Record<string, AdmCapabilityRoute>;
