import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const operationsRoutes = {
  "dashboard": { routeId: "dashboard", path: "/", menuId: "DASHBOARD", label: "통합 운영 Dashboard", group: "operations", icon: "dashboard", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.dashboard.enabled", expectedOperationIds: ["admRuntimeControlFindHealth", "admRuntimeControlFindStatus", "findAdmUnknownResults", "findAdmBrokerDlq", "findAdmBrokerOutbox", "admBatchFindExecutionPage", "getAdmReadiness", "getAdmLiveness", "getAdmSystemVersion", "admPlatformVersion"], component: defineAsyncComponent(() => import("../../features/operations/UnifiedOperationsDashboardPage.vue")), props: undefined },
  "capabilities": { routeId: "capabilities", path: "/capabilities", menuId: "CAPABILITY_FLEET", label: "CPF Capability", group: "operations", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.capabilities.enabled", expectedOperationIds: ["admCapabilityManagementOverview", "admCapabilityManagementIssues"], component: defineAsyncComponent(() => import("../../features/capabilities/CapabilityFleetPage.vue")), props: undefined },
  "topology": { routeId: "topology", path: "/topology", menuId: "TOPOLOGY", label: "서비스 토폴로지", group: "operations", icon: "topology", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.topology.enabled", expectedOperationIds: ["admServiceRegistryFindServices", "admServiceRegistryFindInstances", "admServiceRegistryFindEndpoints", "admServiceRegistryFindHealth"], component: defineAsyncComponent(() => import("../../features/topology/TopologyPage.vue")), props: undefined },
  "health-instances": { routeId: "health-instances", path: "/health-instances", menuId: "TOPOLOGY", label: "Runtime Instance Health", group: "operations", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.health-instances.enabled", expectedOperationIds: ["admHealthInstanceList", "admHealthInstanceDetail"], component: defineAsyncComponent(() => import("../../features/health/InstanceHealthPage.vue")), props: undefined },
  "capacity": { routeId: "capacity", path: "/capacity", menuId: "CAPACITY", label: "Online Runtime Diagnostics", group: "operations", icon: "capacity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.capacity.enabled", expectedOperationIds: ["admRuntimeControlFindHealth", "admRuntimeControlFindStatus", "findAdmBrokerOutbox", "findAdmBrokerInbox", "findAdmIdempotencyRecords", "findAdmFileTransferHistory"], component: defineAsyncComponent(() => import("../../features/operations/OnlineDiagnosticsPage.vue")), props: undefined },
  "serviceRegistry": { routeId: "serviceRegistry", path: "/serviceRegistry", menuId: "SERVICE_REGISTRY", label: "서비스 레지스트리", group: "operations", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.serviceRegistry.enabled", expectedOperationIds: ["admServiceRegistryFindServices", "admServiceRegistryFindInstances", "admServiceRegistryFindEndpoints", "admServiceRegistryFindHealth", "admServiceRegistrySaveService", "admServiceRegistrySaveInstance", "admServiceRegistrySaveEndpoint", "admServiceRegistryFindCallHistory", "admServiceRegistryCapabilities", "admServiceRegistryFindCircuitStates", "admServiceRegistryFindRoutingPolicies"], component: defineAsyncComponent(() => import("../../features/service-registry/ServiceRegistryPage.vue")), props: undefined },
  "servers": { routeId: "servers", path: "/servers", menuId: "RUNTIME_CONTROL", label: "서버 관리", group: "operations", icon: "service", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.servers.enabled", expectedOperationIds: ["admManagedServerFindAll", "admManagedServerFindOne", "admManagedServerSave", "admManagedServerDisable", "admRuntimeInventoryFindAll"], component: defineAsyncComponent(() => import("../../features/server-management/ServerManagementPage.vue")), props: undefined },
  "notifications": { routeId: "notifications", path: "/notifications", menuId: "NOTIFICATION", label: "알림", group: "operations", icon: "incident", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.notifications.enabled", expectedOperationIds: ["admNotificationFindRules", "admNotificationFindRule", "admNotificationFindDeliveryLogs", "admNotificationFindDeliveryAttempts", "admNotificationSaveRule", "admNotificationUpdateRule", "admNotificationRetryDelivery", "admNotificationCancelDelivery", "admNotificationSendTest", "admNotificationFindDlq", "admNotificationDisableRule"], component: defineAsyncComponent(() => import("../../features/notifications/NotificationsPage.vue")), props: undefined },
  "downloads": { routeId: "downloads", path: "/downloads", menuId: "DOWNLOAD", label: "다운로드", group: "operations", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.downloads.enabled", expectedOperationIds: ["admDownloadFindPolicies", "admDownloadFindDownloadAuditLogs", "admDownloadDownloadCsv"], component: defineAsyncComponent(() => import("../../features/downloads/DownloadsPage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
