import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const securityRoutes = {
  "permissions": { routeId: "permissions", path: "/permissions", menuId: "PERMISSION", label: "권한", group: "security", icon: "role", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.permissions.enabled", expectedOperationIds: ["admPermissionFindManagedMenus", "admPermissionFindButtons", "admPermissionFindApiPermissions", "admPermissionFindRoles", "admPermissionFindMenuMatrix", "admPermissionFindButtonMatrix", "admPermissionFindApiPermissionMatrix", "admPermissionFindApiPermission", "admPermissionUpdateApiPermissionStatus", "admPermissionFindButton", "admPermissionUpdateButtonStatus", "admPermissionFindManagedMenu", "admPermissionUpdateMenuStatus", "admPermissionFindRole", "admPermissionUpdateRoleStatus", "admPermissionCreateApiPermission", "admPermissionUpdateApiPermission", "admPermissionCreateButton", "admPermissionUpdateButton", "admPermissionCreateMenu", "admPermissionUpdateMenu", "admPermissionCreateRole", "admPermissionUpdateRole", "admPermissionUpdateRoleApiPermission", "admPermissionUpdateButtonPermission", "admPermissionUpdateMenuPermission"], component: defineAsyncComponent(() => import("../../features/permissions/PermissionsPage.vue")), props: undefined },
  "password": { routeId: "password", path: "/password", menuId: "PASSWORD", label: "비밀번호", group: "security", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.password.enabled", expectedOperationIds: ["admOperatorPasswordPolicy", "admOperatorValidatePassword", "admOperatorChangePassword", "admOperatorResetPassword", "admOperatorRevokeSession"], component: defineAsyncComponent(() => import("../../features/password/PasswordPage.vue")), props: undefined },
  "security": { routeId: "security", path: "/security", menuId: "SECURITY", label: "보안", group: "security", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.security.enabled", expectedOperationIds: ["admSecurityFindMfaStates", "admSecurityRegisterMfa", "admSecurityVerifyMfa", "admSecurityDisableMfa", "admSecurityFindIpAllowlist", "admSecuritySaveIpAllowlist"], component: defineAsyncComponent(() => import("../../features/security/SecurityPage.vue")), props: undefined },
  "operators": { routeId: "operators", path: "/operators", menuId: "OPERATOR", label: "운영자", group: "security", icon: "users", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.operators.enabled", expectedOperationIds: ["admOperatorFindOperators", "admOperatorFindRoles", "admOperatorFindSessions", "admOperatorCreateOperator", "admOperatorUpdateRoles", "admOperatorUpdateStatus", "admOperatorUnlockOperator", "admOperatorUpdateContact", "admOperatorFindMenus", "admOperatorFindCreateResult", "admOperatorCleanupExpiredSessions", "admOperatorRawContact"], component: defineAsyncComponent(() => import("../../features/operators/OperatorsPage.vue")), props: undefined },
  "secrets": { routeId: "secrets", path: "/secrets", menuId: "SECRET", label: "Secret / Key", group: "security", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.secrets.enabled", expectedOperationIds: ["admSecretFindMetadata", "admSecretFindProviders", "admApprovalRequest"], component: defineAsyncComponent(() => import("../../features/secrets/SecretsPage.vue")), props: undefined },
  "approvals": { routeId: "approvals", path: "/approvals", menuId: "APPROVAL", label: "위험조치 승인", group: "security", icon: "approval", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.approvals.enabled", expectedOperationIds: ["admApprovalPolicies", "admApprovalPolicyDetail", "admApprovalPolicySave", "admApprovalRequest", "admApprovalRequestDetail", "admApprovalDecision", "admApprovalExecute", "admApprovalReconcile", "admRuntimeControlFindChange", "admRuntimeControlFindByOperation", "admBreakGlassFindSessions", "admBreakGlassReviewSession"], component: defineAsyncComponent(() => import("../../features/approvals/ApprovalsPage.vue")), props: undefined },
  "breakGlass": { routeId: "breakGlass", path: "/breakGlass", menuId: "BREAK_GLASS", label: "Break-glass", group: "security", icon: "security", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.breakGlass.enabled", expectedOperationIds: ["admBreakGlassFindSessions", "admBreakGlassOpenSession", "admBreakGlassReviewSession", "admBreakGlassCloseSession"], component: defineAsyncComponent(() => import("../../features/break-glass/BreakGlassPage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
