import { defineAsyncComponent } from "vue";
import type { AdmCapabilityRoute } from "./types";

export const traceLogRoutes = {
  "logs": { routeId: "logs", path: "/logs", menuId: "LOG_LIST", label: "거래 로그", group: "traceLog", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.logs.enabled", expectedOperationIds: ["admLogFindLogs", "admLogGetLogDetail", "admLogExportCreate", "admLogExportDownload"], component: defineAsyncComponent(() => import("../../features/logs/LogsPage.vue")), props: undefined },
  "transactionGroups": { routeId: "transactionGroups", path: "/transactionGroups", menuId: "LOG_LIST", label: "Online·Batch 통합 Trace", group: "traceLog", icon: "activity", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.transactionGroups.enabled", expectedOperationIds: ["traceAdmByTransactionId", "traceAdmByTraceId", "traceAdmByBusinessTransactionId", "admTransactionGroupFindTimeline", "admTransactionGroupFindGroups", "admTransactionGroupFindDetail", "admTransactionGroupFindExternalLogs", "admTransactionGroupFindHeaders", "admTransactionGroupFindSegments"], component: defineAsyncComponent(() => import("../../features/operations/IntegratedTracePage.vue")), props: undefined },
  "transactions": { routeId: "transactions", path: "/transactions", menuId: "TRANSACTION_META", label: "온라인 거래 정의", group: "traceLog", icon: "activity", ownerModule: "cpf-admin", riskLevel: "HIGH", featureFlag: "adm.route.transactions.enabled", expectedOperationIds: ["admTransactionMetaFindPage", "admTransactionMetaFindTransaction", "admTransactionMetaInactivate", "admTransactionMetaFindTransactions"], component: defineAsyncComponent(() => import("../../features/transactions/TransactionsPage.vue")), props: undefined },
  "remoteLogs": { routeId: "remoteLogs", path: "/remoteLogs", menuId: "REMOTE_LOG", label: "원격 로그", group: "traceLog", icon: "logs", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.remoteLogs.enabled", expectedOperationIds: ["admRemoteLogSearch", "admRemoteLogPreview", "admRemoteLogBundleJobCreate", "admRemoteLogBundleJobFind", "admRemoteLogBundleJobDownload", "admRemoteLogBundleDownloadTokenIssue", "admRemoteLogBundleDownload", "admRemoteLogDiagnostics", "admRemoteLogDownload"], component: defineAsyncComponent(() => import("../../features/remote-logs/RemoteLogsPage.vue")), props: undefined },
  "standardExecutions": { routeId: "standardExecutions", path: "/standardExecutions", menuId: "STANDARD_EXECUTION", label: "표준 실행", group: "traceLog", icon: "service", ownerModule: "cpf-admin", riskLevel: "MEDIUM", featureFlag: "adm.route.standardExecutions.enabled", expectedOperationIds: ["admStandardExecutionFindAll", "admStandardExecutionFindOne"], component: defineAsyncComponent(() => import("../../features/standard-executions/StandardExecutionsPage.vue")), props: undefined },
} satisfies Record<string, AdmCapabilityRoute>;
