plugins { id 'java-library'; id 'maven-publish' }
group = 'com.cpf.starter'
dependencies {
    api project(':cpf-starter-integration-sftp')
    api project(':cpf-starter-file-archive')
    api project(':cpf-starter-observability')
    api project(':cpf-starter-resilience')
}
tasks.named('test') { useJUnitPlatform() }
publishing { publications { mavenJava(MavenPublication) { from components.java; artifactId = 'cpf-starter-profile-sftp-integration' } } }
