<script setup lang="ts">
import{computed,onMounted,ref}from"vue";import CpfIcon from"../../components/CpfIcon.vue";import CpfTreeNode,{type TreeNode}from"../../components/CpfTreeNode.vue";import{bzaApi,hasBzaPermission}from"../auth/session";
type Row=Record<string,any>;const rows=ref<Row[]>([]),selected=ref<TreeNode|null>(null),error=ref(""),query=ref(""),includeDisabled=ref(true),issues=ref<string[]>([]);
function buildTree(source:Row[]):TreeNode[]{const byId=new Map<string,Row>();source.forEach(r=>byId.set(String(r.organizationCode),r));const children=new Map<string,Row[]>();const roots:Row[]=[];issues.value=[];for(const row of source){const id=String(row.organizationCode),parent=String(row.parentOrganizationCode||"");if(!parent)roots.push(row);else if(!byId.has(parent)){roots.push(row);issues.value.push(`고아 조직: ${id} → ${parent}`);}else{const list=children.get(parent)||[];list.push(row);children.set(parent,list)}}
 const walk=(row:Row,path:Set<string>):TreeNode=>{const id=String(row.organizationCode);if(path.has(id)){issues.value.push(`순환 조직: ${[...path,id].join(' → ')}`);return{id,label:String(row.organizationName||id),subtitle:id,status:row.useYn,children:[],raw:row,cycle:true}}const next=new Set(path);next.add(id);return{id,label:String(row.organizationName||id),subtitle:`${id} · ${row.organizationType||'-'}`,status:String(row.useYn||'Y'),children:(children.get(id)||[]).sort((a,b)=>String(a.organizationName).localeCompare(String(b.organizationName))).map(c=>walk(c,next)),raw:row,orphan:!!row.parentOrganizationCode&&!byId.has(String(row.parentOrganizationCode))}};
 return roots.sort((a,b)=>String(a.organizationName).localeCompare(String(b.organizationName))).map(r=>walk(r,new Set()));}
const tree=computed(()=>buildTree(rows.value.filter(r=>includeDisabled.value||r.useYn!=='N')));const filtered=computed(()=>{const q=query.value.trim().toLowerCase();if(!q)return tree.value;const filter=(n:TreeNode):TreeNode|null=>{const cs=n.children.map(filter).filter(Boolean)as TreeNode[];return(`${n.label} ${n.subtitle}`.toLowerCase().includes(q)||cs.length)?{...n,children:cs}:null};return tree.value.map(filter).filter(Boolean)as TreeNode[]});
async function load(){error.value="";try{rows.value=await bzaApi('/api/bza/backoffice/organizations?limit=5000')}catch(e){error.value=e instanceof Error?e.message:String(e)}}onMounted(load);
</script>
<template><div class="page-stack"><div class="cpf-page-heading"><div><p class="eyebrow">ORGANIZATION DIRECTORY</p><h2>조직도</h2><p>전체 깊이 조직 계층을 검색하고 고아·순환 구조를 즉시 식별합니다.</p></div><button class="ghost" @click="load"><CpfIcon name="refresh"/> 새로고침</button></div><p v-if="error" class="error-banner">{{error}}</p><p v-if="issues.length" class="error-banner">{{issues.join(' / ')}}</p><div class="cpf-toolbar"><input v-model="query" placeholder="조직명·코드 검색"><label><input v-model="includeDisabled" type="checkbox"> 중지 조직 포함</label><span class="count-pill">{{rows.length}} nodes</span></div><div class="bza-org-layout"><section class="cpf-card"><div class="cpf-card-head"><h2>조직 Tree</h2></div><div class="cpf-card-body org-tree"><CpfTreeNode v-for="node in filtered" :key="node.id" :node="node" :selected-id="selected?.id" @select="selected=$event"/><div v-if="!filtered.length" class="cpf-empty">조직 데이터가 없습니다.</div></div></section><aside class="cpf-card bza-detail-drawer"><div class="cpf-card-head"><h2>조직 상세</h2></div><div v-if="selected" class="detail-list"><dl><dt>조직 코드</dt><dd>{{selected.raw.organizationCode}}</dd><dt>조직명</dt><dd>{{selected.raw.organizationName}}</dd><dt>상위 조직</dt><dd>{{selected.raw.parentOrganizationCode||'ROOT'}}</dd><dt>조직 유형</dt><dd>{{selected.raw.organizationType||'-'}}</dd><dt>사용 여부</dt><dd>{{selected.raw.useYn}}</dd><dt>하위 조직</dt><dd>{{selected.children.length}}</dd></dl><p class="cpf-note" v-if="hasBzaPermission('ORGANIZATION','WRITE')">변경은 WRITE 권한과 감사 사유가 적용됩니다.</p></div><div v-else class="cpf-empty">Tree에서 조직을 선택하세요.</div></aside></div></div></template>
