<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { bzaApi } from "../auth/session";
const rows=ref<Record<string,unknown>[]>([]); const error=ref("");
const form=reactive({policyCode:"",policyVersion:1,policyName:"",businessDomain:"BZA",approvalType:"GENERAL",effectiveFrom:new Date().toISOString(),effectiveTo:"",enabledYn:"Y",selfApprovalAllowedYn:"N",description:"",reason:"결재 정책 변경",stepsJson:'[{"stepNo":1,"stepType":"APPROVAL","targetType":"ROLE","targetCode":"BZA_APPROVER","decisionRule":"ALL","requiredYn":"Y","sortOrder":0}]'});
async function load(){try{rows.value=await bzaApi("/api/bza/approval/policies");}catch(e){error.value=e instanceof Error?e.message:String(e);}}
async function save(){try{const steps=JSON.parse(form.stepsJson);await bzaApi("/api/bza/approval/policies",{method:"POST",body:JSON.stringify({...form,effectiveTo:form.effectiveTo||null,steps})});await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}}
onMounted(load);
</script>
<template><div class="page-stack"><section class="card"><div class="card-head"><div><p class="eyebrow">VERSIONED POLICY</p><h2>결재 정책</h2></div><button class="ghost" @click="load">새로고침</button></div><form class="form-grid" @submit.prevent="save"><label><span>정책 코드</span><input v-model="form.policyCode" required></label><label><span>버전</span><input v-model.number="form.policyVersion" type="number" min="1" required></label><label><span>정책명</span><input v-model="form.policyName" required></label><label><span>업무 영역</span><input v-model="form.businessDomain" required></label><label><span>결재 유형</span><input v-model="form.approvalType" required></label><label><span>시작시각</span><input v-model="form.effectiveFrom" required></label><label><span>종료시각</span><input v-model="form.effectiveTo"></label><label><span>활성</span><select v-model="form.enabledYn"><option>Y</option><option>N</option></select></label><label><span>자기승인</span><select v-model="form.selfApprovalAllowedYn"><option>N</option><option>Y</option></select></label><label class="wide"><span>설명</span><textarea v-model="form.description"></textarea></label><label class="wide"><span>단계 JSON</span><textarea v-model="form.stepsJson" rows="8" required></textarea></label><label class="wide"><span>감사 사유</span><textarea v-model="form.reason" required></textarea></label><div class="form-action"><button class="primary">정책 저장</button></div></form><p v-if="error" class="error-banner">{{error}}</p></section><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>policyCode</th><th>version</th><th>name</th><th>domain</th><th>type</th><th>enabled</th><th>effectiveFrom</th></tr></thead><tbody><tr v-for="row in rows" :key="`${row.policyCode}:${row.policyVersion}`"><td>{{row.policyCode}}</td><td>{{row.policyVersion}}</td><td>{{row.policyName}}</td><td>{{row.businessDomain}}</td><td>{{row.approvalType}}</td><td>{{row.enabledYn}}</td><td>{{row.effectiveFrom}}</td></tr></tbody></table></div></section></div></template>
