package com.cpf.starter.kafka;
import com.cpf.core.api.broker.*; import java.time.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicInteger; import org.apache.kafka.clients.producer.*; import org.apache.kafka.common.errors.SerializationException; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.kafka.support.SendResult;
public final class S03KafkaOutcomeHarness{
 public static void main(String[]a){providerFailureIsUnknown();serializationFailureIsFailed();timeoutIsUnknown();ackIsPublished();reservedFailsBeforeSend();System.out.println("S03_KAFKA_OUTCOME_HARNESS PASS cases=5");}
 static void providerFailureIsUnknown(){AtomicInteger c=new AtomicInteger();KafkaTemplate<String,byte[]> t=new KafkaTemplate<>(){public CompletableFuture<SendResult<String,byte[]>> send(ProducerRecord<String,byte[]> r){c.incrementAndGet();throw new IllegalStateException("provider state");}};Throwable x=expect(IllegalStateException.class,()->client(t,Duration.ofSeconds(1)).enqueue(req(Map.of())));check(x.getMessage().contains("UNKNOWN"),"classification");check(c.get()==1,"send calls");}
 static void serializationFailureIsFailed(){KafkaTemplate<String,byte[]> t=new KafkaTemplate<>(){public CompletableFuture<SendResult<String,byte[]>> send(ProducerRecord<String,byte[]> r){throw new SerializationException("bad payload");}};Throwable x=expect(IllegalArgumentException.class,()->client(t,Duration.ofSeconds(1)).enqueue(req(Map.of())));check(x.getMessage().contains("FAILED")&&!x.getMessage().contains("UNKNOWN"),"serialization classification");}
 static void timeoutIsUnknown(){KafkaTemplate<String,byte[]> t=new KafkaTemplate<>(){public CompletableFuture<SendResult<String,byte[]>> send(ProducerRecord<String,byte[]> r){return new CompletableFuture<>();}};Throwable x=expect(IllegalStateException.class,()->client(t,Duration.ofMillis(1)).enqueue(req(Map.of())));check(x.getMessage().contains("UNKNOWN"),"timeout classification");}
 static void ackIsPublished(){KafkaTemplate<String,byte[]> t=new KafkaTemplate<>(){public CompletableFuture<SendResult<String,byte[]>> send(ProducerRecord<String,byte[]> r){return CompletableFuture.completedFuture(new SendResult<>(new RecordMetadata(2,9)));}};var r=client(t,Duration.ofSeconds(1)).enqueue(req(Map.of("X-A","v")));check("PUBLISHED".equals(r.status()),"published");check("2".equals(r.partitionKey()),"partition");}
 static void reservedFailsBeforeSend(){AtomicInteger c=new AtomicInteger();KafkaTemplate<String,byte[]> t=new KafkaTemplate<>(){public CompletableFuture<SendResult<String,byte[]>> send(ProducerRecord<String,byte[]> r){c.incrementAndGet();return null;}};expect(SecurityException.class,()->client(t,Duration.ofSeconds(1)).enqueue(req(Map.of("CPF-TRANSACTION-ID","evil"))));check(c.get()==0,"provider called");}
 static KafkaCpfBrokerClient client(KafkaTemplate<String,byte[]>t,Duration d){return new KafkaCpfBrokerClient(t,new CpfKafkaProperties(d,1024,true),Clock.fixed(Instant.parse("2026-08-05T03:00:00Z"),ZoneOffset.UTC));}
 static CpfBrokerPublishRequest req(Map<String,String>h){return new CpfBrokerPublishRequest("m","topic","k",new byte[]{1},"application/octet-stream","tx","seg","p","c","idem",h,Map.of());}
 static void check(boolean c,String m){if(!c)throw new AssertionError(m);} static Throwable expect(Class<? extends Throwable>t,Runnable r){try{r.run();throw new AssertionError("expected");}catch(Throwable x){if(!t.isInstance(x))throw new AssertionError(x);return x;}}
}
