spring:
  config:
    import:
      - optional:classpath:application-cpf.yml
      - optional:classpath:application-cpf-${spring.profiles.active:local}.yml
      - optional:classpath:application-cmn.yml
      - optional:classpath:application-cmn-${spring.profiles.active:local}.yml
      - optional:classpath:application-mbr.yml
      - optional:classpath:application-mbr-${spring.profiles.active:local}.yml
