<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import {
  bzaCommonCatalogRefresh,
  bzaCommonSearch, bzaCommonDetail, bzaCommonCreate, bzaCommonUpdate, bzaCommonDelete,
  bzaCommonMessageCreate, bzaCommonMessageDisable, bzaCommonMessageSearch, bzaCommonMessageUpdate,
  bzaCommonResponseCodeCreate, bzaCommonResponseCodeDisable, bzaCommonResponseCodeSearch, bzaCommonResponseCodeUpdate
} from "../../generated/cpf-api";

type Row = Record<string, unknown>;
type PageResult = { content?: Row[]; totalElements?: number; page?: number; size?: number };
const tab=ref<"response"|"message">("response"); const keyword=ref(""); const reason=ref(""); const loading=ref(false); const error=ref("");
const result=ref<PageResult>({content:[]}); const selected=ref<Row|null>(null); const page=ref(0); const size=ref(20);
const responseForm=reactive({responseCode:"",messageCode:"",resultType:"E",moduleId:"BZA",responseGroup:"01",sequenceNo:"0001",category:"BUSINESS",retryDisposition:"NEVER",exposure:"SAFE_MESSAGE_ONLY",useYn:"Y",catalogVersion:1,description:""});
const messageForm=reactive({messageId:0,messageCode:"",locale:"ko",messageFormatType:"FIXED",externalMessage:"",internalMessage:"",parameterCount:0,escapeHtmlYn:"Y",maskArgumentsYn:"Y",useYn:"Y",catalogVersion:1,description:""});
type ManagedResource = "CODE"|"PARAMETER"|"CALENDAR"|"TEMPLATE";
type FieldDef = { key:string; label:string; required?:boolean; type?:"text"|"number"|"date"|"select"; options?:string[] };
const managedResource=ref<ManagedResource>("CODE");
const managedRows=ref<Row[]>([]); const managedTotal=ref(0); const managedPage=ref(0); const managedSelected=ref<Row|null>(null);
type ManagedFieldValue = string | number;
const managedForm=reactive<Record<string,ManagedFieldValue>>({});
const resourceDefinitions:Record<ManagedResource,{label:string;keys:string[];version?:string;fields:FieldDef[]}>= {
 CODE:{label:"공통 코드",keys:["code_id"],fields:[{key:"code_id",label:"Code ID",required:true},{key:"parent_id",label:"Parent ID"},{key:"code_key",label:"Code Key",required:true},{key:"code_value",label:"Code Value",required:true},{key:"description",label:"설명"},{key:"use_yn",label:"사용",type:"select",options:["Y","N"]}]},
 PARAMETER:{label:"공통 파라미터",keys:["config_id"],fields:[{key:"config_id",label:"Config ID",required:true},{key:"config_key",label:"Config Key",required:true},{key:"config_value",label:"Config Value",required:true},{key:"config_type",label:"Type",required:true},{key:"encrypted_yn",label:"암호화",type:"select",options:["Y","N"]},{key:"description",label:"설명"},{key:"use_yn",label:"사용",type:"select",options:["Y","N"]}]},
 CALENDAR:{label:"영업일",keys:["calendar_id","business_date"],version:"version_no",fields:[{key:"calendar_id",label:"Calendar ID",required:true},{key:"business_date",label:"영업일",required:true,type:"date"},{key:"business_day_yn",label:"영업일 여부",type:"select",options:["Y","N"]},{key:"day_type",label:"Day Type"},{key:"institution_code",label:"기관 코드"},{key:"reason",label:"설명 사유"},{key:"version_no",label:"Version",type:"number"}]},
 TEMPLATE:{label:"공통 템플릿",keys:["template_code","template_version","channel_code"],version:"revision_no",fields:[{key:"template_code",label:"Template Code",required:true},{key:"template_version",label:"Template Version",required:true},{key:"channel_code",label:"Channel",required:true},{key:"template_body",label:"Template Body",required:true},{key:"allowed_variables",label:"Allowed Variables"},{key:"status_code",label:"Status"},{key:"active_yn",label:"사용",type:"select",options:["Y","N"]},{key:"revision_no",label:"Revision",type:"number"}]},
};
const managedDefinition=computed(()=>resourceDefinitions[managedResource.value]);
const rows=computed(()=>result.value.content??[]); const total=computed(()=>Number(result.value.totalElements??0)); const hasNext=computed(()=>((page.value+1)*size.value)<total.value);
function headers(){if(!reason.value.trim())throw new Error("변경 사유를 입력해 주세요.");return {"X-CPF-Reason":reason.value.trim()};}
function val(row:Row,key:string){const snake=key.replace(/([a-z0-9])([A-Z])/g,"$1_$2").toLowerCase();return row[key]??row[snake]??"";}
async function load(){loading.value=true;error.value="";selected.value=null;try{result.value=tab.value==="response"?await bzaCommonResponseCodeSearch<PageResult>({query:{keyword:keyword.value,page:page.value,size:size.value}}):await bzaCommonMessageSearch<PageResult>({query:{keyword:keyword.value,page:page.value,size:size.value}});}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
function choose(row:Row){selected.value=row;if(tab.value==="response"){for(const k of Object.keys(responseForm)){const v=val(row,k);if(v!=="")(responseForm as Record<string,unknown>)[k]=v;}}else{for(const k of Object.keys(messageForm)){const v=val(row,k);if(v!=="")(messageForm as Record<string,unknown>)[k]=v;}}}
function reset(){selected.value=null;if(tab.value==="response")Object.assign(responseForm,{responseCode:"",messageCode:"",resultType:"E",moduleId:"BZA",responseGroup:"01",sequenceNo:"0001",category:"BUSINESS",retryDisposition:"NEVER",exposure:"SAFE_MESSAGE_ONLY",useYn:"Y",catalogVersion:1,description:""});else Object.assign(messageForm,{messageId:0,messageCode:"",locale:"ko",messageFormatType:"FIXED",externalMessage:"",internalMessage:"",parameterCount:0,escapeHtmlYn:"Y",maskArgumentsYn:"Y",useYn:"Y",catalogVersion:1,description:""});}
async function save(){loading.value=true;error.value="";try{const h=headers();if(tab.value==="response"){if(selected.value)await bzaCommonResponseCodeUpdate({path:{code:String(val(selected.value,"responseCode"))},query:{expectedVersion:Number(val(selected.value,"catalogVersion"))},data:{...responseForm},headers:h});else await bzaCommonResponseCodeCreate({data:{...responseForm},headers:h});}else{if(selected.value)await bzaCommonMessageUpdate({path:{id:Number(val(selected.value,"messageId"))},query:{expectedVersion:Number(val(selected.value,"catalogVersion"))},data:{...messageForm},headers:h});else await bzaCommonMessageCreate({data:{...messageForm},headers:h});}reason.value="";await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function disable(){if(!selected.value)return;loading.value=true;error.value="";try{const h=headers();if(tab.value==="response")await bzaCommonResponseCodeDisable({path:{code:String(val(selected.value,"responseCode"))},query:{expectedVersion:Number(val(selected.value,"catalogVersion"))},headers:h});else await bzaCommonMessageDisable({path:{id:Number(val(selected.value,"messageId"))},query:{expectedVersion:Number(val(selected.value,"catalogVersion"))},headers:h});reason.value="";await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function refreshCache(){loading.value=true;error.value="";try{await bzaCommonCatalogRefresh({headers:headers()});reason.value="";await load();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function goPage(next:number){page.value=Math.max(0,next);await load();}
function managedIdentifiers(source:Record<string,unknown>|Record<string,ManagedFieldValue>){return Object.fromEntries(managedDefinition.value.keys.map(key=>[key,source[key]]).filter(([,value])=>value!==undefined&&value!==null&&String(value)!==""));}
function resetManaged(){managedSelected.value=null;for(const key of Object.keys(managedForm))delete managedForm[key];for(const field of managedDefinition.value.fields){if(field.key.endsWith("_yn"))managedForm[field.key]="Y";}}
function chooseManaged(row:Row){managedSelected.value=row;for(const key of Object.keys(managedForm))delete managedForm[key];for(const field of managedDefinition.value.fields){const value=val(row,field.key);managedForm[field.key]=typeof value==="number"?value:String(value??"");}}
async function loadManaged(){loading.value=true;error.value="";try{const response=await bzaCommonSearch<PageResult>({path:{resource:managedResource.value},query:{query:keyword.value,page:managedPage.value,size:size.value,includeDisabled:true}});managedRows.value=response.content??[];managedTotal.value=Number(response.totalElements??0);}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function managedDetail(row:Row){loading.value=true;error.value="";try{const detail=await bzaCommonDetail<Row>({path:{resource:managedResource.value},data:managedIdentifiers(row)});chooseManaged(detail);}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function saveManaged(){loading.value=true;error.value="";try{const why=reason.value.trim();if(!why)throw new Error("변경 사유를 입력해 주세요.");const identifiers=managedIdentifiers(managedForm);const versionKey=managedDefinition.value.version;const expectedVersion=versionKey&&managedForm[versionKey]!==""?Number(managedForm[versionKey]):undefined;const data={identifiers,values:{...managedForm},expectedVersion,reason:why};if(managedSelected.value)await bzaCommonUpdate({path:{resource:managedResource.value},data});else await bzaCommonCreate({path:{resource:managedResource.value},data});reason.value="";resetManaged();await loadManaged();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function disableManaged(){if(!managedSelected.value)return;loading.value=true;error.value="";try{const why=reason.value.trim();if(!why)throw new Error("변경 사유를 입력해 주세요.");const versionKey=managedDefinition.value.version;const expectedVersion=versionKey&&managedForm[versionKey]!==""?Number(managedForm[versionKey]):undefined;await bzaCommonDelete({path:{resource:managedResource.value},data:{identifiers:managedIdentifiers(managedForm),values:{},expectedVersion,reason:why}});reason.value="";resetManaged();await loadManaged();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;}}
async function selectManagedResource(resource:ManagedResource){managedResource.value=resource;managedPage.value=0;resetManaged();await loadManaged();}
onMounted(async()=>{await load();resetManaged();await loadManaged();});
</script>

<template>
<section class="catalog-page" aria-labelledby="catalogTitle">
  <header class="catalog-head"><div><p class="eyebrow">COMMON PRODUCT SERVICE</p><h2 id="catalogTitle">응답코드 · 메시지 Catalog</h2><p>CMN owner table을 직접 수정하지 않고 Common Management API로 관리합니다.</p></div><button class="ghost" :disabled="loading" @click="refreshCache">Cache Refresh</button></header>
  <div class="catalog-toolbar"><div class="segmented"><button :class="{active:tab==='response'}" @click="tab='response';page=0;reset();load()">응답코드</button><button :class="{active:tab==='message'}" @click="tab='message';page=0;reset();load()">메시지</button></div><input v-model="keyword" aria-label="검색어" placeholder="코드·메시지·설명 검색" @keyup.enter="page=0;load()"><button class="primary" @click="page=0;load()">검색</button><button class="ghost" @click="reset">신규</button></div>
  <p v-if="error" class="error-banner" role="alert">{{error}}</p>
  <div class="catalog-grid">
    <div class="catalog-list" aria-live="polite"><button v-for="row in rows" :key="String(val(row,tab==='response'?'responseCode':'messageId'))" :class="{selected:selected===row}" @click="choose(row)"><strong>{{val(row,tab==='response'?'responseCode':'messageCode')}}</strong><span>{{tab==='response'?val(row,'messageCode'):val(row,'locale')}} · v{{val(row,'catalogVersion')}}</span><small>{{val(row,'description')}}</small></button><p v-if="!loading&&!rows.length" class="empty">조회 결과가 없습니다.</p><nav class="pager" aria-label="목록 페이지"><button type="button" :disabled="page===0||loading" @click="goPage(page-1)">이전</button><span>{{page+1}} 페이지 · 총 {{total}}건</span><button type="button" :disabled="!hasNext||loading" @click="goPage(page+1)">다음</button></nav></div>
    <form class="catalog-form" @submit.prevent="save">
      <template v-if="tab==='response'"><label>Response Code<input v-model="responseForm.responseCode" required :readonly="!!selected"></label><label>Message Code<input v-model="responseForm.messageCode" required></label><label>Category<select v-model="responseForm.category"><option>BUSINESS</option><option>VALIDATION</option><option>NOT_FOUND</option><option>CONFLICT</option><option>RATE_LIMIT</option><option>EXTERNAL</option><option>INFRASTRUCTURE</option><option>INTERNAL</option></select></label><label>Retry<select v-model="responseForm.retryDisposition"><option>NEVER</option><option>SAFE</option><option>RECONCILE</option><option>UNKNOWN</option></select></label><label>Version<input v-model.number="responseForm.catalogVersion" type="number" min="1" required></label><label class="wide">설명<input v-model="responseForm.description"></label></template>
      <template v-else><label>Message Code<input v-model="messageForm.messageCode" required></label><label>Locale<input v-model="messageForm.locale" required></label><label>Version<input v-model.number="messageForm.catalogVersion" type="number" min="1" required></label><label class="wide">외부 메시지<textarea v-model="messageForm.externalMessage" required></textarea></label><label class="wide">내부 메시지<textarea v-model="messageForm.internalMessage" required></textarea></label><label class="wide">설명<input v-model="messageForm.description"></label></template>
      <label class="wide">변경 사유<input v-model="reason" maxlength="500" placeholder="등록·수정·비활성화·refresh 시 필수"></label>
      <div class="catalog-actions wide"><button class="primary" :disabled="loading">{{selected?'수정':'등록'}}</button><button v-if="selected" type="button" class="ghost" :disabled="loading" @click="disable">비활성화</button></div>
    </form>
  </div>
  <section class="managed-card" aria-labelledby="managedTitle">
    <header class="catalog-head"><div><p class="eyebrow">COMMON PRODUCT SERVICE</p><h3 id="managedTitle">Code · Parameter · Calendar · Template</h3><p>CPF Common 정본 API를 통해 조회·등록·수정·비활성화합니다. DB 직접 수정이나 Raw JSON 입력은 사용하지 않습니다.</p></div></header>
    <div class="segmented" role="tablist" aria-label="공통 자원"><button v-for="resource in (['CODE','PARAMETER','CALENDAR','TEMPLATE'] as ManagedResource[])" :key="resource" :class="{active:managedResource===resource}" type="button" @click="selectManagedResource(resource)">{{resourceDefinitions[resource].label}}</button></div>
    <div class="catalog-grid">
      <div class="catalog-list"><button v-for="row in managedRows" :key="JSON.stringify(managedIdentifiers(row))" :class="{selected:managedSelected===row}" type="button" @click="managedDetail(row)"><strong>{{managedDefinition.keys.map(key=>String(val(row,key))).join(' · ')}}</strong><span>{{String(val(row,'description')||val(row,'day_type')||val(row,'status_code')||'')}}</span></button><p v-if="!loading&&!managedRows.length" class="empty">조회 결과가 없습니다.</p><nav class="pager"><button type="button" :disabled="managedPage===0||loading" @click="managedPage--;loadManaged()">이전</button><span>{{managedPage+1}} 페이지 · 총 {{managedTotal}}건</span><button type="button" :disabled="((managedPage+1)*size)>=managedTotal||loading" @click="managedPage++;loadManaged()">다음</button></nav></div>
      <form class="catalog-form" @submit.prevent="saveManaged"><label v-for="field in managedDefinition.fields" :key="field.key" :class="{wide:field.key==='description'||field.key==='template_body'}"><span>{{field.label}}</span><select v-if="field.type==='select'" v-model="managedForm[field.key]" :required="field.required"><option v-for="option in field.options" :key="option" :value="option">{{option}}</option></select><textarea v-else-if="field.key==='template_body'" v-model="managedForm[field.key]" :required="field.required"></textarea><input v-else v-model="managedForm[field.key]" :type="field.type==='number'?'number':field.type==='date'?'date':'text'" :required="field.required" :readonly="!!managedSelected&&managedDefinition.keys.includes(field.key)"></label><label class="wide">변경 사유<input v-model="reason" maxlength="500" placeholder="등록·수정·비활성화 시 필수"></label><div class="catalog-actions wide"><button class="primary" :disabled="loading">{{managedSelected?'수정':'등록'}}</button><button v-if="managedSelected" type="button" class="ghost" :disabled="loading" @click="disableManaged">비활성화</button><button type="button" class="ghost" @click="resetManaged">신규</button></div></form>
    </div>
  </section>
</section>
</template>

<style scoped>
.catalog-page{display:grid;gap:1rem}.managed-card{display:grid;gap:1rem;padding-top:1rem;border-top:1px solid currentColor}.catalog-head,.catalog-toolbar,.catalog-actions{display:flex;align-items:center;justify-content:space-between;gap:.75rem}.catalog-toolbar{justify-content:flex-start;flex-wrap:wrap}.segmented{display:flex}.segmented button.active{font-weight:700}.catalog-grid{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(360px,1.2fr);gap:1rem}.catalog-list{display:grid;align-content:start;gap:.5rem;max-height:64vh;overflow:auto}.catalog-list button{display:grid;text-align:left;gap:.15rem;padding:.8rem}.catalog-list button.selected{outline:2px solid currentColor}.pager{display:flex;align-items:center;justify-content:space-between;gap:.5rem;padding:.4rem}.catalog-form{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.catalog-form label{display:grid;gap:.3rem}.catalog-form .wide{grid-column:1/-1}textarea{min-height:6rem}.empty{padding:1rem}@media(max-width:900px){.catalog-grid{grid-template-columns:1fr}.catalog-form{grid-template-columns:1fr}.catalog-form .wide{grid-column:auto}}
</style>
